Repository tuist/tuist, pull requests merged in 2020-06, with the labels that each got.

#1119 Target content hashing [part 1]
  Sources/TuistCache/ContentHashing/CacheContentHasher.swift
  Sources/TuistCache/ContentHashing/ContentHasher.swift
  Sources/TuistCache/ContentHashing/ContentHashingError.swift
  Sources/TuistCache/ContentHashing/CoreDataModelsContentHasher.swift
  Sources/TuistCache/ContentHashing/GraphContentHasher.swift
  Sources/TuistCache/ContentHashing/SourceFilesContentHasher.swift
  Sources/TuistCache/ContentHashing/TargetActionsContentHasher.swift
  Sources/TuistCache/ContentHashing/TargetContentHasher.swift
  Sources/TuistCacheTesting/ContentHashing/Mocks/MockContentHashing.swift
  Sources/TuistCacheTesting/ContentHashing/Mocks/MockGraphContentHasher.swift
  Sources/TuistSupport/Utils/FileHandler.swift
  Tests/Fixtures/Frameworks/Frameworks.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Tests/TuistCacheIntegrationTests/ContentHashing/ContentHashingIntegrationTests.swift
  Tests/TuistCacheTests/ContentHashing/CacheContentHasherTests.swift
  Tests/TuistCacheTests/ContentHashing/ContentHasherTests.swift
  Tests/TuistCacheTests/ContentHashing/CoreDataModelsContentHasherTests.swift
  Tests/TuistCacheTests/ContentHashing/GraphContentHasherTests.swift
  Tests/TuistCacheTests/ContentHashing/SourceFilesContentHasherTests.swift
  Tests/TuistCacheTests/ContentHashing/TargetActionsContentHasherTests.swift
Labels: type:enhancement

#1471 Add secret command
  CHANGELOG.md
  Sources/TuistKit/Commands/SecretCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/SecretService.swift
  Sources/TuistSupport/Utils/SecureStringGenerator.swift
  Sources/TuistSupportTesting/Utils/MockSecureStringGenerator.swift
  Tests/TuistKitTests/Services/SecretServiceTests.swift
  website/markdown/docs/commands/edit.mdx
  website/markdown/docs/commands/generate.mdx
  website/markdown/docs/commands/graph.mdx
  website/markdown/docs/commands/lint.mdx
  website/markdown/docs/commands/scaffold.mdx
  website/markdown/docs/commands/secret.mdx
  website/markdown/docs/commands/signing.mdx
  website/markdown/docs/commands/up.mdx
  website/markdown/docs/links.mdx
  website/markdown/posts/2020-06-17-version-1.11.0/post.mdx
Labels: domain:tuist

#1470 [Cache] Add the cache storing logic
  Package.resolved
  Package.swift
  Sources/TuistCache/Cache/Cache.swift
  Sources/TuistCache/Cache/CacheRemoteStorage.swift
  Sources/TuistCache/Cache/CloudCacheResponse.swift
  Sources/TuistCache/Cache/CloudHEADResponse.swift
  Sources/TuistCache/Cache/FileUploader.swift
  Sources/TuistCache/GraphMappers/CacheMapper.swift
  Sources/TuistCacheTesting/Cache/Mocks/MockFileUploader.swift
  Sources/TuistCloud/Client/CloudClient.swift
  Sources/TuistCore/Cloud/CloudClienting.swift
  Sources/TuistCore/Cloud/CloudResponseError.swift
  Sources/TuistCoreTesting/Cloud/CloudResponseError+TestData.swift
  Sources/TuistCoreTesting/Cloud/MockCloudClienting.swift
  Sources/TuistKit/Cache/CacheController.swift
  Sources/TuistKit/GraphMappers/GraphMapperProvider.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockManifestLoader.swift
  Sources/TuistSupport/Extensions/String+MD5.swift
  Sources/TuistSupport/HTTP/HTTPRequestDispatcher.swift
  Sources/TuistSupport/HTTP/HTTPResource.swift
  Sources/TuistSupport/Utils/FileArchiver.swift
  Sources/TuistSupport/Utils/FileArchiverFactory.swift
  Sources/TuistSupport/Utils/FileHandler.swift
  Sources/TuistSupport/Utils/TemporaryDirectory.swift
  Sources/TuistSupportTesting/Utils/MockFileArchiving.swift
  Tests/Fixtures/uUI.xcframework.zip
  Tests/TuistCacheTests/Cache/CacheRemoteStorageTests.swift
  Tests/TuistEnvKitTests/Versions/Mocks/MockVersionsController.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/WorkspaceStructureGeneratorTests.swift
  Tests/TuistSupportTests/Utils/FileHandlerTests.swift
Labels: waiting-review

#1498 [Cache] Implement remote fetch logic
  Sources/TuistCache/Cache/CacheRemoteStorage.swift
  Sources/TuistCache/Cache/FileUploader.swift
  Sources/TuistKit/ProjectGenerator/ProjectGenerator.swift
  Sources/TuistSupport/Extensions/URLRequest+Sugar.swift
  Sources/TuistSupport/HTTP/FileClient.swift
  Sources/TuistSupport/Utils/FileArchiver.swift
  Sources/TuistSupport/Utils/FileHandler.swift
  Sources/TuistSupportTesting/HTTP/MockFileClient.swift
  Sources/TuistSupportTesting/TestCase/TuistTestCase.swift
  Sources/TuistSupportTesting/Utils/MockEnvironment.swift
  Sources/TuistSupportTesting/Utils/MockFileArchiving.swift
  Sources/TuistSupportTesting/Utils/MockOpener.swift
  Tests/TuistCacheTests/Cache/CacheRemoteStorageTests.swift
  Tests/TuistGeneratorTests/Generator/WorkspaceStructureGeneratorTests.swift
  Tests/TuistKitTests/Generator/Mocks/MockProjectGenerator.swift
  Tests/TuistSupportTests/Utils/FileHandlerTests.swift
Labels: waiting-review
