Repository tuist/tuist, pull requests merged in 2020-12, with the labels that each got.

#2095 Project Plugins: Add Plugin.swift manifest.
  Sources/ProjectDescription/Config.swift
  Sources/ProjectDescription/Plugin.swift
  Sources/ProjectDescription/PluginLocation.swift
  Tests/ProjectDescriptionTests/ConfigTests.swift
  Tests/ProjectDescriptionTests/PluginLocationTests.swift
  Tests/ProjectDescriptionTests/PluginTests.swift
Labels: plugins

#2103 Project Plugins: Add TuistCore Plugin Models
  Sources/TuistCore/Models/Config.swift
  Sources/TuistCore/Models/Plugin.swift
  Sources/TuistCore/Models/PluginLocation.swift
  Sources/TuistCore/Models/Plugins.swift
  Sources/TuistCore/Models/ProjectDescriptionHelpersPlugin.swift
  Sources/TuistCoreTesting/Models/Config+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/Config+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Plugin+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/PluginLocation+ManifestMapper.swift
  Tests/TuistIntegrationTests/Generator/MultipleConfigurationsIntegrationTests.swift
Labels: plugins

#2111 Fix `ValueGraphTraverser.directTargetDependencies` to return local targets only
  CHANGELOG.md
  Sources/TuistCore/ValueGraph/ValueGraphDependency.swift
  Sources/TuistCore/ValueGraph/ValueGraphTraverser.swift
  Tests/TuistCoreTests/ValueGraph/ValueGraphTraverserTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
Labels: automerge

#2107 Project Plugins: Add GitHandler Service
  Sources/TuistSupport/Utils/GitHandler.swift
  Sources/TuistSupportTesting/Utils/MockGitHandler.swift
  Sources/TuistSupportTesting/Utils/MockSystem.swift
  Tests/TuistSupportTests/Utils/GitHandlerTests.swift
Labels: automerge, plugins

#2079 Init `TuistLintCode` target.
  Package.swift
  Sources/TuistKit/Services/Lint/LintCodeService.swift
  Sources/TuistLinting/Log/Logger.swift
  Sources/TuistLinting/Utilities/CodeLinter.swift
  Sources/TuistLintingTesting/MockCodeLinter.swift
  Tests/TuistDependenciesIntegrationTests/EmptyTests.swift
  Tests/TuistKitTests/Services/Lint/LintCodeServiceTests.swift
  Tests/TuistLintingTests/Utilities/CodeLinterTests.swift
Labels: automerge

#2110 Update generators to use the traverser
  CHANGELOG.md
  Sources/TuistCore/Graph/Graph.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/GraphTraverser/GraphTraversing.swift
  Sources/TuistCore/ValueGraph/ValueGraphTraverser.swift
  Sources/TuistCoreTesting/GraphTraverser/MockGraphTraverser.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
  Sources/TuistGenerator/Generator/DescriptorGenerator.swift
  Sources/TuistGenerator/Generator/LinkGenerator.swift
  Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift
  Sources/TuistGenerator/Generator/ProjectFileElements.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistGenerator/Generator/TargetGenerator.swift
  Sources/TuistGenerator/Generator/WorkspaceDescriptorGenerator.swift
  Sources/TuistGeneratorTesting/Generator/MockDescriptorGenerator.swift
  Sources/TuistKit/Generator/Generator.swift
  Sources/TuistKit/ProjectEditor/ProjectEditor.swift
  Tests/TuistCoreTests/ValueGraph/ValueGraphTraverserTests.swift
  Tests/TuistGeneratorIntegrationTests/Generator/WorkspaceGeneratorIntegrationTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/LinkGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/Mocks/MockProjectDescriptorGenerator.swift
  Tests/TuistGeneratorTests/Generator/Mocks/MockSchemeDescriptorsGenerator.swift
  Tests/TuistGeneratorTests/Generator/Mocks/MockTargetGenerator.swift
  Tests/TuistGeneratorTests/Generator/Mocks/MockWorkspaceDescriptorGenerator.swift
  Tests/TuistGeneratorTests/Generator/ProjectDescriptorGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectFileElementsTests.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/TargetGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/WorkspaceDescriptorGeneratorTests.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  Tests/TuistIntegrationTests/Generator/MultipleConfigurationsIntegrationTests.swift
  Tests/TuistIntegrationTests/Generator/StableStructureIntegrationTests.swift
  Tests/TuistIntegrationTests/Generator/TuistGeneratorPerformanceTests.swift
Labels: automerge

#2051 Missing required module 'XXX' when building project with cached dependencies
  CHANGELOG.md
  Sources/TuistCore/Graph/Graph.swift
  Sources/TuistCore/Graph/Nodes/PrecompiledNode.swift
  Sources/TuistCore/Graph/Nodes/TargetNode.swift
  Sources/TuistCore/ValueGraph/ValueGraphTraverser.swift
  Tests/TuistCoreTests/ValueGraph/ValueGraphTraverserTests.swift
  features/cache-frameworks.feature
  fixtures/ios_app_with_transitive_project/App/Config/App-Info.plist
  fixtures/ios_app_with_transitive_project/App/Config/AppTests-Info.plist
  fixtures/ios_app_with_transitive_project/App/Project.swift
  fixtures/ios_app_with_transitive_project/App/Sources/AppDelegate.swift
  fixtures/ios_app_with_transitive_project/App/Tests/AppDelegateTests.swift
  fixtures/ios_app_with_transitive_project/App/UITests/AppUITest.swift
  fixtures/ios_app_with_transitive_project/Framework1/Config/Framework1-Info.plist
  fixtures/ios_app_with_transitive_project/Framework1/Config/Framework1Tests-Info.plist
  fixtures/ios_app_with_transitive_project/Framework1/Project.swift
  fixtures/ios_app_with_transitive_project/Framework1/Sources/Framework1File.swift
  fixtures/ios_app_with_transitive_project/Framework1/Tests/Framework1FileTests.swift
  fixtures/ios_app_with_transitive_project/Framework1/Tests/Info.plist
  fixtures/ios_app_with_transitive_project/Framework2/Config/Framework2-Info.plist
  fixtures/ios_app_with_transitive_project/Framework2/Project.swift
  fixtures/ios_app_with_transitive_project/Framework2/Sources/Framework2File.swift
  fixtures/ios_app_with_transitive_project/Tuist/Config.swift
  fixtures/ios_app_with_transitive_project/Workspace.swift
Labels: automerge

#2060 Chimera - `carthage` support.
  .github/workflows/tuist.yml
  CHANGELOG.md
  Sources/ProjectDescription/Dependencies.swift
  Sources/ProjectDescription/Dependency.swift
  Sources/ProjectDescription/DependencyManager.swift
  Sources/ProjectDescription/DependencyRequirement.swift
  Sources/TuistCore/Models/CarthageDependency.swift
  Sources/TuistCore/Models/Dependencies.swift
  Sources/TuistCore/Models/Platform.swift
  Sources/TuistDependencies/Carthage/CarthageInteractor.swift
  Sources/TuistDependencies/Carthage/Generators/CartfileContentGenerator.swift
  Sources/TuistDependencies/Carthage/Generators/CarthageCommandGenerator.swift
  Sources/TuistDependencies/CocoaPods/CocoaPodsInteractor.swift
  Sources/TuistDependencies/DependenciesController.swift
  Sources/TuistDependencies/SwiftPackageManager/SPMInteractor.swift
  Sources/TuistDependenciesTesting/Carthage/MockCartfileContentGenerator.swift
  Sources/TuistDependenciesTesting/Carthage/MockCarthageCommandGenerator.swift
  Sources/TuistDependenciesTesting/Carthage/MockCarthageInteractor.swift
  Sources/TuistDependenciesTesting/CocoaPods/MockCocoaPodsInteractor.swift
  Sources/TuistDependenciesTesting/MockDependenciesController.swift
  Sources/TuistDependenciesTesting/SwiftPackageManager/MockSwiftPackageManagerInteractor.swift
  Sources/TuistKit/Commands/DependenciesCommand.swift
  Sources/TuistKit/Services/Dependencies/DependenciesFetchService.swift
  Sources/TuistKit/Services/Dependencies/DependenciesUpdateService.swift
  Sources/TuistLoader/Loaders/DependenciesModelLoader.swift
  Sources/TuistLoader/Loaders/ManifestLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/CarthageDependency+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Dependencies+ManifestMapper.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockDependenciesModelLoader.swift
  Sources/TuistLoaderTesting/Loaders/TestData/ProjectDescription+TestData.swift
  Sources/TuistSupport/Constants.swift
  Templates/Gitignore.stencil
  Tests/ProjectDescriptionTests/DependenciesTests.swift
  Tests/ProjectDescriptionTests/DependencyTests.swift
  Tests/TuistCoreTests/Models/CarthageDependencyTests.swift
  Tests/TuistCoreTests/Models/PlatformTests.swift
  Tests/TuistDependenciesTests/Carthage/CarthageInteractorTests.swift
  Tests/TuistDependenciesTests/Carthage/Generators/CartfileContentGenetatorTests.swift
  Tests/TuistDependenciesTests/Carthage/Generators/CarthageCommandGeneratorTests.swift
  Tests/TuistDependenciesTests/CocoaPods/CocoaPodsInteractorTests.swift
  Tests/TuistDependenciesTests/DependenciesControllerTests.swift
  Tests/TuistDependenciesTests/EmptyTests.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/SwiftPackageManagerInteractorTests.swift
  Tests/TuistKitTests/Services/Dependencies/DependenciesFetchServiceTests.swift
  Tests/TuistKitTests/Services/Dependencies/DependenciesUpdateServiceTests.swift
  Tests/TuistLoaderTests/Loaders/DependenciesModelLoaderTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/DependenciesManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Platform+ManifestMapperTests.swift
  features/dependencies.feature
  features/step_definitions/dependencies.rb
  features/step_definitions/generate.rb
  fixtures/app_with_framework_and_tests_and_dependencies/.gitignore
  fixtures/app_with_framework_and_tests_and_dependencies/App/AppDelegate.swift
  fixtures/app_with_framework_and_tests_and_dependencies/AppTests/AppTests.swift
  fixtures/app_with_framework_and_tests_and_dependencies/Framework/Framework.swift
  fixtures/app_with_framework_and_tests_and_dependencies/FrameworkTests/FrameworkTests.swift
  fixtures/app_with_framework_and_tests_and_dependencies/Project.swift
  fixtures/app_with_framework_and_tests_and_dependencies/Tuist/Config.swift
  fixtures/app_with_framework_and_tests_and_dependencies/Tuist/Dependencies.swift
  fixtures/ios_app_with_helpers/Tuist/Dependencies.swift
Labels: domain:chimera
