Repository tuist/tuist, pull requests merged in 2020-11, with the labels that each got.

#1979 Adding Dependency.Manager to identify which service to use to install the dependency
  Sources/ProjectDescription/Dependency.swift
  Sources/ProjectDescription/DependencyManager.swift
  Sources/TuistLoaderTesting/Loaders/TestData/ProjectDescription+TestData.swift
Labels: domain:chimera

#1977 Include hash in files generated by mappers
  CHANGELOG.md
  Package.swift
  Sources/TuistCache/ContentHashing/CacheContentHasher.swift
  Sources/TuistCache/ContentHashing/GraphContentHasher.swift
  Sources/TuistCache/ContentHashing/SourceFilesContentHasher.swift
  Sources/TuistCache/ContentHashing/TargetContentHasher.swift
  Sources/TuistCache/GraphMappers/CacheMapper.swift
  Sources/TuistCore/Cache/FileContentHashing.swift
  Sources/TuistCore/ContentHashing/ContentHasher.swift
  Sources/TuistCore/ContentHashing/ContentHashing.swift
  Sources/TuistCore/ContentHashing/ContentHashingError.swift
  Sources/TuistCore/Models/SourceFile.swift
  Sources/TuistCore/Models/SourceFileGlob.swift
  Sources/TuistCore/Models/Target.swift
  Sources/TuistCoreTesting/Cache/MockContentHashing.swift
  Sources/TuistCoreTesting/Models/Target+TestData.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistGenerator/Mappers/SynthesizedResourceInterfaceProjectMapper.swift
  Sources/TuistKit/Cache/CacheController.swift
  Sources/TuistKit/Cache/CacheControllerFactory.swift
  Sources/TuistKit/Generator/Generator.swift
  Sources/TuistKit/GraphMappers/ProjectMapperProvider.swift
  Sources/TuistKit/GraphMappers/WorkspaceMapperProvider.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Sources/TuistKit/Services/BuildService.swift
  Sources/TuistKit/Services/Cache/CachePrintHashesService.swift
  Sources/TuistKit/Services/Cache/CacheWarmService.swift
  Sources/TuistKit/Services/DocService.swift
  Sources/TuistKit/Services/Focus/FocusGraphMapperProvider.swift
  Sources/TuistKit/Services/FocusService.swift
  Sources/TuistKit/Services/GenerateService.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Tests/TuistCacheIntegrationTests/ContentHashing/ContentHashingIntegrationTests.swift
  Tests/TuistCacheTests/ContentHashing/CacheContentHasherTests.swift
  Tests/TuistCacheTests/ContentHashing/GraphContentHasherTests.swift
  Tests/TuistCacheTests/ContentHashing/SourceFilesContentHasherTests.swift
  Tests/TuistCoreTests/ContentHashing/ContentHasherTests.swift
  Tests/TuistCoreTests/Models/TargetTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectFileElementsTests.swift
  Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/SynthesizedResourceInterfaceProjectMapperTests.swift
  Tests/TuistIntegrationTests/Generator/MultipleConfigurationsIntegrationTests.swift
  Tests/TuistIntegrationTests/Generator/TestModelGenerator.swift
  Tests/TuistKitTests/Cache/CacheControllerTests.swift
  Tests/TuistKitTests/GraphMappers/ProjectMapperProviderTests.swift
  Tests/TuistKitTests/GraphMappers/WorkspaceMapperProviderTests.swift
  Tests/TuistKitTests/Services/Lint/LintCodeServiceTests.swift
Labels: automerge

#2003 Update CodeLinter to print all standard output and error
  Sources/TuistKit/Lint/CodeLinter.swift
Labels: automerge

#2016 Use the udid of an available device when building the frameworks for the cache
  CHANGELOG.md
  Sources/TuistCache/Utilities/CacheFrameworkBuilder.swift
  Sources/TuistCore/Simulator/SimulatorController.swift
  Sources/TuistCoreTesting/Simulator/MockSimulatorController.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistAutomationIntegrationTests/Simulator/SimulatorControllerIntegrationTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: automerge

#2018 Don't hash target actions and print a warning
  Sources/TuistCache/ContentHashing/TargetContentHasher.swift
  Sources/TuistCache/ContentHashing/TargetScriptsContentHasher.swift
  Sources/TuistCache/Linters/CacheGraphLinter.swift
  Sources/TuistCacheTesting/Linters/Mocks/MockCacheGraphLinter.swift
  Sources/TuistKit/Cache/CacheController.swift
  Sources/TuistKit/Services/Cache/CacheWarmService.swift
  Sources/TuistSupport/Constants.swift
  Tests/TuistCacheIntegrationTests/ContentHashing/ContentHashingIntegrationTests.swift
  Tests/TuistCacheTests/ContentHashing/TargetScriptsContentHasherTests.swift
  Tests/TuistCacheTests/Linters/CacheGraphLinterTests.swift
  Tests/TuistKitTests/Cache/CacheControllerTests.swift
Labels: automerge

#2022 Version 1.24.0 - Sol y sombra
  CHANGELOG.md
  Gemfile.lock
  Sources/TuistSupport/Constants.swift
Labels: automerge

#1941 Add support for CLI tool target
  .github/workflows/tuist.yml
  CHANGELOG.md
  Sources/ProjectDescription/Product.swift
  Sources/TuistCore/Models/Product.swift
  Sources/TuistCore/Models/Target.swift
  Sources/TuistGenerator/Generator/InfoPlistContentProvider.swift
  Sources/TuistGenerator/GraphViz/NodeStyling.swift
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Sources/TuistLoader/Models+ManifestMappers/Product+ManifestMapper.swift
  Tests/TuistCoreTests/Models/ProductTests .swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  features/generate-7.feature
  fixtures/command_line_tool_basic/Project.swift
  fixtures/command_line_tool_basic/main.swift
  fixtures/command_line_tool_with_dynamic_dependencies/Project.swift
  fixtures/command_line_tool_with_static_dependencies/CommandLineTool/main.swift
  fixtures/command_line_tool_with_static_dependencies/Project.swift
  fixtures/command_line_tool_with_static_dependencies/StaticLib/StaticLib.swift
  website/markdown/docs/examples/command-line-tools.mdx
  website/markdown/docs/links.mdx
Labels: automerge

#2020 Add GenerationOption to enable code coverage
  CHANGELOG.md
  Sources/ProjectDescription/Config.swift
  Sources/TuistCore/Models/Config.swift
  Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  Sources/TuistKit/GraphMappers/ProjectMapperProvider.swift
  Sources/TuistKit/ProjectEditor/ProjectEditor.swift
  Sources/TuistLoader/Models+ManifestMappers/Config+ManifestMapper.swift
  Tests/ProjectDescriptionTests/ConfigTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift
  Tests/TuistKitTests/GraphMappers/ProjectMapperProviderTests.swift
  website/markdown/docs/usage/config.mdx
Labels: automerge

#2001 Adding CarthageDependency and DependencyRequirement
  Sources/TuistCore/Models/CarthageDependency.swift
  Sources/TuistCore/Models/Package.swift
  Sources/TuistCore/Models/Requirement.swift
  Sources/TuistLoader/Models+ManifestMappers/Package+ManifestMapper.swift
Labels: domain:chimera

#2032 Add Generation Pipeline Documentation
  website/markdown/docs/contribution/assets/generation-pipeline/generation-pipeline-diagram.drawio.xml
  website/markdown/docs/contribution/assets/generation-pipeline/graph-loading.png
  website/markdown/docs/contribution/assets/generation-pipeline/lint-and-generate.png
  website/markdown/docs/contribution/assets/generation-pipeline/manifest-model-loading.png
  website/markdown/docs/contribution/assets/generation-pipeline/overview.png
  website/markdown/docs/contribution/assets/generation-pipeline/performing-side-effects.png
  website/markdown/docs/contribution/generation-pipeline.mdx
  website/markdown/docs/links.mdx
Labels: domain:documentation

#2049 Don't install Bundler dependencies at vendor
  .github/workflows/release.yml
Labels: automerge

#2052 Ordered launch arguments
  CHANGELOG.md
  Sources/ProjectDescription/Arguments.swift
  Sources/ProjectDescription/LaunchArgument.swift
  Sources/ProjectDescription/Target.swift
  Sources/TuistCore/Models/Arguments.swift
  Sources/TuistCore/Models/LaunchArgument.swift
  Sources/TuistCore/Models/Target.swift
  Sources/TuistCoreTesting/Models/Arguments+TestData.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Arguments+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/LaunchArgument+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Sources/TuistLoaderTesting/Loaders/TestData/ProjectDescription+TestData.swift
  Tests/ProjectDescriptionTests/SchemeTests.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  Tests/TuistIntegrationTests/Generator/TestModelGenerator.swift
  Tests/TuistKitTests/ProjectEditor/ProjectEditorMapperTests.swift
  Tests/TuistLoaderTests/Extensions/TuistTestCase+ManifestMappers.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Scheme+ManifestMapper.swift
  website/markdown/docs/usage/project-description.mdx
Labels: automerge

#2050 Adding platform support for Dependency.swift
  Sources/ProjectDescription/Dependency.swift
  Sources/TuistCore/Models/CarthageDependency.swift
  Sources/TuistLoaderTesting/Loaders/TestData/ProjectDescription+TestData.swift
  fixtures/ios_app_with_helpers/Tuist/Dependencies.swift
Labels: domain:chimera

#2061 [fix-docs] link missing `test schemes` docs
  website/markdown/docs/links.mdx
Labels: domain:documentation, domain:website
