Repository tuist/tuist, pull requests merged in 2021-01, with the labels that each got.

#2225 [fix-unit-tests] change - replace `TuistTestCase` with `TuistUnitTest…
  Tests/TuistCoreTests/Models/CarthageDependencyTests.swift
Labels: domain:chimera

#2194 Project Plugins: Add Plugin Service
  Package.resolved
  Package.swift
  Sources/TuistCore/Graph/Nodes/TargetNode.swift
  Sources/TuistCore/Protocols/GeneratorModelLoading.swift
  Sources/TuistLoader/Loaders/CachedModelLoader.swift
  Sources/TuistLoader/Loaders/GeneratorModelLoader.swift
  Sources/TuistLoader/Models/Manifest.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockGeneratorModelLoader.swift
  Sources/TuistLoaderTesting/Utils/Mocks/MockManifestFilesLocator.swift
  Sources/TuistPlugin/Logger.swift
  Sources/TuistPlugin/PluginService.swift
  Sources/TuistPlugin/PluginServiceError.swift
  Sources/TuistPlugin/PluginServicing.swift
  Sources/TuistSupport/Constants.swift
  Sources/TuistSupportTesting/TestCase/TuistTestCase.swift
  Tests/TuistPluginTests/PluginServiceTests.swift
Labels: plugins

#2304 Update docs
  website/markdown/docs/usage/dynamic-configuration.mdx
Labels: automerge, domain:documentation
