Repository tuist/tuist, pull requests merged in 2021-04, with the labels that each got.

#2686 Support SourceFileLists in TargetActions
  CHANGELOG.md
  Sources/TuistLoader/Models+ManifestMappers/TargetAction+ManifestMapper.swift
  Sources/TuistLoaderTesting/Loaders/TestData/ProjectDescription+TestData.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/TargetAction+ManifestMapperTests.swift
  projects/tuist/fixtures/ios_app_with_actions/App/Project.swift
Labels: domain:generation

#2394 [Chimera] Fetching SPM dependencies.
  CHANGELOG.md
  Sources/ProjectDescription/Dependencies/CarthageDependencies.swift
  Sources/ProjectDescription/Dependencies/Dependencies.swift
  Sources/ProjectDescription/Dependencies/SwiftPackageManagerDependencies.swift
  Sources/TuistDependencies/Carthage/CarthageInteractor.swift
  Sources/TuistDependencies/DependenciesController.swift
  Sources/TuistDependencies/SwiftPackageManager/SPMInteractor.swift
  Sources/TuistDependencies/SwiftPackageManager/SwiftPackageManagerInteractor.swift
  Sources/TuistDependenciesTesting/Carthage/MockCarthageCommandGenerator.swift
  Sources/TuistDependenciesTesting/Carthage/MockCarthageInteractor.swift
  Sources/TuistDependenciesTesting/SwiftPackageManager/MockSwiftPackageManagerInteractor.swift
  Sources/TuistGraph/Models/CarthageDependencies.swift
  Sources/TuistGraph/Models/Dependencies.swift
  Sources/TuistGraph/Models/SwiftPackageManagerDependencies.swift
  Sources/TuistKit/Commands/DependenciesCommand.swift
  Sources/TuistKit/Services/Dependencies/DependenciesFetchService.swift
  Sources/TuistLoader/Loaders/DependenciesModelLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/CarthageDependencies+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Dependencies+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/SwiftPackageManagerDependencies+ManifestMapper.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockDependenciesModelLoader.swift
  Sources/TuistSupport/Constants.swift
  Tests/ProjectDescriptionTests/Dependencies/CarthageDependenciesTests.swift
  Tests/ProjectDescriptionTests/Dependencies/DependenciesTests.swift
  Tests/ProjectDescriptionTests/Dependencies/SwiftPackageManagerDependenciesTests.swift
  Tests/TuistDependenciesTests/Carthage/CarthageInteractorTests.swift
  Tests/TuistDependenciesTests/DependenciesControllerTests.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/SwiftPackageManagerInteractorTests.swift
  Tests/TuistGraphTests/Models/CarthageDependenciesTests.swift
  Tests/TuistGraphTests/Models/SwiftPackageManagerDependenciesTests.swift
  Tests/TuistKitTests/Services/Dependencies/DependenciesFetchServiceTests.swift
  Tests/TuistKitTests/Services/Dependencies/DependenciesUpdateServiceTests.swift
  Tests/TuistLoaderTests/Loaders/DependenciesModelLoaderTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/DependenciesManifestMapperTests.swift
  projects/tuist/features/dependencies.feature
  projects/tuist/fixtures/app_with_framework_and_tests_and_dependencies/Tuist/Dependencies.swift
  projects/tuist/fixtures/ios_app_with_helpers/Tuist/Dependencies.swift
  projects/website/markdown/docs/dependencies/dependencies.mdx
Labels: domain:chimera

#2805 Make documentation of `tuist bundle` better.
  projects/docs/docs/features/version-management.md
Labels: domain:documentation

#2804 `Dependencies.swift` documentation
  Sources/ProjectDescription/Dependencies/CarthageDependencies.swift
  Sources/ProjectDescription/Dependencies/Dependencies.swift
  projects/docs/docs/commands/dependencies.md
  projects/docs/docs/guides/third-party-dependencies.md
  projects/docs/docs/manifests/dependencies.md
  projects/docs/sidebars.js
Labels: domain:dependencies-swift

#2834 Remove pruned targets from codeCoverageTargets
  CHANGELOG.md
  Sources/TuistCache/GraphMappers/CacheTreeShakingGraphMapper.swift
  Tests/TuistCacheTests/GraphMappers/CacheTreeShakingGraphMapperTests.swift
Labels: domain:generation, type:bug
