Repository tuist/tuist, pull requests merged in 2021-02, with the labels that each got.

#2224 [Chimera] Init documentation
  website/markdown/docs/commands/dependencies.mdx
  website/markdown/docs/dependencies/dependencies.mdx
  website/markdown/docs/links.mdx
Labels: domain:chimera

#2395 [Chimera][SPM] TuistGraph's models
  Sources/TuistGraph/Models/Dependencies.swift
  Sources/TuistGraph/Models/SwiftPackageManagerDependency.swift
  Sources/TuistLoader/Loaders/DependenciesModelLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/Dependencies+ManifestMapper.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockDependenciesModelLoader.swift
  Tests/TuistDependenciesTests/DependenciesControllerTests.swift
  Tests/TuistKitTests/Services/Dependencies/DependenciesFetchServiceTests.swift
  Tests/TuistKitTests/Services/Dependencies/DependenciesUpdateServiceTests.swift
  Tests/TuistLoaderTests/Loaders/DependenciesModelLoaderTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/DependenciesManifestMapperTests.swift
Labels: domain:chimera

#2424 [Chimera] Polishing docs
  website/markdown/docs/dependencies/dependencies.mdx
  website/markdown/docs/links.mdx
Labels: domain:chimera

#2327 Project Plugins: Integrate plugins service.
  CHANGELOG.md
  Package.swift
  Sources/ProjectDescription/Plugin.swift
  Sources/ProjectDescription/PluginLocation.swift
  Sources/TuistCore/Protocols/GeneratorModelLoading.swift
  Sources/TuistGraph/Models/PluginLocation.swift
  Sources/TuistKit/Generator/Generator.swift
  Sources/TuistLoader/Loaders/CachedManifestLoader.swift
  Sources/TuistLoader/Loaders/GeneratorModelLoader.swift
  Sources/TuistLoader/Loaders/ManifestLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/PluginLocation+ManifestMapper.swift
  Sources/TuistLoader/Models/ProjectDescriptionHelpersModule.swift
  Sources/TuistLoader/ProjectDEscriptionHelpers/ProjectDescriptionHelpersBuilder.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockGeneratorModelLoader.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockManifestLoader.swift
  Sources/TuistLoaderTesting/Loaders/TestData/ProjectDescription+TestData.swift
  Sources/TuistPlugin/PluginService.swift
  Sources/TuistPlugin/PluginServiceError.swift
  Sources/TuistPlugin/PluginServicing.swift
  Tests/ProjectDescriptionTests/ConfigTests.swift
  Tests/ProjectDescriptionTests/PluginLocationTests.swift
  Tests/TuistKitTests/ProjectEditor/ProjectEditorMapperTests.swift
  Tests/TuistKitTests/Services/Dependencies/DependenciesFetchServiceTests.swift
  Tests/TuistLoaderIntegrationTests/Loaders/ManifestLoaderIntegrationTests.swift
  Tests/TuistLoaderIntegrationTests/ProjectDescriptionHelpers/ProjectDescriptionHelpersBuilderIntegrationTests.swift
  Tests/TuistPluginTests/PluginServiceTests.swift
  features/plugins.feature
  fixtures/app_with_plugin/LocalPlugin/Plugin.swift
  fixtures/app_with_plugin/LocalPlugin/ProjectDescriptionHelpers/LocalHelper.swift
  fixtures/app_with_plugin/Project.swift
  fixtures/app_with_plugin/Source/AppDelegate.swift
  fixtures/app_with_plugin/Source/TestView.swift
  fixtures/app_with_plugin/Tuist/Config.swift
  fixtures/app_with_plugin/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: plugins

#2530 Fix adding framework targets to AppClip
  CHANGELOG.md
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  fixtures/ios_app_with_appclip/Framework/Sources/SharedCode.swift
  fixtures/ios_app_with_appclip/Project.swift
Labels: automerge
