Repository tuist/tuist, pull requests merged in 2022-09, with the labels that each got.

#4744 Fix `tuist edit` when project contains a Templates folder
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Tests/TuistKitTests/ProjectEditor/ProjectEditorMapperTests.swift
Labels: changelog:fixed

#4740 Add support for performanceAntipatternChecker SchemeDiagnosticsOptions
  Sources/ProjectDescription/RunAction.swift
  Sources/ProjectDescription/SchemeDiagnosticsOption.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  Sources/TuistGenerator/Mappers/AutogeneratedWorkspaceSchemeWorkspaceMapper.swift
  Sources/TuistGraph/Models/SchemeDiagnosticsOption.swift
  Sources/TuistGraphTesting/Models/RunAction+TestData.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/SchemeDiagnosticsOption+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/TestAction+ManifestMapper.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  Tests/TuistGeneratorTests/Linter/SchemeLinterTests.swift
  Tests/TuistGraphTests/Models/RunActionTests.swift
  Tests/TuistIntegrationTests/Generator/TestModelGenerator.swift
  projects/tuist/fixtures/ios_app_with_custom_scheme/App/Project.swift
Labels: changelog:added

#4738 Fix computation of target hash within Xcode beta releases
  Sources/TuistCache/Cache/RetryingCacheStorage.swift
  Sources/TuistCache/ContentHashing/CacheGraphContentHasher.swift
  Sources/TuistSupport/System/System.swift
  Sources/TuistSupport/System/Systeming.swift
  Sources/TuistSupportTesting/Utils/MockSystem.swift
  Tests/TuistAutomationTests/Utilities/BuildGraphInspectorTests.swift
  Tests/TuistCacheIntegrationTests/ContentHashing/ContentHashingIntegrationTests.swift
  Tests/TuistCacheTests/Cache/CacheGraphContentHasherTests.swift
Labels: changelog:fixed

#4658 Add support for Xcode 14 compatible watch application targets
  Package.resolved
  Package.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Sources/TuistGenerator/Settings/DefaultSettingsProvider.swift
  Sources/TuistGraph/Models/Target.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  Tuist/Dependencies.swift
  Tuist/Dependencies/Lockfiles/Package.resolved
  projects/tuist/fixtures/ios_app_with_watch_application/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  projects/tuist/fixtures/ios_app_with_watch_application/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  projects/tuist/fixtures/ios_app_with_watch_application/App/Resources/Assets.xcassets/Contents.json
  projects/tuist/fixtures/ios_app_with_watch_application/App/Sources/ClocksApp.swift
  projects/tuist/fixtures/ios_app_with_watch_application/App/Sources/ContentView.swift
  projects/tuist/fixtures/ios_app_with_watch_application/Project.swift
  projects/tuist/fixtures/ios_app_with_watch_application/WatchApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  projects/tuist/fixtures/ios_app_with_watch_application/WatchApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  projects/tuist/fixtures/ios_app_with_watch_application/WatchApp/Resources/Assets.xcassets/Contents.json
  projects/tuist/fixtures/ios_app_with_watch_application/WatchApp/Sources/ContentView.swift
  projects/tuist/fixtures/ios_app_with_watch_application/WatchApp/Sources/WatchApp.swift
Labels: changelog:added, Xcode14

#4766 Allow AppClip tests and their associated AppClip to include the same static framework
  Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift
  Tests/TuistGeneratorTests/Linter/StaticProductsGraphLinterTests.swift
Labels: changelog:fixed

#4773 Add support for watchOS app extension dependencies
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  projects/tuist/fixtures/ios_app_with_watch_application/FrameworkA/FrameworkA.swift
  projects/tuist/fixtures/ios_app_with_watch_application/Project.swift
  projects/tuist/fixtures/ios_app_with_watch_application/WatchWidgetExtension/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  projects/tuist/fixtures/ios_app_with_watch_application/WatchWidgetExtension/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  projects/tuist/fixtures/ios_app_with_watch_application/WatchWidgetExtension/Resources/Assets.xcassets/Contents.json
  projects/tuist/fixtures/ios_app_with_watch_application/WatchWidgetExtension/Resources/Assets.xcassets/WidgetBackground.colorset/Contents.json
  projects/tuist/fixtures/ios_app_with_watch_application/WatchWidgetExtension/Sources/WatchWidgets.swift
Labels: changelog:added, Xcode14

#4733 Fix SwiftPackageManager copy rule parsing
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistDependenciesTesting/DependenciesGraph/DependenciesGraph+TestData.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/PackageInfoMapperTests.swift
Labels: changelog:fixed

#4770 Fix warnings in dependencies project generated with Xcode 14
  Sources/ProjectDescription/DeploymentTarget.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistGraph/Models/Platform.swift
  Sources/TuistSupportTesting/SwiftPackageManager/PackageInfo+TestData.swift
  Sources/TuistSupportTesting/SwiftPackageManager/PlatformTestInfo.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/PackageInfoMapperTests.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/SwiftPackageManagerGraphGeneratorTests.swift
Labels: domain:dependencies-swift, changelog:fixed, Xcode14
