Repository tuist/tuist, pull requests merged in 2022-06, with the labels that each got.

#4517 Fix handling of `--skip-external-dependencies` parameter in `tuist graph` command when `--format json` is specified
  Sources/TuistGenerator/Extensions/Graph+Extras.swift
  Sources/TuistGenerator/GraphViz/GraphToGraphVizMapper.swift
  Sources/TuistKit/Services/GraphService.swift
  Tests/TuistGeneratorTests/GraphViz/GraphToGraphVizMapperTests.swift
  Tests/TuistKitTests/Dot/MockDotGraphGenerator.swift
Labels: changelog:fixed

#4533 Fix crash during `tuist cache warm` when cloud is configured and a lot of targets are present in the project
  Sources/TuistCloud/Client/CloudClient.swift
Labels: changelog:fixed

#4543 Fix `tuist fetch` for dependencies when using Xcode 14
  Sources/TuistSupport/SwiftPackageManager/PackageInfo.swift
  Sources/TuistSupportTesting/SwiftPackageManager/PackageInfo+TestData.swift
  Tests/TuistSupportTests/SwiftPackageManager/SwiftPackageManagerControllerTests.swift
Labels: type:enhancement, changelog:fixed

#4555 Improve cache errors logging
  Sources/TuistCache/Cache/CacheRemoteStorage.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistSupport/HTTP/FileClient.swift
  Sources/TuistSupport/HTTP/HTTPRequestDispatcher.swift
Labels: type:enhancement, changelog:fixed

#4542 Update target resource name
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  projects/tuist/features/cache-frameworks.feature
  projects/tuist/features/generate-2.feature
Labels: changelog:changed

#4519 Send cache hit rate analytics for cache warm command
  Sources/TuistKit/Commands/Cache/CacheWarmCommand.swift
Labels: domain:cloud, changelog:added

#4565 Fix dispatcher error printed when command execution is short (for example, `tuist version`)
  Sources/TuistAnalytics/TuistAnalytics.swift
  Sources/tuist/TuistApp.swift
Labels: changelog:fixed

#4569 Retry failed remote cache request once on error
  Sources/TuistCache/Cache/RetryingCacheStorage.swift
  Sources/TuistCacheTesting/Cache/Mocks/MockCacheStorage.swift
  Sources/TuistKit/Cache/CacheStorageProvider.swift
  Tests/TuistCacheTests/Cache/RetryingCacheStorageTests.swift
  Tests/TuistKitTests/Cache/CacheStorageProviderTests.swift
Labels: changelog:changed

#4566 Support for not generating Info.plist
  Sources/ProjectDescription/Target.swift
  Sources/TuistLoader/Models+ManifestMappers/InfoPlist+ManifestMapper.swift
  Tests/TuistLoaderTests/Extensions/TuistTestCase+ManifestMappers.swift
  projects/tuist/fixtures/ios_app_with_static_libraries/Modules/A/Info.plist
  projects/tuist/fixtures/ios_app_with_static_libraries/Modules/A/Project.swift
  projects/tuist/fixtures/ios_app_with_static_libraries/Modules/A/Tests.plist
Labels: changelog:added

#4579 Delete old tuistenv when updating
  Sources/TuistEnvKit/Installer/EnvInstaller.swift
  Tests/TuistEnvKitTests/Installer/EnvInstallerTests.swift
Labels: changelog:fixed

#4581 Cloud/default bucket
  Gemfile.lock
  projects/cloud/app/frontend/components/pages/remote-cache/RemoteCachePage.tsx
  projects/cloud/app/frontend/components/pages/remote-cache/RemoteCachePageStore.ts
  projects/cloud/app/frontend/components/pages/remote-cache/__tests__/RemoteCachePageStore.test.ts
  projects/cloud/app/frontend/graphql/S3BucketInfo.graphql
  projects/cloud/app/frontend/graphql/types.ts
  projects/cloud/app/frontend/models/S3Bucket.ts
  projects/cloud/app/graphql/types/s3_bucket_type.rb
  projects/cloud/app/services/project_create_service.rb
  projects/cloud/app/services/s3_bucket_create_service.rb
  projects/cloud/config/credentials.yml.enc
  projects/cloud/config/credentials/production.yml.enc
  projects/cloud/config/credentials/test.yml.enc
  projects/cloud/db/migrate/20220626091301_add_default_remote_cache_storage.rb
  projects/cloud/db/schema.rb
  projects/cloud/schema.graphql
  projects/cloud/schema.json
  projects/cloud/test/services/project_create_service_test.rb
Labels: domain:cloud
