Repository tuist/tuist, pull requests merged in 2022-10, with the labels that each got.

#4782 Fix support for master.key with final newline
  Sources/TuistSigning/SigningCipher.swift
  Tests/TuistSigningTests/SigningCipherTests.swift
Labels: changelog:fixed

#4793 Make `tuistenv` ignore empty `.tuist-bin` folder
  Sources/TuistEnvKit/Versions/VersionResolver.swift
  Tests/TuistEnvKitTests/Versions/VersionResolverTests.swift
Labels: changelog:fixed

#4797 Fix `tuist install` when missing trailing zero
  Sources/TuistDependencies/Carthage/Utils/CarthageController.swift
  Sources/TuistEnvKit/Services/InstallService.swift
  Tests/TuistEnvKitTests/Services/InstallServiceTests.swift
Labels: changelog:fixed

#4795 Cloud landing page
  .github/workflows/cloud.yml
  projects/cloud/.vscode/settings.json
  projects/cloud/app/assets/images/logo.svg
  projects/cloud/app/assets/images/tuist.png
  projects/cloud/app/controllers/root_controller.rb
  projects/cloud/app/frontend/components/icons/GithubIcon.tsx
  projects/cloud/app/frontend/components/icons/TuistIcon.tsx
  projects/cloud/app/frontend/components/icons/index.ts
  projects/cloud/app/frontend/components/pages/commandEventDetail/CommandEventDetailPageStore.ts
  projects/cloud/app/frontend/components/pages/commandEventDetail/__tests__/CommandEventDetailPageStore.test.ts
  projects/cloud/app/frontend/components/pages/dashboard/CommandEventItem.tsx
  projects/cloud/app/frontend/components/pages/dashboard/DashboardPage.tsx
  projects/cloud/app/frontend/components/pages/dashboard/__tests__/DashboardPageStore.test.ts
  projects/cloud/app/frontend/components/pages/landingPage/LandingPage.module.scss
  projects/cloud/app/frontend/components/pages/landingPage/LandingPage.tsx
  projects/cloud/app/frontend/components/pages/landingPage/components/BuildTimesChart/BuildTimesChart.module.scss
  projects/cloud/app/frontend/components/pages/landingPage/components/BuildTimesChart/BuildTimesChart.tsx
  projects/cloud/app/frontend/components/pages/landingPage/components/BuildTimesChart/index.ts
  projects/cloud/app/frontend/components/pages/landingPage/components/CommandEventItemShowcase/CommandEventItemShowcase.module.scss
  projects/cloud/app/frontend/components/pages/landingPage/components/CommandEventItemShowcase/CommandEventItemShowcase.tsx
  projects/cloud/app/frontend/components/pages/landingPage/components/CommandEventItemShowcase/index.ts
  projects/cloud/app/frontend/components/pages/landingPage/components/Footer/Footer.module.scss
  projects/cloud/app/frontend/components/pages/landingPage/components/Footer/Footer.tsx
  projects/cloud/app/frontend/components/pages/landingPage/components/Footer/index.ts
  projects/cloud/app/frontend/components/pages/landingPage/components/HighlightText/HighlightText.module.scss
  projects/cloud/app/frontend/components/pages/landingPage/components/HighlightText/HighlightText.tsx
  projects/cloud/app/frontend/components/pages/landingPage/components/HighlightText/index.ts
  projects/cloud/app/frontend/components/pages/landingPage/components/TopBar/TopBar.module.scss
  projects/cloud/app/frontend/components/pages/landingPage/components/TopBar/TopBar.tsx
  projects/cloud/app/frontend/components/pages/landingPage/components/TopBar/index.ts
  projects/cloud/app/frontend/components/pages/landingPage/components/index.ts
  projects/cloud/app/frontend/entrypoints/landing_page.tsx
  projects/cloud/app/frontend/graphql/CommandEvent.graphql
  projects/cloud/app/frontend/graphql/CommandEventDetail.graphql
  projects/cloud/app/frontend/graphql/types.ts
  projects/cloud/app/frontend/models/CommandEvent.ts
  projects/cloud/app/frontend/models/CommandEventDetail.ts
  projects/cloud/app/frontend/server_side_components/Login.tsx
  projects/cloud/app/frontend/shared/styles.d.ts
  projects/cloud/app/frontend/styles/_common.scss
  projects/cloud/app/graphql/types/command_event_type.rb
  projects/cloud/app/models/command_event.rb
  projects/cloud/app/services/command_cache_hit_rate_service.rb
  projects/cloud/app/views/layouts/landing_page.html.erb
  projects/cloud/config/routes.rb
  projects/cloud/package-lock.json
  projects/cloud/package.json
  projects/cloud/schema.graphql
  projects/cloud/schema.json
  projects/cloud/test/services/command/command_average_service_test.rb
  projects/cloud/test/services/command/command_cache_hit_rate_service_test.rb
  projects/cloud/test/services/command/command_event_create_service_test.rb
  projects/cloud/test/services/command/command_event_fetch_service_test.rb
  projects/cloud/test/services/command/command_events_fetch_service_test.rb
  projects/cloud/tsconfig.json
  projects/cloud/up
  projects/cloud/vite.config.ts
Labels: domain:cloud

#4813 Cloud/remove services
  projects/cloud/Gemfile
  projects/cloud/Gemfile.lock
  projects/cloud/app/views/layouts/app.html.erb
  projects/cloud/app/views/layouts/landing_page.html.erb
  projects/cloud/config/application.rb
  projects/cloud/config/credentials.yml.enc
  projects/cloud/config/credentials/production.yml.enc
  projects/cloud/config/credentials/test.yml.enc
  projects/cloud/config/environments/development.rb
  projects/cloud/config/initializers/slack.rb
  projects/cloud/config/stripe/coupons.rb
  projects/cloud/config/stripe/plans.rb
  projects/cloud/config/stripe/prices.rb
  projects/cloud/config/stripe/products.rb
Labels: domain:cloud

#4814 Cloud/add favicon
  projects/cloud/app/views/layouts/app.html.erb
  projects/cloud/app/views/layouts/application.html.erb
  projects/cloud/app/views/layouts/landing_page.html.erb
  projects/cloud/app/views/layouts/shared/base_application.html.erb
  projects/cloud/public/android-chrome-192x192.png
  projects/cloud/public/android-chrome-512x512.png
  projects/cloud/public/apple-touch-icon.png
  projects/cloud/public/browserconfig.xml
  projects/cloud/public/favicon-16x16.png
  projects/cloud/public/favicon-32x32.png
  projects/cloud/public/favicon.ico
  projects/cloud/public/mstile-144x144.png
  projects/cloud/public/mstile-150x150.png
  projects/cloud/public/mstile-310x150.png
  projects/cloud/public/mstile-310x310.png
  projects/cloud/public/mstile-70x70.png
  projects/cloud/public/safari-pinned-tab.svg
  projects/cloud/public/site.webmanifest
Labels: domain:cloud

#4810 Preserve target order defined in `Project.swift` when generating project
  Sources/TuistCache/Mappers/Graph/TreeShakePrunedTargetsGraphMapper.swift
  Tests/TuistCacheTests/Mappers/Graph/TreeShakePrunedTargetsGraphMapperTests.swift
Labels: changelog:fixed

#4822 Fix for resource synthesizers not added to the `tuist edit` project
  Gemfile.lock
  Sources/TuistKit/ProjectEditor/ProjectEditor.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Sources/TuistLoader/Utils/ResourceSynthesizerPathLocator.swift
  Sources/TuistLoaderTesting/Utils/Mocks/MockResourceSynthesizerPathLocator.swift
  Tests/TuistKitTests/ProjectEditor/Mocks/MockProjectEditorMapper.swift
  Tests/TuistKitTests/ProjectEditor/ProjectEditorMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/ResourceSynthesizer+ManifestMapperTests.swift
Labels: changelog:fixed

#4816 Fix parsing of "1" and "0" as String from environment
  Sources/ProjectDescription/Environment.swift
  Tests/ProjectDescriptionTests/EnvironmentTests.swift
Labels: changelog:fixed

#4815 Use relative path in generated Package.swift
  Sources/TuistDependencies/SwiftPackageManager/SwiftPackageManagerInteractor.swift
  Sources/TuistGraph/Models/Dependencies/SwiftPackageManagerDependencies.swift
  Tests/TuistGraphTests/Models/Dependencies/SwiftPackageManagerDependenciesTests.swift
Labels: changelog:fixed

#4812 Fix regression on SwiftPackageManager packages defining file resources with copy rule
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistDependenciesTesting/DependenciesGraph/DependenciesGraph+TestData.swift
  Sources/TuistSupport/Extensions/AbsolutePath+Extras.swift
  Tests/ProjectDescriptionTests/EnvironmentTests.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/PackageInfoMapperTests.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/SwiftPackageManagerGraphGeneratorTests.swift
  projects/tuist/fixtures/app_with_spm_dependencies/App/Sources/App/AppDelegate.swift
  projects/tuist/fixtures/app_with_spm_dependencies/LocalSwiftPackage/Package.swift
  projects/tuist/fixtures/app_with_spm_dependencies/LocalSwiftPackage/Sources/Styles/Resources/Playground.playground/Contents.swift
  projects/tuist/fixtures/app_with_spm_dependencies/LocalSwiftPackage/Sources/Styles/Resources/Playground.playground/contents.xcplayground
  projects/tuist/fixtures/app_with_spm_dependencies/LocalSwiftPackage/Sources/Styles/Resources/jsonFile.json
  projects/tuist/fixtures/app_with_spm_dependencies/LocalSwiftPackage/Sources/Styles/Resources/www/a/test.js
  projects/tuist/fixtures/app_with_spm_dependencies/LocalSwiftPackage/Sources/Styles/Resources/www/b/test.js
  projects/tuist/fixtures/app_with_spm_dependencies/LocalSwiftPackage/Sources/Styles/Resources/www/test.js
Labels: changelog:fixed

#4811 Fix extra Target configurations are generated when Project has custom configurations
  Sources/TuistGenerator/Mappers/ModuleMapMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ModuleMapMapperTests.swift
Labels: changelog:fixed

#4830 Migrate NewProject to the mobx arch
  projects/cloud/app/frontend/components/App.tsx
  projects/cloud/app/frontend/components/NewProject.tsx
  projects/cloud/app/frontend/components/pages/new-project/NewProjectPage.tsx
  projects/cloud/app/frontend/components/pages/new-project/NewProjectPageStore.tsx
Labels: domain:cloud

#4833 Validate names when creating project or organization
  projects/cloud/app/frontend/components/pages/new-project/NewProjectPage.tsx
  projects/cloud/app/frontend/components/pages/new-project/NewProjectPageStore.ts
  projects/cloud/app/frontend/components/pages/new-project/__tests__/NewProjectPageStore.test.ts
Labels: domain:cloud

#4848 When tuist chooses a simulator device while building, make sure it's available
  Sources/TuistCore/Simulator/SimulatorController.swift
Labels: changelog:fixed

#4847 Fix nonfunctional acceptance test steps
  projects/fourier/lib/fourier/services/test/tuist/acceptance.rb
  projects/fourier/test/fourier/services/test/tuist/acceptance_test.rb
  projects/tuist/features/generate-4.feature
  projects/tuist/features/step_definitions/build.rb
  projects/tuist/features/step_definitions/cache.rb
  projects/tuist/features/step_definitions/shared/xcode.rb
Labels: ruby

#4844 Fix loading of stencils using `{% extends %}`
  Package.resolved
  Package.swift
  Sources/TuistScaffold/TemplateGenerator.swift
  Tuist/Dependencies.swift
  Tuist/Dependencies/Lockfiles/Package.resolved
Labels: changelog:fixed

#4836 Update Community Url in Constants.swift file
  Sources/TuistSupport/Constants.swift
Labels: changelog:fixed
