Repository tuist/tuist, pull requests merged in 2022-12, with the labels that each got.

#4908 Fix linting rules for allowing a watchOS as a dependency of a test target
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Sources/TuistGraph/Models/Target.swift
  projects/tuist/fixtures/ios_app_with_watch_application/FrameworkA/FrameworkA.swift
  projects/tuist/fixtures/ios_app_with_watch_application/FrameworkA/Sources/FrameworkA.swift
  projects/tuist/fixtures/ios_app_with_watch_application/FrameworkA/Tests/FrameworkATests.swift
  projects/tuist/fixtures/ios_app_with_watch_application/Project.swift
  projects/tuist/fixtures/ios_app_with_watch_application/WatchApp/Sources/WatchConfig.swift
  projects/tuist/fixtures/ios_app_with_watch_application/WatchApp/Tests/WatchTests.swift
Labels: changelog:fixed

#4925 Add support for `.rcproject` source files
  Sources/TuistGraph/Models/Target.swift
  Tests/TuistGraphTests/Models/TargetTests.swift
Labels: changelog:added

#4926 Fix generation of resource accessor for AR reference images
  Sources/TuistGenerator/Templates/AssetsTemplate.swift
Labels: changelog:fixed

#4927 Fix appearance of multiple default buckets
  projects/cloud/app/frontend/components/pages/remote-cache/RemoteCachePageStore.ts
  projects/cloud/app/frontend/graphql/S3BucketsQuery.graphql
  projects/cloud/app/frontend/graphql/types.ts
  projects/cloud/app/graphql/types/query_type.rb
  projects/cloud/app/services/s3_buckets_fetch_service.rb
  projects/cloud/schema.graphql
  projects/cloud/schema.json
  projects/cloud/test/services/s3_buckets_fetch_service_test.rb
Labels: domain:cloud

#4930 Add `TargetDependency.target()` helper accepting a target instance
  Sources/ProjectDescription/TargetDependency.swift
  Tests/ProjectDescriptionTests/TargetDependencyTests.swift
Labels: changelog:added

#4936 Set up error handling for creating a project
  projects/cloud/app/controllers/graphql_controller.rb
  projects/cloud/app/frontend/components/pages/new-project/NewProjectPage.tsx
  projects/cloud/app/frontend/components/pages/new-project/NewProjectPageStore.ts
  projects/cloud/app/frontend/graphql/CreateProject.graphql
  projects/cloud/app/frontend/graphql/types.ts
  projects/cloud/app/graphql/mutations/create_project.rb
  projects/cloud/app/graphql/tuist_cloud_schema.rb
  projects/cloud/app/graphql/types/create_project_type.rb
  projects/cloud/app/graphql/types/mutation_type.rb
  projects/cloud/app/graphql/types/user_error.rb
  projects/cloud/app/services/project_create_service.rb
  projects/cloud/schema.graphql
  projects/cloud/schema.json
  projects/cloud/test/services/project_create_service_test.rb
Labels: domain:cloud

#4943 Cloud/tuist image
  Sources/TuistSupport/Utils/HTTPRedirectListener.swift
Labels: domain:cloud

#4945 Fix Cloud analytics data race
  Sources/TuistCache/Cache/Cache.swift
  Sources/TuistCache/Cache/CacheAnalytics.swift
  Sources/TuistCache/Cache/CacheLocalStorage.swift
  Sources/TuistCache/Cache/CacheRemoteStorage.swift
  Sources/TuistKit/Cache/CacheController.swift
Labels: domain:cloud, changelog:fixed

#4946 Cloud/polaris viz upgrade
  projects/cloud/app/frontend/components/pages/dashboard/AverageCommandDurationCard.tsx
  projects/cloud/app/frontend/components/pages/dashboard/DashboardPage.tsx
  projects/cloud/package-lock.json
  projects/cloud/package.json
Labels: domain:cloud
