Repository tuist/tuist, pull requests merged in 2022-05, with the labels that each got.

#4387 Defer the display of warnings untill after project generation
  Sources/TuistCore/Models/LintingIssue.swift
  Sources/TuistKit/Generator/Generator.swift
  Sources/TuistKit/Services/GraphService.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistSigning/SigningInteractor.swift
  Sources/TuistSupportTesting/TestCase/TuistTestCase.swift
  Tests/TuistGraphTests/Models/LintingIssueTests.swift
  Tests/TuistIntegrationTests/Generator/MultipleConfigurationsIntegrationTests.swift
  Tests/TuistKitIntegrationTests/Utils/ManifestGraphLoaderIntegrationTests.swift
  Tests/TuistKitTests/Mocks/MockManifestGraphLoader.swift
Labels: changelog:changed

#4420 Allow AppClips to link Static Frameworks
  Sources/TuistGenerator/Linter/GraphLinter.swift
Labels: changelog:fixed

#4413 Add support for automatic resources in SwiftPackageManager
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistDependenciesTesting/DependenciesGraph/DependenciesGraph+TestData.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/PackageInfoMapperTests.swift
  projects/tuist/fixtures/app_with_spm_dependencies/App/Project.swift
  projects/tuist/fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
  projects/tuist/fixtures/app_with_spm_dependencies/Tuist/Dependencies.swift
Labels: changelog:added

#4355 Fix zipping and unzipping cached frameworks with symlinks
  Package.resolved
  Package.swift
  Project.swift
  Sources/TuistSupport/Utils/FileArchiver.swift
  Sources/TuistSupport/Utils/FileHandler.swift
  Sources/TuistSupport/Utils/FileUnarchiver.swift
  Tests/TuistGeneratorTests/Generator/WorkspaceStructureGeneratorTests.swift
  Tuist/Config.swift
  Tuist/Dependencies.swift
  Tuist/Dependencies/Lockfiles/Package.resolved
  projects/fourier/lib/fourier/services/generate/tuist.rb
  projects/fourier/test/fourier/services/generate/tuist_test.rb
Labels: changelog:fixed

#4425 Add attachDebugger parameter to TestAction.testPlans(...)
  Sources/ProjectDescription/TestAction.swift
Labels: changelog:added

#4388 Add local tuist plugin to `tuist init` generated project
  .github/workflows/tuist.yml
  Templates/AppProject.stencil
  Templates/Config.stencil
  Templates/LocalHelper.stencil
  Templates/Package.stencil
  Templates/Plugin.stencil
  Templates/default/default.swift
  Templates/main.stencil
  Templates/swiftui/swiftui.swift
Labels: changelog:added

#4429 Send cache targets hits analytics metadata
  Package.resolved
  Package.swift
  Project.swift
  Sources/TuistAnalytics/Models/CommandEvent.swift
  Sources/TuistCache/Cache/Cache.swift
  Sources/TuistCache/Cache/CacheAnalytics.swift
  Sources/TuistCache/Cache/CacheLocalStorage.swift
  Sources/TuistCache/Cache/CacheRemoteStorage.swift
  Sources/TuistKit/Commands/GenerateCommand.swift
  Sources/TuistKit/Commands/GraphCommand.swift
  Sources/TuistKit/Commands/InitCommand.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableCommand.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableParametersDelegate.swift
  Tests/TuistAnalyticsTests/Models/TestData/CommandEvent+TestData.swift
  Tests/TuistKitTests/CommandTracking/TrackableCommandTests.swift
  Tuist/Dependencies.swift
  Tuist/Dependencies/Lockfiles/Package.resolved
  projects/cloud/app/controllers/analytics_controller.rb
  projects/cloud/app/frontend/components/pages/commandEventDetail/CommandEventDetailPage.tsx
  projects/cloud/app/frontend/components/pages/commandEventDetail/CommandEventDetailPageStore.ts
  projects/cloud/app/frontend/components/pages/commandEventDetail/__tests__/CommandEventDetailPageStore.test.ts
  projects/cloud/app/frontend/components/pages/commandEventDetail/components/CacheCardSection.tsx
  projects/cloud/app/frontend/graphql/CommandEventDetail.graphql
  projects/cloud/app/frontend/graphql/types.ts
  projects/cloud/app/frontend/models/CommandEventDetail.ts
  projects/cloud/app/graphql/types/command_event_type.rb
  projects/cloud/app/services/command_event_create_service.rb
  projects/cloud/db/migrate/20220505193115_add_cache_metadata_to_command_event.rb
  projects/cloud/db/schema.rb
  projects/cloud/schema.graphql
  projects/cloud/schema.json
  projects/cloud/test/services/command_event_create_service_test.rb
Labels: domain:cloud, changelog:added

#4441 Fix: swap comments inside generated resources finder file
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
Labels: changelog:fixed

#4447 Skip resources warning for SPM dependencies
  Sources/TuistLoader/Models+ManifestMappers/ResourceFileElement+ManifestMapper.swift
Labels: changelog:fixed

#4427 Feature: Add four new SettingsTransformers
  Sources/ProjectDescription/SettingsTransformers.swift
  Tests/ProjectDescriptionTests/SettingsTests.swift
Labels: changelog:added

#4477 Handle missing remote cache storage
  projects/cloud/app/services/cache_service.rb
  projects/cloud/test/services/cache_service_test.rb
Labels: domain:cloud

#4478 Avoid generated file name conflicts by prepending Tuist to them
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistGenerator/Mappers/SynthesizedResourceInterfaceProjectMapper.swift
  Tests/TuistEnvKitTests/Commands/CommandRunnerTests.swift
  Tests/TuistEnvKitTests/Services/LocalServiceTests.swift
  Tests/TuistEnvKitTests/Versions/VersionsControllerTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/SynthesizedResourceInterfaceProjectMapperTests.swift
  Tests/TuistGraphTests/Models/LintingIssueTests.swift
  Tests/TuistSigningTests/SigningInteractorTests.swift
  projects/tuist/features/generate-2.feature
  projects/tuist/features/generate-8.feature
Labels: changelog:changed

#4476 Render cloud errors
  projects/cloud/app/controllers/api_controller.rb
  projects/cloud/app/controllers/cache_controller.rb
  projects/cloud/app/services/project_fetch_service.rb
  projects/cloud/config/routes.rb
  projects/cloud/test/services/project_fetch_service_test.rb
Labels: domain:cloud

#4493 Fixed rendering of generated `Info.plist` in Xcode
  Sources/TuistGenerator/Mappers/GenerateInfoPlistProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/GenerateInfoPlistProjectMapperTests.swift
Labels: changelog:fixed

#4495 Avoid pruning schemes with test plans
  Sources/TuistCache/Mappers/Graph/TreeShakePrunedTargetsGraphMapper.swift
  Tests/TuistCacheTests/Mappers/Graph/TreeShakePrunedTargetsGraphMapperTests.swift
Labels: changelog:fixed

#4497 Fix rendering not found error
  projects/cloud/app/controllers/cache_controller.rb
Labels: domain:cloud

#4498 Handle AWS forbidden error
  projects/cloud/app/services/cache_service.rb
  projects/cloud/test/services/cache_service_test.rb
Labels: domain:cloud

#4480 Fix showing cloud errors
  Sources/TuistCache/Cache/Resources/CloudCacheResourceFactory.swift
  Sources/TuistCacheTesting/Cache/Mocks/MockCloudCacheResponseFactory.swift
Labels: domain:cloud, changelog:fixed

#4503 Generate Package.swift with correct format when custom swift version is specified
  Package.resolved
  Sources/TuistDependencies/Carthage/Utils/CarthageController.swift
  Sources/TuistDependencies/SwiftPackageManager/SwiftPackageManagerInteractor.swift
  Sources/TuistSupport/SwiftPackageManager/SwiftPackageManagerController.swift
  Sources/TuistSupportTesting/SwiftPackageManager/MockSwiftPackageManagerController.swift
  Sources/TuistSupportTesting/Utils/MockGitHandler.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/SwiftPackageManagerInteractorTests.swift
  Tests/TuistKitIntegrationTests/Automation/CacheFrameworkBuilderIntegrationTests.swift
  Tests/TuistSupportTests/SwiftPackageManager/SwiftPackageManagerControllerTests.swift
  Tuist/Config.swift
  Tuist/Dependencies/Lockfiles/Package.resolved
  projects/tuist/fixtures/app_with_spm_dependencies/Tuist/Dependencies.swift
Labels: changelog:fixed
