Repository tuist/tuist, pull requests merged in 2022-07, with the labels that each got.

#4586 Support for custom remote plugins location
  Sources/ProjectDescription/PluginLocation.swift
  Sources/TuistGraph/Models/PluginLocation.swift
  Sources/TuistLoader/Models+ManifestMappers/PluginLocation+ManifestMapper.swift
  Sources/TuistPlugin/PluginService.swift
  Tests/ProjectDescriptionTests/ConfigTests.swift
  Tests/ProjectDescriptionTests/PluginLocationTests.swift
  Tests/TuistKitTests/Services/FetchServiceTests.swift
  Tests/TuistPluginTests/PluginServiceTests.swift
  projects/docs/docs/plugins/using-plugins.md
Labels: domain:plugin, changelog:added

#4587 Fetch remote plugins when loading them
  Sources/TuistKit/Commands/DumpCommand.swift
  Sources/TuistKit/Commands/EditCommand.swift
  Sources/TuistKit/Commands/ListCommand.swift
  Sources/TuistKit/Commands/ScaffoldCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/DumpService.swift
  Sources/TuistKit/Services/EditService.swift
  Sources/TuistKit/Services/FetchService.swift
  Sources/TuistKit/Services/ListService.swift
  Sources/TuistKit/Services/ScaffoldService.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistPlugin/PluginService.swift
  Sources/TuistSupportTesting/Extensions/XCTestCase+Extras.swift
  Tests/TuistKitIntegrationTests/Commands/DumpServiceIntegrationTests.swift
  Tests/TuistKitTests/Services/FetchServiceTests.swift
  Tests/TuistKitTests/Services/ListServiceTests.swift
  Tests/TuistKitTests/Services/ScaffoldServiceTests.swift
  Tests/TuistPluginTests/PluginServiceTests.swift
Labels: domain:plugin, changelog:fixed

#4588 Fix resource bundle signing error when archiving with Xcode 14 beta
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  projects/tuist/fixtures/ios_app_with_static_frameworks_with_resources/Project.swift
Labels: changelog:fixed

#4570 Add multiplatform support for external SPM dependencies
  Sources/TuistCore/Graph/DependenciesGraph.swift
  Sources/TuistDependencies/Carthage/Utils/CarthageGraphGenerator.swift
  Sources/TuistDependencies/DependenciesController.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/SwiftPackageManagerGraphGenerator.swift
  Sources/TuistDependenciesTesting/DependenciesGraph/DependenciesGraph+TestData.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistGenerator/Mappers/SynthesizedResourceInterfaceProjectMapper.swift
  Sources/TuistGraph/DependenciesGraph/DependenciesGraph.swift
  Sources/TuistGraphTesting/DependenciesGraph/DependenciesGraph+TestData.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistLoader/Loaders/ManifestModelConverter.swift
  Sources/TuistLoader/Models+ManifestMappers/Project+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/TargetDependency+ManifestMapper.swift
  Sources/TuistSupportTesting/SwiftPackageManager/PackageInfo+TestData.swift
  Sources/TuistSupportTesting/SwiftPackageManager/PlatformTestInfo.swift
  Tests/TuistDependenciesTests/Carthage/Utils/CarthageGraphGeneratorTests.swift
  Tests/TuistDependenciesTests/DependenciesControllerTests.swift
  Tests/TuistDependenciesTests/DependenciesGraph/DependenciesGraphControllerTests.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/PackageInfoMapperTests.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/SwiftPackageManagerGraphGeneratorTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/TargetDependency+ManifestMapperTests.swift
  projects/tuist/features/dependencies.feature
  projects/tuist/fixtures/app_with_spm_dependencies/App/Project.swift
  projects/tuist/fixtures/app_with_spm_dependencies/App/Sources/Watch/App/.gitkeep
  projects/tuist/fixtures/app_with_spm_dependencies/App/Sources/Watch/Extension/.gitkeep
  projects/tuist/fixtures/app_with_spm_dependencies/Features/FeatureOne/Project.swift
  projects/tuist/fixtures/app_with_spm_dependencies/Tuist/Dependencies.swift
Labels: changelog:added

#4623 Add support to enable frame gpu capture
  Sources/ProjectDescription/RunActionOptions.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistGraph/Models/RunActionOptions.swift
  Sources/TuistLoader/Models+ManifestMappers/RunActionOptions+ManifestMapper.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  projects/tuist/fixtures/ios_app_with_custom_scheme/App/Project.swift
Labels: schemes, changelog:added

#4637 Add support for `--no-open` flag in `tuist graph`
  Sources/TuistKit/Commands/GraphCommand.swift
  Sources/TuistKit/Services/GraphService.swift
  Tests/TuistKitTests/Services/GraphServiceTests.swift
Labels: changelog:added

#4642 Add support for `systemLibrary` SwiftPackageManager targets
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/SwiftPackageManagerModuleMapGenerator.swift
  Sources/TuistSupport/SwiftPackageManager/PackageInfo.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/PackageInfoMapperTests.swift
  projects/tuist/fixtures/app_with_spm_dependencies/App/Project.swift
  projects/tuist/fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
  projects/tuist/fixtures/app_with_spm_dependencies/Tuist/Dependencies.swift
Labels: changelog:added

#4646 Fix for `tuist clean dependencies` cleaning also the `Tuist/Dependencies/Lockfiles` folder
  Sources/TuistCore/Cache/CacheDirectoriesProvider.swift
  Sources/TuistKit/Services/CleanService.swift
  Tests/TuistKitTests/Services/CleanServiceTests.swift
Labels: changelog:fixed
