Repository tuist/tuist, pull requests merged in 2023-03, with the labels that each got.

#5049 Fix CoreData model when `xcdatamodel` file has a name different from the `xcdatamodeld` folder
  Sources/TuistLoader/Models+ManifestMappers/CoreDataModel+ManifestMapper.swift
  projects/tuist/features/dependencies.feature
  projects/tuist/features/step_definitions/build.rb
  projects/tuist/fixtures/app_with_spm_dependencies/App/Project.swift
  projects/tuist/fixtures/app_with_spm_dependencies/Tuist/Dependencies.swift
Labels: changelog:fixed

#5092 Ignore UUID when matching default s3 buckets
  projects/cloud/app/services/s3_buckets_fetch_service.rb
  projects/cloud/test/services/s3_buckets_fetch_service_test.rb
Labels: domain:cloud

#5088 Add support for build rules
  Sources/ProjectDescription/BuildRule+CompilerSpec.swift
  Sources/ProjectDescription/BuildRule+FileType.swift
  Sources/ProjectDescription/BuildRule.swift
  Sources/ProjectDescription/Target.swift
  Sources/TuistGenerator/Generator/BuildRulesGenerator.swift
  Sources/TuistGenerator/Generator/TargetGenerator.swift
  Sources/TuistGraph/Models/BuildRule+CompilerSpec.swift
  Sources/TuistGraph/Models/BuildRule+FileType.swift
  Sources/TuistGraph/Models/BuildRule.swift
  Sources/TuistGraph/Models/Target.swift
  Sources/TuistLoader/Models+ManifestMappers/BuildRule+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/BuildRule.CompilerSpec+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/BuildRule.FileType+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Tests/TuistGraphTests/Models/BuildRule.CompilerSpecTests.swift
  Tests/TuistGraphTests/Models/BuildRule.FileTypeTests.swift
  Tests/TuistGraphTests/Models/BuildRuleTests.swift
  projects/tuist/features/build-rules.feature
  projects/tuist/features/step_definitions/shared/xcode.rb
  projects/tuist/fixtures/app_with_build_rules/App/AppDelegate.swift
  projects/tuist/fixtures/app_with_build_rules/Project.swift
Labels: changelog:added

#5075 Add option to cache as device or simulator xcframeworks
  Sources/TuistCache/Utilities/CacheXCFrameworkBuilder.swift
  Sources/TuistCore/Cache/CacheOutputType.swift
  Sources/TuistCore/Cache/CacheXCFrameworkDestination.swift
  Sources/TuistKit/Cache/CacheController.swift
  Sources/TuistKit/Commands/Cache/CacheOptions.swift
  Sources/TuistKit/Commands/Cache/CachePrintHashesCommand.swift
  Sources/TuistKit/Commands/Cache/CacheWarmCommand.swift
  Sources/TuistKit/Commands/GenerateCommand.swift
  Sources/TuistKit/Generator/GeneratorFactory.swift
  Sources/TuistKit/Services/Cache/CachePrintHashesService.swift
  Sources/TuistKit/Services/Cache/CacheWarmService.swift
  Sources/TuistKit/Services/GenerateService.swift
  Tests/TuistCacheIntegrationTests/ContentHashing/ContentHashingIntegrationTests.swift
  Tests/TuistCacheTests/Cache/CacheGraphContentHasherTests.swift
  Tests/TuistCacheTests/Mappers/Graph/TargetsToCacheBinariesGraphMapperTests.swift
  Tests/TuistKitIntegrationTests/Automation/CacheXCFrameworkBuilderIntegrationTests.swift
  Tests/TuistKitTests/Cache/CacheControllerTests.swift
  Tests/TuistKitTests/Generator/Mocks/MockGeneratorFactory.swift
  Tests/TuistKitTests/Services/Cache/CachePrintHashesServiceTests.swift
  Tests/TuistKitTests/Services/GenerateServiceTests.swift
  projects/docs/docs/commands/cache.md
  projects/docs/docs/commands/generate.md
  projects/tuist/features/cache-xcframeworks.feature
  projects/tuist/features/step_definitions/cache.rb
  projects/tuist/features/step_definitions/shared/tuist.rb
  projects/tuist/features/step_definitions/shared/xcode.rb
  projects/tuist/fixtures/ios_app_with_device_only_xcframework/Lib/Sources/Lib.swift
  projects/tuist/fixtures/ios_app_with_device_only_xcframework/MyTarget/Sources/MyClass.swift
  projects/tuist/fixtures/ios_app_with_device_only_xcframework/Project.swift
  projects/tuist/fixtures/ios_app_with_device_only_xcframework/Tuist/Config.swift
Labels: changelog:added

#5077 Support for `xpc` product type on `macOS`
  Sources/ProjectDescription/Product.swift
  Sources/TuistAutomation/Utilities/TargetRunner.swift
  Sources/TuistCore/Graph/ModelExtensions/Product+Core.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Generator/InfoPlistContentProvider.swift
  Sources/TuistGenerator/GraphViz/NodeStyling.swift
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  Sources/TuistGraph/Models/Product.swift
  Sources/TuistGraph/Models/Target.swift
  Sources/TuistLoader/Models+ManifestMappers/Product+ManifestMapper.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistGraphTests/Models/ProductTests.swift
  projects/tuist/fixtures/macos_app_with_xpc/MainApp/Info.plist
  projects/tuist/fixtures/macos_app_with_xpc/MainApp/Sources/main.swift
  projects/tuist/fixtures/macos_app_with_xpc/Project.swift
  projects/tuist/fixtures/macos_app_with_xpc/XPCApp/Sources/main.swift
Labels: changelog:added

#5082 Fix for `tuist fetch` not failing when run outside of a Tuist project
  Sources/TuistKit/Services/FetchService.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistLoader/Loaders/CachedManifestLoader.swift
  Sources/TuistLoader/Loaders/ManifestLoader.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockManifestLoader.swift
  Tests/TuistKitTests/Services/FetchServiceTests.swift
  Tests/TuistLoaderTests/Loaders/CachedManifestLoaderTests.swift
  projects/tuist/features/edit.feature
Labels: changelog:fixed

#5095 Add support for disabling `Mac (designed for iOS)` destination for iOS deployment target
  Sources/ProjectDescription/DeploymentTarget.swift
  Sources/TuistCache/ContentHashing/DeploymentTargetContentHasher.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
  Sources/TuistGenerator/Generator/InfoPlistContentProvider.swift
  Sources/TuistGraph/Models/DeploymentTarget.swift
  Sources/TuistGraph/Models/Target.swift
  Sources/TuistGraphTesting/Models/Target+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/DeploymentTarget+ManifestMapper.swift
  Tests/TuistCacheIntegrationTests/ContentHashing/ContentHashingIntegrationTests.swift
  Tests/TuistCacheTests/ContentHashing/DeploymentTargetContentHasherTests.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/InfoPlistContentProviderTests.swift
  Tests/TuistGraphTests/Models/DeploymentTargetTests.swift
  Tests/TuistGraphTests/Models/TargetTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/DeploymentTarget+ManifestMapperTests.swift
  Tuist/Dependencies/Lockfiles/Package.resolved
Labels: changelog:added

#5119 Fix link phase for tvOS top shelf extension
  Sources/TuistGraph/Models/Target.swift
Labels: changelog:fixed
