Repository tuist/tuist, pull requests merged in 2023-10, with the labels that each got.

#5459 Fix linking of precompiled static xcframeworks that are transitive dependencies of a static framework
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistGenerator/Linter/PackageLinter.swift
  Sources/TuistGraph/Graph/GraphDependency.swift
  Sources/TuistSupport/Extensions/URL+Extras.swift
  Tests/TuistCoreTests/Graph/GraphDependencyTests.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
Labels: changelog:fixed

#5473 Fix invitation link
  Sources/TuistCloudTesting/Services/MockCreateOrganizationInviteService.swift
  Sources/TuistKit/Services/Cloud/CloudOrganizationInviteService.swift
  Tests/TuistKitTests/Services/Cloud/CloudOrganizationInviteServiceTests.swift
Labels: domain:cloud, changelog:fixed

#5467 Add tuist cloud analytics command
  Sources/TuistKit/Commands/Cloud/CloudAnalyticsCommand.swift
  Sources/TuistKit/Commands/CloudCommand.swift
  Sources/TuistKit/Services/Cloud/CloudAnalyticsService.swift
Labels: changelog:added

#5487 Deployment target derived correctly for tuist test
  Package.swift
  Sources/TuistCore/Simulator/SimulatorController.swift
  Tests/TuistCoreTests/Simulator/SimulatorControllerTests.swift
Labels: changelog:fixed, bounty

#5492 Add support for SwiftPackageManager `enableExperimentalFeature` target setting
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistSupport/SwiftPackageManager/PackageInfo.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/PackageInfoMapperTests.swift
Labels: changelog:added

#5500 Instruct the asset locators on how to look up assets when `tuist` is installed by Homebrew
  Sources/TuistCore/Utils/BinaryLocator.swift
  Sources/TuistLoader/Utils/ResourceLocator.swift
  Sources/TuistScaffold/TemplatesDirectoryLocator.swift
Labels: changelog:added

#5509 Reuse HTTP connection when interacting with Tuist Cloud
  .gitattributes
  .tuist-cloud-version
Labels: changelog:fixed

#5501 Reuse binaries for tuist test, generate test project in the current working directory
  .tuist-cloud-version
  Sources/TuistAutomation/WorkspaceMappers/AutomationPathWorkspaceMapper.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Generator/GeneratorFactory.swift
  Sources/TuistKit/Mappers/Factories/GraphMapperFactory.swift
  Sources/TuistKit/Mappers/Factories/WorkspaceMapperFactory.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistAutomationTests/WorkspaceMappers/AutomationPathWorkspaceMapperTests.swift
  Tests/TuistKitTests/Generator/Mocks/MockGeneratorFactory.swift
  Tests/TuistKitTests/Mappers/Factories/GraphMapperFactoryTests.swift
  Tests/TuistKitTests/Mappers/Factories/WorkspaceMapperFactoryTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:added

#5499 Locate root directory where Workspace.swift file is located
  Sources/TuistCore/Utils/RootDirectoryLocator.swift
  Sources/TuistCoreTesting/Utils/MockRootDirectoryLocator.swift
  Sources/TuistLoader/Utils/ManifestFilesLocator.swift
  Tests/TuistCoreIntegrationTests/RootDirectoryLocatorIntegrationTests.swift
  Tests/TuistLoaderTests/Utils/ManifestFilesLocatorTests.swift
  projects/tuist/features/edit.feature
  projects/tuist/fixtures/workspace_with_multiple_projects/ProjectA/.gitignore
  projects/tuist/fixtures/workspace_with_multiple_projects/ProjectA/Project.swift
  projects/tuist/fixtures/workspace_with_multiple_projects/ProjectA/Targets/App/Sources/AppDelegate.swift
  projects/tuist/fixtures/workspace_with_multiple_projects/ProjectA/Targets/App/Tests/AppTests.swift
  projects/tuist/fixtures/workspace_with_multiple_projects/ProjectB/.gitignore
  projects/tuist/fixtures/workspace_with_multiple_projects/ProjectB/Project.swift
  projects/tuist/fixtures/workspace_with_multiple_projects/ProjectB/Targets/App/Sources/AppDelegate.swift
  projects/tuist/fixtures/workspace_with_multiple_projects/ProjectB/Targets/App/Tests/AppTests.swift
  projects/tuist/fixtures/workspace_with_multiple_projects/Workspace.swift
Labels: type:bug, bounty

#5493 Add support for symbolset resources in default resource synthesizer
  Sources/TuistGenerator/Templates/AssetsTemplate.swift
Labels: changelog:added

#5528 Allow empty `.gitkeep` files in templates
  Sources/TuistScaffold/TemplateGenerator.swift
  Tests/TuistScaffoldTests/TemplateGeneratorTests.swift
Labels: changelog:added

#5525 Support optional frameworks and xcframeworks
  Sources/ProjectAutomation/TargetDependency.swift
  Sources/ProjectDescription/TargetDependency.swift
  Sources/TuistCore/Graph/GraphDependencyReference.swift
  Sources/TuistCore/Graph/GraphLoader.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/MetadataProviders/FrameworkMetadataProvider.swift
  Sources/TuistCore/MetadataProviders/XCFrameworkMetadataProvider.swift
  Sources/TuistCore/NodeLoaders/FrameworkLoader.swift
  Sources/TuistCore/NodeLoaders/XCFrameworkLoader.swift
  Sources/TuistCoreTesting/Graph/GraphDependencyReference+TestData.swift
  Sources/TuistCoreTesting/MetadataProviders/MockFrameworkMetadataProvider.swift
  Sources/TuistCoreTesting/MetadataProviders/MockXCFrameworkMetadataProvider.swift
  Sources/TuistCoreTesting/NodeLoaders/MockFrameworkNodeLoader.swift
  Sources/TuistCoreTesting/NodeLoaders/MockXCFrameworkLoader.swift
  Sources/TuistGenerator/Generator/LinkGenerator.swift
  Sources/TuistGenerator/Generator/ProjectFileElements.swift
  Sources/TuistGenerator/GraphViz/GraphToGraphVizMapper.swift
  Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Sources/TuistGenerator/Utils/EmbedScriptGenerator.swift
  Sources/TuistGraph/Graph/GraphDependency.swift
  Sources/TuistGraph/Models/Metadata/FrameworkMetadata.swift
  Sources/TuistGraph/Models/Metadata/XCFrameworkMetadata.swift
  Sources/TuistGraph/Models/TargetDependency.swift
  Sources/TuistGraphTesting/DependenciesGraph/DependenciesGraph+TestData.swift
  Sources/TuistGraphTesting/Graph/GraphDependency+TestData.swift
  Sources/TuistGraphTesting/Models/Metadata/FrameworkMetadata+TestData.swift
  Sources/TuistGraphTesting/Models/Metadata/XCFrameworkMetadata+TestData.swift
  Sources/TuistKit/Services/GraphService.swift
  Sources/TuistLoader/Models+ManifestMappers/FrameworkStatus+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/TargetDependency+ManifestMapper.swift
  Tests/TuistCoreIntegrationTests/MetadataProviders/PrecompiledMetadataProviderIntegrationTests.swift
  Tests/TuistCoreTests/Graph/GraphLoaderTests.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistCoreTests/MetadataProviders/FrameworkMetadataProviderTests.swift
  Tests/TuistCoreTests/MetadataProviders/XCFrameworkMetadataProviderTests.swift
  Tests/TuistCoreTests/NodeLoaders/FrameworkLoaderTests.swift
  Tests/TuistCoreTests/NodeLoaders/XCFrameworkLoaderTests.swift
  Tests/TuistDependenciesTests/DependenciesControllerTests.swift
  Tests/TuistDependenciesTests/DependenciesGraph/DependenciesGraphControllerTests.swift
  Tests/TuistGeneratorTests/Generator/LinkGeneratorTests.swift
  Tests/TuistGraphTests/Models/TargetDependencyTests.swift
  Tests/TuistIntegrationTests/Generator/TestModelGenerator.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/TargetDependency+ManifestMapperTests.swift
Labels: changelog:added
