Repository tuist/tuist, pull requests merged in 2023-06, with the labels that each got.

#5005 Add support for ExtensionKit extensions
  Sources/ProjectDescription/Product.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/Graph/ModelExtensions/Product+Core.swift
  Sources/TuistCore/GraphTraverser/GraphTraversing.swift
  Sources/TuistCoreTesting/GraphTraverser/MockGraphTraverser.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Generator/InfoPlistContentProvider.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistGenerator/GraphViz/NodeStyling.swift
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift
  Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  Sources/TuistGenerator/Utils/SettingsHelper.swift
  Sources/TuistGraph/Models/Product.swift
  Sources/TuistGraph/Models/Target.swift
  Sources/TuistLoader/Models+ManifestMappers/Product+ManifestMapper.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistGraphTests/Models/ProductTests.swift
  projects/tuist/features/generate-4.feature
  projects/tuist/features/step_definitions/generate.rb
  projects/tuist/features/step_definitions/shared/xcode.rb
  projects/tuist/features/support/xcode.rb
  projects/tuist/fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtension.swift
  projects/tuist/fixtures/ios_app_with_extensions/AppIntentExtension/Sources/AppIntentExtensionExtension.swift
  projects/tuist/fixtures/ios_app_with_extensions/Project.swift
Labels: changelog:added

#5225 Set BuildIndependentTargetsInParallel setting to true by default
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistDependenciesTesting/DependenciesGraph/DependenciesGraph+TestData.swift
  Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/PackageInfoMapperTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectDescriptorGeneratorTests.swift
Labels: changelog:changed

#5229 Mark bundle product type doesn't support sources for all platforms
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift
Labels: changelog:fixed

#5239 Fix bucket limit
  .github/workflows/tuist.yml
  .vscode/launch.json
  projects/cloud/app/frontend/components/App.tsx
  projects/cloud/app/frontend/components/pages/remote-cache/RemoteCachePage.tsx
  projects/cloud/app/frontend/components/pages/remote-cache/RemoteCachePageStore.ts
  projects/cloud/app/frontend/components/pages/remote-cache/__tests__/RemoteCachePageStore.test.ts
  projects/cloud/app/frontend/components/pages/remote-cache/components/CreateBucketModal/CreateBucketModal.tsx
  projects/cloud/app/frontend/components/pages/remote-cache/components/CreateBucketModal/CreateBucketStore.ts
  projects/cloud/app/frontend/components/pages/remote-cache/components/CreateBucketModal/__tests__/CreateBucketStore.test.ts
  projects/cloud/app/frontend/components/pages/remote-cache/components/CreateBucketModal/index.ts
  projects/cloud/app/frontend/components/pages/remote-cache/components/EditBucketForm.tsx
  projects/cloud/app/frontend/components/pages/remote-cache/components/index.ts
  projects/cloud/app/frontend/graphql/S3BucketInfo.graphql
  projects/cloud/app/frontend/graphql/types.ts
  projects/cloud/app/frontend/models/Project.ts
  projects/cloud/app/frontend/models/S3Bucket.ts
  projects/cloud/app/frontend/models/index.ts
  projects/cloud/app/frontend/stores/ProjectStore.ts
  projects/cloud/app/graphql/mutations/change_remote_cache_storage.rb
  projects/cloud/app/graphql/mutations/clear_remote_cache_storage.rb
  projects/cloud/app/graphql/types/mutation_type.rb
  projects/cloud/app/graphql/types/project_type.rb
  projects/cloud/app/graphql/types/s3_bucket_type.rb
  projects/cloud/app/models/project.rb
  projects/cloud/app/models/s3_bucket.rb
  projects/cloud/app/services/cache_clear_service.rb
  projects/cloud/app/services/cache_service.rb
  projects/cloud/app/services/command_cache_hit_rate_service.rb
  projects/cloud/app/services/project_change_remote_cache_storage_service.rb
  projects/cloud/app/services/project_create_service.rb
  projects/cloud/app/services/project_delete_service.rb
  projects/cloud/app/services/s3_bucket_clear_service.rb
  projects/cloud/app/services/s3_bucket_create_service.rb
  projects/cloud/app/services/s3_buckets_fetch_service.rb
  projects/cloud/app/services/s3_client_service.rb
  projects/cloud/db/migrate/20230601202210_remove_default_project.rb
  projects/cloud/db/schema.rb
  projects/cloud/schema.graphql
  projects/cloud/schema.json
  projects/cloud/test/services/cache_clear_service_test.rb
  projects/cloud/test/services/cache_service_test.rb
  projects/cloud/test/services/project_change_remote_cache_storage_service_test.rb
  projects/cloud/test/services/project_create_service_test.rb
  projects/cloud/test/services/project_delete_service_test.rb
  projects/cloud/test/services/s3_bucket_create_service_test.rb
  projects/cloud/test/services/s3_buckets_fetch_service_test.rb
Labels: domain:cloud
