Repository tuist/tuist, pull requests merged in 2023-11, with the labels that each got.

#5521 Add support for specifying the RunAction `launchStyle`
  Sources/ProjectDescription/LaunchStyle.swift
  Sources/ProjectDescription/RunAction.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistGraph/Models/LaunchStyle.swift
  Sources/TuistGraph/Models/RunAction.swift
  Sources/TuistGraphTesting/Models/RunAction+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/LaunchStyle+ManifestMappers.swift
  Sources/TuistLoader/Models+ManifestMappers/RunAction+ManifestMapper.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
Labels: changelog:added

#5535 Add support for parsing macOS provisioning profiles
  Sources/TuistSigning/ProvisioningProfile/ProvisioningProfile.swift
Labels: changelog:added

#5530 AssetTemplate's Images struct is missing when synthesizing only symbolset resources
  Sources/TuistGenerator/Templates/AssetsTemplate.swift
Labels: changelog:fixed

#5539 Add support for Swift Macros using the native integration
  Sources/ProjectAutomation/TargetDependency.swift
  Sources/ProjectDescription/TargetDependency.swift
  Sources/TuistCore/Graph/CircularDependencyLinter.swift
  Sources/TuistCore/Graph/GraphLoader.swift
  Sources/TuistGenerator/Generator/LinkGenerator.swift
  Sources/TuistGenerator/GraphViz/GraphToGraphVizMapper.swift
  Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Sources/TuistGenerator/Mappers/ModuleMapMapper.swift
  Sources/TuistGraph/Graph/GraphDependency.swift
  Sources/TuistGraph/Models/TargetDependency.swift
  Sources/TuistGraphTesting/Graph/GraphDependency+TestData.swift
  Sources/TuistKit/Services/GraphService.swift
  Sources/TuistLoader/Models+ManifestMappers/TargetDependency+ManifestMapper.swift
  Tests/TuistCoreTests/Graph/GraphLoaderTests.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistGeneratorIntegrationTests/Generator/SwiftPackageManagerInteractorTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectDescriptorGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectFileElementsTests.swift
  Tests/TuistGeneratorTests/Linter/StaticProductsGraphLinterTests.swift
  projects/tuist/features/build.feature
  projects/tuist/fixtures/framework_with_swift_macro/.package.resolved
  projects/tuist/fixtures/framework_with_swift_macro/Project.swift
  projects/tuist/fixtures/framework_with_swift_macro/Sources/Framework.swift
Labels: changelog:added

#5575 Flatten the workspace groups hierarchy for dependencies
  Sources/TuistGenerator/Generator/WorkspaceDescriptorGenerator.swift
  Sources/TuistGenerator/Generator/WorkspaceStructureGenerator.swift
  Tests/TuistGeneratorTests/Generator/WorkspaceStructureGeneratorTests.swift
Labels: changelog:added

#5577 Automatically use the github-actions renderer
  Sources/TuistCore/Utils/BinaryLocator.swift
  Sources/TuistSupport/Utils/Environment.swift
  Sources/TuistSupportTesting/Utils/MockEnvironment.swift
Labels: changelog:added

#5581 Config.swift defaults to `https://cloud.tuist.io` as the Tuist Cloud URL
  Sources/ProjectDescription/Cloud.swift
Labels: changelog:added

#5584 Increase the timeout for uploading and downloading files
  Sources/TuistSupport/HTTP/FileClient.swift
Labels: changelog:changed

#5563 Fix mapping of `registry` SwiftPackageManager dependencies
  Sources/TuistDependencies/SwiftPackageManager/Utils/SwiftPackageManagerGraphGenerator.swift
Labels: changelog:fixed

#5609 Fix warnings with including `.stencil` files when running `tuist edit`. Fixes #5603
  Sources/TuistKit/ProjectEditor/ProjectEditor.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Tests/TuistKitTests/ProjectEditor/Mocks/MockProjectEditorMapper.swift
  Tests/TuistKitTests/ProjectEditor/ProjectEditorMapperTests.swift
Labels: changelog:fixed

#5615 Fix usage of --test-targets
  .github/workflows/tuist.yml
  Project.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
  Tests/TuistTestAcceptanceTests/TestAcceptanceTests.swift
  features/step_definitions/test.rb
  features/test-plan.feature
  features/test.feature
  fixtures/app_with_framework_and_tests/FrameworkTests/FrameworkTests.swift
  fixtures/app_with_test_plan/All.xctestplan
  fixtures/app_with_test_plan/Project.swift
  fixtures/app_with_test_plan/Targets/tvOSFramework/Sources/tvOSFramework.swift
  fixtures/app_with_test_plan/Targets/tvOSFramework/Tests/tvOSFrameworkTests.swift
Labels: changelog:fixed
