Repository tuist/tuist, pull requests merged in 2023-08, with the labels that each got.

#5312 Add tuist cloud project create command
  .swiftformat
  .swiftlint.yml
  Package.resolved
  Package.swift
  Project.swift
  Sources/TuistCloud/Client/AuthenticationMiddleware.swift
  Sources/TuistCloud/Models/CloudProject.swift
  Sources/TuistCloud/OpenAPI/Client.swift
  Sources/TuistCloud/OpenAPI/Types.swift
  Sources/TuistCloud/OpenAPI/cloud.yml
  Sources/TuistCloud/Services/CloudURLService.swift
  Sources/TuistCloud/Services/CreateProjectServiceNext.swift
  Sources/TuistKit/Commands/Cloud/CloudProjectCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudProjectCreateCommand.swift
  Sources/TuistKit/Commands/CloudCommand.swift
  Sources/TuistKit/Services/Cloud/CloudInitService.swift
  Sources/TuistKit/Services/Cloud/CloudProjectCreateService.swift
  Tuist/Dependencies.swift
  Tuist/Dependencies/Lockfiles/Package.resolved
  projects/tuist/fixtures/ios_app_with_templates/Tuist/ProjectDescriptionHelpers/Platform.swift
Labels: changelog:added

#5316 Add tuist cloud project list command
  Sources/TuistCloud/Client/Client+Cloud.swift
  Sources/TuistCloud/Models/CloudProject.swift
  Sources/TuistCloud/OpenAPI/Client.swift
  Sources/TuistCloud/OpenAPI/Types.swift
  Sources/TuistCloud/OpenAPI/cloud.yml
  Sources/TuistCloud/Services/CreateProjectServiceNext.swift
  Sources/TuistCloud/Services/ListProjectsService.swift
  Sources/TuistCloudTesting/Services/MockCleanRemoteCacheStorageService.swift
  Sources/TuistCloudTesting/Services/MockCreateProjectService.swift
  Sources/TuistCloudTesting/Services/MockListProjectsService.swift
  Sources/TuistKit/Commands/Cloud/CloudProjectCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudProjectListCommand.swift
  Sources/TuistKit/Services/Cloud/CloudProjectCreateService.swift
  Sources/TuistKit/Services/Cloud/CloudProjectListService.swift
  Tests/TuistKitTests/Services/Cloud/CloudProjectListServiceTests.swift
Labels: changelog:added

#5326 Add cloud organization create command
  Sources/TuistCloud/Models/CloudOrganization.swift
  Sources/TuistCloud/OpenAPI/Client.swift
  Sources/TuistCloud/OpenAPI/Types.swift
  Sources/TuistCloud/OpenAPI/cloud.yml
  Sources/TuistCloud/Services/CreateOrganizationService.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationCreateCommand.swift
  Sources/TuistKit/Commands/CloudCommand.swift
  Sources/TuistKit/Services/Cloud/CloudOrganizationCreateService.swift
Labels: changelog:added

#5321 Add tuist cloud project delete command
  Sources/TuistCloud/OpenAPI/Client.swift
  Sources/TuistCloud/OpenAPI/Types.swift
  Sources/TuistCloud/OpenAPI/cloud.yml
  Sources/TuistCloud/Services/CreateProjectServiceNext.swift
  Sources/TuistCloud/Services/DeleteProjectService.swift
  Sources/TuistCloud/Services/GetProjectService.swift
  Sources/TuistCloud/Services/ListProjectsService.swift
  Sources/TuistCloudTesting/Services/MockDeleteProjectService.swift
  Sources/TuistCloudTesting/Services/MockGetProjectService.swift
  Sources/TuistCloudTesting/Services/MockListProjectsService.swift
  Sources/TuistKit/Commands/Cloud/CloudAuthCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudProjectCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudProjectDeleteCommand.swift
  Sources/TuistKit/Services/Cloud/CloudAuthService.swift
  Sources/TuistKit/Services/Cloud/CloudProjectDeleteService.swift
  Sources/TuistSupport/Credentials/CredentialsStore.swift
  Sources/TuistSupportTesting/Credentials/MockCredentialsStore.swift
  Tests/TuistKitTests/Services/Cloud/CloudAuthServiceTests.swift
  Tests/TuistKitTests/Services/Cloud/CloudProjectDeleteServiceTests.swift
  Tests/TuistKitTests/Services/Cloud/CloudProjectListServiceTests.swift
Labels: domain:cloud, changelog:added

#5330 Add tuist cloud organization delete command
  Sources/TuistCloud/OpenAPI/Client.swift
  Sources/TuistCloud/OpenAPI/Types.swift
  Sources/TuistCloud/OpenAPI/cloud.yml
  Sources/TuistCloud/Services/DeleteOrganizationService.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationDeleteCommand.swift
  Sources/TuistKit/Services/Cloud/CloudOrganizationDeleteService.swift
Labels: domain:cloud, changelog:added

#5334 Add cloud organization remove invite command
  Sources/TuistCloud/OpenAPI/Client.swift
  Sources/TuistCloud/OpenAPI/Types.swift
  Sources/TuistCloud/OpenAPI/cloud.yml
  Sources/TuistCloud/Services/CancelOrganizationInviteService.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationRemoveCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationRemoveInviteCommand.swift
  Sources/TuistKit/Services/Cloud/CloudOrganizationRemoveInviteService.swift
Labels: domain:cloud, changelog:added

#5335 Add cloud organization remove member command
  Sources/TuistCloud/OpenAPI/Client.swift
  Sources/TuistCloud/OpenAPI/Types.swift
  Sources/TuistCloud/OpenAPI/cloud.yml
  Sources/TuistCloud/Services/RemoveOrganizationMemberService.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationRemoveCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationRemoveMemberCommand.swift
  Sources/TuistKit/Services/Cloud/CloudOrganizationRemoveMemberService.swift
Labels: domain:cloud, changelog:added

#5336 Add cloud organization update member command
  Sources/TuistCloud/OpenAPI/Client.swift
  Sources/TuistCloud/OpenAPI/Types.swift
  Sources/TuistCloud/OpenAPI/cloud.yml
  Sources/TuistCloud/Services/UpdateOrganizationMemberService.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationUpdateCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationUpdateMemberCommand.swift
  Sources/TuistKit/Services/Cloud/CloudOrganizationUpdateMemberService.swift
Labels: domain:cloud, changelog:added

#5338 Rewrite cloud commands to use REST instead of GraphQL
  .gitignore
  Package.resolved
  Package.swift
  Project.swift
  Sources/TuistCloud/OpenAPI/Client.swift
  Sources/TuistCloud/OpenAPI/Types.swift
  Sources/TuistCloud/OpenAPI/cloud.yml
  Sources/TuistCloud/Services/CleanCacheService.swift
  Sources/TuistCloud/Services/CleanRemoteCacheStorageService.swift
  Sources/TuistCloud/Services/CreateProjectService.swift
  Sources/TuistCloud/Services/CreateProjectServiceNext.swift
  Sources/TuistCloud/Services/DeleteProjectService.swift
  Sources/TuistCloud/Utilities/Apollo+Client.swift
  Sources/TuistCloud/graphql/ClearRemoteCacheStorage.graphql
  Sources/TuistCloud/graphql/ClearRemoteCacheStorageMutation.graphql.swift
  Sources/TuistCloud/graphql/CreateProject.graphql
  Sources/TuistCloud/graphql/CreateProjectMutation.graphql.swift
  Sources/TuistCloudSchema/InputObjects/ClearRemoteCacheStorageInput.graphql.swift
  Sources/TuistCloudSchema/InputObjects/CreateProjectInput.graphql.swift
  Sources/TuistCloudSchema/Objects/ClearRemoteCacheStorage.graphql.swift
  Sources/TuistCloudSchema/Objects/CreateProject.graphql.swift
  Sources/TuistCloudSchema/Objects/Mutation.graphql.swift
  Sources/TuistCloudSchema/Objects/Project.graphql.swift
  Sources/TuistCloudSchema/Objects/S3Bucket.graphql.swift
  Sources/TuistCloudSchema/Objects/UserError.graphql.swift
  Sources/TuistCloudSchema/SchemaConfiguration.swift
  Sources/TuistCloudSchema/SchemaMetadata.graphql.swift
  Sources/TuistCloudTesting/Services/MockCleanRemoteCacheStorageService.swift
  Sources/TuistCloudTesting/Services/MockCreateProjectService.swift
  Sources/TuistKit/Commands/Cloud/CloudInitCommand.swift
  Sources/TuistKit/Services/Cloud/CloudCleanService.swift
  Sources/TuistKit/Services/Cloud/CloudInitService.swift
  Sources/TuistKit/Services/Cloud/CloudProjectCreateService.swift
  Tests/TuistKitTests/Services/Cloud/CloudCleanServiceTests.swift
  Tests/TuistKitTests/Services/Cloud/CloudInitServiceTests.swift
  Tuist/Dependencies.swift
  Tuist/Dependencies/Lockfiles/Package.resolved
Labels: domain:cloud

#5342 Add `--skip-cache` argument to `tuist generate`
  Sources/TuistCache/Mappers/Graph/TargetsToCacheBinariesGraphMapper.swift
  Sources/TuistKit/Commands/GenerateCommand.swift
  Sources/TuistKit/Generator/GeneratorFactory.swift
  Sources/TuistKit/Mappers/Factories/GraphMapperFactory.swift
  Sources/TuistKit/Services/GenerateService.swift
  Tests/TuistCacheTests/Mappers/Graph/TargetsToCacheBinariesGraphMapperTests.swift
  Tests/TuistKitTests/Generator/Mocks/MockGeneratorFactory.swift
  Tests/TuistKitTests/Mappers/Factories/GraphMapperFactoryTests.swift
  Tests/TuistKitTests/Services/GenerateServiceTests.swift
Labels: changelog:added

#5302 Fix tuist cache warm --xcframeworks of SPM frameworks due to missing macCatalyst availability
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistDependenciesTesting/DependenciesGraph/DependenciesGraph+TestData.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/PackageInfoMapperTests.swift
Labels: changelog:fixed

#5352 Allow mlpackage files to be included into source files
  Sources/TuistGraph/Models/Target.swift
  Tests/TuistGraphTests/Models/TargetTests.swift
Labels: changelog:added

#5358 Fix issue #5237 by adding `toValidSwiftIdentifier()` extension to `String`
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistSupport/Extensions/String+Extras.swift
  Tests/TuistSupportTests/Extensions/String+ExtrasTests.swift
Labels: changelog:fixed

#5366 Fix cloud auth race condition
  Sources/TuistSupport/Utils/HTTPRedirectListener.swift
Labels: domain:cloud, changelog:fixed

#5367 Print URL when inviting a user
  Sources/TuistCloud/Models/CloudInvitation.swift
  Sources/TuistCloud/OpenAPI/Types.swift
  Sources/TuistCloud/OpenAPI/cloud.yml
  Sources/TuistCloudTesting/Models/CloudInvitation+TestData.swift
  Sources/TuistKit/Services/Cloud/CloudOrganizationInviteService.swift
Labels: domain:cloud, changelog:changed

#5368 Add support for TUIST_CLOUD_URL to override the default Cloud URL
  Sources/TuistCloud/Services/CloudURLService.swift
  Sources/TuistSupport/Constants.swift
Labels: domain:cloud, changelog:added

#5378 Hoist `tuistfixturegen` to the root and rename it to `tuistfixturegenerator`
  .github/workflows/checks.yml
  .github/workflows/fixturegen.yml
  Package.swift
  Project.swift
  Sources/tuistfixturegenerator/Commands/GenerateCommand.swift
  Sources/tuistfixturegenerator/Generator/Generator.swift
  Sources/tuistfixturegenerator/Generator/GeneratorConfig.swift
  Sources/tuistfixturegenerator/Templates/ManifestTemplate.swift
  Sources/tuistfixturegenerator/Templates/SourceTemplate.swift
  Sources/tuistfixturegenerator/main.swift
  projects/fixturegen/.gitignore
  projects/fixturegen/Package.resolved
  projects/fixturegen/Package.swift
  projects/fourier/lib/fourier/commands/lint.rb
  projects/fourier/lib/fourier/constants.rb
  projects/fourier/lib/fourier/services/build/fixture.rb
  projects/fourier/lib/fourier/services/lint/fixturegen.rb
  projects/fourier/lib/fourier/utilities/system.rb
  projects/fourier/test/fourier/services/lint/fixturegen_test.rb
Labels: changelog:changed

#5299 Add support for SPM `Build Tool Plug-ins`
  Package.resolved
  Package.swift
  Sources/ProjectAutomation/TargetDependency.swift
  Sources/ProjectDescription/TargetDependency.swift
  Sources/TuistCache/ContentHashing/DependenciesContentHasher.swift
  Sources/TuistCore/Graph/CircularDependencyLinter.swift
  Sources/TuistCore/Graph/GraphLoader.swift
  Sources/TuistGenerator/Generator/LinkGenerator.swift
  Sources/TuistGenerator/GraphViz/GraphToGraphVizMapper.swift
  Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Sources/TuistGenerator/Mappers/ModuleMapMapper.swift
  Sources/TuistGraph/Graph/GraphDependency.swift
  Sources/TuistGraph/Models/TargetDependency.swift
  Sources/TuistKit/Services/GraphService.swift
  Sources/TuistLoader/Models+ManifestMappers/TargetDependency+ManifestMapper.swift
  Tests/TuistCoreTests/Graph/GraphLoaderTests.swift
  Tests/TuistGeneratorTests/Linter/StaticProductsGraphLinterTests.swift
  Tuist/Dependencies.swift
  Tuist/Dependencies/Lockfiles/Package.resolved
  projects/tuist/fixtures/ios_app_with_actions/App/Project.swift
Labels: changelog:added
