Repository tuist/tuist, pull requests merged in 2023-12, with the labels that each got.

#5617 Improve the group hierarchy for cache binaries
  Sources/TuistCore/Cache/CacheCategory.swift
  Sources/TuistCore/Cache/CacheDirectoriesProvider.swift
  Sources/TuistGenerator/Generator/ProjectFileElements.swift
  Sources/TuistGenerator/Generator/ProjectGroups.swift
  Tests/TuistGeneratorTests/Generator/LinkGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectFileElementsTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectGroupsTests.swift
Labels: changelog:changed

#5627 Fix for package platform parsing to be case insensitive
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfo+graphPlatform.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/SettingsMapper.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/PackageInfoGraphPlatformTests.swift
Labels: changelog:fixed

#5628 [Multiplatform] Add support for multi platform conditions for source and resource files
  Makefile
  Sources/ProjectDescription/PlatformCondition.swift
  Sources/ProjectDescription/ResourceFileElement.swift
  Sources/ProjectDescription/SourceFilesList.swift
  Sources/ProjectDescription/TargetDependency.swift
  Sources/TuistCore/Graph/GraphDependencyReference.swift
  Sources/TuistCore/Graph/GraphLoader.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift
  Sources/TuistCore/GraphTraverser/GraphTraversing.swift
  Sources/TuistCoreTesting/Graph/GraphDependencyReference+TestData.swift
  Sources/TuistCoreTesting/GraphTraverser/MockGraphTraverser.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistGenerator/Extensions/Xcodeproj+Extras.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Generator/LinkGenerator.swift
  Sources/TuistGraph/Graph/Graph.swift
  Sources/TuistGraph/Models/PlatformCondition.swift
  Sources/TuistGraph/Models/ResourceFileElement.swift
  Sources/TuistGraph/Models/SourceFile.swift
  Sources/TuistGraph/Models/SourceFileGlob.swift
  Sources/TuistGraph/Models/TargetDependency.swift
  Sources/TuistGraphTesting/Graph/Graph+TestData.swift
  Sources/TuistGraphTesting/Models/Condition+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/ResourceFileElement+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/TargetDependency+ManifestMapper.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistGeneratorTests/Extensions/Xcodeproj+ExtrasTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistGraphTests/Models/TargetDependencyTests.swift
  fixtures/multiplatform_app_with_sdk/Framework/Shared/FrameworkClass.swift
  fixtures/multiplatform_app_with_sdk/Framework/iOS/FrameworkClassiOS.swift
  fixtures/multiplatform_app_with_sdk/Framework/macOS/FrameworkClassmacOS.swift
  fixtures/multiplatform_app_with_sdk/Framework/tvOS/FrameworkClasstvOS.swift
  fixtures/multiplatform_app_with_sdk/Project.swift
Labels: changelog:added

#5637 Revert using `Workspace.swift` to detect the root directory
  Sources/TuistCore/Utils/RootDirectoryLocator.swift
  Sources/TuistCoreTesting/Utils/MockRootDirectoryLocator.swift
  Sources/TuistLoader/Utils/ManifestFilesLocator.swift
  Tests/TuistCoreIntegrationTests/RootDirectoryLocatorIntegrationTests.swift
  Tests/TuistLoaderTests/Utils/ManifestFilesLocatorTests.swift
  features/edit.feature
Labels: changelog:fixed

#5643 Fix regression in platform specific settings mapping
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/SettingsMapper.swift
  Sources/TuistGraph/Models/Settings.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/SettingsMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#5635 Add flag to opt out from beautifying `xcodebuild` logs
  .github/workflows/tuist.yml
  Sources/TuistAutomation/Utilities/TargetBuilder.swift
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
  Sources/TuistAutomationTesting/Utilities/MockTargetBuilder.swift
  Sources/TuistCore/Automation/Extensions/AsyncThrowingStream+XcodeBuildOutput.swift
  Sources/TuistCore/Automation/XcodeBuildControlling.swift
  Sources/TuistCoreTesting/Automation/MockXcodeBuildController.swift
  Sources/TuistKit/Commands/BuildCommand.swift
  Sources/TuistKit/Commands/RunCommand.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Services/BuildService.swift
  Sources/TuistKit/Services/RunService.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistAutomationTests/Utilities/TargetBuilderTests.swift
  Tests/TuistAutomationTests/XcodeBuild/XcodeBuildControllerTests.swift
  Tests/TuistKitTests/Services/BuildServiceTests.swift
  Tests/TuistKitTests/Services/RunServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:added

#5662 Prevent duplicated warnings
  Sources/TuistSupport/Utils/WarningController.swift
Labels: changelog:fixed

#5673 Fix --skip-test-targets with a test class
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:fixed

#5697 Export the `TuistDependencies` product
  Package.swift
Labels: changelog:added

#5696 Add option to export raw xcodebuild logs to a given file
  Sources/TuistAutomation/Utilities/TargetBuilder.swift
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
  Sources/TuistAutomationTesting/Utilities/MockTargetBuilder.swift
  Sources/TuistCore/Automation/XcodeBuildControlling.swift
  Sources/TuistCoreTesting/Automation/MockXcodeBuildController.swift
  Sources/TuistKit/Commands/BuildCommand.swift
  Sources/TuistKit/Commands/RunCommand.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Services/BuildService.swift
  Sources/TuistKit/Services/RunService.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistSupport/Logging/FileLogger.swift
  Tests/TuistAutomationTests/Utilities/TargetBuilderTests.swift
  Tests/TuistAutomationTests/XcodeBuild/XcodeBuildControllerTests.swift
  Tests/TuistKitTests/Services/BuildServiceTests.swift
  Tests/TuistKitTests/Services/RunServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: type:enhancement

#5691 [Multiplatform] Enhance build phases to account for platform conditions
  Package.swift
  Project.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/GraphTraverser/GraphTraversing.swift
  Sources/TuistCoreTesting/GraphTraverser/MockGraphTraverser.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGraph/Models/Target.swift
  Tests/TuistBuildAcceptanceTests/BuildAcceptanceTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  fixtures/multiplatform_app_with_extension/.gitignore
  fixtures/multiplatform_app_with_extension/App/Sources/TuistApp.swift
  fixtures/multiplatform_app_with_extension/Extensions/WidgetExtension/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/multiplatform_app_with_extension/Extensions/WidgetExtension/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/multiplatform_app_with_extension/Extensions/WidgetExtension/Resources/Assets.xcassets/Contents.json
  fixtures/multiplatform_app_with_extension/Extensions/WidgetExtension/Resources/Assets.xcassets/WidgetBackground.colorset/Contents.json
  fixtures/multiplatform_app_with_extension/Extensions/WidgetExtension/Sources/Widget.swift
  fixtures/multiplatform_app_with_extension/Project.swift
  fixtures/multiplatform_app_with_extension/Support/App-Info.plist
  fixtures/multiplatform_app_with_extension/Tuist/Config.swift
  fixtures/multiplatform_app_with_extension/WatchApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/multiplatform_app_with_extension/WatchApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/multiplatform_app_with_extension/WatchApp/Resources/Assets.xcassets/Contents.json
  fixtures/multiplatform_app_with_extension/WatchApp/Sources/WatchApp.swift
Labels: changelog:added

#5704 Fix a bug that causes platform from being wrongly stripped
  Sources/TuistDependencies/Mappers/ExternalProjectsPlatformNarrowerGraphMapper.swift
  Tests/TuistDependenciesTests/Mappers/ExternalProjectsPlatformNarrowerGraphMapperTests.swift
Labels: changelog:fixed
