Repository tuist/tuist, pull requests merged in 2023-01, with the labels that each got.

#4942 Sets sending of analytics to cloud dashboard as default behavior
  Sources/ProjectDescription/Cloud.swift
  Sources/TuistAnalytics/Backends/TuistAnalyticsCloudBackend.swift
  Sources/TuistGraph/Models/Cloud.swift
  Sources/TuistLoader/Models+ManifestMappers/Cloud+ManifestMapper.swift
  Tests/TuistAnalyticsTests/Backends/TuistAnalyticsCloudBackendTests.swift
Labels: changelog:changed

#4956 Add string prefix for new cloud buckets
  projects/cloud/app/services/project_create_service.rb
  projects/cloud/test/services/project_create_service_test.rb
Labels: domain:cloud

#4940 Support for defining a dependency file in run script phases
  Sources/ProjectDescription/TargetScript.swift
  Sources/TuistCache/ContentHashing/TargetScriptsContentHasher.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGraph/Models/TargetScript.swift
  Sources/TuistLoader/Models+ManifestMappers/TargetAction+ManifestMapper.swift
  Sources/TuistLoaderTesting/Loaders/TestData/ProjectDescription+TestData.swift
  Tests/TuistCacheTests/ContentHashing/TargetScriptsContentHasherTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  projects/tuist/features/generate-4.feature
  projects/tuist/features/step_definitions/shared/xcode.rb
  projects/tuist/fixtures/ios_app_with_actions/App/Project.swift
  projects/tuist/fixtures/ios_app_with_actions/App/script-with-dependency.sh
Labels: changelog:added

#4971 Fix support for template attributes located in a remote git repository in `tuist init`
  Sources/TuistKit/Commands/InitCommand.swift
  Sources/TuistKit/Services/InitService.swift
  Sources/TuistLoader/Loaders/TemplateGitLoader.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockTemplateGitLoader.swift
  Tests/TuistKitTests/Services/InitServiceTests.swift
  Tests/TuistLoaderTests/Loaders/TemplateGitLoaderTests.swift
Labels: changelog:fixed

#4985 Support for period (`.`) character in `Target.productName`
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift
Labels: changelog:fixed

#4986 Fix xcframeworks caching for frameworks which include documentation catalogs
  Sources/TuistCache/Utilities/CacheXCFrameworkBuilder.swift
  Tests/Fixtures/Frameworks/Documentation/Documentation.docc/Documentation.md
  Tests/Fixtures/Frameworks/Documentation/Documentation.h
  Tests/Fixtures/Frameworks/Documentation/Documentation.swift
  Tests/Fixtures/Frameworks/Documentation/Info.plist
  Tests/Fixtures/Frameworks/Frameworks.xcodeproj/project.pbxproj
  Tests/Fixtures/Frameworks/Frameworks.xcodeproj/xcshareddata/xcschemes/Documentation-iOS.xcscheme
  Tests/TuistKitIntegrationTests/Automation/CacheXCFrameworkBuilderIntegrationTests.swift
Labels: changelog:fixed

#4983 Add support for language and region to autogenerated schemes
  Sources/ProjectDescription/ProjectOptions.swift
  Sources/ProjectDescription/RunActionOptions.swift
  Sources/ProjectDescription/WorkspaceGenerationOptions.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/ManifestMapping/ProjectOption+ManifestMapper.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  Sources/TuistGenerator/Mappers/AutogeneratedWorkspaceSchemeWorkspaceMapper.swift
  Sources/TuistGraph/Models/ProjectOptions.swift
  Sources/TuistGraph/Models/RunActionOptions.swift
  Sources/TuistGraph/Models/Workspace.swift
  Sources/TuistGraph/Models/WorkspaceGenerationOptions.swift
  Sources/TuistGraphTesting/Models/Workspace+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/ProjectOption+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/RunActionOptions+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/WorkspaceGenerationOptions+ManifestMapper.swift
  Tests/TuistGeneratorTests/GraphMappers/AutogeneratedWorkspaceSchemeWorkspaceMapperTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift
  projects/tuist/fixtures/project_with_test_and_run_locales/Project.swift
  projects/tuist/fixtures/workspace_with_test_locale/Project.swift
  projects/tuist/fixtures/workspace_with_test_locale/Workspace.swift
Labels: changelog:added
