Repository tuist/tuist, pull requests merged in 2023-09, with the labels that each got.

#5364 Add glob support for `inputPaths` in `TargetScript`
  Sources/ProjectDescription/TargetScript.swift
  Sources/TuistLoader/Models+ManifestMappers/TargetAction+ManifestMapper.swift
  Sources/TuistLoaderTesting/Loaders/TestData/ProjectDescription+TestData.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/TargetScript+ManifestMapperTests.swift
Labels: changelog:changed

#5402 Fix StoreKit Configuration file paths
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  projects/tuist/fixtures/ios_app_with_custom_scheme/App/Config/ProjectStoreKitConfig.storekit
  projects/tuist/fixtures/ios_app_with_custom_scheme/App/Project.swift
  projects/tuist/fixtures/ios_app_with_custom_scheme/Workspace.swift
Labels: changelog:fixed

#5245 Add configuration option to control location of SPM clones with Xcode native integration
  Sources/ProjectDescription/ConfigGenerationOptions.swift
  Sources/TuistGenerator/Utils/SwiftPackageManagerInteractor.swift
  Sources/TuistGraph/Models/ConfigGenerationOptions.swift
  Sources/TuistGraphTesting/Models/Config+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/Config+ManifestMapper.swift
  Tests/ProjectDescriptionTests/ConfigTests.swift
  Tests/TuistGeneratorIntegrationTests/Generator/SwiftPackageManagerInteractorTests.swift
Labels: type:enhancement

#5135 Add test plan support within Tuist test
  Sources/TuistAutomation/Utilities/BuildGraphInspector.swift
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
  Sources/TuistAutomationTesting/Utilities/MockBuildGraphInspector.swift
  Sources/TuistCache/Extensions/GraphTraverser+Extras.swift
  Sources/TuistCache/Mappers/Graph/FocusTargetsGraphMappers.swift
  Sources/TuistCache/Mappers/Graph/TestsCacheGraphMapper.swift
  Sources/TuistCore/Automation/XcodeBuildControlling.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/GraphTraverser/GraphTraversing.swift
  Sources/TuistCore/Models/TestIdentifier.swift
  Sources/TuistCore/Models/TestPlanConfiguration.swift
  Sources/TuistCoreTesting/Automation/MockXcodeBuildController.swift
  Sources/TuistCoreTesting/GraphTraverser/MockGraphTraverser.swift
  Sources/TuistGraph/Models/TestPlan.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Generator/GeneratorFactory.swift
  Sources/TuistKit/Mappers/Factories/GraphMapperFactory.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistLoader/Models+ManifestMappers/TestAction+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/TestPlan+ManifestMapper.swift
  Sources/TuistLoader/Models/XCTestPlan.swift
  Tests/TuistAutomationTests/Utilities/BuildGraphInspectorTests.swift
  Tests/TuistAutomationTests/XcodeBuild/XcodeBuildControllerTests.swift
  Tests/TuistCacheTests/Extensions/GraphTraverser+ExtrasTests.swift
  Tests/TuistCacheTests/Mappers/Graph/TestsCacheGraphMapperTests.swift
  Tests/TuistCacheTests/Mappers/Graph/TreeShakePrunedTargetsGraphMapperTests.swift
  Tests/TuistCoreTests/Models/TestIdentifierTests.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  Tests/TuistGraphTests/Models/TestPlanTests.swift
  Tests/TuistKitTests/Generator/Mocks/MockGeneratorFactory.swift
  Tests/TuistKitTests/Mappers/Factories/GraphMapperFactoryTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
  projects/tuist/features/step_definitions/test.rb
  projects/tuist/features/test-plan.feature
  projects/tuist/fixtures/app_with_test_plan/.gitignore
  projects/tuist/fixtures/app_with_test_plan/All.xctestplan
  projects/tuist/fixtures/app_with_test_plan/Project.swift
  projects/tuist/fixtures/app_with_test_plan/Targets/App/Sources/AppDelegate.swift
  projects/tuist/fixtures/app_with_test_plan/Targets/App/Tests/AppTests.swift
  projects/tuist/fixtures/app_with_test_plan/Targets/MacFramework/Sources/MacFramework.swift
  projects/tuist/fixtures/app_with_test_plan/Targets/MacFramework/Tests/MacFrameworkTests.swift
  projects/tuist/fixtures/app_with_test_plan/Targets/tvOSFramework/Sources/tvOSFramework.swift
  projects/tuist/fixtures/app_with_test_plan/Targets/tvOSFramework/Tests/tvOSFrameworkTests.swift
Labels: changelog:added

#5308 Fix parsing of SwiftPackageManager dependencies including `macro` targets
  Sources/TuistSupport/SwiftPackageManager/PackageInfo.swift
  projects/tuist/fixtures/app_with_spm_dependencies/App/Project.swift
  projects/tuist/fixtures/app_with_spm_dependencies/StringifyMacro/.gitignore
  projects/tuist/fixtures/app_with_spm_dependencies/StringifyMacro/Package.resolved
  projects/tuist/fixtures/app_with_spm_dependencies/StringifyMacro/Package.swift
  projects/tuist/fixtures/app_with_spm_dependencies/StringifyMacro/Sources/Stringify/Stringify.swift
  projects/tuist/fixtures/app_with_spm_dependencies/StringifyMacro/Sources/StringifyClient/main.swift
  projects/tuist/fixtures/app_with_spm_dependencies/StringifyMacro/Sources/StringifyMacros/StringifyMacro.swift
  projects/tuist/fixtures/app_with_spm_dependencies/StringifyMacro/Tests/StringifyTests/StringifyTests.swift
  projects/tuist/fixtures/app_with_spm_dependencies/Tuist/Dependencies.swift
Labels: changelog:fixed

#5391 Support preferredScreenCaptureFormat in test options
  Package.resolved
  Package.swift
  Sources/ProjectDescription/ProjectOptions.swift
  Sources/ProjectDescription/ScreenCaptureFormat.swift
  Sources/ProjectDescription/TestActionOptions.swift
  Sources/ProjectDescription/WorkspaceGenerationOptions.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/ManifestMapping/ProjectOption+ManifestMapper.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  Sources/TuistGenerator/Mappers/AutogeneratedWorkspaceSchemeWorkspaceMapper.swift
  Sources/TuistGraph/Models/ProjectOptions.swift
  Sources/TuistGraph/Models/ScreenCaptureFormat.swift
  Sources/TuistGraph/Models/TestAction.swift
  Sources/TuistGraph/Models/Workspace.swift
  Sources/TuistGraph/Models/WorkspaceGenerationOptions.swift
  Sources/TuistGraphTesting/Models/TestAction+TestData.swift
  Sources/TuistGraphTesting/Models/Workspace+TestData.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistLoader/Models+ManifestMappers/ProjectOption+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/ScreenCaptureFormat+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/TestAction+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/WorkspaceGenerationOptions+ManifestMapper.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  Tests/TuistGeneratorTests/GraphMappers/AutogeneratedWorkspaceSchemeWorkspaceMapperTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift
  Tuist/Dependencies.swift
  projects/tuist/fixtures/ios_app_with_custom_scheme/Workspace.swift
  projects/tuist/fixtures/ios_app_with_tests/Project.swift
Labels: changelog:added

#5232 Allow specifying target environment variables as disabled
  Sources/ProjectDescription/Arguments.swift
  Sources/ProjectDescription/EnvironmentVariable.swift
  Sources/ProjectDescription/Target.swift
  Sources/TuistCache/ContentHashing/TargetContentHasher.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  Sources/TuistGraph/Models/Arguments.swift
  Sources/TuistGraph/Models/EnvironmentVariable.swift
  Sources/TuistGraph/Models/Target.swift
  Sources/TuistGraphTesting/Models/Arguments+TestData.swift
  Sources/TuistGraphTesting/Models/Target+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/Arguments+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/EnvironmentVariable+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Sources/tuist/tuist.docc/Tutorials/Tuist/Getting-Started/Create-Project/inital-project-templates.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift
  Tests/TuistGraphTests/Models/ArgumentsTests.swift
  Tests/TuistGraphTests/Models/ProfileActionTests.swift
  Tests/TuistGraphTests/Models/RunActionTests.swift
  Tests/TuistIntegrationTests/Generator/TestModelGenerator.swift
  Tests/TuistLoaderTests/Extensions/TuistTestCase+ManifestMappers.swift
Labels: changelog:added

#5377 File generation for Entitlements
  Sources/ProjectDescription/Entitlements.swift
  Sources/ProjectDescription/InfoPlist.swift
  Sources/ProjectDescription/Plist.swift
  Sources/ProjectDescription/Target.swift
  Sources/TuistCache/ContentHashing/InfoPlistContentHasher.swift
  Sources/TuistCache/ContentHashing/PlistContentHasher.swift
  Sources/TuistCache/ContentHashing/TargetContentHasher.swift
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
  Sources/TuistGenerator/Generator/InfoPlistContentProvider.swift
  Sources/TuistGenerator/Generator/ProjectFileElements.swift
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Sources/TuistGenerator/Mappers/GenerateEntitlementsProjectMapper.swift
  Sources/TuistGraph/Models/InfoPlist.swift
  Sources/TuistGraph/Models/Plist.swift
  Sources/TuistGraph/Models/Target.swift
  Sources/TuistGraphTesting/Models/Target+TestData.swift
  Sources/TuistKit/Mappers/Factories/ProjectMapperFactory.swift
  Sources/TuistLoader/Models+ManifestMappers/Entitlements+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Plist+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Sources/TuistLoaderTesting/Loaders/TestData/ProjectDescription+TestData.swift
  Sources/TuistSupport/Constants.swift
  Templates/Project+Templates.stencil
  Tests/TuistCacheTests/ContentHashing/PlistContentHasherTests.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/Mocks/MockInfoPlistContentProvider.swift
  Tests/TuistGeneratorTests/Generator/ProjectFileElementsTests.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift
  Tests/TuistLoaderTests/Extensions/TuistTestCase+ManifestMappers.swift
  projects/tuist/fixtures/app_with_tasks/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  projects/tuist/fixtures/ios_app_with_frameworks/Framework1/Project.swift
  projects/tuist/fixtures/ios_app_with_helpers/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: changelog:added

#5415 Fix wording in documentation regarding Entitlements
  Sources/ProjectDescription/Entitlements.swift
  Sources/ProjectDescription/Plist.swift
  Sources/TuistGenerator/Mappers/GenerateEntitlementsProjectMapper.swift
  Sources/TuistGraph/Models/Plist.swift
Labels: domain:documentation

#5424 Fix missing input file paths in generated script build phases
  Sources/TuistLoader/Models+ManifestMappers/TargetAction+ManifestMapper.swift
  Sources/TuistLoader/Models/FileListGlob+Unfold.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/TargetScript+ManifestMapperTests.swift
Labels: changelog:fixed

#5412 Fix cache issues when the graph contains transitive static libraries and frameworks
  Sources/TuistCore/Graph/GraphTraverser.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
Labels: changelog:fixed

#5432 Fixed a bug in the uninstall script
  script/uninstall
Labels: changelog:fixed

#5420 5354 workaround for Xcode 15 RC bug
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
Labels: changelog:fixed

#5431 `XPC` product can embed dynamic libraries and frameworks
  .swiftformat
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  projects/tuist/fixtures/macos_app_with_xpc/DynamicFramework/Sources/DynamicFramework.swift
  projects/tuist/fixtures/macos_app_with_xpc/Project.swift
  projects/tuist/fixtures/macos_app_with_xpc/StaticFramework/Sources/StaticFramework.swift
Labels: changelog:added

#5438 Add supported platforms build setting when specifying multiple destinations
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
Labels: changelog:added

#5351 Introduce mergeable libraries
  Sources/ProjectDescription/MergedBinaryType.swift
  Sources/ProjectDescription/Target.swift
  Sources/TuistCore/Graph/GraphDependencyReference.swift
  Sources/TuistCore/Graph/GraphLoader.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/MetadataProviders/XCFrameworkMetadataProvider.swift
  Sources/TuistCore/NodeLoaders/XCFrameworkLoader.swift
  Sources/TuistGenerator/GraphViz/GraphToGraphVizMapper.swift
  Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Sources/TuistGenerator/Settings/DefaultSettingsProvider.swift
  Sources/TuistGraph/Graph/GraphDependency.swift
  Sources/TuistGraph/Models/MergedBinaryType.swift
  Sources/TuistGraph/Models/Metadata/XCFrameworkMetadata.swift
  Sources/TuistGraph/Models/Target.swift
  Sources/TuistGraph/Models/XCFrameworkInfoPlist.swift
  Sources/TuistGraphTesting/Graph/GraphDependency+TestData.swift
  Sources/TuistGraphTesting/Models/Metadata/XCFrameworkMetadata+TestData.swift
  Sources/TuistGraphTesting/Models/Target+TestData.swift
  Sources/TuistGraphTesting/Models/XCFrameworkInfoPlist+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/MergedBinaryType+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Tests/Fixtures/MyMergeableFramework.xcframework/Info.plist
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-arm64/MyMergeableFramework.framework/Headers/MyMergeableFramework-Swift.h
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-arm64/MyMergeableFramework.framework/Info.plist
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-arm64/MyMergeableFramework.framework/Modules/MyMergeableFramework.swiftmodule/arm64-apple-ios.abi.json
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-arm64/MyMergeableFramework.framework/Modules/MyMergeableFramework.swiftmodule/arm64-apple-ios.private.swiftinterface
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-arm64/MyMergeableFramework.framework/Modules/MyMergeableFramework.swiftmodule/arm64-apple-ios.swiftdoc
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-arm64/MyMergeableFramework.framework/Modules/MyMergeableFramework.swiftmodule/arm64-apple-ios.swiftinterface
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-arm64/MyMergeableFramework.framework/Modules/MyMergeableFramework.swiftmodule/arm64-apple-ios.swiftmodule
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-arm64/MyMergeableFramework.framework/Modules/module.modulemap
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-arm64/MyMergeableFramework.framework/MyMergeableFramework
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-x86_64-simulator/MyMergeableFramework.framework/Headers/MyMergeableFramework-Swift.h
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-x86_64-simulator/MyMergeableFramework.framework/Info.plist
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-x86_64-simulator/MyMergeableFramework.framework/Modules/MyMergeableFramework.swiftmodule/x86_64-apple-ios-simulator.abi.json
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-x86_64-simulator/MyMergeableFramework.framework/Modules/MyMergeableFramework.swiftmodule/x86_64-apple-ios-simulator.private.swiftinterface
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-x86_64-simulator/MyMergeableFramework.framework/Modules/MyMergeableFramework.swiftmodule/x86_64-apple-ios-simulator.swiftdoc
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-x86_64-simulator/MyMergeableFramework.framework/Modules/MyMergeableFramework.swiftmodule/x86_64-apple-ios-simulator.swiftinterface
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-x86_64-simulator/MyMergeableFramework.framework/Modules/MyMergeableFramework.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-x86_64-simulator/MyMergeableFramework.framework/Modules/module.modulemap
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-x86_64-simulator/MyMergeableFramework.framework/MyMergeableFramework
  Tests/Fixtures/MyMergeableFramework.xcframework/ios-x86_64-simulator/MyMergeableFramework.framework/_CodeSignature/CodeResources
  Tests/TuistCoreTests/Graph/GraphLoaderTests.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistCoreTests/MetadataProviders/XCFrameworkMetadataProviderTests.swift
  Tests/TuistCoreTests/NodeLoaders/XCFrameworkLoaderTests.swift
  Tests/TuistGeneratorTests/Generator/LinkGeneratorTests.swift
  Tests/TuistGeneratorTests/Settings/DefaultSettingsProviderTests.swift
Labels: changelog:added

#5306 Support for specifying the target for variable expansion in the RunAction
  Sources/ProjectDescription/RunAction.swift
  Sources/ProjectDescription/TestAction.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistGenerator/Linter/SchemeLinter.swift
  Sources/TuistGraph/Models/RunAction.swift
  Sources/TuistGraphTesting/Models/RunAction+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/RunAction+ManifestMapper.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  projects/tuist/fixtures/ios_app_with_custom_scheme/Workspace.swift
Labels: changelog:added

#5454 Generate TuistStrings+Module for correct localisation strings file
  Sources/TuistGenerator/Mappers/SynthesizedResourceInterfaceProjectMapper.swift
  projects/tuist/features/generate-2.feature
  projects/tuist/features/step_definitions/generate.rb
  projects/tuist/fixtures/ios_app_with_custom_development_region/App/Resources/en.lproj/Greetings.strings
  projects/tuist/fixtures/ios_app_with_custom_development_region/App/Resources/fr.lproj/Greetings.strings
  projects/tuist/fixtures/ios_app_with_custom_development_region/App/Sources/AppDelegate.swift
  projects/tuist/fixtures/ios_app_with_custom_development_region/Project.swift
Labels: changelog:fixed

#5446 Add tuist cloud organization billing command
  Sources/TuistCloud/Models/CloudOrganization.swift
  Sources/TuistCloud/OpenAPI/Types.swift
  Sources/TuistCloud/OpenAPI/cloud.yml
  Sources/TuistCloudTesting/Models/CloudOrganization+TestData.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationBillingCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudOrganizationCommand.swift
  Sources/TuistKit/Services/Cloud/CloudOrganizationBillingService.swift
  Sources/TuistKit/Services/Cloud/CloudOrganizationShowService.swift
  Tests/TuistKitTests/Services/Cloud/CloudOrganizationShowServiceTests.swift
Labels: changelog:added

#5441 Support linting multi-destination targets
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
Labels: changelog:added

#5455 Fix iOS min deployment version for `Dependencies.swift` in Xcode 15
  Project.swift
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistGraph/Models/Platform.swift
Labels: changelog:fixed
