Repository tuist/tuist, pull requests merged in 2024-10, with the labels that each got.

#6745 Allow embedding `.extensionKitExtension` targets into macOS apps
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  fixtures/macos_app_with_extensions/App/Resources/App.appextensionpoint
  fixtures/macos_app_with_extensions/ExtensionKitExtension/Sources/Extension.swift
  fixtures/macos_app_with_extensions/Project.swift
Labels: changelog:changed

#6784 Fix tuist commands failing due to a git error
  Sources/TuistKit/Commands/TrackableCommand/CommandEventFactory.swift
  Sources/TuistSupport/Utils/GitController.swift
  Tests/TuistKitTests/CommandTracking/CommandEventFactoryTests.swift
Labels: changelog:fixed

#6792 Fix tuist init failure due to missing ProjectDescriptionHelpers
  Sources/TuistCore/Utils/RootDirectoryLocator.swift
  Sources/TuistGenerator/Linter/EnvironmentLinter.swift
  Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift
  Sources/TuistKit/ProjectEditor/ProjectEditor.swift
  Sources/TuistKit/Services/CleanService.swift
  Sources/TuistKit/Services/InitService.swift
  Sources/TuistKit/Services/InstallService.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistKit/Utils/TuistVersionLoader.swift
  Sources/TuistLoader/Loaders/ConfigLoader.swift
  Sources/TuistLoader/Loaders/ManifestModelConverter.swift
  Sources/TuistLoader/Loaders/PackageSettingsLoader.swift
  Sources/TuistLoader/Loaders/RecursiveManifestLoader.swift
  Sources/TuistLoader/Loaders/TemplateLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/Config+ManifestMapper.swift
  Sources/TuistLoader/Models/GeneratorPaths.swift
  Sources/TuistLoader/Utils/HelpersDirectoryLocator.swift
  Sources/TuistLoader/Utils/ManifestFilesLocator.swift
  Sources/TuistLoader/Utils/ResourceSynthesizerPathLocator.swift
  Sources/TuistLoader/Utils/StencilPathLocator.swift
  Sources/TuistScaffold/TemplatesDirectoryLocator.swift
  Tests/TuistCoreIntegrationTests/RootDirectoryLocatorIntegrationTests.swift
  Tests/TuistCoreTests/Utils/RootDirectoryLocatorErrorTests.swift
  Tests/TuistGeneratorTests/Linter/EnvironmentLinterTests.swift
  Tests/TuistKitTests/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapperTests.swift
  Tests/TuistKitTests/Mocks/MockTuistVersionLoader.swift
  Tests/TuistKitTests/Services/InitServiceTests.swift
  Tests/TuistKitTests/Utils/TuistVersionLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/ConfigLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/ManifestModelConverterTests.swift
  Tests/TuistLoaderTests/Loaders/PackageSettingsLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/RecursiveManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/TemplateLoaderTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/CodeCoverageMode+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Configuration+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/CopyFileElement+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/CopyFilesAction+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/CoreDataModel+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/FileElement+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Headers+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Project+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/ResourceFileElementManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/ResourceSynthesizer+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Scheme+ManifestMapper.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Settings+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/TargetDependency+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/TargetScript+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Workspace+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/WorkspaceGenerationOptions+ManifestWrapperTests.swift
  Tests/TuistLoaderTests/Models/GeneratorPathsTests.swift
  Tests/TuistLoaderTests/Utils/ManifestFilesLocatorTests.swift
  fixtures/framework_with_swift_macro/Tuist/Config.swift
  fixtures/ios_app_with_custom_development_region/Tuist/Config.swift
  fixtures/ios_app_with_custom_resource_parser_options/Tuist/Config.swift
  fixtures/ios_app_with_privacy_manifest/Tuist/Config.swift
  fixtures/ios_app_with_weakly_linked_framework/Tuist/Config.swift
Labels: changelog:fixed

#6793 Add dedicated fixture for showcasing Realm integration
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  fixtures/app_with_realm/.gitignore
  fixtures/app_with_realm/.mise.toml
  fixtures/app_with_realm/App/Sources/ContentView.swift
  fixtures/app_with_realm/App/Sources/MyApp.swift
  fixtures/app_with_realm/App/Tests/AppTests.swift
  fixtures/app_with_realm/Project.swift
  fixtures/app_with_realm/README.md
  fixtures/app_with_realm/Tuist/Config.swift
  fixtures/app_with_realm/Tuist/Package.resolved
  fixtures/app_with_realm/Tuist/Package.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: domain:dependencies

#6795 Fix tuist generate with an xcmappingmodel resource
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistSupport/Extensions/AbsolutePath+Extras.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistSupportTests/Extensions/AbsolutePath+ExtrasTests.swift
  fixtures/app_with_airship_sdk/.gitignore
  fixtures/app_with_airship_sdk/App/Sources/ContentView.swift
  fixtures/app_with_airship_sdk/App/Sources/MyApp.swift
  fixtures/app_with_airship_sdk/Project.swift
  fixtures/app_with_airship_sdk/README.md
  fixtures/app_with_airship_sdk/Tuist/Config.swift
  fixtures/app_with_airship_sdk/Tuist/Package.resolved
  fixtures/app_with_airship_sdk/Tuist/Package.swift
  fixtures/app_with_realm/.mise.toml
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6803 Fix regression when including directories that are considered source like DocC catalogs.
  Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  fixtures/ios_app_with_extensions/Sources/Documentation.docc/Documentation.md
Labels: changelog:fixed

#6800 feat: add support for device previews
  Package.resolved
  Package.swift
  Sources/TuistAutomation/Device/DeviceController.swift
  Sources/TuistAutomation/Device/PhysicalDevice.swift
  Sources/TuistAutomation/Utilities/AppBundle.swift
  Sources/TuistAutomation/Utilities/AppRunner.swift
  Sources/TuistAutomation/Utilities/TargetBuilder.swift
  Sources/TuistAutomation/Utilities/TargetRunner.swift
  Sources/TuistCore/Models/DestinationType.swift
  Sources/TuistCore/Utils/XcodeProjectBuildDirectoryLocator.swift
  Sources/TuistKit/Services/ShareService.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/App
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/App.debug.dylib
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework1.framework/Framework1
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework1.framework/Info.plist
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework1.framework/_CodeSignature/CodeResources
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework2.framework/Framework2
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework2.framework/Info.plist
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework2.framework/_CodeSignature/CodeResources
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework3.framework/Framework3
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework3.framework/Info.plist
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework3.framework/_CodeSignature/CodeResources
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework4.framework/Framework4
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework4.framework/Info.plist
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework4.framework/_CodeSignature/CodeResources
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework5.framework/Framework5
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework5.framework/Info.plist
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Frameworks/Framework5.framework/_CodeSignature/CodeResources
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Info.plist
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Main.storyboardc/Info.plist
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Main.storyboardc/T3K-U3-fqE-view-C2z-Us-3Oq.nib
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/Main.storyboardc/UIViewController-T3K-U3-fqE.nib
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/PkgInfo
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/_CodeSignature/CodeResources
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/__preview.dylib
  Tests/Fixtures/ios_app_with_frameworks_iphoneos-App.app/embedded.mobileprovision
  Tests/TuistAutomationTests/Device/DeviceControllerTests.swift
  Tests/TuistAutomationTests/Utilities/AppBundleLoaderTests.swift
  Tests/TuistAutomationTests/Utilities/AppRunnerTests.swift
  Tests/TuistAutomationTests/Utilities/TargetBuilderTests.swift
  Tests/TuistAutomationTests/Utilities/TargetRunnerTests.swift
  Tests/TuistCoreTests/Utils/XcodeProjectBuildDirectoryLocatorTests.swift
  Tests/TuistKitAcceptanceTests/CacheAcceptanceTests.swift
  Tests/TuistKitTests/Services/ShareServiceTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  app/TuistApp/Sources/Log.swift
  app/TuistApp/Sources/Views/DevicesView/DevicesView.swift
  app/TuistApp/Sources/Views/DevicesView/DevicesViewModel.swift
  app/TuistApp/Sources/Views/MenuBarView/MenuBarView.swift
  app/TuistApp/Sources/Views/PhysicalDeviceRow/PhysicalDeviceRow.swift
  app/TuistApp/Tests/DevicesViewModelTests.swift
  docs/docs/guides/share/previews.md
  fixtures/ios_app_with_frameworks/App/Project.swift
  fixtures/ios_app_with_frameworks/App/Sources/AppDelegate.swift
  fixtures/ios_app_with_frameworks/App/Sources/ContentView.swift
  fixtures/ios_app_with_frameworks/App/Sources/Main.storyboard
  fixtures/ios_app_with_frameworks/Project.swift
Labels: changelog:added

#6710 Fix implicit-imports command not reporting implicit imports of external dependencies
  Sources/TuistKit/Services/Inspect/InspecImplicitImportsService.swift
  Tests/TuistKitTests/Services/Inspect/InspectImplicitImportsServiceTests.swift
Labels: changelog:fixed

#6821 Fix error when resolving a symlink for a directory during tuist test
  Package.resolved
  Package.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:fixed

#6824 Fix caching for unused platforms
  Sources/TuistCore/Graph/GraphTraverser.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
Labels: changelog:fixed

#6823 Fix missing `.package.resolved` for project with only transitive remote dependencies
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGenerator/Utils/SwiftPackageManagerInteractor.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorIntegrationTests/Generator/SwiftPackageManagerInteractorTests.swift
  fixtures/app_with_local_spm_module_with_remote_dependencies/.gitignore
  fixtures/app_with_local_spm_module_with_remote_dependencies/App/Sources/App.swift
  fixtures/app_with_local_spm_module_with_remote_dependencies/App/Sources/ContentView.swift
  fixtures/app_with_local_spm_module_with_remote_dependencies/LocalSwiftPackage/Package.swift
  fixtures/app_with_local_spm_module_with_remote_dependencies/LocalSwiftPackage/Sources/LocalSwiftPackage/LocalSwiftPackage.swift
  fixtures/app_with_local_spm_module_with_remote_dependencies/Project.swift
  fixtures/app_with_local_spm_module_with_remote_dependencies/README.md
  fixtures/app_with_local_spm_module_with_remote_dependencies/Tuist/Config.swift
  fixtures/app_with_local_spm_module_with_remote_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6840 Fix tuist generate failing due to too many files being opened
  Sources/TuistCore/ContentHashing/ContentHasher.swift
Labels: changelog:fixed

#6854 Feature: Translate index.md file to Korean
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistHasher/PlistContentHasher.swift
  Sources/TuistMigration/Utilities/SettingsToXCConfigExtractor.swift
  docs/docs/ko/index.md
Labels: type:enhancement

#6849 feat: add support for .ipa in Tuist Previews
  Sources/TuistKit/Commands/ShareCommand.swift
  Sources/TuistKit/Services/RunService.swift
  Sources/TuistKit/Services/ShareService.swift
  Sources/TuistServer/Models/PreviewType.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/MultipartUploadStartPreviewsService.swift
  Sources/TuistServer/Services/PreviewsUploadService.swift
  Tests/TuistKitTests/Services/RunServiceTests.swift
  Tests/TuistKitTests/Services/ShareServiceTests.swift
  Tests/TuistServerTests/Services/PreviewsUploadServiceTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  app/TuistApp/Sources/Views/DevicesView/DevicesViewModel.swift
  app/TuistApp/Tests/DevicesViewModelTests.swift
Labels: changelog:added

#6599 Fix non-deterministic caching of ProjectDescriptionHelpers
  Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersBuilder.swift
  Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersBuilderFactory.swift
  Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersHasher.swift
  Sources/TuistSupportTesting/Utils/MockSystem.swift
  Tests/TuistCoreTests/Simulator/SimulatorControllerTests.swift
  Tests/TuistLoaderIntegrationTests/ProjectDescriptionHelpers/ProjectDescriptionHelpersBuilderIntegrationTests.swift
  Tests/TuistLoaderTests/ProjectDescriptionHelpers/Mocks/MockProjectDescriptionHelpersHasher.swift
  Tests/TuistLoaderTests/ProjectDescriptionHelpers/ProjectDescriptionHelpersBuilderTests.swift
  Tests/TuistLoaderTests/ProjectDescriptionHelpers/ProjectDescriptionHelpersHasherTests.swift
  Tests/TuistSupportTests/Utils/GitControllerTests.swift
Labels: changelog:fixed

#6711 Skip implicit import false positive when import is commented out
  Sources/TuistKit/Services/TargetImportsScanner.swift
  Sources/TuistKit/Utils/ImportSourceCodeScanner.swift
  Tests/TuistKitTests/ImportFinder/ImportSourceCodeScannerTests.swift
Labels: changelog:fixed

#6865 Fix running framework previews with resources
  Sources/TuistCore/Graph/GraphTraverser.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  fixtures/app_with_previews/App/Sources/App.swift
  fixtures/app_with_previews/App/Sources/ContentView.swift
  fixtures/app_with_previews/Project.swift
  fixtures/app_with_previews/Tuist/Package.swift
Labels: changelog:fixed

#6861 Fix Tuist Previews not posted in the GitHub PR comment
  Sources/TuistKit/Services/ShareService.swift
  docs/docs/en/guides/share/previews.md
Labels: changelog:fixed

#6858 Feature/translate korean/install tuist.md
  docs/docs/ko/guides/quick-start/install-tuist.md
Labels: type:enhancement

#6877 Fix failing git operation when git repo has commits but no origin
  Sources/TuistKit/Commands/TrackableCommand/CommandEventFactory.swift
  Sources/TuistSupport/Utils/GitController.swift
  Tests/TuistKitTests/CommandTracking/CommandEventFactoryTests.swift
Labels: changelog:fixed

#6878 Skip storing analytics events to disk when the project is not connected to the server
  Sources/TuistKit/Commands/TrackableCommand/TrackableCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Tests/TuistKitTests/CommandTracking/TrackableCommandTests.swift
Labels: changelog:fixed

#6870 Fix missing Swift Testing output
  Package.resolved
  Package.swift
  fixtures/ios_app_with_frameworks/App/Tests/AppDelegateTests.swift
  fixtures/ios_app_with_frameworks/App/Tests/MyAppTests.swift
  fixtures/ios_app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6889 Respect overriding the TEST_HOST build setting
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
  Sources/TuistGenerator/Settings/DefaultSettingsProvider.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
  Tests/TuistGeneratorTests/Settings/DefaultSettingsProviderTests.swift
Labels: changelog:fixed

#6866 Do not include CFBundleExecutable for bundle targets without sources
  Sources/TuistGenerator/Generator/InfoPlistContentProvider.swift
  Tests/TuistGeneratorTests/Generator/InfoPlistContentProviderTests.swift
Labels: changelog:fixed

#6902 Add tuist share --json support
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Commands/ShareCommand.swift
  Sources/TuistKit/Services/ShareService.swift
  Sources/TuistServer/Models/Preview.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/MultipartUploadCompletePreviewsService.swift
  Sources/TuistServer/Services/PreviewsUploadService.swift
  Tests/TuistKitTests/Services/ShareServiceTests.swift
  Tests/TuistServerTests/Services/PreviewsUploadServiceTests.swift
  docs/docs/en/guides/share/previews.md
  docs/docs/public/images/guides/share/github-app-with-preview.png
Labels: changelog:added

#6907 Fix selective test results not being stored
  Sources/TuistKit/Services/TestService.swift
Labels: changelog:fixed

#6901 Add Preview support for watch2App and appClip targets
  Sources/TuistKit/Services/ShareService.swift
  Tests/TuistKitTests/Services/ShareServiceTests.swift
  Tests/TuistServerTests/Client/ServerClientAuthenticationMiddlewareTests.swift
  Tests/TuistServerTests/Client/ServerClientOutputWarningsMiddlewareTests.swift
Labels: changelog:added

#6913 feat: Add ability to control "Find Implicit Dependencies" check on a schemes build action
  Package.resolved
  Package.swift
  Sources/ProjectDescription/BuildAction.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistLoader/Models+ManifestMappers/BuildAction+ManifestMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  fixtures/app_with_custom_scheme/App/AppDelegate.swift
  fixtures/app_with_custom_scheme/Project.swift
  fixtures/app_with_custom_scheme/README.md
  fixtures/app_with_custom_scheme/Tuist/Config.swift
Labels: changelog:added

#6929 fix: When defaultSettings is set to .essential, TEST_HOST will not be created #6926
  Sources/TuistGenerator/Settings/DefaultSettingsProvider.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
Labels: changelog:fixed

#6935 Add --no-upload flag to tuist test
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistServer/Cache/CacheStorageFactorying.swift
  Sources/TuistServer/Cache/EmptyCacheStorageFactory.swift
  Tests/TuistKitTests/CommandEnvironmentVariables/CommandEnvironmentVariableTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:added

#6954 Fix SwiftLint warning in generated resource bundle accessors
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
Labels: changelog:fixed

#6895 Fix tests crashing when accessing SPM dependency resource bundle
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistAutomationAcceptanceTests/TestAcceptanceTests.swift
  fixtures/framework_with_spm_bundle/Feature/Project.swift
  fixtures/framework_with_spm_bundle/Feature/Sources/FeatureView.swift
  fixtures/framework_with_spm_bundle/Feature/Tests/FeatureViewTest.swift
  fixtures/framework_with_spm_bundle/SharedUI/Project.swift
  fixtures/framework_with_spm_bundle/SharedUI/Sources/PaymentTextField.swift
  fixtures/framework_with_spm_bundle/Tuist/Package.resolved
  fixtures/framework_with_spm_bundle/Tuist/Package.swift
  fixtures/framework_with_spm_bundle/Workspace.swift
Labels: changelog:fixed

#6957 Improve globbing performance by using parallelized Swift glob implementation
  Package.resolved
  Package.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistLoader/Loaders/RecursiveManifestLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/ResourceFileElement+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Workspace+ManifestMapper.swift
  Sources/TuistLoader/Models/FileListGlob+Unfold.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistLoaderTests/Loaders/ManifestModelConverterTests.swift
  Tests/TuistLoaderTests/Loaders/RecursiveManifestLoaderTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/ResourceFileElementManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Workspace+ManifestMapperTests.swift
  fixtures/app_with_alamofire/.gitignore
  fixtures/app_with_alamofire/.mise.toml
  fixtures/app_with_alamofire/App/Sources/AppApp.swift
  fixtures/app_with_alamofire/App/Sources/ContentView.swift
  fixtures/app_with_alamofire/App/Tests/AppTests.swift
  fixtures/app_with_alamofire/Project.swift
  fixtures/app_with_alamofire/Tuist/Config.swift
  fixtures/app_with_alamofire/Tuist/Package.resolved
  fixtures/app_with_alamofire/Tuist/Package.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
  fixtures/app_with_spm_dependencies/Features/FeatureOne/Project.swift
  fixtures/app_with_spm_dependencies/Features/FeatureOne/Sources/FeatureOne.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:changed

#6959 Fix running selective tests with a custom result bundle path when all tests are skipped
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:fixed

#6963 Improve performance by loading Swift tools version directly from Package manifests
  Sources/TuistCore/Models/PackageSettings.swift
  Sources/TuistLoader/Loaders/PackageSettingsLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/FileElement+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/PackageSettings+ManifestMapper.swift
  Sources/TuistLoader/Models/PackageInfo.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/Loaders/PackageSettingsLoaderTests.swift
  Tests/TuistLoaderTests/Models/PackageInfoTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:changed

#6820 Add support for dependencies on app targets from different projects
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/GraphTraverser/GraphTraversing.swift
  Sources/TuistGenerator/Generator/LinkGenerator.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Generator/LinkGeneratorTests.swift
  fixtures/app_with_executable_non_local_dependencies/.gitignore
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/.gitignore
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Project.swift
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Sources/AppDelegate.swift
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Targets/AppExtension/Extension.swift
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Targets/AppExtension/ExtensionBundle.swift
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Targets/AppExtension/Info.plist
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Targets/TestHost/TestHostAppDelegate.swift
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Targets/WatchApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Targets/WatchApp/Assets.xcassets/Contents.json
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Targets/WatchApp/Base.lproj/Interface.storyboard
  fixtures/app_with_executable_non_local_dependencies/MainApp/Project.swift
  fixtures/app_with_executable_non_local_dependencies/MainApp/Targets/App/Sources/AppDelegate.swift
  fixtures/app_with_executable_non_local_dependencies/MainApp/Targets/App/Tests/AppTests.swift
  fixtures/app_with_executable_non_local_dependencies/README.md
  fixtures/app_with_executable_non_local_dependencies/Tuist/Config.swift
  fixtures/app_with_executable_non_local_dependencies/Workspace.swift
Labels: changelog:added
