Repository tuist/tuist, pull requests merged in 2024-06, with the labels that each got.

#6373 Upload test run result bundle objects
  Sources/TuistKit/Utils/TuistAnalyticsCloudBackend.swift
  Sources/TuistServer/Models/CloudCommandEvent.swift
  Sources/TuistServer/Models/InvocationRecord.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/cloud.yml
  Sources/TuistServer/Services/AnalyticsArtifactUploadService.swift
  Sources/TuistServer/Services/MultipartUploadCompleteAnalyticsService.swift
  Sources/TuistServer/Services/MultipartUploadGenerateURLAnalyticsService.swift
  Sources/TuistServer/Services/MultipartUploadStartAnalyticsService.swift
  Sources/TuistServer/Utilities/XCResultToolController.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsCloudBackendTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
  Tests/TuistServerTests/Services/AnalyticsArtifactUploadServiceTests.swift
  Tests/TuistServerTests/TestData/InvocationRecord+TestData.swift
Labels: changelog:added

#6372 Fix extra logs from Xcode commands
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
  Sources/TuistGenerator/Utils/SwiftPackageManagerInteractor.swift
  Sources/TuistSupport/System/System.swift
  Sources/TuistSupport/System/Systeming.swift
  Sources/TuistSupportTesting/Utils/MockSystem.swift
  Tests/TuistSupportIntegrationTests/System/SystemIntegrationTests.swift
Labels: changelog:fixed

#6388 Do not generate resource accessors for internal targets with resources and Objective-C source files
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
Labels: changelog:changed

#6386 Fix missing platform-specific settings for SPM packages
  Sources/TuistLoader/SwiftPackageManager/PackageInfo+graphPlatform.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistLoader/SwiftPackageManager/SettingsMapper.swift
  Tests/TuistAcceptanceTests/RunAcceptanceTests.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoGraphPlatformTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/SettingsMapperTests.swift
  fixtures/command_line_tool_basic/Project.swift
  fixtures/command_line_tool_basic/Tuist/Package.resolved
  fixtures/command_line_tool_basic/Tuist/Package.swift
Labels: changelog:fixed

#6382 Complete analytics uploads with extra test metadata
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Sources/TuistKit/Utils/TuistAnalyticsCloudBackend.swift
  Sources/TuistServer/Cache/CacheAnalytics.swift
  Sources/TuistServer/Models/CloudModule.swift
  Sources/TuistServer/Network/URLSession+Cloud.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/cloud.yml
  Sources/TuistServer/Services/AnalyticsArtifactUploadService.swift
  Sources/TuistServer/Services/CompleteAnalyticsArtifactsUploads.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsCloudBackendTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
  Tests/TuistServerTests/Services/AnalyticsArtifactUploadServiceTests.swift
Labels: changelog:changed

#6398 Finish early instead of failing when testing a scheme with no tests
  Sources/TuistAutomation/Utilities/BuildGraphInspector.swift
  Sources/TuistAutomationTesting/Utilities/MockBuildGraphInspector.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableCommand.swift
  Sources/TuistKit/Generator/Generator.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistKitTests/Generator/Mocks/MockGenerator.swift
  Tests/TuistKitTests/Services/BuildServiceTests.swift
  Tests/TuistKitTests/Services/GenerateServiceTests.swift
  Tests/TuistKitTests/Services/RunServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:changed

#6394 Fix sporadic errors when Tuist tries to preserve the SPM lockfile across project generations
  Sources/TuistGenerator/Utils/SwiftPackageManagerInteractor.swift
Labels: changelog:fixed

#6415 Allow iOS app extensions to depend on bundles
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  fixtures/ios_app_with_extensions/Bundle/dummy.jpg
  fixtures/ios_app_with_extensions/Project.swift
Labels: changelog:changed

#6421 Surface current organization usage in cloud organization show
  Sources/TuistKit/Services/Cloud/CloudOrganizationShowService.swift
  Sources/TuistServer/Models/CloudOrganizationUsage.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/cloud.yml
  Sources/TuistServer/Services/GetOrganizationUsage.swift
  Tests/TuistKitTests/Cloud/CloudOrganizationShowServiceTests.swift
Labels: changelog:changed

#6422 Fix tuist clean when no category is provided
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
Labels: changelog:fixed

#6429 Fix caching ProjectDescriptionHelpers across macOS versions
  Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersHasher.swift
  Sources/TuistSupport/MachineEnvironment.swift
  Tests/TuistLoaderTests/Loaders/ManifestLoaderFactoryTests.swift
  Tests/TuistLoaderTests/ProjectDescriptionHelpers/ProjectDescriptionHelpersHasherTests.swift
Labels: changelog:fixed

#6424 Add test targets to project when generating from `Package.swift` file.
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/SettingsMapperTests.swift
  fixtures/spm_package/Package.swift
  fixtures/spm_package/Sources/MyCommonPackage/MyCommonPackage.swift
  fixtures/spm_package/Sources/MyUIKitPackage/MyUIKitPackage.swift
  fixtures/spm_package/Tests/MyUIKitPackageTests/MyUIKitPackageTests.swift
Labels: changelog:added

#6435 Skip tests for schemes removed by selective testing
  Sources/TuistAutomation/Utilities/AutomationStorage.swift
  Sources/TuistCore/Automation/XcodeBuildControlling.swift
  Sources/TuistCoreTesting/Automation/MockXcodeBuildController.swift
  Sources/TuistKit/Generator/GeneratorFactory.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:fixed

#6440 Print only JSON string for dump and when --json flag is present
  Sources/TuistKit/Commands/DumpCommand.swift
  Sources/TuistKit/Services/Cloud/CloudOrganizationListService.swift
  Sources/TuistKit/Services/Cloud/CloudOrganizationShowService.swift
  Sources/TuistKit/Services/Cloud/CloudProjectListService.swift
  Sources/TuistKit/Services/DumpService.swift
  Sources/TuistKit/Services/ListService.swift
  Sources/TuistServer/Client/CloudClientOutputWarningsMiddleware.swift
  Sources/TuistSupport/Logging/JSONLogHandler.swift
  Sources/TuistSupport/Logging/Logger.Metadata+Tuist.swift
  Sources/TuistSupport/Logging/Logger.swift
  Sources/tuist/TuistApp.swift
  Tests/TuistServerTests/Client/CloudClientOutputWarningsMiddlewareTests.swift
Labels: changelog:fixed

#6451 Handle unauthorized server errors
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/cloud.yml
  Sources/TuistServer/Services/CacheExistsService.swift
  Sources/TuistServer/Services/CancelOrganizationInviteService.swift
  Sources/TuistServer/Services/CleanCacheService.swift
  Sources/TuistServer/Services/CompleteAnalyticsArtifactsUploads.swift
  Sources/TuistServer/Services/CreateCommandEventService.swift
  Sources/TuistServer/Services/CreateOrganizationInviteService.swift
  Sources/TuistServer/Services/CreateProjectService.swift
  Sources/TuistServer/Services/DeleteOrganizationService.swift
  Sources/TuistServer/Services/DeleteProjectService.swift
  Sources/TuistServer/Services/GetCacheService.swift
  Sources/TuistServer/Services/GetOrganizationService.swift
  Sources/TuistServer/Services/GetOrganizationUsage.swift
  Sources/TuistServer/Services/GetProjectService.swift
  Sources/TuistServer/Services/ListOrganizationsService.swift
  Sources/TuistServer/Services/ListProjectsService.swift
  Sources/TuistServer/Services/MultipartUploadCompleteAnalyticsService.swift
  Sources/TuistServer/Services/MultipartUploadCompleteCacheService.swift
  Sources/TuistServer/Services/MultipartUploadGenerateURLAnalyticsService.swift
  Sources/TuistServer/Services/MultipartUploadGenerateURLCacheService.swift
  Sources/TuistServer/Services/MultipartUploadStartAnalyticsService.swift
  Sources/TuistServer/Services/MultipartUploadStartCacheService.swift
  Sources/TuistServer/Services/RemoveOrganizationMemberService.swift
  Sources/TuistServer/Services/UpdateOrganizationMemberService.swift
  Sources/TuistServer/Services/UpdateOrganizationService.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:fixed

#6405 Add support for enabling explicit modules for Xcode 16
  Sources/ProjectDescription/SettingsTransformers.swift
Labels: changelog:added

#6445 Fix generation of Quick's SPM QuickObjcRuntime target
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
Labels: changelog:fixed

#6450 Provide better error message for a missing Tuist server token
  Package.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistServer/Client/CloudClientAuthenticationMiddleware.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
Labels: changelog:fixed

#6455 Fix deleting Tuist project and organization
  Project.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/cloud.yml
  Sources/TuistServer/Services/DeleteProjectService.swift
  Tests/TuistKitAcceptanceTests/BuildRulesAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/EditAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/GraphAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/InitAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/ListTargetsAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/PluginAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/PrecompiledAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/RunAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/ScaffoldAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/ServerAcceptanceTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  codemagic.yaml
Labels: changelog:fixed
