Repository tuist/tuist, pull requests merged in 2024-03, with the labels that each got.

#6008 Fix crash when accessing bundle resources in Previews
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistSupport/Vendored/HTTPStatusCodes/HTTPStatusCode+Extensions.swift
  Sources/TuistSupport/Vendored/HTTPStatusCodes/HTTPStatusCodes.swift
  Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
  fixtures/app_with_previews/PreviewsFramework/Sources/TestView.swift
  fixtures/app_with_previews/Project.swift
  fixtures/app_with_previews/ResourcesFramework/Package.swift
  fixtures/app_with_previews/ResourcesFramework/Sources/ResourcesFramework/BundleReader.swift
  fixtures/app_with_previews/ResourcesFramework/Sources/ResourcesFramework/Resources/file.txt
  fixtures/app_with_previews/Tuist/Package.swift
  fixtures/tuist_plugin/Package.swift
  fixtures/tuist_plugin/Sources/CreateFile/main.swift
  fixtures/tuist_plugin/Sources/InspectGraph/main.swift
  fixtures/tuist_plugin/Templates/custom_two/custom_two.swift
  fixtures/tuist_plugin/Tests/CreateFileTests/Test.swift
Labels: changelog:fixed

#6011 Support for SPM only projects
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGraph/Models/Dependencies/PackageSettings.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistLoader/Loaders/CachedManifestLoader.swift
  Sources/TuistLoader/Loaders/ManifestLoader.swift
  Sources/TuistLoader/Loaders/RecursiveManifestLoader.swift
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/Workspace+ManifestMapper.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistLoader/Utils/ManifestFilesLocator.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockManifestLoader.swift
  Sources/TuistSupport/SwiftPackageManager/PackageInfo.swift
  Sources/TuistSupportTesting/SwiftPackageManager/MockSwiftPackageManagerController.swift
  Sources/TuistSupportTesting/SwiftPackageManager/PackageInfo+TestData.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistLoaderIntegrationTests/Loaders/ManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/CachedManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/RecursiveManifestLoaderTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  Tests/TuistSupportTests/SwiftPackageManager/PackageInfoTests.swift
  Tests/TuistSupportTests/SwiftPackageManager/SwiftPackageManagerControllerTests.swift
  docs/Sources/tuist/tuist.docc/Articles/Tuist/Users/project-structure.md
  fixtures/spm_package/.gitignore
  fixtures/spm_package/Package.resolved
  fixtures/spm_package/Package.swift
  fixtures/spm_package/Sources/MyCLI/main.swift
  fixtures/spm_package/Sources/MyPackage/MyPackage.swift
  fixtures/spm_package/Tests/MyPackageTests/MyPackageTests.swift
  fixtures/spm_package/Tuist/.gitkeep
Labels: changelog:added

#6021 Fix tuist test when using Nimble
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistDependencies/Mappers/PruneOrphanExternalTargetsGraphMapper.swift
  Sources/TuistKit/Mappers/Factories/GraphMapperFactory.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistDependenciesTests/Mappers/PruneOrphanExternalTargetsGraphMapperTests.swift
Labels: changelog:fixed

#6027 Fix generation of SPM packages when some resources are missing
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6028 fix: Previews crash when accessing resources from cached XCFrameworks
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
Labels: changelog:fixed

#6035 Prevent cached frameworks from crashing in Previews after deleting derived data
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
Labels: changelog:fixed

#6039 Fix generate with Workspace.swift
  Sources/TuistLoader/Loaders/RecursiveManifestLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/Workspace+ManifestMapper.swift
  fixtures/multiplatform_app_with_sdk/Tuist/Package.resolved
  fixtures/multiplatform_app_with_sdk/Tuist/Package.swift
  fixtures/multiplatform_app_with_sdk/Workspace.swift
Labels: changelog:fixed

#6042 Fix compiling libraries with umbrella headers that have a dash
  Sources/TuistLoader/SwiftPackageManager/SwiftPackageManagerModuleMapGenerator.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6047 Skip targets with unsupported platforms instead of throwing an error
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6049 Fix reading metadata of swift-package-manager-google-mobile-ads
  Sources/TuistCore/MetadataProviders/PrecompiledMetadataProvider.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6051 Force addition of macro flags regardless of inherited presence
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
  Sources/TuistGenerator/Utils/SettingsHelper.swift
  fixtures/app_with_spm_dependencies/Tuist/ProjectDescriptionHelpers/Settings+Templates.swift
Labels: changelog:fixed

#6062 Fix integration of swift-testing
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Generator/LinkGenerator.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/LinkGeneratorTests.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/App/Tests/AppKit/AppKitTests.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6057 Add cached artifacts into a new group called `/Cache`
  Sources/TuistGenerator/Generator/ProjectFileElements.swift
  Sources/TuistGenerator/Generator/ProjectGroups.swift
  Tests/TuistGeneratorTests/Generator/ProjectFileElementsTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectGroupsTests.swift
Labels: changelog:added

#6070 Fix setting custom package baseSettings
  Sources/TuistCoreTesting/Graph/DependenciesGraph+TestData.swift
  Sources/TuistGraph/Models/Settings.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/app_with_spm_dependencies/Tuist/ProjectDescriptionHelpers/Settings+Templates.swift
Labels: changelog:fixed

#6054 Skip flagging the install error if there's no instance of external dependency in the graph
  Sources/ProjectDescription/Project.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistLoader/Loaders/RecursiveManifestLoader.swift
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Tests/TuistLoaderTests/Loaders/RecursiveManifestLoaderTests.swift
Labels: changelog:fixed

#6073 Allow specifying explicit product destinations in PackageSettings
  Sources/ProjectDescription/PackageSettings.swift
  Sources/TuistGraph/Models/Dependencies/PackageSettings.swift
  Sources/TuistGraphTesting/Models/PackageSettings+TestData.swift
  Sources/TuistKit/ProjectEditor/ProjectEditor.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/PackageSettings+ManifestMapper.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistLoader/Utils/ManifestFilesLocator.swift
  Sources/TuistLoaderTesting/Utils/Mocks/MockManifestFilesLocator.swift
  Tests/TuistAcceptanceTests/EditAcceptanceTests.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistKitTests/ProjectEditor/ProjectEditorTests.swift
  Tests/TuistKitTests/Services/CleanServiceTests.swift
  Tests/TuistKitTests/Services/InstallServiceTests.swift
  Tests/TuistLoaderTests/Loaders/PackageSettingsLoaderTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/spm_package/Package.swift
  fixtures/spm_package/Sources/MyUIKitPackage/MyPackage.swift
Labels: changelog:added

#6095 Fix the look up of the templates directory in a Homebrew installation
  Sources/TuistScaffold/TemplatesDirectoryLocator.swift
Labels: changelog:fixed

#5773 Fix testing search path build settings when forcing explicit dependencies
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/GraphTraverser/GraphTraversing.swift
  Sources/TuistCoreTesting/GraphTraverser/MockGraphTraverser.swift
  Sources/TuistGenerator/Mappers/ExplicitDependencyGraphMapper.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ExplicitDependencyGraphMapperTests.swift
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/.gitignore
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Modules/ModuleA/Example/Sources/AppDelegate.swift
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Modules/ModuleA/Example/SupportingFiles/App-Info.plist
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Modules/ModuleA/Implementation/Sources/FrameworkA.swift
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Modules/ModuleA/Interface/Sources/FrameworkAInterface.swift
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Modules/ModuleA/Project.swift
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Modules/ModuleA/TestSupporting/Sources/FrameworkATestSupporting.swift
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Modules/ModuleA/Tests/Sources/FrameworkATests.swift
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Tuist/Config.swift
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Tuist/Dependencies.swift
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Tuist/Package.resolved
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Tuist/Package.swift
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Tuist/ProjectDescriptionHelpers/Extensions.swift
  fixtures/multiplatform_µFeature_unit_tests_with_explicit_dependencies/Workspace.swift
Labels: changelog:fixed

#6044 Updated init template with `.mise.toml` and `Package.swift` files
  Sources/TuistKit/Services/InitService.swift
  Sources/TuistKit/Utils/TuistVersionLoader.swift
  Templates/default/Package.stencil
  Templates/default/default.swift
  Templates/default/mise.stencil
  Tests/TuistAcceptanceTests/InitAcceptanceTests.swift
  Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
  Tests/TuistKitTests/Mocks/MockTuistVersionLoader.swift
  Tests/TuistKitTests/Services/InitServiceTests.swift
  Tests/TuistKitTests/Utils/TuistVersionLoaderTests.swift
Labels: changelog:added

#6080 Fix custom configurations from target when `enforceExplicitDependencies` option is enabled
  Sources/TuistGenerator/Mappers/ExplicitDependencyGraphMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ExplicitDependencyGraphMapperTests.swift
Labels: changelog:fixed

#6109 Fix Swift Macros when embedded apps
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Resources/Assets.xcassets/Contents.json
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/ContentView.swift
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/App/Sources/TestApp.swift
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Modules/ModuleA/Sources/ModuleA.swift
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Project.swift
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Tuist/Package.resolved
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Tuist/Package.swift
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Resources/Assets.xcassets/Contents.json
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/ContentView.swift
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchApp.swift
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/WatchApp/Sources/WatchConfig.swift
Labels: changelog:fixed

#6110 Preserve custom arguments passed on launch and working directory
  Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Tests/TuistGeneratorTests/Generator/Mocks/MockSchemeDescriptorsGenerator.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
Labels: changelog:changed

#6122 Improve the error message when parsing malformed property list files.
  Sources/TuistSupport/Utils/FileHandler.swift
  Tests/TuistSupportTests/Utils/FileHandlerTests.swift
Labels: changelog:changed

#6121 Fix SPM integration of the latest version of swift-testing
  .swift-version
  .swiftformat
  .xcode-version
  Package.swift
  Sources/TuistLoader/SwiftPackageManager/SettingsMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/SettingsMapperTests.swift
  Tuist/Config.swift
  codemagic.yaml
  fixtures/app_with_spm_dependencies/StringifyMacro/Package.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6127 Fix adding newline at the end of tuist version in `.mise.toml` file
  Sources/TuistKit/Utils/TuistVersionLoader.swift
  Tests/TuistKitTests/Utils/TuistVersionLoaderTests.swift
Labels: changelog:fixed

#6129 Fix running Tuist.graph() in a Tuist task
  Sources/ProjectAutomation/Tuist.swift
  Sources/TuistGenerator/Extensions/Graph+Extras.swift
  fixtures/app_with_plugins/InspectGraph/Package.resolved
  fixtures/app_with_plugins/InspectGraph/Package.swift
  fixtures/app_with_plugins/InspectGraph/Sources/InspectGraph/main.swift
  fixtures/app_with_plugins/Tuist/Config.swift
Labels: changelog:fixed
