Repository tuist/tuist, pull requests merged in 2024-05, with the labels that each got.

#6242 Get PRODUCT_NAME value from settings if consistent and present
  Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift
  Tests/TuistGraphTests/Models/TargetTests.swift
Labels: type:enhancement

#6247 Add (void) to generated Obj-C Bundle accessor
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
Labels: changelog:fixed

#6178 Add On Demand Resources Support
  Sources/ProjectDescription/OnDemandResourcesTags.swift
  Sources/ProjectDescription/Target.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
  Sources/TuistGenerator/Generator/KnownAssetTagsFetcher.swift
  Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Sources/TuistGraph/Models/OnDemandResourcesTags.swift
  Sources/TuistGraph/Models/Target.swift
  Sources/TuistGraphTesting/Models/Target+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift
  fixtures/README.md
  fixtures/ios_app_with_on_demand_resources/.gitignore
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/OnDemandResources/on-demand-data.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/AR Resources.arresourcegroup/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Cube Texture.cubetextureset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Cube Texture.cubetextureset/Universal +X.mipmapset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Cube Texture.cubetextureset/Universal +Y.mipmapset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Cube Texture.cubetextureset/Universal +Z.mipmapset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Cube Texture.cubetextureset/Universal -X.mipmapset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Cube Texture.cubetextureset/Universal -Y.mipmapset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Cube Texture.cubetextureset/Universal -Z.mipmapset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Data.dataset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Image.imageset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/NewFolder/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/NewFolder/nestedimage.imageset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Sprites.spriteatlas/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Sprites.spriteatlas/Sprite.imageset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Stack.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Stack.imagestack/Back.imagestacklayer/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Stack.imagestack/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Stack.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Stack.imagestack/Front.imagestacklayer/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Stack.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Stack.imagestack/Middle.imagestacklayer/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Texture.textureset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Texture.textureset/Universal.mipmapset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/LaunchScreen.storyboard
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Sources/AppWithOnDemandResourcesApp.swift
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Sources/ContentView.swift
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Tests/AppWithOnDemandResourcesTests.swift
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/on-demand-data.txt
  fixtures/ios_app_with_on_demand_resources/Project.swift
  fixtures/ios_app_with_on_demand_resources/Tuist/Config.swift
Labels: changelog:added

#6258 Remove trailing backslash from Cloud url if present
  Sources/TuistLoader/Models+ManifestMappers/Cloud+ManifestMapper.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Cloud+ManifestMapperTests.swift
Labels: changelog:fixed

#6264 Fix integration of SPM packages with spaces in their name
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistCoreTesting/Graph/DependenciesGraph+TestData.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistSupport/Extensions/String+Extras.swift
  Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/ios_app_with_spm_dependencies/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/ios_app_with_spm_dependencies/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/ios_app_with_spm_dependencies/App/Resources/Assets.xcassets/Contents.json
  fixtures/ios_app_with_spm_dependencies/App/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  fixtures/ios_app_with_spm_dependencies/App/Sources/AppApp.swift
  fixtures/ios_app_with_spm_dependencies/App/Sources/ContentView.swift
  fixtures/ios_app_with_spm_dependencies/AppTests/AppTests.swift
  fixtures/ios_app_with_spm_dependencies/Project.swift
  fixtures/ios_app_with_spm_dependencies/README.md
  fixtures/ios_app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/ios_app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6265 Align bundle name with dashes sanitizing with SPM
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Sources/App/AppDelegate.swift
Labels: changelog:fixed

#6255 Add defaultConfiguration generation option to Config.swift
  Sources/ProjectDescription/ConfigGenerationOptions.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGraph/Models/ConfigGenerationOptions.swift
  Sources/TuistGraphTesting/Models/Config+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/Config+ManifestMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  fixtures/app_with_custom_default_configuration/.gitignore
  fixtures/app_with_custom_default_configuration/.mise.toml
  fixtures/app_with_custom_default_configuration/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/app_with_custom_default_configuration/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/app_with_custom_default_configuration/App/Resources/Assets.xcassets/Contents.json
  fixtures/app_with_custom_default_configuration/App/Resources/LaunchScreen.storyboard
  fixtures/app_with_custom_default_configuration/App/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  fixtures/app_with_custom_default_configuration/App/Sources/AppApp.swift
  fixtures/app_with_custom_default_configuration/App/Sources/ContentView.swift
  fixtures/app_with_custom_default_configuration/App/Tests/AppTests.swift
  fixtures/app_with_custom_default_configuration/Framework/Sources/Framework.swift
  fixtures/app_with_custom_default_configuration/Project.swift
  fixtures/app_with_custom_default_configuration/README.md
  fixtures/app_with_custom_default_configuration/Tuist/Config.swift
  fixtures/app_with_custom_default_configuration/Tuist/Package.swift
Labels: changelog:added

#6244 Do not automatically add -ObjC flag when integrating Objective-C dependencies
  Sources/TuistGenerator/Mappers/ModuleMapMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ModuleMapMapperTests.swift
  docs/docs/guide/project/dependencies.md
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/README.md
  fixtures/app_with_spm_dependencies/Tuist/ProjectDescriptionHelpers/Settings+Templates.swift
Labels: changelog:fixed

#6260 Fix integration of SPM packages with slashes in their targets names
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistGraph/Models/Target.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistLoader/SwiftPackageManager/SwiftPackageManagerModuleMapGenerator.swift
  Sources/TuistSupport/Extensions/String+Extras.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  fixtures/ios_app_with_spm_dependencies/App/Sources/ContentView.swift
  fixtures/ios_app_with_spm_dependencies/Project.swift
  fixtures/ios_app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/ios_app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6287 Add Widget Extension support to AppClips
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  fixtures/ios_app_with_appclip/AppClip1Widgets/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/ios_app_with_appclip/AppClip1Widgets/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/ios_app_with_appclip/AppClip1Widgets/Resources/Assets.xcassets/Contents.json
  fixtures/ios_app_with_appclip/AppClip1Widgets/Resources/Assets.xcassets/WidgetBackground.colorset/Contents.json
  fixtures/ios_app_with_appclip/AppClip1Widgets/Sources/Widget.swift
  fixtures/ios_app_with_appclip/Project.swift
Labels: changelog:added

#6298 Fix tuist generate when a binary SPM dependency is removed
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:fixed

#6299 Fix missing -package-name when a target has custom swiftSettings
  Sources/TuistCoreTesting/Graph/DependenciesGraph+TestData.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/ios_app_with_spm_dependencies/App/Sources/ContentView.swift
  fixtures/ios_app_with_spm_dependencies/Project.swift
  fixtures/ios_app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/ios_app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6302 Support "Code Sign on Copy" in Copy Files Actions
  Sources/ProjectDescription/CopyFileElement.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGraph/Models/CopyFileElement.swift
  Sources/TuistLoader/Models+ManifestMappers/CopyFileElement+ManifestMapper.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
Labels: changelog:added

#6290 Fix target linter warnings for target products that allow dots and hyphens
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift
Labels: changelog:fixed

#6293 Add capability to specify variable entitlements
  Sources/ProjectDescription/Entitlements.swift
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
  Sources/TuistGraph/Models/Plist.swift
  Sources/TuistLoader/Models+ManifestMappers/Entitlements+ManifestMapper.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
Labels: changelog:added

#6268 Fix --platform case sensitivity with test and build commands
  Sources/TuistGraph/Models/Platform.swift
  Sources/TuistKit/Services/BuildService.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistGraphTests/Models/PlatformTests.swift
Labels: changelog:fixed

#6309 Fix the initialization of projects in Homebrew-managed installations
  Sources/TuistScaffold/TemplatesDirectoryLocator.swift
Labels: changelog:fixed

#6322 Fixes #6321: Handle formatting multiline text
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
Labels: changelog:fixed

#6300 Support xcodebuild arguments in build and test commands
  Sources/TuistAcceptanceTesting/TuistAcceptanceTestCase.swift
  Sources/TuistAutomation/Utilities/TargetBuilder.swift
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
  Sources/TuistAutomationTesting/Utilities/MockTargetBuilder.swift
  Sources/TuistCore/Automation/XcodeBuildControlling.swift
  Sources/TuistCoreTesting/Automation/MockXcodeBuildController.swift
  Sources/TuistKit/Commands/BuildCommand.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Services/BuildService.swift
  Sources/TuistKit/Services/RunService.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistSupportTesting/Extensions/XCTestCase+Extras.swift
  Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
  Tests/TuistAutomationAcceptanceTests/TestAcceptanceTests.swift
  Tests/TuistKitTests/Services/BuildServiceTests.swift
  Tests/TuistKitTests/Services/RunServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
  docs/docs/guide/automation/build.md
  docs/docs/guide/automation/test.md
Labels: changelog:added

#6337 Fix detection of XCTest dependency
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistGraphTesting/Graph/GraphDependency+TestData.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
Labels: changelog:fixed

#6345 Upload test result bundle
  Sources/TuistCore/Analytics/CommandEvent.swift
  Sources/TuistCore/Cache/CacheCategory.swift
  Sources/TuistKit/Commands/GenerateCommand.swift
  Sources/TuistKit/Commands/GraphCommand.swift
  Sources/TuistKit/Commands/InitCommand.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Commands/TrackableCommand/CommandEventFactory.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableCommand.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableParametersDelegate.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistKit/Utils/TuistAnalyticsCloudBackend.swift
  Sources/TuistLoader/Loaders/ConfigLoader.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockConfigLoader.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/cloud.yml
  Sources/TuistServer/Services/AnalyticsArtifactUploadService.swift
  Sources/TuistServer/Services/MultipartUploadArtifactService.swift
  Sources/TuistServer/Services/MultipartUploadCompleteAnalyticsService.swift
  Sources/TuistServer/Services/MultipartUploadGenerateURLAnalyticsService.swift
  Sources/TuistServer/Services/MultipartUploadStartAnalyticsService.swift
  Sources/TuistServer/Utilities/DelayProvider.swift
  Sources/TuistServer/Utilities/RetryProvider.swift
  Sources/TuistSupport/Constants.swift
  Tests/TuistKitTests/Cloud/CloudAuthServiceTests.swift
  Tests/TuistKitTests/Cloud/CloudCleanServiceTests.swift
  Tests/TuistKitTests/Cloud/CloudInitServiceTests.swift
  Tests/TuistKitTests/Cloud/CloudLogoutServiceTests.swift
  Tests/TuistKitTests/Cloud/CloudOrganizationInviteServiceTests.swift
  Tests/TuistKitTests/Cloud/CloudOrganizationListServiceTests.swift
  Tests/TuistKitTests/Cloud/CloudOrganizationRemoveSSOServiceTests.swift
  Tests/TuistKitTests/Cloud/CloudOrganizationShowServiceTests.swift
  Tests/TuistKitTests/Cloud/CloudOrganizationUpdateSSOService.swift
  Tests/TuistKitTests/Cloud/CloudProjectDeleteServiceTests.swift
  Tests/TuistKitTests/Cloud/CloudProjectListServiceTests.swift
  Tests/TuistKitTests/Cloud/CloudSessionServiceTests.swift
  Tests/TuistKitTests/CommandTracking/CommandEventFactoryTests.swift
  Tests/TuistKitTests/CommandTracking/TrackableCommandTests.swift
  Tests/TuistKitTests/Services/EditServiceTests.swift
  Tests/TuistKitTests/Services/InstallServiceTests.swift
  Tests/TuistKitTests/Services/ScaffoldServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
  Tests/TuistKitTests/Services/TuistServiceTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsCloudBackendTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
  Tests/TuistServerTests/Services/AnalyticsArtifactUploadServiceTests.swift
  Tests/TuistServerTests/Utilities/DelayProviderTests.swift
  Tests/TuistServerTests/Utilities/RetryProviderTests.swift
  fixtures/ios_app_with_frameworks/Tuist/Config.swift
Labels: changelog:added

#6307 Making `tuist run` interactive by selecting simulators
  Sources/TuistAutomation/Utilities/TargetRunner.swift
  Sources/TuistCore/Simulator/SimulatorController.swift
  Sources/TuistCoreTesting/Simulator/MockSimulatorController.swift
  Sources/TuistSupport/UserInputReader.swift
  Tests/TuistSupportTests/Utils/UserInputReaderTests.swift
  docs/docs/guide/automation/run.md
Labels: changelog:added
