Repository tuist/tuist, pull requests merged in 2024-11, with the labels that each got.

#6970 Fix glob regression for hidden files and excluding sources
  Package.resolved
  Package.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/FileElement+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Target+ManifestMapperTests.swift
  fixtures/app_with_globs/App/.hidden.yml
  fixtures/app_with_globs/App/Sources/ContentView.swift
  fixtures/app_with_globs/App/Sources/FileExcludeMe.swift
  fixtures/app_with_globs/App/Sources/MyApp.swift
  fixtures/app_with_globs/Project.swift
  fixtures/app_with_globs/README.md
  fixtures/app_with_globs/Tuist/Config.swift
  fixtures/app_with_globs/Tuist/Package.swift
Labels: changelog:fixed

#6977 Fix searching for files in symlinked directories
  Package.resolved
  Package.swift
Labels: changelog:fixed

#6996 Fix tuist edit when a directory contains a tuist file instead of a Tuist/ directory
  Sources/TuistLoader/Utils/ManifestFilesLocator.swift
  Tests/TuistLoaderTests/Utils/ManifestFilesLocatorTests.swift
Labels: changelog:fixed

#6995 Skip .DS_Store when expanding globs
  Package.resolved
  Package.swift
Labels: changelog:fixed

#7003 Use manifests cache in the tuist dump command
  Sources/TuistKit/Services/DumpService.swift
  Sources/TuistKit/Services/GenerateService.swift
Labels: changelog:changed

#6993 Do not rebuild project description helpers when cached
  Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersBuilder.swift
  Tests/TuistLoaderIntegrationTests/ProjectDescriptionHelpers/ProjectDescriptionHelpersBuilderIntegrationTests.swift
  Tests/TuistLoaderTests/ProjectDescriptionHelpers/ProjectDescriptionHelpersBuilderTests.swift
Labels: changelog:fixed

#7007 Fix tuist clean hanging
  Package.resolved
  Package.swift
Labels: changelog:fixed

#7020 feat: Update the default server URL to `tuist.dev`
  Sources/ProjectDescription/Cloud.swift
  Sources/ProjectDescription/Config.swift
  Sources/TuistServer/Models/Preview.swift
  Sources/TuistServer/Models/ServerCommandEvent.swift
  Sources/TuistServer/Utilities/ServerAuthenticationController.swift
  Sources/TuistServer/Utilities/ServerCredentialsStore.swift
  Sources/TuistSupport/Constants.swift
  Tests/TuistKitIntegrationTests/Commands/DumpServiceIntegrationTests.swift
  Tests/TuistKitTests/Services/AuthServiceTests.swift
  Tests/TuistKitTests/Services/LogoutServiceTests.swift
  Tests/TuistKitTests/Services/Organization/OrganizationInviteServiceTests.swift
  Tests/TuistKitTests/Services/Organization/OrganizationListServiceTests.swift
  Tests/TuistKitTests/Services/Organization/OrganizationRemoveSSOServiceTests.swift
  Tests/TuistKitTests/Services/Organization/OrganizationShowServiceTests.swift
  Tests/TuistKitTests/Services/Organization/OrganizationUpdateSSOServiceTests.swift
  Tests/TuistKitTests/Services/Project/ProjectDeleteServiceTests.swift
  Tests/TuistKitTests/Services/Project/ProjectListServiceTests.swift
  Tests/TuistKitTests/Services/Project/ProjectTokensCreateServiceTests.swift
  Tests/TuistKitTests/Services/Project/ProjectTokensListServiceTests.swift
  Tests/TuistKitTests/Services/Project/ProjectTokensRevokeServiceTests.swift
  Tests/TuistKitTests/Services/SessionServiceTests.swift
  Tests/TuistKitTests/Services/ShareServiceTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsServerBackendTests.swift
  Tests/TuistServerTests/Utilities/ServerAuthenticationControllerTests.swift
  app/TuistApp/Tests/Services/DeviceServiceTests.swift
  app/TuistApp/Tests/ViewModels/DevicesViewModelTests.swift
Labels: changelog:changed

#7021 feat: add support for preview icons
  Sources/TuistAutomation/Utilities/AppBundle.swift
  Sources/TuistKit/Services/ShareService.swift
  Sources/TuistServer/Models/Preview.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/DownloadPreviewService.swift
  Sources/TuistServer/Services/PreviewsUploadService.swift
  Sources/TuistServer/Services/UploadPreviewIconService.swift
  Tests/Fixtures/App.app/App
  Tests/Fixtures/App.app/App.debug.dylib
  Tests/Fixtures/App.app/AppIcon60x60@2x.png
  Tests/Fixtures/App.app/AppIcon76x76@2x~ipad.png
  Tests/Fixtures/App.app/Assets.car
  Tests/Fixtures/App.app/Frameworks/Framework1.framework/Framework1
  Tests/Fixtures/App.app/Frameworks/Framework1.framework/Info.plist
  Tests/Fixtures/App.app/Frameworks/Framework1.framework/_CodeSignature/CodeResources
  Tests/Fixtures/App.app/Frameworks/Framework2.framework/Framework2
  Tests/Fixtures/App.app/Frameworks/Framework2.framework/Info.plist
  Tests/Fixtures/App.app/Frameworks/Framework2.framework/_CodeSignature/CodeResources
  Tests/Fixtures/App.app/Frameworks/Framework3.framework/Framework3
  Tests/Fixtures/App.app/Frameworks/Framework3.framework/Info.plist
  Tests/Fixtures/App.app/Frameworks/Framework3.framework/_CodeSignature/CodeResources
  Tests/Fixtures/App.app/Frameworks/Framework4.framework/Framework4
  Tests/Fixtures/App.app/Frameworks/Framework4.framework/Info.plist
  Tests/Fixtures/App.app/Frameworks/Framework4.framework/_CodeSignature/CodeResources
  Tests/Fixtures/App.app/Frameworks/Framework5.framework/Framework5
  Tests/Fixtures/App.app/Frameworks/Framework5.framework/Info.plist
  Tests/Fixtures/App.app/Frameworks/Framework5.framework/_CodeSignature/CodeResources
  Tests/Fixtures/App.app/Info.plist
  Tests/Fixtures/App.app/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib
  Tests/Fixtures/App.app/LaunchScreen.storyboardc/Info.plist
  Tests/Fixtures/App.app/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib
  Tests/Fixtures/App.app/PlugIns/WidgetExtension.appex/Info.plist
  Tests/Fixtures/App.app/PlugIns/WidgetExtension.appex/WidgetExtension
  Tests/Fixtures/App.app/Watch/WatchApp.app/Info.plist
  Tests/Fixtures/App.app/Watch/WatchApp.app/PkgInfo
  Tests/Fixtures/App.app/Watch/WatchApp.app/WatchApp
  Tests/Fixtures/App.app/_CodeSignature/CodeResources
  Tests/Fixtures/App.app/__preview.dylib
  Tests/TuistAutomationTests/Utilities/AppBundleLoaderTests.swift
  Tests/TuistKitTests/Services/ShareServiceTests.swift
  Tests/TuistServerTests/Services/PreviewsUploadServiceTests.swift
  app/TuistApp/Sources/AppPreviewTile.swift
  app/TuistApp/Sources/CachedAsyncImage.swift
  app/TuistApp/Sources/Views/AppPreviews/AppPreview.swift
  app/TuistApp/Sources/Views/AppPreviews/AppPreviewsModel.swift
Labels: changelog:added

#7031 Fix glob with extension options
  Package.resolved
Labels: changelog:fixed

#7030 Fix glob for opaque directories like xcassets
  Sources/TuistLoader/Models+ManifestMappers/ResourceFileElement+ManifestMapper.swift
  Sources/TuistSupport/Extensions/AbsolutePath+Extras.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/ResourceFileElementManifestMapperTests.swift
  Tests/TuistSupportTests/Extensions/AbsolutePath+ExtrasTests.swift
Labels: changelog:fixed

#7034 Add support for Okta organization SSO
  Sources/TuistKit/Commands/Organization/OrganizationUpdateSSOCommand.swift
  Sources/TuistKit/Services/Organization/OrganizationShowService.swift
  Sources/TuistKit/Services/Organization/OrganizationUpdateService.swift
  Sources/TuistServer/Models/SSOOrganization.swift
  Sources/TuistServer/Models/ServerOrganization.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/UpdateOrganizationService.swift
  Tests/TuistKitTests/Services/Organization/OrganizationShowServiceTests.swift
  Tests/TuistKitTests/Services/Organization/OrganizationUpdateSSOServiceTests.swift
  docs/docs/en/server/introduction/authentication.md
Labels: changelog:added

#7025 fix: macro compiling when user script sandboxing is enabled
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  fixtures/multiplatform_app_with_macros_and_embedded_watchos_app/Tuist/Package.swift
Labels: changelog:fixed

#7009 Allow configuration-specific settings for individual targets in PackageSettings
  Sources/ProjectDescription/PackageSettings.swift
  Sources/TuistCore/Models/PackageSettings.swift
  Sources/TuistLoader/Models+ManifestMappers/PackageSettings+ManifestMapper.swift
  Sources/TuistLoader/Models/DependenciesGraph.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistLoader/SwiftPackageManager/SettingsMapper.swift
  Sources/TuistSupportTesting/TestCase/TuistTestCase.swift
  Tests/TuistLoaderIntegrationTests/Loaders/ManifestLoaderTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/SettingsMapperTests.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
  fixtures/spm_package/Package.swift
Labels: changelog:changed

#7041 Always wait for command event to be uploaded when running tuist share
  Sources/TuistAsyncQueue/AsyncQueue.swift
  Sources/TuistAsyncQueueTesting/MockAsyncQueuer.swift
  Sources/TuistKit/Commands/ShareCommand.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableCommand.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableParsableCommand.swift
  Tests/TuistKitTests/CommandTracking/TrackableCommandTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
Labels: changelog:fixed

#7040 Fix caching failing due to tree-shaking logic not pruning dependencies
  Sources/TuistKit/Mappers/TreeShakePrunedTargetsGraphMapper.swift
  Tests/TuistKitTests/Mappers/Graph/TreeShakePrunedTargetsGraphMapperTests.swift
Labels: type:bug, changelog:fixed

#6990 Allow files generated during build to be used as sources.
  Sources/ProjectDescription/SourceFilesList.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Sources/TuistSupport/Extensions/AbsolutePath+Extras.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Target+ManifestMapperTests.swift
  fixtures/app_with_generated_sources/App/Scripts/generate_empty_file.sh
  fixtures/app_with_generated_sources/App/Sources/AppDelegate.swift
  fixtures/app_with_generated_sources/Project.swift
  fixtures/app_with_generated_sources/README.md
  fixtures/app_with_generated_sources/Tuist/Config.swift
Labels: changelog:added

#7057 Fix glob groups
  Package.swift
  fixtures/app_with_globs/App/Config.xcconfig
  fixtures/app_with_globs/App/Debug.entitlements
  fixtures/app_with_globs/App/Release.entitlements
  fixtures/app_with_globs/Project.swift
Labels: changelog:fixed

#7056 Override GENERATE_MASTER_OBJECT_FILE to NO for the generated resources target
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
Labels: changelog:fixed

#7060 Speed up hashing-dependent features like caching or selective testing
  Package.resolved
  Package.swift
  Sources/TuistHasher/CopyFilesContentHasher.swift
  Sources/TuistHasher/CoreDataModelsContentHasher.swift
  Sources/TuistHasher/DependenciesContentHasher.swift
  Sources/TuistHasher/DeploymentTargetsContentHasher.swift
  Sources/TuistHasher/HeadersContentHasher.swift
  Sources/TuistHasher/PlistContentHasher.swift
  Sources/TuistHasher/ResourcesContentHasher.swift
  Sources/TuistHasher/SettingsContentHasher.swift
  Sources/TuistHasher/SourceFilesContentHasher.swift
  Sources/TuistHasher/TargetContentHasher.swift
  Sources/TuistHasher/TargetScriptsContentHasher.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistLoader/Loaders/ManifestModelConverter.swift
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/Project+ManifestMapper.swift
  Sources/TuistLoader/Models/DependenciesGraph.swift
  Sources/TuistLoader/Models/SwiftPackageManagerWorkspaceState.swift
  Tests/TuistHasherTests/TargetContentHasherTests.swift
  Tests/TuistLoaderTests/Loaders/ManifestModelConverterTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Project+ManifestMapperTests.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
Labels: changelog:changed

#7066 Fix error when cancelling invitation
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
Labels: changelog:fixed

#7043 Rename `Config` to `Tuist` and nest project's configuration into `Tuist.project`
  Sources/ProjectDescription/ConfigGenerationOptions.swift
  Sources/ProjectDescription/Tuist.swift
  Sources/ProjectDescription/TuistProject.swift
  Sources/TuistLoader/Models+ManifestMappers/Config+ManifestMapper.swift
  Templates/default/Tuist.stencil
  Tests/TuistKitIntegrationTests/Commands/DumpServiceIntegrationTests.swift
  docs/.vitepress/config.mjs
  docs/docs/en/guides/develop/projects/manifests.md
  docs/docs/en/guides/develop/projects/plugins.md
  docs/docs/en/guides/quick-start/gather-insights.md
  docs/docs/en/guides/start/migrate/swift-package.md
  docs/docs/en/guides/start/migrate/xcode-project.md
  docs/docs/en/guides/start/new-project.md
  docs/docs/en/server/introduction/accounts-and-projects.md
  fixtures/app_with_framework_and_tests/Tuist.swift
Labels: changelog:changed

#7010 Add --quiet flag
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistSupport/Constants.swift
  Sources/TuistSupport/Logging/Logger.swift
  Sources/tuist/TuistApp.swift
Labels: changelog:added

#7077 feat: when running latest preview, filter supported platforms
  Package.resolved
  Package.swift
  Sources/TuistKit/Services/RunService.swift
  Sources/TuistKit/Services/ShareService.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/ListPreviewsService.swift
  Sources/TuistServer/Services/MultipartUploadStartPreviewsService.swift
  Sources/TuistServer/Services/PreviewsUploadService.swift
  Tests/TuistKitTests/Services/RunServiceTests.swift
  Tests/TuistKitTests/Services/ShareServiceTests.swift
  Tests/TuistServerTests/Services/PreviewsUploadServiceTests.swift
  app/TuistApp/Sources/Extensions/DestinationType+Extras.swift
  app/TuistApp/Sources/Views/AppPreviews/AppPreviewsModel.swift
  app/TuistApp/Tests/ViewModels/AppPreviewsViewModelTests.swift
Labels: changelog:changed

#7038 Align ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES with the Xcode default
  Sources/TuistGenerator/Settings/DefaultSettingsProvider.swift
  fixtures/workspace_with_test_locale/Project.swift
Labels: changelog:changed

#7082 Fix data race when refreshing an access token
  Sources/TuistServer/Client/ServerClientAuthenticationMiddleware.swift
  Sources/TuistServer/Utilities/CachedValueStore.swift
  Tests/TuistServerTests/Client/ServerClientAuthenticationMiddlewareTests.swift
Labels: changelog:fixed

#7080 Change behavior of --no-selective-testing to still run all tests, but store the results
  Sources/TuistKit/Commands/TestCommand.swift
Labels: changelog:changed

#7087 fix: when hashing packages, hash should include extra metadata like Swift compiler version
  Sources/TuistHasher/TargetContentHasher.swift
  Tests/TuistHasherTests/TargetContentHasherTests.swift
Labels: changelog:fixed

#7000 Fix false positive warning for SPM dependencies when running tuist inspect implicit-imports
  Sources/TuistKit/Services/Inspect/InspecImplicitImportsService.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectImplicitImportsServiceTests.swift
Labels: changelog:fixed

#7096 Speed up artifacts uploads, such as upload app bundles when running tuist share
  Sources/TuistServer/Services/MultipartUploadArtifactService.swift
Labels: changelog:changed

#7099 Add project update --visibility option
  Sources/TuistKit/Commands/Project/ProjectUpdateCommand.swift
  Sources/TuistKit/Services/Project/ProjectShowService.swift
  Sources/TuistKit/Services/Project/ProjectUpdateService.swift
  Sources/TuistServer/Client/ServerClientVerboseLoggingMiddleware.swift
  Sources/TuistServer/Models/ServerProject.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/UpdateProjectService.swift
  Tests/TuistKitAcceptanceTests/CacheAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/ProjectAcceptanceTests.swift
  Tests/TuistKitTests/Services/Project/ProjectShowServiceTests.swift
  Tests/TuistKitTests/Services/Project/ProjectUpdateServiceTests.swift
  fixtures/app_with_composable_architecture/Tuist/Package.resolved
  fixtures/app_with_composable_architecture/Tuist/Package.swift
Labels: changelog:added

#7115 Fix stale external dependencies hash
  Sources/TuistHasher/TargetContentHasher.swift
  Tests/TuistCacheIntegrationTests/CacheGraphContentHasherIntegrationTests.swift
  Tests/TuistHasherTests/TargetContentHasherTests.swift
  Tests/TuistKitAcceptanceTests/CacheAcceptanceTests.swift
Labels: changelog:fixed
