Repository tuist/tuist, pull requests merged in 2024-08, with the labels that each got.

#6538 Deduplicate external resources
  Sources/ProjectDescription/ResourceFileElement.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistSupport/Utils/FileHandler.swift
  Sources/TuistSupportTesting/TestCase/TuistTestCase.swift
  Tests/TuistGeneratorTests/Generator/WorkspaceStructureGeneratorTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:fixed, 🙋 Bounty claim

#6594 Prevent Tuist authentication kickouts by retrying token refresh
  Sources/TuistServer/Client/ServerClientAuthenticationMiddleware.swift
Labels: changelog:fixed

#6593 Fix unstable hashing of target dependencies
  Sources/TuistHasher/DependenciesContentHasher.swift
  Tests/TuistHasherTests/DependenciesContentHasherTests.swift
Labels: changelog:fixed

#6592 Fix generate performance when using Tuist Cache xcframeworks
  Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift
  Tests/TuistGeneratorTests/Linter/StaticProductsGraphLinterTests.swift
Labels: changelog:fixed

#6439 Add classPrefix support
  Sources/ProjectDescription/Project.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift
  Sources/TuistLoader/Models+ManifestMappers/Project+ManifestMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectDescriptorGeneratorTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Project+ManifestMapperTests.swift
  fixtures/project_with_class_prefix/Project.swift
  fixtures/project_with_class_prefix/README.md
  fixtures/project_with_class_prefix/Tuist/Config.swift
Labels: changelog:added

#6604 Fix missing external resource bundle in app extension
  Sources/TuistCore/Graph/GraphTraverser.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
Labels: changelog:fixed

#6610 Favor TUIST_CONFIG_TOKEN over TUIST_CONFIG_CLOUD_TOKEN
  Sources/TuistServer/Utilities/ServerAuthenticationController.swift
  Tests/TuistServerTests/Utilities/ServerAuthenticationControllerTests.swift
Labels: changelog:changed

#6611 Fix app not found when running tuist share with different target and product names
  Sources/TuistKit/Services/ShareService.swift
  Tests/TuistKitTests/Services/ShareServiceTests.swift
Labels: changelog:fixed

#6614 Skip user token deprecation warning when new user tokens are available
  Sources/TuistServer/Utilities/ServerAuthenticationController.swift
  Tests/TuistServerTests/Utilities/ServerAuthenticationControllerTests.swift
Labels: changelog:fixed

#6605 Add Swift library sdk type
  Package.resolved
  Package.swift
  Sources/ProjectDescription/TargetDependency.swift
  Sources/TuistCore/MetadataProviders/SystemFrameworkMetadataProvider.swift
  Sources/TuistLoader/Models+ManifestMappers/TargetDependency+ManifestMapper.swift
  Tests/TuistCoreTests/MetadataProviders/SystemFrameworkMetadataProviderTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/TargetDependency+ManifestMapperTests.swift
  fixtures/app_with_custom_default_configuration/.mise.toml
  fixtures/app_with_google_maps/.mise.toml
  fixtures/ios_app_with_sdk/Framework/FrameworkClass.swift
  fixtures/ios_app_with_sdk/Project.swift
Labels: changelog:added

#6133 Add support for XCFrameworks with .dylib libraries
  Sources/TuistCore/MetadataProviders/XCFrameworkMetadataProvider.swift
Labels: changelog:added

#6613 Fix missing linked system libraries in Tuist Cache
  Sources/TuistCore/Graph/GraphTraverser.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
Labels: changelog:fixed

#6630 Support #import with spaces prefix in umbrella headers.
  Sources/TuistLoader/Loaders/UmbrellaHeaderHeadersExtractor.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Headers+ManifestMapperTests.swift
Labels: changelog:fixed

#6627 Prune schemes when expandVariableFromTarget is pruned
  Sources/TuistKit/Mappers/TreeShakePrunedTargetsGraphMapper.swift
  Tests/TuistKitTests/Mappers/Graph/TreeShakePrunedTargetsGraphMapperTests.swift
Labels: changelog:fixed

#6652 Default to --no-open in CI environments for tuist generate
  Sources/TuistKit/Commands/GenerateCommand.swift
Labels: changelog:changed

#6654 fix: not embed dynamic frameworks in app extensions
  Sources/TuistAcceptanceTesting/TuistAcceptanceTestCase+Extra.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  codemagic.yaml
  fixtures/app_with_framework_and_tests/AppExtension/Extension.swift
  fixtures/app_with_framework_and_tests/AppExtension/ExtensionBundle.swift
  fixtures/app_with_framework_and_tests/AppExtension/Info.plist
  fixtures/app_with_framework_and_tests/Project.swift
Labels: changelog:fixed

#6664 Prohibit unit test depending on an app extension as it's an invalid combination
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  fixtures/ios_app_with_extension_and_tests/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/ios_app_with_extension_and_tests/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/ios_app_with_extension_and_tests/App/Resources/Assets.xcassets/Contents.json
  fixtures/ios_app_with_extension_and_tests/App/Sources/MainApp.swift
  fixtures/ios_app_with_extension_and_tests/AppExtension/ExtensionViewController.swift
  fixtures/ios_app_with_extension_and_tests/AppExtensionTests/ExtensionTests.swift
  fixtures/ios_app_with_extension_and_tests/Project.swift
  fixtures/ios_app_with_extension_and_tests/README.md
Labels: changelog:fixed

#6516 Add `tuist inspect implicit-dependencies` to detect implicit dependencies
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Commands/Inspect/InspectImplicitImportsCommand.swift
  Sources/TuistKit/Commands/InspectCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/Inspect/InspecImplicitImportsService.swift
  Sources/TuistKit/Services/TargetImportsScanner.swift
  Sources/TuistKit/Utils/ImportSourceCodeScanner.swift
  Tests/TuistKitAcceptanceTests/InspectAcceptanceTests.swift
  Tests/TuistKitTests/ImportFinder/ImportSourceCodeScannerTests.swift
  Tests/TuistKitTests/ImportFinder/TargetImportsScannerTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectImplicitImportsServiceTests.swift
  docs/.vitepress/icons.mjs
  docs/.vitepress/sidebars.mjs
  docs/docs/guides/develop/inspect/implicit-dependencies.md
Labels: changelog:added

#6659 Report extra metadata in command events for the new GitHub app
  .mise.toml
  Sources/TuistCore/Analytics/CommandEvent.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistKit/Commands/ShareCommand.swift
  Sources/TuistKit/Commands/TrackableCommand/CommandEventFactory.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/ShareService.swift
  Sources/TuistKit/Utils/TuistAnalyticsServerBackend.swift
  Sources/TuistLoader/Loaders/TemplateGitLoader.swift
  Sources/TuistLoader/Loaders/TemplateLoader.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockTemplateGitLoader.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockTemplateLoader.swift
  Sources/TuistPlugin/PluginService.swift
  Sources/TuistScaffold/TemplateGenerator.swift
  Sources/TuistScaffold/TemplatesDirectoryLocator.swift
  Sources/TuistScaffoldTesting/Utils/Mocks/MockTemplateGenerator.swift
  Sources/TuistScaffoldTesting/Utils/Mocks/MockTemplatesDirectoryLocator.swift
  Sources/TuistServer/Models/Preview.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/CreateCommandEventService.swift
  Sources/TuistServer/Services/MultipartUploadCompleteAnalyticsService.swift
  Sources/TuistServer/Services/MultipartUploadStartPreviewsService.swift
  Sources/TuistServer/Services/PreviewsUploadService.swift
  Sources/TuistSupport/Utils/GitController.swift
  Sources/TuistSupportTesting/Utils/MockGitHandler.swift
  Tests/TuistGeneratorTests/Generator/ProjectFileElementsTests.swift
  Tests/TuistKitTests/CommandTracking/CommandEventFactoryTests.swift
  Tests/TuistKitTests/CommandTracking/TrackableCommandTests.swift
  Tests/TuistKitTests/ProjectEditor/ProjectEditorTests.swift
  Tests/TuistKitTests/Services/InitServiceTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectImplicitImportsServiceTests.swift
  Tests/TuistKitTests/Services/ListServiceTests.swift
  Tests/TuistKitTests/Services/ScaffoldServiceTests.swift
  Tests/TuistKitTests/Services/ShareServiceTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
  Tests/TuistLoaderTests/Loaders/TemplateGitLoaderTests.swift
  Tests/TuistPluginTests/PluginServiceTests.swift
  Tests/TuistServerTests/Services/PreviewsUploadServiceTests.swift
  Tests/TuistSupportTests/Utils/GitControllerTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  docs/docs/guides/dashboard/on-premise/install.md
Labels: changelog:changed

#6675 Fix false positive when linting duplicate symbols of a macro
  Sources/TuistGenerator/Linter/StaticProductsGraphLinter.swift
  Tests/TuistGeneratorTests/Linter/StaticProductsGraphLinterTests.swift
Labels: changelog:fixed

#6671 Add support for updating the connected git repository
  Project.swift
  Sources/TuistKit/Commands/Project/ProjectUpdateCommand.swift
  Sources/TuistKit/Services/Project/ProjectShowService.swift
  Sources/TuistKit/Services/Project/ProjectUpdateService.swift
  Sources/TuistServer/Models/ServerProject.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/UpdateProjectService.swift
  Tests/TuistKitAcceptanceTests/ProjectAcceptanceTests.swift
  Tests/TuistKitTests/Services/Project/ProjectShowServiceTests.swift
  Tests/TuistKitTests/Services/Project/ProjectUpdateServiceTests.swift
Labels: changelog:changed
