Repository tuist/tuist, pull requests merged in 2024-04, with the labels that each got.

#6142 Filter out empty auxiliary groups
  Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift
  Sources/TuistGenerator/Generator/ProjectGroups.swift
  Tests/TuistGeneratorTests/Generator/ProjectGroupsTests.swift
Labels: changelog:changed

#6151 Fix resources filename mismatch when a dependency has a +
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  fixtures/multiplatform_app_with_sdk/Project.swift
  fixtures/multiplatform_app_with_sdk/Tuist/Package.resolved
  fixtures/multiplatform_app_with_sdk/Tuist/Package.swift
Labels: changelog:fixed

#6117 Add support for privacy manifest file generation
  Sources/ProjectDescription/PrivacyManifest.swift
  Sources/ProjectDescription/ResourceFileElements.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift
  Sources/TuistGenerator/Generator/ProjectFileElements.swift
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Sources/TuistGenerator/Mappers/GeneratePrivacyManifestProjectMapper.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistGenerator/Mappers/SynthesizedResourceInterfaceProjectMapper.swift
  Sources/TuistGraph/Models/PrivacyManifest.swift
  Sources/TuistGraph/Models/ResourceFileElements.swift
  Sources/TuistGraph/Models/Target.swift
  Sources/TuistGraphTesting/Models/Target+TestData.swift
  Sources/TuistKit/Mappers/Factories/ProjectMapperFactory.swift
  Sources/TuistKit/Services/ProjectAutomation+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistSupport/Constants.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectDescriptorGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectFileElementsTests.swift
  Tests/TuistGeneratorTests/Generator/TargetGeneratorTests.swift
  Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/SynthesizedResourceInterfaceProjectMapperTests.swift
  Tests/TuistKitTests/Mappers/Factories/ProjectMapperFactoryTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/ios_app_with_framework_and_resources/App/Project.swift
  fixtures/ios_app_with_privacy_manifest/.gitignore
  fixtures/ios_app_with_privacy_manifest/MyApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/ios_app_with_privacy_manifest/MyApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/ios_app_with_privacy_manifest/MyApp/Resources/Assets.xcassets/Contents.json
  fixtures/ios_app_with_privacy_manifest/MyApp/Resources/LaunchScreen.storyboard
  fixtures/ios_app_with_privacy_manifest/MyApp/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  fixtures/ios_app_with_privacy_manifest/MyApp/Sources/ContentView.swift
  fixtures/ios_app_with_privacy_manifest/MyApp/Sources/MyAppApp.swift
  fixtures/ios_app_with_privacy_manifest/MyApp/Tests/MyAppTests.swift
  fixtures/ios_app_with_privacy_manifest/Project.swift
  fixtures/ios_app_with_privacy_manifest/README.md
Labels: changelog:added

#6195 Fix integration of Cuckoo
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/App/Tests/AppKit/AppKitTests.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6170 Fix missing external target settings with config conditions
  Sources/TuistGraph/Models/Settings.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistLoader/SwiftPackageManager/SettingsMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/SettingsMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6218 Use relative paths instead of absolute paths for header search paths for modulemaps
  Sources/TuistGenerator/Mappers/ModuleMapMapper.swift
  Sources/TuistKit/Mappers/Factories/GraphMapperFactory.swift
  Sources/TuistKit/Mappers/Factories/WorkspaceMapperFactory.swift
  Tests/TuistGeneratorTests/ProjectMappers/ModuleMapMapperTests.swift
  Tests/TuistKitTests/Mappers/Factories/GraphMapperFactoryTests.swift
  Tests/TuistKitTests/Mappers/Factories/WorkspaceMapperFactoryTests.swift
Labels: changelog:fixed

#6221 Fix regression in ModuleMapMapper due to outdated Graph properties
  Sources/TuistGenerator/Mappers/ModuleMapMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ModuleMapMapperTests.swift
Labels: changelog:fixed

#6201 Fix generating CoreData models in resourceSynthesizer .coreData()
  Sources/TuistGenerator/Mappers/SynthesizedResourceInterfaceProjectMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/SynthesizedResourceInterfaceProjectMapperTests.swift
  fixtures/ios_app_with_coredata/CoreData/Unversioned.xcdatamodeld/Unversioned.xcdatamodel/contents
  fixtures/ios_app_with_coredata/CoreData/Users.xcdatamodeld/1.xcdatamodel/contents
  fixtures/ios_app_with_coredata/CoreData/Users.xcdatamodeld/2.xcdatamodel/contents
  fixtures/ios_app_with_coredata/CoreData/UsersAutoDetect.xcdatamodeld/1.xcdatamodel/contents
  fixtures/ios_app_with_coredata/CoreData/UsersAutoDetect.xcdatamodeld/2.5.xcdatamodel/contents
  fixtures/ios_app_with_coredata/CoreData/UsersAutoDetect.xcdatamodeld/2.xcdatamodel/contents
  fixtures/ios_app_with_coredata/Project.swift
  fixtures/ios_app_with_coredata/README.md
  fixtures/ios_app_with_coredata/Tuist/ResourceSynthesizers/CoreData.stencil
Labels: changelog:fixed

#6146 Align resource bundle accessor generation with SPM
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistGenerator/Templates/AssetsTemplate.swift
  Sources/TuistGenerator/Templates/StringsTemplate.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/LocalSwiftPackage/Sources/Styles/StylesResources.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#6234 Align bundle name sanization with SPM
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Sources/App/AppDelegate.swift
Labels: changelog:fixed

#6237 Revert "Embed external xcframeworks regardless of linking type (#6217)"
  Sources/TuistCore/Graph/GraphLoader.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/NodeLoaders/XCFrameworkLoader.swift
  Sources/TuistCoreTesting/NodeLoaders/MockXCFrameworkLoader.swift
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Sources/TuistGraph/Graph/GraphDependency.swift
  Sources/TuistGraph/Models/TargetDependency.swift
  Sources/TuistGraphTesting/Graph/GraphDependency+TestData.swift
  Sources/TuistKit/Services/ProjectAutomation+ManifestMapper.swift
  Sources/TuistLoader/Loaders/ManifestModelConverter.swift
  Sources/TuistLoader/Models+ManifestMappers/Project+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/TargetDependency+ManifestMapper.swift
  Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
  Tests/TuistCoreTests/Graph/GraphLoaderTests.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistCoreTests/NodeLoaders/XCFrameworkLoaderTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/TargetDependency+ManifestMapperTests.swift
Labels: changelog:fixed
