Repository tuist/tuist, pull requests merged in 2024-09, with the labels that each got.

#6663 Detect and warn about outdated dependencies
  Sources/TuistKit/Services/InstallService.swift
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Sources/TuistSupportTesting/Extensions/XCTestCase+Extras.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistKitTests/Services/InstallServiceTests.swift
  Tests/TuistLoaderTests/Loaders/SwiftPackageManagerGraphLoaderTests.swift
Labels: changelog:added

#6685 Add support for SPM moduleAliases
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistLoader/Loaders/RecursiveManifestLoader.swift
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistLoaderTests/Loaders/RecursiveManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/SwiftPackageManagerGraphLoaderTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/app_with_spm_module_aliases/.gitignore
  fixtures/app_with_spm_module_aliases/App/Sources/App.swift
  fixtures/app_with_spm_module_aliases/App/Sources/ContentView.swift
  fixtures/app_with_spm_module_aliases/LibraryA/.gitignore
  fixtures/app_with_spm_module_aliases/LibraryA/Package.swift
  fixtures/app_with_spm_module_aliases/LibraryA/Sources/LibraryA/LibraryA.swift
  fixtures/app_with_spm_module_aliases/LibraryA/Sources/Utilities/Utilities.swift
  fixtures/app_with_spm_module_aliases/LibraryB/.gitignore
  fixtures/app_with_spm_module_aliases/LibraryB/Package.swift
  fixtures/app_with_spm_module_aliases/LibraryB/Sources/LibraryB/LibraryB.swift
  fixtures/app_with_spm_module_aliases/LibraryB/Sources/Utilities/Utilities.swift
  fixtures/app_with_spm_module_aliases/Project.swift
  fixtures/app_with_spm_module_aliases/Tuist/Package.swift
Labels: changelog:added

#6612 Add install options with SPM arguments to Config
  Sources/ProjectDescription/Config.swift
  Sources/ProjectDescription/ConfigInstallOptions.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistCore/Models/Config.swift
  Sources/TuistCore/Models/ConfigInstallOptions.swift
  Sources/TuistKit/Services/InstallService.swift
  Sources/TuistLoader/Models+ManifestMappers/Config+ManifestMapper.swift
  Sources/TuistSupport/SwiftPackageManager/SwiftPackageManagerController.swift
  Sources/TuistSupportTesting/SwiftPackageManager/MockSwiftPackageManagerController.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistGeneratorIntegrationTests/Generator/MultipleConfigurationsIntegrationTests.swift
  Tests/TuistGeneratorIntegrationTests/Generator/SwiftPackageManagerInteractorTests.swift
  Tests/TuistKitIntegrationTests/Commands/DumpServiceIntegrationTests.swift
  Tests/TuistKitTests/Services/InstallServiceTests.swift
  Tests/TuistLoaderTests/Loaders/ConfigLoaderTests.swift
  Tests/TuistPluginTests/PluginServiceTests.swift
  Tests/TuistSupportTests/SwiftPackageManager/SwiftPackageManagerControllerTests.swift
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/App/Resources/Assets.xcassets/Contents.json
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/App/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/App/Sources/AppApp.swift
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/App/Sources/ContentView.swift
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/AppTests/AppTests.swift
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/Project.swift
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/README.md
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/Tuist/Config.swift
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/Tuist/Package.resolved
  fixtures/ios_app_with_spm_dependencies_forced_resolved_versions/Tuist/Package.swift
Labels: changelog:added

#6695 Fix stored run event being too large
  Sources/TuistAnalytics/Utilities/TuistAnalyticsDispatcher.swift
  Sources/TuistAsyncQueue/AsyncQueue.swift
  Sources/TuistAsyncQueue/AsyncQueuePersistor.swift
  Sources/TuistCore/Analytics/CommandEvent.swift
  Sources/TuistCore/Analytics/CommandEventGraphTarget.swift
  Sources/TuistCore/Analytics/CommandEventProject.swift
  Sources/TuistCore/Analytics/CommandEventTarget.swift
  Sources/TuistCore/Cache/CacheDirectoriesProvider.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Commands/TrackableCommand/CommandEventFactory.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableCommand.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableParametersDelegate.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Utils/TuistAnalyticsServerBackend.swift
  Sources/TuistServer/Cache/CacheAnalytics.swift
  Sources/TuistServer/Services/AnalyticsArtifactUploadService.swift
  Sources/TuistSupport/Utils/Environment.swift
  Sources/TuistSupportTesting/Utils/MockEnvironment.swift
  Sources/tuist/TuistApp.swift
  Tests/TuistAsyncQueueTests/AsyncQueuePersistorTests.swift
  Tests/TuistHasherTests/ResourcesContentHasherTests.swift
  Tests/TuistKitTests/CommandTracking/CommandEventFactoryTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
  Tests/TuistServerTests/Client/ServerClientOutputWarningsMiddlewareTests.swift
  Tests/TuistServerTests/Services/AnalyticsArtifactUploadServiceTests.swift
Labels: changelog:fixed

#6643 Allow adding macOS bundles to iOS targets
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
Labels: changelog:changed

#6722 Fix selective testing of a test plan
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:fixed

#6753 Fix missing metal resources in the Tuist SPM integration
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:fixed

#6701 Optimize storing and fetching selective tests
  Sources/TuistServer/Models/ServerCacheActionItem.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/CacheExistsService.swift
  Sources/TuistServer/Services/GetCacheActionItemService.swift
  Sources/TuistServer/Services/UploadCacheActionItemService.swift
Labels: changelog:changed

#6721 Embed precompiled bundles linked through a dynamic framework
  Sources/TuistCore/Graph/GraphTraverser.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
Labels: changelog:fixed

#6757 Fix integrating static xcframeworks linked through dynamic xcframeworks
  Package.resolved
  Package.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/GraphTraverser/GraphTraversing.swift
  Sources/TuistKit/Mappers/Factories/GraphMapperFactory.swift
  Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistKitTests/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapperTests.swift
Labels: changelog:fixed

#6754 Do not put Resources Bundle in the Products folder when archiving
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
Labels: changelog:fixed

#6770 Fix tuist test failing due to a conflict when uploading test results
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/UploadCacheActionItemService.swift
Labels: changelog:fixed

#6771 Fix compiling swift-syntax in Swift 6 language mode
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistSupport/SwiftPackageManager/SwiftPackageManagerController.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:fixed
