Repository tuist/tuist, pull requests merged in 2024-01, with the labels that each got.

#5711 Add a `--generate-only` flag to the build command
  Sources/TuistKit/Commands/BuildCommand.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Services/BuildService.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistKitTests/Services/BuildServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:added

#5751 Add Package.swift support for tuist edit
  Sources/TuistKit/ProjectEditor/ProjectEditor.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Sources/TuistLoader/Utils/ManifestFilesLocator.swift
  Sources/TuistLoaderTesting/Utils/Mocks/MockManifestFilesLocator.swift
  Sources/TuistSupport/SwiftPackageManager/SwiftPackageManagerController.swift
  Sources/TuistSupport/Xcode/XcodeController.swift
  Sources/TuistSupportTesting/SwiftPackageManager/MockSwiftPackageManagerController.swift
  Tests/TuistAcceptanceTests/EditAcceptanceTests.swift
  Tests/TuistKitTests/ProjectEditor/Mocks/MockProjectEditorMapper.swift
  Tests/TuistKitTests/ProjectEditor/ProjectEditorMapperTests.swift
  Tests/TuistKitTests/ProjectEditor/ProjectEditorTests.swift
  Tests/TuistLoaderTests/Utils/ManifestFilesLocatorTests.swift
Labels: changelog:added

#5742 Align the behaviour of `--path` in `tuist fetch` with the rest of the CLI
  Sources/TuistKit/Services/FetchService.swift
  Tests/TuistKitTests/Services/FetchServiceTests.swift
Labels: changelog:fixed

#5758 Prefer an exact match on `developmentRegion` when choosing localization strings files
  Sources/TuistGenerator/Mappers/SynthesizedResourceInterfaceProjectMapper.swift
  Tests/TuistGenerateAcceptanceTests/GenerateAcceptanceTests.swift
  fixtures/ios_app_with_custom_development_region/App/Resources/fr-CA.lproj/Greetings.strings
Labels: changelog:added

#5768 Verbose-log the `xcodebuild` command that's being executed
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
Labels: changelog:added

#5767 Add SkippedTests for TestAction
  Sources/ProjectDescription/TestAction.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistGraph/Models/TestAction.swift
  Sources/TuistGraphTesting/Models/TestAction+TestData.swift
  Sources/TuistLoader/Models+ManifestMappers/TestAction+ManifestMapper.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
Labels: changelog:added

#5772 Add support for transitive Swift Macros
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/GraphTraverser/GraphTraversing.swift
  Sources/TuistCoreTesting/GraphTraverser/MockGraphTraverser.swift
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
Labels: changelog:fixed

#5770 Optimize the graph traverser function to obtain the platforms for external dependencies
  Sources/TuistCore/Graph/GraphTraverser.swift
Labels: changelog:fixed

#5776 Remove raw xcodebuild logs in favor of resultBundlePath and xcactivitylog
  .github/workflows/tuist.yml
  Sources/TuistAutomation/Utilities/TargetBuilder.swift
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
  Sources/TuistAutomationTesting/Utilities/MockTargetBuilder.swift
  Sources/TuistCore/Automation/XcodeBuildControlling.swift
  Sources/TuistCoreTesting/Automation/MockXcodeBuildController.swift
  Sources/TuistKit/Commands/BuildCommand.swift
  Sources/TuistKit/Commands/RunCommand.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Services/BuildService.swift
  Sources/TuistKit/Services/RunService.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistAutomationTests/Utilities/TargetBuilderTests.swift
  Tests/TuistAutomationTests/XcodeBuild/XcodeBuildControllerTests.swift
  Tests/TuistDependenciesTests/Mappers/PruneOrphanExternalTargetsGraphMapperTests.swift
  Tests/TuistKitTests/Services/BuildServiceTests.swift
  Tests/TuistKitTests/Services/RunServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:changed

#5801 Fix generation not including macros from XCFrameworks
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
Labels: changelog:fixed

#5805 Fix loading PackageSettings when not specified in Package.swift
  Sources/TuistLoader/Loaders/ManifestLoader.swift
  Tests/TuistLoaderIntegrationTests/Loaders/ManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/ManifestLoaderErrorTests.swift
Labels: changelog:fixed

#5809 Add back `SwiftPackageManagerDependencies` conformance to `ExpressibleByArrayLiteral` for backwards compatibility
  Sources/ProjectDescription/Dependencies/SwiftPackageManagerDependencies.swift
  Tests/ProjectDescriptionTests/Dependencies/DependenciesTests.swift
  Tests/ProjectDescriptionTests/Dependencies/SwiftPackageManagerDependenciesTests.swift
  Tests/TuistLoaderTests/Loaders/DependenciesModelLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/PackageSettingsLoaderTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/DependenciesManifestMapperTests.swift
  fixtures/multiplatform_app_with_sdk/Tuist/Dependencies.swift
Labels: changelog:fixed

#5826 Rename Compiled group to Frameworks
  Sources/TuistGenerator/Generator/ProjectFileElements.swift
  Sources/TuistGenerator/Generator/ProjectGroups.swift
  Tests/TuistGeneratorTests/Generator/ProjectFileElementsTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectGroupsTests.swift
Labels: changelog:fixed

#5831 Use the correct Swift tools version when loading the PackageSettings
  Sources/TuistLoader/Loaders/ManifestLoader.swift
  Tests/TuistLoaderIntegrationTests/Loaders/ManifestLoaderTests.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#5837 Improve editing of PackageSettings in Package.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Tests/TuistKitTests/ProjectEditor/ProjectEditorMapperTests.swift
Labels: changelog:changed

#5846 Fix parsing of `conditon` on SPM `.product` dependencies
  Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift
  Sources/TuistSupport/SwiftPackageManager/PackageInfo.swift
  Sources/TuistSupportTesting/SwiftPackageManager/PackageInfo+TestData.swift
  Tests/TuistDependenciesTests/SwiftPackageManager/Utils/PackageInfoMapperTests.swift
  fixtures/app_with_spm_dependencies/LocalSwiftPackage/Package.swift
  fixtures/app_with_spm_dependencies/LocalSwiftPackageB/Package.swift
  fixtures/app_with_spm_dependencies/LocalSwiftPackageB/Sources/LibraryA/MyStruct.swift
Labels: changelog:fixed

#5849 Fix missing plugin executable when the macro framework/library is not precompiled but the executable is
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistGraph/Graph/GraphDependency.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
  Tests/TuistGraphTests/Graph/GraphDependencyTests.swift
Labels: changelog:fixed

#5853 Simplify tuist init
  Sources/TuistKit/Commands/InitCommand.swift
  Sources/TuistKit/Services/InitService.swift
  Templates/AppProject.stencil
  Templates/Config.stencil
  Templates/KitSource.stencil
  Templates/KitTests.stencil
  Templates/LocalHelper.stencil
  Templates/Package.stencil
  Templates/Package.swift
  Templates/Plugin.stencil
  Templates/Project+Templates.stencil
  Templates/UISource.stencil
  Templates/UITests.stencil
  Templates/default/AppDelegate.stencil
  Templates/default/AppProject.stencil
  Templates/default/AppTests.stencil
  Templates/default/ContentView.stencil
  Templates/default/Gitignore.stencil
  Templates/default/LaunchScreen+iOS.stencil
  Templates/default/LaunchScreen+macOS.stencil
  Templates/default/LaunchScreen+tvOS.stencil
  Templates/default/Preview Content/Preview Assets.xcassets/Contents.json
  Templates/default/app.stencil
  Templates/default/default.swift
  Templates/default/ios/Assets.xcassets/AccentColor.colorset/Contents.json
  Templates/default/ios/Assets.xcassets/AppIcon.appiconset/Contents.json
  Templates/default/ios/Assets.xcassets/Contents.json
  Templates/default/macos/Assets.xcassets/AccentColor.colorset/Contents.json
  Templates/default/macos/Assets.xcassets/AppIcon.appiconset/Contents.json
  Templates/default/macos/Assets.xcassets/Contents.json
  Templates/default/tvos/Assets.xcassets/AccentColor.colorset/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  Templates/default/tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  Templates/default/tvos/Assets.xcassets/Contents.json
  Templates/default/watchos/Assets.xcassets/AccentColor.colorset/Contents.json
  Templates/default/watchos/Assets.xcassets/AppIcon.appiconset/Contents.json
  Templates/default/watchos/Assets.xcassets/Contents.json
  Templates/main.stencil
  Templates/swiftui/swiftui.swift
  Tests/TuistAcceptanceTests/InitAcceptanceTests.swift
Labels: changelog:changed
