Repository tuist/tuist, pull requests merged in 2024-02, with the labels that each got.

#5857 Rename `fetch` to `install`
  Sources/TuistKit/Commands/InstallCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/InstallService.swift
  Sources/TuistPlugin/PluginService.swift
  Tests/TuistAcceptanceTests/EditAcceptanceTests.swift
  Tests/TuistAcceptanceTests/PluginAcceptanceTests.swift
  Tests/TuistAcceptanceTests/ScaffoldAcceptanceTests.swift
  Tests/TuistBuildAcceptanceTests/BuildAcceptanceTests.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistKitTests/Services/InstallServiceTests.swift
  Tuist/Config.swift
  docs/Sources/tuist/tuist.docc/Articles/Tuist/Contributors/get-started-as-contributor.md
  docs/Sources/tuist/tuist.docc/Articles/Tuist/Users/Tutorials/Tuist Tutorial/Getting-Started/Add External Dependencies/external-dependencies.tutorial
  docs/Sources/tuist/tuist.docc/Articles/Tuist/Users/Tutorials/Tuist Tutorial/Getting-Started/Add External Dependencies/tuist-install.sh
  docs/Sources/tuist/tuist.docc/Articles/Tuist/Users/command-line-interface.md
  make/tasks/tuist/build.sh
  make/tasks/tuist/generate.sh
  make/tasks/tuist/test.sh
Labels: changelog:changed

#5868 Fix running tuist clean without a specific category
  Sources/TuistKit/Commands/CleanCommand.swift
Labels: changelog:fixed

#5872 Fix tuist clean dependencies
  Sources/TuistKit/Services/CleanService.swift
  Tests/TuistKitTests/Services/CleanServiceTests.swift
Labels: changelog:fixed

#5874 Throw an error when focusing on a non-existent target
  Sources/TuistKit/Mappers/FocusTargetsGraphMappers.swift
  Tests/TuistKitTests/Mappers/FocusTargetsGraphMappersTests.swift
Labels: changelog:fixed

#5871 Improve performance of resolving manifest file paths
  Sources/TuistLoader/Utils/ManifestFilesLocator.swift
Labels: changelog:changed

#5875 Fix error message on missing dependencies
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
Labels: changelog:fixed

#5892 Support visionOS from the default templates to synthesize resources
  Sources/TuistGenerator/Templates/FontsTemplate.swift
Labels: changelog:added

#5909 Fix DEFINES_MODULE warning
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:fixed

#5905 Improve verbose logging by logging the workspace, project, and workspace transformations
  Sources/TuistAutomation/ProjectMappers/SkipUITestsProjectMapper.swift
  Sources/TuistAutomation/ProjectMappers/SourceRootPathProjectMapper.swift
  Sources/TuistDependencies/Mappers/ExternalProjectsPlatformNarrowerGraphMapper.swift
  Sources/TuistDependencies/Mappers/PruneOrphanExternalTargetsGraphMapper.swift
  Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  Sources/TuistGenerator/Mappers/AutogeneratedWorkspaceSchemeWorkspaceMapper.swift
  Sources/TuistGenerator/Mappers/DeleteDerivedDirectoryProjectMapper.swift
  Sources/TuistGenerator/Mappers/ExplicitDependencyGraphMapper.swift
  Sources/TuistGenerator/Mappers/GenerateEntitlementsProjectMapper.swift
  Sources/TuistGenerator/Mappers/GenerateInfoPlistProjectMapper.swift
  Sources/TuistGenerator/Mappers/IDETemplateMacrosMapper.swift
  Sources/TuistGenerator/Mappers/LastUpgradeVersionWorkspaceMapper.swift
  Sources/TuistGenerator/Mappers/ModuleMapMapper.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistGenerator/Mappers/SynthesizedResourceInterfaceProjectMapper.swift
  Sources/TuistGenerator/Mappers/TargetActionDisableShowEnvVarsProjectMapper.swift
  Sources/TuistKit/Mappers/Graph/UpdateWorkspaceProjectsGraphMapper.swift
  Sources/TuistKit/Mappers/TreeShakePrunedTargetsGraphMapper.swift
  Sources/TuistKit/Mappers/Workspace/TuistWorkspaceIdentifierMapper.swift
  Sources/TuistKit/Mappers/Workspace/TuistWorkspaceRenderMarkdownMapper.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Sources/TuistSupport/Utils/FileHandler.swift
Labels: changelog:changed

#5887 Fix integration of Objective C dependencies
  Sources/TuistGenerator/Mappers/ModuleMapMapper.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistLoader/SwiftPackageManager/SwiftPackageManagerModuleMapGenerator.swift
  Tests/TuistGeneratorTests/ProjectMappers/ModuleMapMapperTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/SwiftPackageManagerModuleMapGeneratorTests.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
  fixtures/app_with_spm_dependencies/Package.resolved
  fixtures/app_with_spm_dependencies/Package.swift
Labels: changelog:fixed

#5914 Fix caching package manifests
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Sources/TuistSupport/SwiftPackageManager/PackageInfo.swift
  Tests/TuistSupportTests/SwiftPackageManager/PackageInfoTests.swift
Labels: changelog:fixed

#5919 Improve the error when users try to build or test multi-platform targets
  Sources/TuistKit/Utils/Target+PlatformResolution.swift
Labels: changelog:changed

#5923 Remove Mockable from the list of targets that depend on XCTest
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
Labels: changelog:changed

#5922 Improve performance by replacing globing with FileManager when finding resource files
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistLoader/Utils/ManifestFilesLocator.swift
  Sources/TuistSupport/Utils/FileHandler.swift
  Sources/TuistSupportTesting/TestCase/TuistTestCase.swift
  Tests/TuistGeneratorTests/Generator/WorkspaceStructureGeneratorTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:changed

#5929 Fix runtime crash when using Obj-C dependencies
  Sources/TuistGenerator/Mappers/ModuleMapMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ModuleMapMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
Labels: changelog:fixed

#5932 Fix integration of Objective C dependencies with resources
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistLoader/SwiftPackageManager/SwiftPackageManagerModuleMapGenerator.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
Labels: changelog:fixed

#5935 Fix integration of AppCenter
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
  fixtures/app_with_spm_dependencies/Package.resolved
  fixtures/app_with_spm_dependencies/Package.swift
Labels: changelog:fixed

#5945 Fix integration of SPM dependencies with resources
  Sources/TuistCore/Graph/ModelExtensions/Project+Core.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistKit/Mappers/Factories/ProjectMapperFactory.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
  fixtures/app_with_spm_dependencies/Package.resolved
  fixtures/app_with_spm_dependencies/Package.swift
Labels: changelog:fixed

#5946 Fix DEFINES_MODULE warning
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:fixed

#5947 Make Tuist/Package.swift a valid location for the SPM manifest
  Sources/TuistKit/Services/CleanService.swift
  Sources/TuistKit/Services/InstallService.swift
  Sources/TuistLoader/Loaders/PackageSettingsLoader.swift
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Sources/TuistLoader/Utils/ManifestFilesLocator.swift
  Tests/TuistKitTests/Services/CleanServiceTests.swift
  Tests/TuistKitTests/Services/InstallServiceTests.swift
  Tests/TuistLoaderTests/Loaders/PackageSettingsLoaderTests.swift
  Tests/TuistLoaderTests/Utils/ManifestFilesLocatorTests.swift
  docs/Sources/tuist/tuist.docc/Articles/Tuist/Users/Tutorials/Tuist Tutorial/Getting-Started/Add External Dependencies/external-dependencies.tutorial
  docs/Sources/tuist/tuist.docc/Articles/Tuist/Users/dependencies.md
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
  fixtures/framework_with_native_swift_macro/Tuist/.gitkeep
  fixtures/multiplatform_app_with_sdk/Tuist/.gitkeep
Labels: changelog:changed

#5948 Fix failing tuist install when a package is removed
  Sources/TuistAutomation/Utilities/BuildGraphInspector.swift
  Sources/TuistCore/Graph/ModelExtensions/Project+Core.swift
  Sources/TuistDependencies/Mappers/ExternalDependencyPathWorkspaceMapper.swift
  Sources/TuistGenerator/Generator/WorkspaceStructureGenerator.swift
  Sources/TuistGenerator/Mappers/GenerateInfoPlistProjectMapper.swift
  Sources/TuistGenerator/Mappers/ModuleMapMapper.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistKit/Mappers/Factories/WorkspaceMapperFactory.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistLoader/SwiftPackageManager/SwiftPackageManagerModuleMapGenerator.swift
  Sources/TuistSupport/Constants.swift
  Tests/TuistDependenciesTests/Mappers/ExternalDependencyPathWorkspaceMapper.swift
  Tests/TuistGeneratorTests/Generator/WorkspaceStructureGeneratorTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ModuleMapMapperTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/SwiftPackageManagerModuleMapGeneratorTests.swift
Labels: changelog:fixed

#5954 Add missing `region` parameter in static helper `RunActionOptions`.`options`
  Sources/ProjectDescription/RunActionOptions.swift
  Sources/TuistLoaderTesting/Loaders/TestData/ProjectDescription+TestData.swift
  Tests/ProjectDescriptionTests/SchemeTests.swift
Labels: changelog:fixed

#5957 Fix integration of local packages with Objective C targets
  Sources/TuistGenerator/Mappers/DeleteDerivedDirectoryProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/DeleteDerivedDirectoryProjectMapperTests.swift
  fixtures/app_with_spm_dependencies/LocalSwiftPackageB/Package.swift
  fixtures/app_with_spm_dependencies/LocalSwiftPackageB/Sources/LibraryA/MyStruct.swift
  fixtures/app_with_spm_dependencies/LocalSwiftPackageB/Sources/LibraryAProxy/Test.mm
  fixtures/app_with_spm_dependencies/LocalSwiftPackageB/Sources/LibraryAProxy/include/Test.h
Labels: changelog:fixed

#5953 Remove PackageSettings platforms property
  Package.swift
  Sources/ProjectDescription/PackageSettings.swift
  Sources/TuistGraph/Models/Dependencies/PackageSettings.swift
  Sources/TuistGraphTesting/Models/PackageSettings+TestData.swift
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/PackageSettings+ManifestMapper.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistKitIntegrationTests/Commands/DumpServiceIntegrationTests.swift
  Tests/TuistLoaderIntegrationTests/Loaders/ManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/PackageSettingsLoaderTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  docs/Sources/tuist/tuist.docc/Articles/Tuist/Users/Tutorials/Tuist Tutorial/Getting-Started/Add External Dependencies/Package.swift
  fixtures/app_with_plugins/Package.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
  fixtures/multiplatform_app_with_sdk/Package.swift
Labels: changelog:changed

#5913 Migrate CI pipelines to Codemagic
  .github/workflows/deploy-tuist-docc-dry-run.yml
  .github/workflows/deploy-tuist-docc.yml
  .github/workflows/tuist.yml
  codemagic.yaml
Labels: changelog:added

#5813 avoid infinite loop caused by symbolic links
  Sources/TuistSupport/Extensions/FileManager+Extras.swift
Labels: changelog:fixed

#5983 Add support for the new `package` access modifier
  Sources/TuistCoreTesting/Graph/DependenciesGraph+TestData.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:added

#5990 SPM dependencies now implicitly support all platforms
  Sources/TuistCore/Simulator/SimulatorController.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/App/Sources/VisionOS/App/VisionOSApp.swift
Labels: changelog:changed

#5999 Fix spm bundle recursion
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  fixtures/app_with_spm_dependencies/App/Project.swift
  fixtures/app_with_spm_dependencies/App/Sources/AppKit/AppKit.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#5992 Add `bundleId` and `settings` to `ProjectAutomation` graph
  Sources/ProjectAutomation/Configuration.swift
  Sources/ProjectAutomation/Settings.swift
  Sources/ProjectAutomation/Target.swift
  Sources/TuistKit/Services/GraphService.swift
  Sources/TuistKit/Services/ProjectAutomation+ManifestMapper.swift
  Sources/TuistKit/Services/TuistService.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
Labels: changelog:added
