Repository tuist/tuist, pull requests merged in 2024-12, with the labels that each got.

#7124 Document the TUIST_S3_VIRTUAL_HOST environment variable
  docs/docs/en/server/on-premise/install.md
Labels: changelog:added, size:XS, lgtm

#6537 Add metal diagnostics options to 'RunAction'
  Sources/ProjectDescription/MetalOptions.swift
  Sources/ProjectDescription/RunAction.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceTestCase+Extra.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/MetalOptions+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/RunAction+ManifestMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorIntegrationTests/Generator/TestModelGenerator.swift
  Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/MetalOptions+ManifestMapperTests.swift
  fixtures/app_with_metal_options/App/MetalOptionsApp.swift
  fixtures/app_with_metal_options/Project.swift
  fixtures/app_with_metal_options/README.md
  fixtures/app_with_metal_options/Tuist/Config.swift
Labels: changelog:added, size:L, lgtm

#7121 Update implicit dependencies tip in cost of convenience
  docs/docs/en/guides/develop/projects/cost-of-convenience.md
Labels: changelog:changed, size:XS, lgtm

#7117 Automate Tuist app homebrew cask release
  .github/workflows/release.yml
  .mise/tasks/workspace/release/homebrew-cask
  docs/docs/en/guides/share/previews.md
Labels: lgtm

#7113 feat: keep message of installed preview with its commit sha
  Sources/TuistKit/Services/RunService.swift
  Sources/TuistServer/Models/Preview.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/GetPreviewService.swift
  Tests/TuistKitTests/Services/RunServiceTests.swift
  app/TuistApp/Sources/Services/DeviceService.swift
  app/TuistApp/Sources/StatusView.swift
  app/TuistApp/Sources/Utilities/StatusReporter/TaskState.swift
  app/TuistApp/Sources/Utilities/StatusReporter/TaskStatus.swift
  app/TuistApp/Sources/Utilities/StatusReporter/TaskStatusReporter.swift
  app/TuistApp/Sources/Views/DevicesView/DevicesViewModel.swift
  app/TuistApp/Tests/Services/DeviceServiceTests.swift
Labels: size:L

#7116 New Crowdin updates
  docs/docs/es/guides/develop/projects/cost-of-convenience.md
  docs/docs/es/guides/share/previews.md
  docs/docs/es/server/on-premise/install.md
  docs/docs/es/server/on-premise/metrics.md
  docs/docs/ja/contributors/get-started.md
  docs/docs/ja/guides/develop/projects/cost-of-convenience.md
  docs/docs/ja/guides/quick-start/create-a-project.md
  docs/docs/ja/guides/quick-start/gather-insights.md
  docs/docs/ja/guides/share/previews.md
  docs/docs/ja/guides/start/swift-package.md
  docs/docs/ja/server/on-premise/install.md
  docs/docs/ja/server/on-premise/metrics.md
  docs/docs/ko/guides/develop/projects/cost-of-convenience.md
  docs/docs/ko/guides/share/previews.md
  docs/docs/ko/server/on-premise/install.md
  docs/docs/ko/server/on-premise/metrics.md
  docs/docs/pt/guides/develop/projects/cost-of-convenience.md
  docs/docs/pt/guides/share/previews.md
  docs/docs/pt/server/on-premise/install.md
  docs/docs/pt/server/on-premise/metrics.md
  docs/docs/ru/guides/develop/projects/cost-of-convenience.md
  docs/docs/ru/guides/share/previews.md
  docs/docs/ru/server/on-premise/install.md
  docs/docs/ru/server/on-premise/metrics.md
Labels: size:L

#7131 Remove duplicate Path dependency to fix warning.
  Package.swift
Labels: changelog:fixed, size:XS, lgtm

#7135 Documentation: Fix typo, remove duplicated import
  docs/docs/en/guides/start/migrate/xcode-project.md
Labels: changelog:fixed, size:XS, lgtm

#7138 Show Codemagic more prominently in our README
  README.md
Labels: size:S, lgtm

#7141 Document new accounts, previews, and projects metrics
  docs/docs/en/server/on-premise/metrics.md
Labels: changelog:added, size:M, lgtm

#7147 Fix bundle access synthesized interface for static libraries with Objective-C code
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
Labels: type:bug, changelog:fixed, size:M, lgtm

#7140 New Crowdin updates
  docs/docs/es/contributors/code-reviews.md
  docs/docs/es/server/on-premise/metrics.md
  docs/docs/ja/contributors/get-started.md
  docs/docs/ja/server/on-premise/metrics.md
  docs/docs/ko/server/on-premise/metrics.md
  docs/docs/pt/server/on-premise/metrics.md
  docs/docs/ru/server/on-premise/metrics.md
Labels: size:L

#7149 New Crowdin updates
  docs/.vitepress/strings/ko.json
  docs/docs/es/server/on-premise/metrics.md
  docs/docs/ja/contributors/get-started.md
  docs/docs/ja/server/on-premise/metrics.md
  docs/docs/ko/server/on-premise/metrics.md
  docs/docs/pt/server/on-premise/metrics.md
  docs/docs/ru/server/on-premise/metrics.md
Labels: size:M

#7136 Remove unnecessary Copy Executables build phase.
  Sources/TuistGenerator/Generator/LinkGenerator.swift
  Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Generator/LinkGeneratorTests.swift
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Project.swift
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Targets/WatchApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Targets/WatchApp/Assets.xcassets/Contents.json
  fixtures/app_with_executable_non_local_dependencies/HelperAppTargets/Targets/WatchApp/Base.lproj/Interface.storyboard
  fixtures/app_with_executable_non_local_dependencies/MainApp/Project.swift
Labels: changelog:fixed, size:L, lgtm

#7108 Fix mise exec tuist generate in documentation
  docs/docs/en/guides/develop/automate/continuous-integration.md
Labels: size:XS, lgtm

#7134 Add support for building Mac Catalyst apps
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistAutomation/Utilities/XcodeBuildDestination+Find.swift
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
  Sources/TuistCore/Automation/XcodeBuildControlling.swift
  Sources/TuistCore/Simulator/SimulatorController.swift
  Sources/TuistGenerator/Settings/DefaultSettingsProvider.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Settings/DefaultSettingsProviderTests.swift
  codemagic.yaml
  fixtures/ios_app_with_catalyst/App/Sources/AppDelegate.swift
  fixtures/ios_app_with_catalyst/App/Sources/ContentView.swift
  fixtures/ios_app_with_catalyst/Project.swift
  fixtures/ios_app_with_catalyst/Tuist.swift
  fixtures/ios_app_with_catalyst/Tuist/Package.swift
Labels: changelog:added, size:L, lgtm

#7102 Update vitepress
  docs/.vitepress/config.mjs
  docs/.vitepress/data/cli.js
  docs/docs/en/guides/start/migrate/bazel-project.md
  docs/package.json
  docs/pnpm-lock.yaml
Labels: changelog:changed, size:S

#7095 Update social links in docs and README
  README.md
  docs/.vitepress/config.mjs
Labels: size:XS, lgtm

#7154 Fix not hashing additional strings such as configuration
  Sources/TuistHasher/TargetContentHasher.swift
  Tests/TuistCacheIntegrationTests/CacheGraphContentHasherIntegrationTests.swift
  Tests/TuistHasherTests/TargetContentHasherTests.swift
  Tests/TuistKitAcceptanceTests/CacheAcceptanceTests.swift
Labels: changelog:fixed, size:M

#7158 Do not output warnings for cache xcframeworks linked mulitple times
  Sources/TuistCore/Graph/Mappers/MapperEnvironmentKeys.swift
  Sources/TuistKit/Generator/Generator.swift
Labels: type:enhancement, changelog:fixed, size:S, lgtm

#7159 Fix XcodeProj-based integration of packages with dashes in their name e.g. swift-cmark
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/app_with_swift_cmark/App/Sources/ContentView.swift
  fixtures/app_with_swift_cmark/App/Sources/MyApp.swift
  fixtures/app_with_swift_cmark/Project.swift
  fixtures/app_with_swift_cmark/Tuist.swift
  fixtures/app_with_swift_cmark/Tuist/Package.resolved
  fixtures/app_with_swift_cmark/Tuist/Package.swift
Labels: changelog:fixed, size:L, lgtm

#7163 Add "Example" Suffix to targetSchemesGrouping.
  Sources/ProjectDescription/ProjectOptions.swift
Labels: changelog:changed, size:XS, lgtm

#7162 Update Synthesized files to Comply with Xcode auto generated code for image assets
  Sources/TuistGenerator/Templates/AssetsTemplate.swift
  fixtures/ios_app_with_framework_and_resources/App/Sources/AppDelegate.swift
  fixtures/ios_app_with_framework_and_resources/StaticFramework3/Project.swift
  fixtures/ios_app_with_framework_and_resources/StaticFramework3/Resources/Assets.xcassets/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework3/Sources/ResourcesStaticFramework3.swift
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Assets.xcassets/Symbol.symbolset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Resources/Preview Content/Preview Assets.xcassets/Image.imageset/Contents.json
  fixtures/ios_app_with_on_demand_resources/AppWithOnDemandResources/Sources/ContentView.swift
Labels: type:enhancement, changelog:changed, size:L, lgtm

#7156 Fix generate project with local spm dependency without Tuist directory in path
  Sources/TuistCore/Utils/RootDirectoryLocator.swift
  Tests/TuistCoreIntegrationTests/RootDirectoryLocatorTests.swift
Labels: changelog:fixed, size:M, lgtm

#7169 Fix missing package-name setting when a custom OTHER_SWIFT_FLAGS value is defined
  Sources/TuistLoader/Models/DependenciesGraph.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/app_with_composable_architecture/Tuist/Package.swift
Labels: changelog:fixed, size:L, lgtm

#7171 Rename 'smart test runs' to 'selective testing'
  docs/.vitepress/bars.mjs
  docs/.vitepress/config.mjs
  docs/.vitepress/strings/en.json
  docs/docs/en/guides/develop/projects/dependencies.md
  docs/docs/en/guides/develop/test.md
  docs/docs/en/guides/develop/test/selective-testing.md
Labels: size:S, lgtm

#7173 Add ProjectDescription scheme
  Project.swift
Labels: type:enhancement, size:XS, lgtm

#7177 docs: Fix configuration name in xcode-project.md
  docs/docs/en/guides/start/migrate/xcode-project.md
Labels: changelog:fixed, size:XS

#7184 Document how to verify the authenticity of binaries
  docs/docs/en/guides/quick-start/install-tuist.md
  docs/docs/public/verify.sh
Labels: changelog:changed, size:S

#7183 Add TUIST_CACHE_EXTERNAL_ONLY environment value for `tuist cache`
  Sources/TuistKit/Commands/CacheCommand.swift
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Tests/TuistKitTests/CommandEnvironmentVariables/CommandEnvironmentVariableTests.swift
Labels: type:enhancement, changelog:added, size:M, lgtm

#7195 Add docs for registry usage in Xcode projects
  docs/docs/en/guides/develop/build/registry.md
  docs/docs/public/images/guides/develop/build/registry/registry-add-package.png
Labels: size:XS

#7201 Update deprecation warning message to PackageSettings initializer
  Sources/ProjectDescription/PackageSettings.swift
Labels: type:enhancement, changelog:changed, size:XS, lgtm
