Repository tuist/tuist, pull requests merged in 2024-07, with the labels that each got.

#6447 Add missing target settings `MERGED_BINARY_TYPE` and `MERGEABLE_LIBRARY`
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
Labels: changelog:fixed

#6469 Fix generate failing due to duplicate keys
  Package.resolved
  Package.swift
  Sources/TuistCore/Utils/RootDirectoryLocator.swift
  Sources/TuistCoreTesting/Utils/MockRootDirectoryLocator.swift
  Sources/TuistLoader/Loaders/ManifestLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/Workspace+ManifestMapper.swift
  Sources/TuistLoader/Utils/ProjectDescription+TestData.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockManifestLoader.swift
  Sources/TuistLoaderTesting/Loaders/TestData/ProjectDescription+TestData.swift
  Tests/TuistGeneratorTests/Linter/EnvironmentLinterTests.swift
  Tests/TuistKitTests/Services/CleanServiceTests.swift
  Tests/TuistKitTests/Services/EditServiceTests.swift
  Tests/TuistKitTests/Services/Plugin/PluginArchiveServiceTests.swift
  Tests/TuistLoaderTests/Loaders/CachedManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/ConfigLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/ManifestModelConverterTests.swift
  Tests/TuistLoaderTests/Loaders/PackageSettingsLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/RecursiveManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/TemplateLoaderTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Workspace+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models/GeneratorPathsTests.swift
  Tests/TuistPluginTests/PluginServiceTests.swift
  Tests/TuistServerTests/Services/AnalyticsArtifactUploadServiceTests.swift
  Tests/TuistServerTests/Session/CloudSessionControllerTests.swift
Labels: changelog:fixed

#6472 Change tuist project subcommands to accept full handle
  Sources/TuistKit/Commands/Cloud/CloudInitCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudProjectCreateCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudProjectDeleteCommand.swift
  Sources/TuistKit/Commands/Cloud/CloudProjectTokenCommand.swift
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Services/Cloud/CloudInitService.swift
  Sources/TuistKit/Services/Cloud/CloudProjectCreateService.swift
  Sources/TuistKit/Services/Cloud/CloudProjectDeleteService.swift
  Sources/TuistKit/Services/Cloud/CloudProjectTokenService.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/cloud.yml
  Sources/TuistServer/Services/CreateProjectService.swift
  Sources/TuistServer/Services/GetProjectService.swift
  Tests/TuistKitAcceptanceTests/ServerAcceptanceTests.swift
  Tests/TuistKitTests/Cloud/CloudInitServiceTests.swift
  Tests/TuistKitTests/Cloud/CloudProjectDeleteServiceTests.swift
  Tests/TuistKitTests/CommandEnvironmentVariables/CommandEnvironmentVariableTests.swift
  docs/docs/cloud/get-started.md
Labels: changelog:fixed

#6474 Flatten the tuist-cloud cache directory into the tuist cache directory
  Sources/TuistCore/Cache/CacheCategory.swift
  Sources/TuistCore/Cache/CacheDirectoriesProvider.swift
  Sources/TuistCore/Cache/CacheDirectoriesProviderFactory.swift
  Sources/TuistKit/ProjectEditor/ProjectEditor.swift
  Sources/TuistKit/Services/CleanService.swift
  Sources/TuistKit/Services/EditService.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistKit/Utils/TuistAnalyticsServerBackend.swift
  Sources/TuistLoader/Loaders/CachedManifestLoader.swift
  Sources/TuistLoader/Loaders/ManifestLoader.swift
  Sources/TuistPlugin/PluginService.swift
  Sources/TuistServer/Cache/CacheStoring.swift
  Sources/TuistServer/Cache/EmptyCacheStorage.swift
  Sources/TuistServer/OpenAPI/CacheCategoryParameter+Extras.swift
  Sources/TuistServer/Services/CacheExistsService.swift
  Sources/TuistServer/Services/GetCacheService.swift
  Sources/TuistServer/Services/MultipartUploadCompleteCacheService.swift
  Sources/TuistServer/Services/MultipartUploadGenerateURLCacheService.swift
  Sources/TuistServer/Services/MultipartUploadStartCacheService.swift
  Tests/TuistKitTests/Services/CleanServiceTests.swift
  Tests/TuistKitTests/Services/EditServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsServerBackendTests.swift
  Tests/TuistLoaderTests/Loaders/CachedManifestLoaderTests.swift
  Tests/TuistPluginTests/PluginServiceTests.swift
Labels: changelog:changed

#6475 Deprecate cloud in Config in favor of fullHandle and url
  Sources/ProjectDescription/Config.swift
  Sources/ProjectDescription/ConfigGenerationOptions.swift
  Sources/TuistCore/Models/Cloud.swift
  Sources/TuistCore/Models/Config.swift
  Sources/TuistCore/Models/ConfigGenerationOptions.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/AnalyticsService.swift
  Sources/TuistKit/Services/AuthService.swift
  Sources/TuistKit/Services/CleanService.swift
  Sources/TuistKit/Services/LogoutService.swift
  Sources/TuistKit/Services/Organization/OrganizationBillingService.swift
  Sources/TuistKit/Services/Organization/OrganizationCreateService.swift
  Sources/TuistKit/Services/Organization/OrganizationDeleteService.swift
  Sources/TuistKit/Services/Organization/OrganizationInviteService.swift
  Sources/TuistKit/Services/Organization/OrganizationListService.swift
  Sources/TuistKit/Services/Organization/OrganizationRemoveInviteService.swift
  Sources/TuistKit/Services/Organization/OrganizationRemoveMemberService.swift
  Sources/TuistKit/Services/Organization/OrganizationRemoveSSOService.swift
  Sources/TuistKit/Services/Organization/OrganizationShowService.swift
  Sources/TuistKit/Services/Organization/OrganizationUpdateMemberService.swift
  Sources/TuistKit/Services/Organization/OrganizationUpdateService.swift
  Sources/TuistKit/Services/Project/ProjectCreateService.swift
  Sources/TuistKit/Services/Project/ProjectDeleteService.swift
  Sources/TuistKit/Services/Project/ProjectListService.swift
  Sources/TuistKit/Services/Project/ProjectTokenService.swift
  Sources/TuistKit/Services/SessionService.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistKit/Utils/TuistAnalyticsServerBackend.swift
  Sources/TuistLoader/Models+ManifestMappers/Cloud+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Config+ManifestMapper.swift
  Sources/TuistLoader/Utils/ProjectDescription+TestData.swift
  Sources/TuistServer/Models/ServerCacheArtifact.swift
  Sources/TuistServer/Services/ServerURLService.swift
  Sources/TuistSupport/Constants.swift
  Tests/TuistGeneratorIntegrationTests/Generator/MultipleConfigurationsIntegrationTests.swift
  Tests/TuistGeneratorIntegrationTests/Generator/SwiftPackageManagerInteractorTests.swift
  Tests/TuistKitIntegrationTests/Commands/DumpServiceIntegrationTests.swift
  Tests/TuistKitTests/Services/AuthServiceTests.swift
  Tests/TuistKitTests/Services/CleanServiceTests.swift
  Tests/TuistKitTests/Services/LogoutServiceTests.swift
  Tests/TuistKitTests/Services/Organization/OrganizationInviteServiceTests.swift
  Tests/TuistKitTests/Services/Organization/OrganizationListServiceTests.swift
  Tests/TuistKitTests/Services/Organization/OrganizationRemoveSSOServiceTests.swift
  Tests/TuistKitTests/Services/Organization/OrganizationShowServiceTests.swift
  Tests/TuistKitTests/Services/Organization/OrganizationUpdateSSOService.swift
  Tests/TuistKitTests/Services/Project/ProjectDeleteServiceTests.swift
  Tests/TuistKitTests/Services/Project/ProjectListServiceTests.swift
  Tests/TuistKitTests/Services/SessionServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsServerBackendTests.swift
  Tests/TuistLoaderTests/Loaders/ConfigLoaderTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Cloud+ManifestMapperTests.swift
  Tests/TuistPluginTests/PluginServiceTests.swift
  docs/docs/cloud/get-started.md
  fixtures/ios_app_with_frameworks/Tuist/Config.swift
Labels: changelog:changed

#6476 Deprecate the usage TUIST_CONFIG_CLOUD_TOKEN in favor of TUIST_CONFIG_TOKEN
  Project.swift
  Sources/TuistKit/Commands/Project/ProjectTokenCommand.swift
  Sources/TuistServer/Utilities/ServerAuthenticationController.swift
  Sources/TuistSupport/Constants.swift
  docs/docs/cloud/get-started.md
Labels: changelog:changed

#6483 Fix missing test targets when generating an SPM package
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  fixtures/spm_package/Package.resolved
  fixtures/spm_package/Package.swift
Labels: changelog:fixed

#6491 Lint target references in a scheme
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
Labels: changelog:added

#6513 Escape header search paths for external dependencies from SPM
  Sources/TuistLoader/SwiftPackageManager/SettingsMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:fixed

#6518 Respect --verbose for machine readable commands
  Sources/TuistSupport/Logging/Logger.swift
  Sources/tuist/TuistApp.swift
Labels: changelog:fixed

#6520 Fix linking static xcframeworks linked via dynamic xcframeworks
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  fixtures/ios_app_with_dynamic_frameworks_linking_static_frameworks/.gitignore
  fixtures/ios_app_with_dynamic_frameworks_linking_static_frameworks/App/Sources/App.swift
  fixtures/ios_app_with_dynamic_frameworks_linking_static_frameworks/App/Sources/ContentView.swift
  fixtures/ios_app_with_dynamic_frameworks_linking_static_frameworks/App/Tests/AppTests.swift
  fixtures/ios_app_with_dynamic_frameworks_linking_static_frameworks/DynamicFrameworkA/DynamicFrameworkA.swift
  fixtures/ios_app_with_dynamic_frameworks_linking_static_frameworks/DynamicFrameworkA/Thing.swift
  fixtures/ios_app_with_dynamic_frameworks_linking_static_frameworks/DynamicFrameworkB/Choice.swift
  fixtures/ios_app_with_dynamic_frameworks_linking_static_frameworks/Project.swift
  fixtures/ios_app_with_dynamic_frameworks_linking_static_frameworks/Tuist/Package.resolved
  fixtures/ios_app_with_dynamic_frameworks_linking_static_frameworks/Tuist/Package.swift
Labels: changelog:fixed

#6507 Add email and password auth options for non-interactive login
  Project.swift
  Sources/TuistAcceptanceTesting/ServerAcceptanceTestCase.swift
  Sources/TuistKit/Commands/AuthCommand.swift
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Services/AuthService.swift
  Sources/TuistServer/Models/ServerAuthenticationTokens.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/cloud.yml
  Sources/TuistServer/Services/AuthenticateService.swift
  Sources/TuistSupport/UserInputReader.swift
  Tests/TuistKitAcceptanceTests/ServerAcceptanceTests.swift
  Tests/TuistKitTests/Services/AuthServiceTests.swift
  Tests/TuistSupportTests/Utils/UserInputReaderTests.swift
Labels: changelog:added

#6528 Fix token not found when using TUIST_CONFIG_TOKEN environment variable
  Sources/TuistLoader/Loaders/ManifestLoaderFactory.swift
  Sources/TuistSupport/Utils/Environment.swift
  Sources/TuistSupportTesting/Utils/MockEnvironment.swift
  Tests/TuistLoaderTests/Loaders/ManifestLoaderFactoryTests.swift
Labels: changelog:fixed

#6530 Fix optionalAuthentication generation option in Config.swift
  Sources/TuistCore/Models/Config.swift
  Sources/TuistLoader/Models+ManifestMappers/Config+ManifestMapper.swift
  Tests/TuistLoaderTests/Loaders/ConfigLoaderTests.swift
Labels: changelog:fixed

#6531 Mark the Cloud static initializer as deprecated
  Sources/ProjectDescription/Cloud.swift
Labels: changelog:changed

#6540 Update generated code templates to add `Sendable` Conformance
  Sources/TuistGenerator/Templates/AssetsTemplate.swift
  Sources/TuistGenerator/Templates/FontsTemplate.swift
  Sources/TuistGenerator/Templates/PlistsTemplate.swift
  Sources/TuistGenerator/Templates/StringsTemplate.swift
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Project.swift
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/Property List.plist
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Color.colorset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Cube Texture.cubetextureset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Cube Texture.cubetextureset/Universal +X.mipmapset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Cube Texture.cubetextureset/Universal +Y.mipmapset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Cube Texture.cubetextureset/Universal +Z.mipmapset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Cube Texture.cubetextureset/Universal -X.mipmapset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Cube Texture.cubetextureset/Universal -Y.mipmapset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Cube Texture.cubetextureset/Universal -Z.mipmapset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Data.dataset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Sprites.spriteatlas/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Sprites.spriteatlas/Sprite.imageset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Symbol.symbolset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Texture.textureset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/assets.xcassets/Texture.textureset/Universal.mipmapset/Contents.json
  fixtures/ios_app_with_framework_and_resources/StaticFramework5/Resources/en.lproj/Localizable.strings
Labels: changelog:changed

#6536 Validate target references in custom workspace schemes
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistLoader/Linter/ManifestLinter.swift
  Tests/TuistLoaderTests/Linters/ManifestLinterTests.swift
  Tests/TuistLoaderTests/Linters/Mocks/MockManifestLinter.swift
Labels: changelog:added

#6559 Default to staticLibrary in product type mapping if automatic product type exists
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:fixed, 🙋 Bounty claim

#6561 Support unit test depending on an app extension
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGenerator/Linter/GraphLinter.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  fixtures/ios_app_with_extension_and_tests/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/ios_app_with_extension_and_tests/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/ios_app_with_extension_and_tests/App/Resources/Assets.xcassets/Contents.json
  fixtures/ios_app_with_extension_and_tests/App/Sources/MainApp.swift
  fixtures/ios_app_with_extension_and_tests/AppExtension/ExtensionViewController.swift
  fixtures/ios_app_with_extension_and_tests/AppExtensionTests/ExtensionTests.swift
  fixtures/ios_app_with_extension_and_tests/Project.swift
  fixtures/ios_app_with_extension_and_tests/README.md
Labels: changelog:added

#6571 Fix the Homebrew installation instructions in the docs
  docs/docs/guides/quick-start/install-tuist.md
Labels: changelog:fixed

#6566 Improve the help menu by grouping the flat list of commands and add `tuist project view` command
  Package.resolved
  Package.swift
  Sources/TuistKit/Commands/AnalyticsCommand.swift
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Commands/Project/ProjectViewCommand.swift
  Sources/TuistKit/Commands/ProjectCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/AnalyticsService.swift
  Sources/TuistKit/Services/Project/ProjectViewService.swift
  Sources/TuistSupport/Utils/Opener.swift
  Tests/TuistKitTests/CommandEnvironmentVariables/CommandEnvironmentVariableTests.swift
  Tests/TuistKitTests/Services/Project/ProjectViewServiceTests.swift
Labels: changelog:changed

#6174 Fix globstar expansion logic to prevent infinite loop when file path contains `**`
  Sources/TuistSupport/Utils/Glob.swift
  Tests/TuistSupportTests/Utils/GlobTests.swift
Labels: changelog:fixed

#6572 Fix storing test results of non-tested schemes
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistAutomation/Utilities/AutomationStorage.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/Graph/Mappers/GraphMapper.swift
  Sources/TuistCore/Graph/Mappers/MapperEnvironment.swift
  Sources/TuistCore/Graph/Mappers/MapperEnvironmentKeys.swift
  Sources/TuistCore/GraphTraverser/GraphTraversing.swift
  Sources/TuistCoreTesting/GraphTraverser/MockGraphTraverser.swift
  Sources/TuistDependencies/Mappers/ExternalProjectsPlatformNarrowerGraphMapper.swift
  Sources/TuistDependencies/Mappers/PruneOrphanExternalTargetsGraphMapper.swift
  Sources/TuistGenerator/Mappers/ExplicitDependencyGraphMapper.swift
  Sources/TuistGenerator/Mappers/ModuleMapMapper.swift
  Sources/TuistKit/Generator/Generator.swift
  Sources/TuistKit/Generator/GeneratorFactory.swift
  Sources/TuistKit/Mappers/Factories/GraphMapperFactory.swift
  Sources/TuistKit/Mappers/FocusTargetsGraphMappers.swift
  Sources/TuistKit/Mappers/Graph/UpdateWorkspaceProjectsGraphMapper.swift
  Sources/TuistKit/Mappers/TreeShakePrunedTargetsGraphMapper.swift
  Sources/TuistKit/Services/GraphService.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Tests/TuistAutomationAcceptanceTests/TestAcceptanceTests.swift
  Tests/TuistCoreTests/Graph/Mappers/GraphMapperTests.swift
  Tests/TuistDependenciesTests/Mappers/ExternalProjectsPlatformNarrowerGraphMapperTests.swift
  Tests/TuistDependenciesTests/Mappers/PruneOrphanExternalTargetsGraphMapperTests.swift
  Tests/TuistGeneratorTests/Generator/LinkGeneratorTests.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ExplicitDependencyGraphMapperTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ModuleMapMapperTests.swift
  Tests/TuistKitIntegrationTests/Utils/ManifestGraphLoaderIntegrationTests.swift
  Tests/TuistKitTests/Generator/Mocks/MockGenerator.swift
  Tests/TuistKitTests/Mappers/FocusTargetsGraphMappersTests.swift
  Tests/TuistKitTests/Mappers/Graph/TreeShakePrunedTargetsGraphMapperTests.swift
  Tests/TuistKitTests/Mappers/Graph/UpdateWorkspaceProjectsGraphMapperTests.swift
  Tests/TuistKitTests/Mocks/MockManifestGraphLoader.swift
  Tests/TuistKitTests/Services/Cache/CachePrintHashesServiceTests.swift
  Tests/TuistKitTests/Services/GraphServiceTests.swift
  Tests/TuistKitTests/Services/RunServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:fixed

#6580 Fix clean printed twice in tuist --help
  Sources/TuistKit/Commands/TuistCommand.swift
Labels: changelog:fixed

#6584 Generate SPM Objective-C resource accessor only when a bundle is generated
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
Labels: changelog:fixed
