Repository tuist/tuist, pull requests merged in 2025-05, with the labels that each got.

#7550 Fix compilation error in synthesised code when the feature "InternalImportsByDefault" is enabled
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
Labels: changelog:fixed

#7558 Fix implicit import detection when target points to absent files
  Sources/TuistKit/Services/TargetImportsScanner.swift
  Tests/TuistKitTests/ImportFinder/TargetImportsScannerTests.swift
Labels: changelog:fixed

#7436 Add bundle analysis
  Package.resolved
  Package.swift
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Commands/Inspect/InspectBundleCommand.swift
  Sources/TuistKit/Commands/InspectCommand.swift
  Sources/TuistKit/Services/Inspect/InspectBundleCommandService.swift
  Sources/TuistServer/Models/ServerBundle.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/AuthenticateService.swift
  Sources/TuistServer/Services/CreateBundleService.swift
  Tests/TuistKitAcceptanceTests/InspectAcceptanceTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectBundleCommandServiceTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  docs/docs/en/guides/develop/bundle-size.md
  docs/docs/en/index.md
  docs/docs/public/images/guides/develop/bundle-size/analyzed-bundle.png
  docs/docs/public/images/guides/develop/bundle-size/bundle-size-graph.png
  docs/docs/public/images/guides/develop/insights/builds-dashboard.png
Labels: changelog:added

#7573 Fix `--verbose` not working
  Sources/TuistKit/Extensions/ServiceContext+Tuist.swift
  Sources/TuistKit/Utils/LogsController.swift
  Sources/TuistSupport/Logging/Logger.swift
Labels: changelog:fixed

#7578 Fix missing bundle git metadata
  Sources/TuistKit/Services/Inspect/InspectBundleCommandService.swift
  Tests/TuistKitTests/Services/Inspect/InspectBundleCommandServiceTests.swift
Labels: changelog:fixed

#7580 Send git reference when inspecting bundle
  Sources/TuistKit/Services/Inspect/InspectBundleCommandService.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/CreateBundleService.swift
  Tests/TuistKitTests/Services/Inspect/InspectBundleCommandServiceTests.swift
  docs/.vitepress/bars.mjs
  docs/.vitepress/strings/en.json
  docs/docs/en/guides/develop/bundle-size.md
  docs/docs/public/images/guides/develop/bundle-size/github-app-with-bundles.png
Labels: changelog:changed

#7572 Support .apinotes files
  Package.resolved
  Package.swift
Labels: changelog:added

#7583 Reorder enable directives so SwiftFormat runs before SwiftLint
  Sources/TuistGenerator/Templates/AssetsTemplate.swift
  Sources/TuistGenerator/Templates/FilesTemplate.swift
  Sources/TuistGenerator/Templates/FontsTemplate.swift
  Sources/TuistGenerator/Templates/PlistsTemplate.swift
  Sources/TuistGenerator/Templates/StringsTemplate.swift
Labels: changelog:fixed

#7601 When uploading build insights, attach git metadata
  Sources/TuistKit/Services/Inspect/InspectBuildCommandService.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/CreateBuildService.swift
  Tests/TuistKitTests/Services/Inspect/InspectBuildCommandServiceTests.swift
Labels: changelog:changed

#7611 Remove unmatched resource glob warnings
  Sources/TuistLoader/Models+ManifestMappers/ResourceFileElement+ManifestMapper.swift
  Tests/TuistLoaderTests/Loaders/ManifestModelConverterTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/ResourceFileElementManifestMapperTests.swift
Labels: changelog:changed

#7594 Sandbox manifest builds with option to opt out
  Sources/ProjectDescription/ConfigGenerationOptions.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistCore/Models/TuistGeneratedProjectOptions.swift
  Sources/TuistKit/Generator/Generator.swift
  Sources/TuistKit/MCP/MCPResourcesRepository.swift
  Sources/TuistKit/Services/BuildService.swift
  Sources/TuistKit/Services/DumpService.swift
  Sources/TuistKit/Services/GenerateService.swift
  Sources/TuistKit/Services/GraphService.swift
  Sources/TuistKit/Services/Hash/HashCacheCommandService.swift
  Sources/TuistKit/Services/Hash/HashSelectiveTestingCommandService.swift
  Sources/TuistKit/Services/Inspect/InspectImplicitImportsService.swift
  Sources/TuistKit/Services/Inspect/InspectRedundantImportsService.swift
  Sources/TuistKit/Services/RunCommandService.swift
  Sources/TuistKit/Services/ShareCommandService.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistLoader/Loaders/CachedManifestLoader.swift
  Sources/TuistLoader/Loaders/ManifestLoader.swift
  Sources/TuistLoader/Loaders/PackageSettingsLoader.swift
  Sources/TuistLoader/Loaders/RecursiveManifestLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/TuistGeneratedProject+ManifestMapper.swift
  Sources/TuistLoaderTesting/Loaders/Mocks/MockPackageSettingsLoader.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistKitIntegrationTests/Commands/DumpServiceIntegrationTests.swift
  Tests/TuistKitIntegrationTests/Utils/ManifestGraphLoaderIntegrationTests.swift
  Tests/TuistKitTests/MCP/MCPResourcesRepositoryTests.swift
  Tests/TuistKitTests/Services/BuildServiceTests.swift
  Tests/TuistKitTests/Services/GenerateServiceTests.swift
  Tests/TuistKitTests/Services/GraphServiceTests.swift
  Tests/TuistKitTests/Services/Hash/HashCacheCommandServiceTests.swift
  Tests/TuistKitTests/Services/Hash/HashSelectiveTestingCommandServiceTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectImplicitImportsServiceTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectRedundantImportsServiceTests.swift
  Tests/TuistKitTests/Services/RunCommandServiceTests.swift
  Tests/TuistKitTests/Services/ShareCommandServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
  Tests/TuistLoaderIntegrationTests/Loaders/ManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/CachedManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/ManifestModelConverterTests.swift
  Tests/TuistLoaderTests/Loaders/PackageSettingsLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/RecursiveManifestLoaderTests.swift
  fixtures/ios_app_with_sandbox_disabled/App/Sources/AppDelegate.swift
  fixtures/ios_app_with_sandbox_disabled/Project.swift
  fixtures/ios_app_with_sandbox_disabled/README.md
  fixtures/ios_app_with_sandbox_disabled/Tuist.swift
Labels: size:XL
