Repository tuist/tuist, pull requests merged in 2025-09, with the labels that each got.

#8128 fix(server): running Oban cron jobs
  server/config/runtime.exs
Labels: type:bug, size:XS, lgtm

#8097 feat(server): QA run analytics and overview dashboard
  server/assets/app/css/pages.css
  server/assets/app/css/pages/qa.css
  server/lib/tuist/qa.ex
  server/lib/tuist/qa/run.ex
  server/lib/tuist_web/components/app_layout_components.ex
  server/lib/tuist_web/controllers/api/analytics_controller.ex
  server/lib/tuist_web/controllers/api/qa_controller.ex
  server/lib/tuist_web/live/ops_qa_logs_live.html.heex
  server/lib/tuist_web/live/qa_live.ex
  server/lib/tuist_web/live/qa_live.html.heex
  server/lib/tuist_web/router.ex
  server/mix.exs
  server/mix.lock
  server/priv/repo/migrations/20250826000001_add_finished_at_to_qa_runs.exs
  server/priv/repo/seeds.exs
  server/runner/lib/runner/qa/tools.ex
  server/runner/test/qa/tools_test.exs
  server/test/support/tuist_test_support/fixtures/qa_fixtures.ex
  server/test/tuist/qa_test.exs
  server/test/tuist_web/controllers/analytics_controller_test.exs
Labels: type:enhancement, domain:dashboard, size:XXL, lgtm

#8129 fix(server): Add oban_met as dependency to enable Oban analytics in the split worker setup
  server/mix.exs
Labels: type:bug, size:XS, lgtm

#8131 fix(server): don't suspend canary machine
  server/fly.canary.toml
Labels: type:bug, size:XS, lgtm

#8136 fix(server): macOS app download
  server/lib/tuist/github/releases.ex
  server/test/tuist/github/releases_test.exs
Labels: type:bug, size:L, lgtm, domain:app

#8138 ci(app): fix app homebrew release
  .github/workflows/release.yml
  mise/tasks/app/release/homebrew-cask.sh
Labels: type:bug, size:XS, lgtm, domain:app

#7999 fix(cli): XCFramework signature
  cli/Sources/TuistCore/MetadataProviders/XCFrameworkSignatureProvider.swift
  cli/Tests/TuistCoreTests/MetadataProviders/XCFrameworkSignatureProviderIntegrationTests.swift
Labels: type:bug, domain:generated-projects, size:M, lgtm

#8130 fix(server): display improvements for QA dashboard
  server/lib/tuist/qa.ex
  server/lib/tuist_web/live/qa_live.ex
  server/lib/tuist_web/live/qa_live.html.heex
Labels: type:bug, size:S, domain:dashboard, lgtm

#8137 refactor(server): move web and worker into one process
  docs/docs/en/guides/server/self-host/install.md
  server/config/runtime.exs
  server/fly.prod.toml
  server/lib/tuist/application.ex
  server/lib/tuist/environment.ex
  server/lib/tuist/registry/swift/workers/create_package_release_worker.ex
  server/lib/tuist/registry/swift/workers/sync_packages_worker.ex
  server/rel/overlays/bin/server
  server/rel/overlays/bin/start
  server/rel/overlays/bin/web
  server/rel/overlays/bin/worker
Labels: size:L, lgtm

#8147 fix(server): don't try to create package releases when they already exist
  server/lib/tuist/registry/swift/packages.ex
  server/lib/tuist/registry/swift/workers/create_package_release_worker.ex
  server/test/tuist/registry/swift/create_package_release_worker_test.exs
Labels: type:bug, size:M, lgtm, domain:registry

#8151 fix(server): disable preview pages being public by default
  server/lib/tuist/app_builds.ex
  server/lib/tuist_web/router.ex
  server/mise.toml
  server/test/tuist/app_builds_test.exs
  server/test/tuist/registry/swift/create_package_release_worker_test.exs
Labels: type:bug, size:M, domain:previews, security, lgtm

#8154 fix(server): bump Elixir version in Dockerfile
  server/Dockerfile
Labels: type:bug, size:XS, lgtm

#8121 fix(docs): Fix translate.tuist.dev links
  .env.json
  README.md
  docs/docs/en/contributors/translate.md
  server/mise.toml
Labels: size:S, domain:docs, lgtm

#8159 fix(server): disable HTTP2 for S3
  server/lib/tuist/environment.ex
Labels: type:bug, size:XS, domain:registry

#8140 feat(server): log component
  server/assets/app/css/components.css
  server/assets/app/css/components/headless.css
  server/assets/app/css/components/logs.css
  server/assets/app/css/pages/ops/qa_logs.css
  server/assets/app/css/pages/qa_run.css
  server/lib/tuist/qa.ex
  server/lib/tuist_web.ex
  server/lib/tuist_web/components/headless_components.ex
  server/lib/tuist_web/components/logs.ex
  server/lib/tuist_web/live/ops_qa_logs_live.ex
  server/lib/tuist_web/live/ops_qa_logs_live.html.heex
  server/lib/tuist_web/live/qa_live.html.heex
  server/lib/tuist_web/live/qa_run_live.ex
  server/lib/tuist_web/live/qa_run_live.html.heex
  server/lib/tuist_web/router.ex
  server/test/tuist/qa_test.exs
Labels: type:enhancement, domain:dashboard, size:XXL, lgtm

#8158 fix(cli): not generate bundle accessors in when buildable folders don't resolve to any resources
  cli/Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  cli/Sources/TuistGenerator/Generator/BuildableFolderChecker.swift
  cli/Sources/TuistGenerator/Generator/TargetGenerator.swift
  cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  cli/Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  cli/Tests/TuistGeneratorTests/Generator/BuildableFolderCheckerTests.swift
  cli/Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
Labels: type:bug, domain:generated-projects, size:L, lgtm

#8161 Temporarily use an older Tuist version to make the release pass
  mise/tasks/cli/bundle.sh
Labels: type:bug, size:XS, lgtm

#8149 fix(server): fix CLA workflow for fork contributions
  .github/workflows/server-cla.yml
  mise.toml
  server/cla/signatures.json
Labels: size:L, domain:integrations, lgtm

#8168 feat(server): optimize bundle loading performance with database indexes
  server/priv/repo/migrations/20250909124838_add_artifacts_indexes.exs
Labels: type:enhancement, p2, size:S, lgtm, domain:app

#8160 feat(server): sanitize agent output
  server/lib/tuist.ex
  server/lib/tuist/markdown.ex
  server/lib/tuist_web/components/logs.ex
  server/lib/tuist_web/live/qa_run_live.ex
  server/lib/tuist_web/live/qa_run_live.html.heex
  server/mix.exs
  server/mix.lock
Labels: type:enhancement, size:M, lgtm

#8174 chore(server): rename marketing CTA to talk to us
  server/lib/tuist_web/marketing/controllers/marketing_html/home.html.heex
Labels: size:XS, lgtm

#8179 feat(server): LLM usage token billing
  server/config/runtime.exs
  server/lib/tuist/accounts.ex
  server/lib/tuist/billing.ex
  server/lib/tuist/billing/sync_customer_stripe_meters.ex
  server/lib/tuist/billing/sync_stripe_meters.ex
  server/lib/tuist/billing/update_all_customers_remote_cache_hits_count_worker.ex
  server/lib/tuist/billing/update_customer_remote_cache_hits_count_worker.ex
  server/lib/tuist/command_events.ex
  server/lib/tuist/command_events/clickhouse.ex
  server/lib/tuist/command_events/postgres.ex
  server/priv/repo/migrations/20250911123301_add_token_usages_account_timestamp_index.exs
  server/test/tuist/accounts_test.exs
  server/test/tuist/billing/sync_customer_stripe_meters_test.exs
  server/test/tuist/billing/sync_stripe_meters_test.exs
  server/test/tuist/billing/update_all_customers_remote_cache_hits_count_worker_test.exs
  server/test/tuist/billing/update_customer_remote_cache_hits_count_worker_test.exs
  server/test/tuist/billing_test.exs
  server/test/tuist/command_events_test.exs
Labels: type:enhancement, size:XL, lgtm

#8193 fix(server): handle 0 bundle download size
  server/lib/tuist_web/live/bundles_live.ex
  server/lib/tuist_web/marketing/controllers/marketing_controller.ex
  server/test/tuist_web/live/bundles_live_test.exs
Labels: type:bug, size:M, lgtm

#8196 fix(server): Lean on multiplexing requests in a single connection over having many HTTP2 connections against GitHub
  server/lib/tuist/application.ex
  server/lib/tuist/github/client.ex
Labels: type:bug, p2, size:M, domain:integrations, lgtm

#8197 feat(server): project settings
  server/assets/app/css/pages.css
  server/assets/app/css/pages/project_settings.css
  server/assets/app/css/pages/qa_settings.css
  server/lib/tuist.ex
  server/lib/tuist/billing/sync_customer_stripe_meters.ex
  server/lib/tuist/projects/project.ex
  server/lib/tuist/qa.ex
  server/lib/tuist_web/components/app_layout_components.ex
  server/lib/tuist_web/components/layouts/project.html.heex
  server/lib/tuist_web/live/project_settings_live.ex
  server/lib/tuist_web/live/project_settings_live.html.heex
  server/lib/tuist_web/live/qa_settings_live.ex
  server/lib/tuist_web/live/qa_settings_live.html.heex
  server/lib/tuist_web/router.ex
  server/mix.exs
  server/mix.lock
  server/test/tuist/projects/project_test.exs
  server/test/tuist/qa_test.exs
  server/test/tuist_web/controllers/qa_controller_test.exs
Labels: type:enhancement, size:XXL, lgtm

#8173 feat(cli): Remove user credentials when the token sent on refresh is invalid
  cli/Sources/TuistServer/Client/ServerAuthenticationController.swift
  cli/Tests/TuistServerTests/Utilities/ServerAuthenticationControllerTests.swift
Labels: type:enhancement, size:L, security, lgtm

#8194 feat(server): namespace unit minute billing
  server/config/runtime.exs
  server/lib/tuist/billing.ex
  server/lib/tuist/billing/sync_stripe_meters.ex
  server/lib/tuist/billing/workers/sync_customer_stripe_meters_worker.ex
  server/lib/tuist/billing/workers/sync_stripe_meters_worker.ex
  server/lib/tuist/namespace.ex
  server/test/tuist/billing/sync_customer_stripe_meters_worker_test.exs
  server/test/tuist/billing/sync_stripe_meters_worker_test.exs
  server/test/tuist/billing_test.exs
  server/test/tuist/namespace_test.exs
Labels: type:enhancement, size:L, lgtm

#8211 fix(server): Fix the module name of the worker to sync the Stripe meters
  server/config/runtime.exs
  server/lib/tuist/billing.ex
  server/lib/tuist/billing/sync_stripe_meters.ex
  server/lib/tuist/billing/workers/sync_customer_stripe_meters_worker.ex
  server/lib/tuist/billing/workers/sync_stripe_meters_worker.ex
  server/lib/tuist/namespace.ex
  server/test/tuist/billing/sync_customer_stripe_meters_worker_test.exs
  server/test/tuist/billing/sync_stripe_meters_worker_test.exs
  server/test/tuist/billing_test.exs
  server/test/tuist/namespace_test.exs
Labels: type:bug, size:L, lgtm

#8215 fix(server): run correct worker for billing
  server/config/runtime.exs
Labels: type:bug, size:XS, lgtm

#8214 chore(server): Align canary and staging's workers setup with production to catch issues earlier
  server/config/can.exs
  server/config/runtime.exs
  server/config/stag.exs
  server/lib/tuist/mautic/workers/sync_companies_and_contacts_worker.ex
  server/lib/tuist/ops/daily_slack_report_worker.ex
  server/lib/tuist/ops/hourly_slack_report_worker.ex
  server/lib/tuist/registry/swift/workers/sync_packages_worker.ex
  server/lib/tuist/slack.ex
  server/priv/secrets/can.yml.enc
  server/priv/secrets/prod.yml.enc
  server/priv/secrets/stag.yml.enc
  server/test/tuist/mautic/workers/sync_companies_and_contacts_worker_test.exs
  server/test/tuist/ops/daily_slack_report_worker_test.exs
  server/test/tuist/ops/hourly_slack_report_worker_test.exs
  server/test/tuist/registry/swift/sync_packages_worker_test.exs
Labels: size:XL, lgtm

#8218 feat(server): add QA app description
  server/assets/app/css/pages/qa_run.css
  server/assets/app/css/pages/qa_settings.css
  server/lib/tuist/projects/project.ex
  server/lib/tuist/qa.ex
  server/lib/tuist/qa/run.ex
  server/lib/tuist_web/live/qa_run_live.html.heex
  server/lib/tuist_web/live/qa_settings_live.ex
  server/lib/tuist_web/live/qa_settings_live.html.heex
  server/mix.exs
  server/mix.lock
  server/priv/repo/migrations/20250916075933_add_qa_app_description_to_projects.exs
  server/priv/repo/migrations/20250916143744_add_app_description_to_qa_runs.exs
  server/runner/lib/runner.ex
  server/runner/lib/runner/commands/qa.ex
  server/runner/lib/runner/qa/agent.ex
  server/test/tuist/qa_test.exs
Labels: type:enhancement, size:L, lgtm

#8223 fix(server): registry scope
  server/lib/tuist/accounts/account_token.ex
  server/test/tuist/accounts/account_token_test.exs
Labels: type:bug, size:M, lgtm, domain:registry

#8226 fix(server): Change modal title from 'Create project' to 'Invite member'
  server/lib/tuist_web/live/members_live.ex
Labels: size:XS, domain:dashboard, lgtm

#8221 feat(server): add QA credentials
  server/assets/app/css/pages/qa_run.css
  server/assets/app/css/pages/qa_settings.css
  server/lib/tuist/projects/project.ex
  server/lib/tuist/qa.ex
  server/lib/tuist/qa/run.ex
  server/lib/tuist_web/live/qa_run_live.html.heex
  server/lib/tuist_web/live/qa_settings_live.ex
  server/lib/tuist_web/live/qa_settings_live.html.heex
  server/mix.exs
  server/mix.lock
  server/priv/repo/migrations/20250917084738_add_qa_credentials_to_projects.exs
  server/priv/repo/migrations/20250917084814_add_credentials_to_qa_runs.exs
  server/runner/lib/runner/commands/qa.ex
  server/runner/lib/runner/qa/agent.ex
  server/test/tuist/qa_test.exs
Labels: type:enhancement, size:L, lgtm

#8231 chore(server): add CI for deploying to render
  .github/workflows/server-canary-deployment.yml
  .github/workflows/server-production-deployment.yml
  .github/workflows/server-staging-deployment.yml
  server/Dockerfile
  server/lib/tuist/environment.ex
  server/mise.toml
Labels: size:L, lgtm

#8233 fix(server): fix ci
  .github/workflows/server-canary-deployment.yml
  server/mise.toml
Labels: type:bug, size:XS

#8236 fix(server): upload QA recording
  server/config/runtime.exs
  server/runner/lib/runner/qa/agent.ex
  server/runner/test/qa/agent_test.exs
Labels: type:bug, size:S, lgtm

#8191 feat(cli): Add SE-0162 support for custom SPM target layouts
  cli/Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  cli/Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: type:enhancement, size:L, domain:dependencies, lgtm

#8237 chore(server): update Dockerfile
  server/Dockerfile
Labels: size:L, lgtm

#8229 chore(server): update the main copy
  server/lib/tuist_web/marketing/controllers/marketing_html/home.html.heex
Labels: size:XS, lgtm

#8249 fix(server): Revert "chore(server): update dependencies (#8216)"
  server/config/dev.exs
  server/lib/tuist_web/live/build_run_live.html.heex
  server/lib/tuist_web/live/build_runs_live.html.heex
  server/lib/tuist_web/live/cache_runs_live.html.heex
  server/lib/tuist_web/live/generate_runs_live.html.heex
  server/lib/tuist_web/live/qa_live.html.heex
  server/lib/tuist_web/live/test_runs_live.html.heex
  server/lib/tuist_web/marketing/components/marketing_home_components.ex
  server/lib/tuist_web/marketing/controllers/marketing_html/blog_post.html.heex
  server/lib/tuist_web/marketing/controllers/marketing_html/home.html.heex
  server/lib/tuist_web/marketing/controllers/marketing_html/pricing.html.heex
  server/lib/tuist_web/marketing/live/marketing_blog_live.html.heex
  server/mix.exs
  server/mix.lock
Labels: type:bug, size:M, domain:dashboard, lgtm

#8250 chore(server): align pool sizes with fly ones
  render.yaml
Labels: size:XS, lgtm

#8251 feat(server): update icon radius to liquid glass
  server/assets/app/app.css
  server/assets/app/css/components/previews/app_preview.css
  server/assets/app/css/pages/preview.css
  server/assets/app/css/pages/qa_run.css
Labels: type:enhancement, size:S, lgtm, domain:app

#8244 feat(cli): change sandbox to be opt-in
  cli/Sources/ProjectDescription/ConfigGenerationOptions.swift
  cli/Sources/TuistCore/Models/TuistGeneratedProjectOptions.swift
  cli/Sources/TuistKit/Generator/Generator.swift
  cli/Sources/TuistKit/Services/DumpService.swift
  cli/Sources/TuistKit/Services/GraphService.swift
  cli/Sources/TuistKit/Services/ShareCommandService.swift
  cli/Sources/TuistLoader/Loaders/CachedManifestLoader.swift
  cli/Tests/TuistCoreTests/Models/TuistGeneratedProjectOptionsTests.swift
  cli/Tests/TuistKitTests/Commands/DumpServiceIntegrationTests.swift
Labels: type:enhancement, domain:generated-projects, size:M, lgtm

#8259 fix(server): incorrect Sort by label for Build duration
  server/lib/tuist_web/live/build_run_live.html.heex
Labels: type:bug, size:XS

#8260 fix(server): Check for the truthiness of TUIST_HOSTED
  server/rel/env.sh.eex
Labels: type:bug, size:S, lgtm

#8264 chore(server): Blog post: Why Large Swift Projects Hit a Wall (And How to Break Through)
  server/priv/marketing/blog/2025/09/22/scale.md
Labels: size:M, domain:docs, lgtm

#8265 chore(server): Fix the server production pipeline
  .github/workflows/server-production-deployment.yml
Labels: type:bug, size:S, lgtm

#8207 fix(cli): add default.metallib in static framework
  cli/Fixtures/generated_metallib_in_static_framework/Project.swift
  cli/Fixtures/generated_metallib_in_static_framework/StaticMetallibFramework/Sources/Bundle.swift
  cli/Fixtures/generated_metallib_in_static_framework/StaticMetallibFramework/Sources/Metal.metal
  cli/Fixtures/generated_metallib_in_static_framework/Tuist.swift
  cli/Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  cli/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  cli/Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
Labels: domain:generated-projects, size:M, lgtm

#8254 feat(cli): Support exclusion of files and configuration of compiler flags for files in buildable folders
  Package.resolved
  Package.swift
  cli/Fixtures/app_with_buildable_folders/App/Sources/Excluded.swift
  cli/Fixtures/app_with_buildable_folders/App/Sources/WithCompilerFlags.swift
  cli/Fixtures/app_with_buildable_folders/Project.swift
  cli/Sources/ProjectDescription/BuildableFolder.swift
  cli/Sources/ProjectDescription/BuildableFolderException.swift
  cli/Sources/ProjectDescription/BuildableFolderExceptions.swift
  cli/Sources/TuistGenerator/Generator/BuildableFolderChecker.swift
  cli/Sources/TuistGenerator/Generator/TargetGenerator.swift
  cli/Sources/TuistHasher/TargetContentHasher.swift
  cli/Sources/TuistLoader/Models+ManifestMappers/BuildableFolder+ManifestMapper.swift
  cli/Sources/TuistLoader/Models+ManifestMappers/BuildableFolderException+ManifestMapper.swift
  cli/Sources/TuistLoader/Models+ManifestMappers/BuildableFolderExceptions+ManifestMapper.swift
  cli/Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  cli/Tests/TuistGeneratorTests/Generator/BuildableFolderCheckerTests.swift
  cli/Tests/TuistGeneratorTests/Generator/ProjectFileElementsTests.swift
  cli/Tests/TuistGeneratorTests/Generator/TargetGeneratorTests.swift
  cli/Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  cli/Tests/TuistHasherTests/TargetContentHasherTests.swift
  cli/Tests/TuistKitTests/Mappers/Factories/GraphMapperFactoryTests.swift
  cli/Tests/TuistLoaderTests/Loaders/ManifestLoaderTests.swift
  cli/Tests/TuistLoaderTests/Models+ManifestMappers/Target+ManifestMapperTests.swift
Labels: type:enhancement, domain:generated-projects, size:L, lgtm

#8293 fix(cli): Make `excluded` optional in buildable folder exceptions
  cli/Sources/ProjectDescription/BuildableFolderException.swift
Labels: type:bug, size:XS, lgtm, domain:cli

#8292 fix(cli): Fix synthesized bundle interfaces not generated for `.xcassets` in buildable folders
  cli/Fixtures/ios_app_with_framework_buildable_folders_and_xcassets/App/Sources/MyApp.swift
  cli/Fixtures/ios_app_with_framework_buildable_folders_and_xcassets/Modules/Framework/Resources/Assets.xcassets/Contents.json
  cli/Fixtures/ios_app_with_framework_buildable_folders_and_xcassets/Modules/Framework/Resources/Assets.xcassets/logo.imageset/Contents.json
  cli/Fixtures/ios_app_with_framework_buildable_folders_and_xcassets/Modules/Framework/Resources/Assets.xcassets/logo.imageset/logo.png
  cli/Fixtures/ios_app_with_framework_buildable_folders_and_xcassets/Modules/Framework/Sources/FrameworkResourceProvider.swift
  cli/Fixtures/ios_app_with_framework_buildable_folders_and_xcassets/Project.swift
  cli/Fixtures/ios_app_with_framework_buildable_folders_and_xcassets/README.md
  cli/Fixtures/ios_app_with_framework_buildable_folders_and_xcassets/Tuist.swift
  cli/Sources/TuistGenerator/Generator/BuildableFolderChecker.swift
  cli/Sources/TuistGenerator/Mappers/SynthesizedResourceInterfaceProjectMapper.swift
  cli/Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
Labels: type:bug, domain:generated-projects, size:L, lgtm

#8297 Double the production DB pool size to 40
  render.yaml
Labels: size:XS, lgtm

#8301 fix(server): upload QA recording with standard mp4 format
  server/runner/lib/runner/qa/agent.ex
  server/runner/lib/runner/qa/simulators.ex
  server/runner/test/qa/agent_test.exs
Labels: type:bug, size:M, lgtm

#8300 fix(server): db connections by moving from direct connection to session pooler
  server/priv/secrets/can.yml.enc
  server/priv/secrets/prod.yml.enc
Labels: type:bug, size:XS

#8306 ci(cli): unstuck cache acceptance tests
  .github/workflows/server-production-deployment.yml
Labels: type:bug, size:XS

#8305 fix(server): triggering QA session on preview upload
  server/lib/tuist/qa.ex
  server/lib/tuist_web/controllers/api/previews_controller.ex
  server/lib/tuist_web/controllers/webhooks/github_controller.ex
  server/test/test_helper.exs
  server/test/tuist/qa_test.exs
  server/test/tuist_web/controllers/api/previews_controller_test.exs
  server/test/tuist_web/controllers/webhooks/github_controller_test.exs
Labels: type:bug, size:M, domain:previews, lgtm

#8298 fix(cli): Add support for headers in buildable folders
  Package.resolved
  Package.swift
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/.gitignore
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/App/Resources/Assets.xcassets/Contents.json
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/App/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/App/Sources/ContentView.swift
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/App/Sources/FrameworkUsage.m
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/App/Sources/TuistApp.swift
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/App/Sources/include/App.h
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/App/Tests/TuistPlayGroundTests.swift
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/Framework/Sources/Framework.h
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/Framework/Sources/Framework.m
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/Framework/Sources/include/bar.h
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/Framework/Sources/include/baz.h
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/Project.swift
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/Tuist.swift
  cli/Fixtures/ios_app_with_framework_headers_in_buildable_folders/Tuist/Package.swift
  cli/Sources/ProjectDescription/BuildableFolderException.swift
  cli/Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  cli/Sources/TuistGenerator/Generator/TargetGenerator.swift
  cli/Sources/TuistHasher/TargetContentHasher.swift
  cli/Sources/TuistLoader/Models+ManifestMappers/BuildableFolderException+ManifestMapper.swift
  cli/Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  cli/Tests/TuistGeneratorTests/Generator/TargetGeneratorTests.swift
  cli/Tests/TuistHasherTests/TargetContentHasherTests.swift
  cli/Tests/TuistLoaderTests/Models+ManifestMappers/BuildableFolderException+ManifestMapperTests.swift
  cli/Tests/TuistLoaderTests/Models+ManifestMappers/Target+ManifestMapperTests.swift
Labels: type:enhancement, domain:generated-projects, size:XL, lgtm

#8276 fix(cli): don't mark inspected build as failed when it has warnings only
  .github/workflows/app.yml
  cli/Sources/TuistXCActivityLog/XCActivityLogController.swift
  cli/Tests/Fixtures/build-with-warning.xcactivitylog
  cli/Tests/TuistXCActivityLogTests/XCActivityLog/XCActivityLogControllerTests.swift
  mise.toml
Labels: size:M, lgtm, domain:cli

#8314 fix(server): latest preview link for non-main branch or multiple bundle ids
  docs/docs/en/guides/features/previews.md
  server/lib/tuist_web/controllers/preview_controller.ex
  server/test/tuist_web/controllers/preview_controller_test.exs
Labels: type:bug, size:L, domain:previews, lgtm

#8308 fix(cli): Fix cache warming when external targets are excluded by platform conditions
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/.gitignore
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/Project.swift
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/README.md
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/Tuist.swift
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/Tuist/Package.resolved
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/Tuist/Package.swift
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/TuistCacheIssue/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/TuistCacheIssue/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/TuistCacheIssue/Resources/Assets.xcassets/Contents.json
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/TuistCacheIssue/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/TuistCacheIssue/Sources/ContentView.swift
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/TuistCacheIssue/Sources/TuistCacheIssueApp.swift
  cli/Fixtures/generated_ios_app_with_external_dependencies_filtered_out/TuistCacheIssue/Tests/TuistCacheIssueTests.swift
  cli/Sources/TuistDependencies/Mappers/ExternalProjectsPlatformNarrowerGraphMapper.swift
  cli/Tests/TuistCacheEEAcceptanceTests/TuistCacheEEAcceptanceTests.swift
  cli/Tests/TuistDependenciesTests/Mappers/ExternalProjectsPlatformNarrowerGraphMapperTests.swift
Labels: type:bug, size:L, domain:dependencies, lgtm

#8317 fix(app): only commit and release after all builds are finished
  .github/workflows/release.yml
Labels: type:bug, size:XS, lgtm

#8316 fix(server): Respond with bad request to image requests against HTML endpoints
  server/lib/tuist_web/controllers/preview_controller.ex
  server/lib/tuist_web/router.ex
Labels: type:bug, size:M, lgtm

#8320 ci(app): release app with the GitHub runner
  .github/workflows/release.yml
Labels: size:XS

#8323 fix(app): reorder release steps
  .github/workflows/release.yml
  app/Sources/TuistApp/TuistApp.swift
Labels: size:L

#8325 fix(app): correct macOS app artifact location
  .github/workflows/release.yml
  app/Sources/TuistApp/TuistApp.swift
Labels: size:S

#8326 fix(app): retain app artifact paths on download
  .github/workflows/release.yml
  app/Sources/TuistApp/TuistApp.swift
Labels: size:XS

#8330 feat(server,cli): add configuration to build insights
  cli/Fixtures/xcode_project_with_inspect_build/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme
  cli/Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  cli/Sources/TuistGenerator/Mappers/AutogeneratedWorkspaceSchemeGraphMapper.swift
  cli/Sources/TuistGenerator/Utils/BuildInsightsActionMapper.swift
  cli/Sources/TuistKit/Services/Inspect/InspectBuildCommandService.swift
  cli/Sources/TuistServer/OpenAPI/Types.swift
  cli/Sources/TuistServer/OpenAPI/server.yml
  cli/Sources/TuistServer/Services/CreateBuildService.swift
  cli/Tests/TuistGeneratorTests/GraphMappers/AutogeneratedWorkspaceSchemeWorkspaceMapperTests.swift
  cli/Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift
  cli/Tests/TuistGeneratorTests/Utils/BuildInsightsActionMapperTests.swift
  cli/Tests/TuistKitTests/Services/Inspect/InspectBuildCommandServiceTests.swift
  docs/docs/en/guides/features/insights.md
  docs/docs/public/images/guides/features/insights/inspect-build-scheme-post-action.png
  server/lib/tuist/runs/build.ex
  server/lib/tuist_web/controllers/api/runs_controller.ex
  server/lib/tuist_web/live/build_run_live.html.heex
  server/lib/tuist_web/live/build_runs_live.html.heex
  server/priv/repo/migrations/20250929085828_add_configuration_to_build_runs.exs
  server/priv/repo/seeds.exs
  server/test/support/tuist_test_support/fixtures/runs_fixtures.ex
  server/test/tuist_web/controllers/api/runs_controller_test.exs
Labels: type:enhancement, p2, size:L, lgtm

#8333 feat(server): Add support for offline-validated licenses
  docs/docs/en/guides/server/self-host/install.md
  server/lib/tuist/environment.ex
  server/lib/tuist/license.ex
  server/lib/tuist_web/live/build_run_live.html.heex
  server/test/tuist/license_test.exs
Labels: type:enhancement, size:L, lgtm

#8334 fix(server): Runtime error trying to access encrypted secrets
  server/lib/tuist/environment.ex
Labels: type:bug, size:S, lgtm

#8343 fix(server): case insensitive comparison for invitations
  server/lib/tuist/accounts.ex
  server/lib/tuist/accounts/invitation.ex
  server/test/tuist/accounts/invitation_test.exs
  server/test/tuist/accounts_test.exs
Labels: type:bug, size:M, lgtm
