Repository tuist/tuist, pull requests merged in 2025-02, with the labels that each got.

#7278 Upload binary cache and selective testing hashes to the server
  Sources/TuistCore/Analytics/CommandEvent.swift
  Sources/TuistCore/Analytics/CommandEventGraphTarget.swift
  Sources/TuistCore/Analytics/CommandEventProject.swift
  Sources/TuistCore/Analytics/CommandEventTarget.swift
  Sources/TuistCore/Analytics/RunCacheHit.swift
  Sources/TuistCore/Analytics/RunCacheTargetMetadata.swift
  Sources/TuistCore/Analytics/RunGraph.swift
  Sources/TuistCore/Analytics/RunMetadataStorage.swift
  Sources/TuistCore/Analytics/RunProject.swift
  Sources/TuistCore/Analytics/RunTarget.swift
  Sources/TuistCore/Cache/CacheCategory.swift
  Sources/TuistCore/Cache/CacheItem.swift
  Sources/TuistCore/Graph/Mappers/MapperEnvironmentKeys.swift
  Sources/TuistKit/Commands/Cache/CacheService.swift
  Sources/TuistKit/Commands/CacheCommand.swift
  Sources/TuistKit/Commands/GenerateCommand.swift
  Sources/TuistKit/Commands/GraphCommand.swift
  Sources/TuistKit/Commands/InitCommand.swift
  Sources/TuistKit/Commands/ShareCommand.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Commands/TrackableCommand/CommandEventFactory.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableCommand.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableParametersDelegate.swift
  Sources/TuistKit/Services/GenerateService.swift
  Sources/TuistKit/Services/ShareService.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistKit/Utils/TuistAnalyticsServerBackend.swift
  Sources/TuistServer/Models/ServerModule.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/AnalyticsArtifactUploadService.swift
  Sources/TuistServer/Services/CompleteAnalyticsArtifactsUploads.swift
  Sources/TuistServer/Services/CreateCommandEventService.swift
  Tests/TuistKitTests/CommandTracking/CommandEventFactoryTests.swift
  Tests/TuistKitTests/CommandTracking/TrackableCommandTests.swift
  Tests/TuistKitTests/Services/GenerateServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsServerBackendTests.swift
  Tests/TuistServerTests/Services/AnalyticsArtifactUploadServiceTests.swift
Labels: changelog:added

#7295 Fix default settings for multiplatform targets
  Sources/TuistGenerator/Settings/DefaultSettingsProvider.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
  Tests/TuistGeneratorTests/Settings/DefaultSettingsProviderTests.swift
Labels: changelog:fixed

#7261 Improve the debugging experience by persisting logs in the file system for every run
  Package.resolved
  Package.swift
  Sources/TuistKit/Commands/BuildCommand.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Utils/LogConfigurableCommand.swift
  Sources/TuistKit/Utils/LogsController.swift
  Sources/TuistSupport/Logging/Logger.swift
  Sources/TuistSupport/Utils/Environment.swift
  Sources/TuistSupportTesting/Utils/MockEnvironment.swift
  Sources/tuist/TuistCLI.swift
  Tests/TuistKitTests/Services/XcodeBuildServiceTests.swift
  Tests/TuistKitTests/Utils/LogsCleanerTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  docs/.vitepress/bars.mjs
  docs/.vitepress/config.mjs
  docs/.vitepress/data/cli.js
  docs/.vitepress/strings/en.json
  docs/docs/en/cli/logging.md
  docs/docs/en/contributors/cli/logging.md
Labels: changelog:changed

#7303 Upload and show run detail link for long-running commands like tuist xcodebuild
  Sources/TuistCore/Analytics/CommandEvent.swift
  Sources/TuistCore/Analytics/RunMetadataStorage.swift
  Sources/TuistKit/Commands/TrackableCommand/CommandEventFactory.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Commands/XcodeBuildCommand.swift
  Sources/TuistKit/Services/XcodeBuildService.swift
  Sources/TuistKit/Utils/TuistAnalyticsServerBackend.swift
  Sources/TuistServer/Models/ServerCommandEvent.swift
  Sources/TuistServer/Services/AnalyticsArtifactUploadService.swift
  Sources/TuistServer/Utilities/UniqueIDGenerator.swift
  Sources/TuistSupport/Utils/UniqueIDGenerator.swift
  Tests/TuistKitTests/CommandTracking/CommandEventFactoryTests.swift
  Tests/TuistKitTests/CommandTracking/TrackableCommandTests.swift
  Tests/TuistKitTests/Services/XcodeBuildServiceTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsServerBackendTests.swift
  Tests/TuistServerTests/Services/AnalyticsArtifactUploadServiceTests.swift
Labels: changelog:added

#7305 Gracefully handle suffix grouping when target has the same name as suffix
  Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift
Labels: changelog:fixed

#6698 Add a new command to inspect redundant dependencies
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Commands/Inspect/InspectRedundantImportsCommand.swift
  Sources/TuistKit/Commands/InspectCommand.swift
  Sources/TuistKit/Services/Inspect/GraphImportsLinter.swift
  Sources/TuistKit/Services/Inspect/InspecImplicitImportsService.swift
  Sources/TuistKit/Services/Inspect/InspectImplicitImportsService.swift
  Sources/TuistKit/Services/Inspect/InspectRedundantImportsService.swift
  Tests/TuistKitAcceptanceTests/InspectAcceptanceTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectImplicitImportsServiceTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectRedundantImportsServiceTests.swift
Labels: size:XL

#7324 Fix inspect implicit imports in large projects
  Sources/TuistKit/Services/TargetImportsScanner.swift
Labels: changelog:fixed

#7322 Add tuist graph support for non-generated Xcode projects
  Sources/TuistKit/Services/GraphService.swift
  Tests/TuistKitTests/Services/GraphServiceTests.swift
Labels: changelog:added

#7317 Add support for selective testing for Xcode projects with local packages
  Package.resolved
  Package.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistCache/SelectiveTestingServicing.swift
  Sources/TuistHasher/GraphContentHasher.swift
  Sources/TuistHasher/TargetContentHasher.swift
  Sources/TuistKit/Commands/XcodeBuildCommand.swift
  Sources/TuistKit/Services/XcodeBuildService.swift
  Sources/TuistLoader/Loaders/CachedManifestLoader.swift
  Sources/TuistLoader/Loaders/ManifestLoader.swift
  Sources/TuistLoader/Loaders/PackageInfoLoader.swift
  Sources/TuistLoader/Models/PackageInfo.swift
  Sources/TuistLoader/Models/PlatformTestInfo.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfo+graphPlatform.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistHasherTests/GraphContentHasherTests.swift
  Tests/TuistKitTests/Services/Plugin/PluginArchiveServiceTests.swift
  Tests/TuistKitTests/Services/XcodeBuildServiceTests.swift
  Tests/TuistLoaderIntegrationTests/Loaders/ManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/PackageInfoLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/RecursiveManifestLoaderTests.swift
  Tests/TuistLoaderTests/Models/PackageInfoTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfo+TestData.swift
  fixtures/xcode_project_with_packages_and_tests/.gitignore
  fixtures/xcode_project_with_packages_and_tests/App.xcodeproj/project.pbxproj
  fixtures/xcode_project_with_packages_and_tests/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme
  fixtures/xcode_project_with_packages_and_tests/App.xctestplan
  fixtures/xcode_project_with_packages_and_tests/App/AppApp.swift
  fixtures/xcode_project_with_packages_and_tests/App/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/xcode_project_with_packages_and_tests/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/xcode_project_with_packages_and_tests/App/Assets.xcassets/Contents.json
  fixtures/xcode_project_with_packages_and_tests/App/ContentView.swift
  fixtures/xcode_project_with_packages_and_tests/App/LibraryA/.gitignore
  fixtures/xcode_project_with_packages_and_tests/App/LibraryA/Package.swift
  fixtures/xcode_project_with_packages_and_tests/App/LibraryA/Sources/LibraryA/LibraryA.swift
  fixtures/xcode_project_with_packages_and_tests/App/LibraryA/Tests/LibraryATests/LibraryATests.swift
  fixtures/xcode_project_with_packages_and_tests/App/LibraryB/.gitignore
  fixtures/xcode_project_with_packages_and_tests/App/LibraryB/Package.swift
  fixtures/xcode_project_with_packages_and_tests/App/LibraryB/Sources/LibraryB/LibraryB.swift
  fixtures/xcode_project_with_packages_and_tests/App/LibraryB/Tests/LibraryBTests/LibraryBTests.swift
  fixtures/xcode_project_with_packages_and_tests/App/Preview Content/Preview Assets.xcassets/Contents.json
  fixtures/xcode_project_with_packages_and_tests/AppTests/AppTests.swift
  fixtures/xcode_project_with_packages_and_tests/Tuist.swift
Labels: changelog:added

#7328 Remove default subcommand of tuist auth in favor of calling tuist auth login explicitly
  Sources/TuistKit/Commands/Auth/AuthCommand.swift
  Templates/default/Tuist.stencil
  docs/docs/en/contributors/get-started.md
  docs/docs/en/guides/quick-start/gather-insights.md
  docs/docs/en/guides/quick-start/optimize-workflows.md
  docs/docs/en/guides/share/previews.md
  docs/docs/en/server/introduction/authentication.md
Labels: changelog:changed

#7333 Fix compiling Package.swift without @preconcurrency import modifier in project generated by tuist edit
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Tests/TuistKitTests/ProjectEditor/ProjectEditorMapperTests.swift
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
Labels: changelog:fixed

#7338 Explicitly use `Foundation.FileManager` to negotiate conflicting `FileManager` symbol in module itself in synthesized resource accessors
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
Labels: changelog:fixed

#7344 Improve error message on unhandled errors
  Sources/TuistSupport/Errors/FatalError.swift
Labels: changelog:changed

#7346 Remove duplicates for some settings when using binary cache
  Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift
  Tests/TuistKitTests/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapperTests.swift
Labels: changelog:fixed

#7347 #7345 Add command lint tool as valid target for unit tests on macOS.
  Sources/TuistGenerator/Linter/GraphLinter.swift
Labels: changelog:added

#7352 Fix selective testing of projects with aggregate targets
  Package.resolved
  Package.swift
Labels: changelog:fixed

#7365 Fix missing OTHER_SWIFT_FLAGS such as -Xfrontend when using binary cache
  Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift
  Tests/TuistKitTests/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapperTests.swift
Labels: changelog:fixed
