Repository tuist/tuist, pull requests merged in 2025-08, with the labels that each got.

#7930 refactor(server): remove denormalized Xcode target view
  server/lib/tuist/xcode/clickhouse.ex
  server/lib/tuist/xcode/clickhouse/xcode_project.ex
  server/lib/tuist/xcode/clickhouse/xcode_target.ex
  server/lib/tuist/xcode/clickhouse/xcode_target_denormalized.ex
  server/priv/ingest_repo/migrations/20250728120556_add_command_event_id_to_xcode_targets.exs
  server/test/support/tuist_test_support/fixtures/xcode_fixtures.ex
Labels: type:enhancement, size:L, lgtm

#7955 chore(server): upgrade styler
  server/.credo.exs
  server/config/config.exs
  server/lib/tuist/accounts.ex
  server/lib/tuist/accounts/organization.ex
  server/lib/tuist/accounts/user_notifier.ex
  server/lib/tuist/api/pipeline.ex
  server/lib/tuist/authorization.ex
  server/lib/tuist/command_events.ex
  server/lib/tuist/environment.ex
  server/lib/tuist/key_value_store.ex
  server/lib/tuist/projects.ex
  server/lib/tuist/vault.ex
  server/lib/tuist/vault/binary.ex
  server/lib/tuist/xcode/clickhouse/xcode_target.ex
  server/lib/tuist_web/authentication.ex
  server/lib/tuist_web/authorization.ex
  server/lib/tuist_web/controllers/api/bundles_controller.ex
  server/lib/tuist_web/controllers/api/organizations_controller.ex
  server/lib/tuist_web/controllers/preview_controller.ex
  server/lib/tuist_web/live/builds_live.ex
  server/lib/tuist_web/live/preview_live.ex
  server/lib/tuist_web/live/projects_live.ex
  server/lib/tuist_web/live/user_login_live.ex
  server/lib/tuist_web/live/user_okta_login_live.ex
  server/mix.exs
  server/mix.lock
  server/priv/repo/migrations/20250731162845_drop_okta_site_from_organizations.exs
  server/test/support/tuist_test_support/fixtures/xcode_fixtures.ex
  server/test/tuist/accounts_test.exs
  server/test/tuist/api/pipeline_test.exs
  server/test/tuist/cache_action_items_test.exs
  server/test/tuist/command_events_test.exs
  server/test/tuist/license_test.exs
  server/test/tuist/registry/swift/update_packages_worker_test.exs
  server/test/tuist_web/controllers/api/auth_controller_test.exs
  server/test/tuist_web/controllers/api/cache_controller_test.exs
  server/test/tuist_web/controllers/api/projects_controller_test.exs
  server/test/tuist_web/controllers/api_controller_test.exs
  server/test/tuist_web/controllers/error_html_test.exs
  server/test/tuist_web/plugs/loader_plug_test.exs
Labels: type:enhancement, size:L, lgtm

#7964 fix(server): do not set charset for png preview responses
  server/lib/tuist_web/controllers/preview_controller.ex
  server/test/tuist_web/controllers/preview_controller_test.exs
Labels: type:bug, size:XS, domain:previews, lgtm

#7965 fix(cli): treat the new .icon asset as an opaque directory
  cli/Sources/TuistSupport/Extensions/AbsolutePath+Extras.swift
Labels: size:XS, lgtm, domain:cli

#7942 feat(server): create ingestion buffer for CommandEvents
  docs/docs/en/guides/server/self-host/install.md
  server/config/dev.exs
  server/config/runtime.exs
  server/config/test.exs
  server/lib/tuist/application.ex
  server/lib/tuist/command_events/buffer.ex
  server/lib/tuist/command_events/clickhouse.ex
  server/lib/tuist/command_events/clickhouse/event.ex
  server/lib/tuist/environment.ex
  server/lib/tuist/ingestion/buffer.ex
  server/lib/tuist/ingestion/bufferable.ex
  server/lib/tuist/uuid_v7.ex
  server/test/support/tuist_test_support/cases/conn_case.ex
  server/test/support/tuist_test_support/utilities.ex
  server/test/test_helper.exs
  server/test/tuist/accounts_test.exs
  server/test/tuist/command_events_test.exs
  server/test/tuist/ingestion/buffer_test.exs
  server/test/tuist_web/controllers/analytics_controller_test.exs
  server/test/tuist_web/live/cache_runs_live_test.exs
  server/test/tuist_web/live/generate_runs_live_test.exs
  server/test/tuist_web/live/run_detail_live_test.exs
  server/test/tuist_web/live/test_runs_live_test.exs
Labels: type:enhancement, size:XXL, lgtm

#7914 feat(server): run llm QA agent
  .env.json
  server/lib/tuist/environment.ex
  server/lib/tuist/qa/agent.ex
  server/lib/tuist/qa/tools.ex
  server/mix.exs
  server/mix.lock
  server/test/test_helper.exs
  server/test/tuist/qa/agent_test.exs
  server/test/tuist/qa/tools_test.exs
Labels: type:enhancement, size:XXL, lgtm

#7966 docs: update readme.md for abb logo
  README.md
  assets/companies/abb-logo-slogan.png
Labels: size:S, domain:docs, lgtm

#7969 chore: add coderabbit configuration
  .coderabbit.yaml
Labels: size:S, lgtm

#7952 chore(server): add local MinIO support for development
  .gitignore
  mise.toml
  server/.gitignore
  server/config/runtime.exs
  server/lib/tuist/application.ex
  server/lib/tuist/environment.ex
  server/lib/tuist/minio_bucket_creator.ex
  server/lib/tuist/storage.ex
  server/mix.exs
  server/mix.lock
  server/test/tuist/qa/agent_test.exs
  server/test/tuist/storage_test.exs
Labels: type:enhancement, size:L, lgtm

#7974 fix(server): fix crash on unknown sorting parameters
  server/lib/tuist_web/live/bundle_live.ex
Labels: type:bug, size:XS, lgtm

#7971 fix(server): handle xcresult upload with asynchronously inserted command events
  server/lib/tuist/command_events.ex
  server/lib/tuist_web/controllers/api/analytics_controller.ex
  server/test/tuist_web/controllers/analytics_controller_test.exs
Labels: type:bug, size:L, lgtm

#7972 feat(cli): print the full sandbox command when a system command fails
  cli/Sources/TuistSupport/System/System.swift
Labels: type:enhancement, size:S, lgtm, domain:cli

#7975 fix(server): use request version instead of header for determining ID format
  server/lib/tuist_web/controllers/api/analytics_controller.ex
  server/test/tuist_web/controllers/analytics_controller_test.exs
Labels: type:enhancement, size:L, lgtm

#7967 feat(server): send QA agent events
  .env.json
  server/config/runtime.exs
  server/lib/tuist.ex
  server/lib/tuist/authentication.ex
  server/lib/tuist/authorization.ex
  server/lib/tuist/environment.ex
  server/lib/tuist/guardian.ex
  server/lib/tuist/qa.ex
  server/lib/tuist/qa/agent.ex
  server/lib/tuist/qa/client.ex
  server/lib/tuist/qa/run.ex
  server/lib/tuist/qa/screenshot.ex
  server/lib/tuist/qa/step.ex
  server/lib/tuist/qa/tools.ex
  server/lib/tuist/qa/workers/test_worker.ex
  server/lib/tuist_web/controllers/api/qa_controller.ex
  server/lib/tuist_web/plugs/api/authorization/authorization_plug.ex
  server/lib/tuist_web/router.ex
  server/mix.exs
  server/mix.lock
  server/priv/repo/migrations/20250805121532_create_qa_runs.exs
  server/priv/repo/migrations/20250805121921_create_qa_steps.exs
  server/priv/repo/migrations/20250805130346_create_qa_screenshots.exs
  server/test/support/tuist_test_support/fixtures/qa_fixtures.ex
  server/test/test_helper.exs
  server/test/tuist/authentication_test.exs
  server/test/tuist/guardian_test.exs
  server/test/tuist/qa/agent_test.exs
  server/test/tuist/qa/client_test.exs
  server/test/tuist/qa/run_step_test.exs
  server/test/tuist/qa/run_test.exs
  server/test/tuist/qa/screenshot_test.exs
  server/test/tuist/qa/tools_test.exs
  server/test/tuist/qa_test.exs
  server/test/tuist_web/controllers/api/qa_controller_test.exs
Labels: type:enhancement, size:XXL, lgtm

#7988 fix(cli): unexpected behaviours when renaming resources in cached targets
  .github/workflows/app.yml
  .github/workflows/cli-cache-ee.yml
  .github/workflows/conventional-pr.yml
  cli/Sources/TuistHasher/ResourcesContentHasher.swift
  cli/Tests/TuistHasherTests/ResourcesContentHasherTests.swift
Labels: type:enhancement, size:M

#7980 chore(server): 'Tuist's AI whitepaper' post
  server/priv/marketing/blog/2025/08/11/tuist-ai-whitepaper.md
Labels: size:L, domain:docs, lgtm

#7993 feat(cli): add support for XcodeKit SDK
  Package.resolved
Labels: size:L, domain:dependencies, lgtm

#7961 feat(cli): support hashing transitive `.xcconfig` files
  cli/Sources/TuistHasher/SettingsContentHasher.swift
  cli/Sources/TuistHasher/TargetContentHasher.swift
  cli/Sources/TuistHasher/XCConfigContentHasher.swift
  cli/Tests/TuistHasherTests/SettingsContentHasherTests.swift
  cli/Tests/TuistHasherTests/XCConfigContentHasherTests.swift
Labels: type:enhancement, size:L, lgtm

#7996 chore(cli): Fix TuistCacheEE submodule initialization in CI pipelines
  .github/workflows/cli-cache-ee.yml
  mise/tasks/cli/ee.sh
Labels: size:S, domain:cache, lgtm

#8004 chore(cli): fix CLI releases and documentation deployments
  .github/workflows/release.yml
  docs/.vitepress/data/cli.js
Labels: size:M, domain:docs, lgtm

#7997 feat(server): run QA in Namespace runners
  .github/workflows/server.yml
  server/.formatter.exs
  server/.gitignore
  server/Dockerfile
  server/lib/tuist.ex
  server/lib/tuist/accounts.ex
  server/lib/tuist/accounts/account.ex
  server/lib/tuist/environment.ex
  server/lib/tuist/namespace.ex
  server/lib/tuist/namespace/instance.ex
  server/lib/tuist/namespace/jwt_token.ex
  server/lib/tuist/qa.ex
  server/lib/tuist/qa/workers/test_worker.ex
  server/lib/tuist/ssh_client.ex
  server/lib/tuist_web/controllers/apple_app_site_association_controller.ex
  server/lib/tuist_web/controllers/webhooks/github_controller.ex
  server/lib/tuist_web/controllers/well_known_controller.ex
  server/lib/tuist_web/router.ex
  server/mix.exs
  server/mix.lock
  server/priv/repo/migrations/20250811121337_add_tenant_id_to_accounts.exs
  server/priv/secrets/can.yml.enc
  server/priv/secrets/prod.yml.enc
  server/priv/secrets/stag.yml.enc
  server/runner/lib/runner.ex
  server/runner/lib/runner/commands/qa.ex
  server/runner/lib/runner/qa/agent.ex
  server/runner/lib/runner/qa/client.ex
  server/runner/lib/runner/qa/log_streamer.ex
  server/runner/lib/runner/qa/simulators.ex
  server/runner/lib/runner/qa/simulators/simulator_device.ex
  server/runner/lib/runner/qa/tools.ex
  server/runner/lib/runner/zip.ex
  server/runner/mix.exs
  server/runner/test/qa/agent_test.exs
  server/runner/test/qa/client_test.exs
  server/runner/test/qa/log_streamer_test.exs
  server/runner/test/qa/simulators_test.exs
  server/runner/test/qa/tools_test.exs
  server/runner/test/test_helper.exs
  server/test/support/tuist_test_support/fixtures/app_builds_fixtures.ex
  server/test/test_helper.exs
  server/test/tuist/accounts/account_test.exs
  server/test/tuist/accounts_test.exs
  server/test/tuist/namespace_test.exs
  server/test/tuist/qa_test.exs
  server/test/tuist_web/channels/qa_log_channel_test.exs
  server/test/tuist_web/controllers/apple_app_site_association_controller_test.exs
  server/test/tuist_web/controllers/webhooks/github_controller_test.exs
  server/test/tuist_web/controllers/well_known_controller_test.exs
Labels: type:enhancement, size:XXL, lgtm

#8010 fix(cli,app): fetching devices when running previews
  cli/Sources/TuistAutomation/Device/DeviceController.swift
  cli/Tests/TuistAutomationTests/Device/DeviceControllerTests.swift
Labels: type:bug, size:M, domain:previews, lgtm

#8012 fix(server): fix rendering preview QR code images in GitLab
  server/lib/tuist_web/router.ex
Labels: size:S, domain:previews

#8005 feat(server): ops page, QA agent logs and business intelligence, LLM token usage tracking
  server/assets/app/css/layouts.css
  server/assets/app/css/layouts/ops.css
  server/assets/app/css/pages.css
  server/assets/app/css/pages/ops/qa.css
  server/assets/app/css/pages/ops/qa_logs.css
  server/config/config.exs
  server/config/runtime.exs
  server/lib/tuist.ex
  server/lib/tuist/application.ex
  server/lib/tuist/billing.ex
  server/lib/tuist/billing/token_usage.ex
  server/lib/tuist/error_tracker/ignorer.ex
  server/lib/tuist/qa.ex
  server/lib/tuist/qa/log.ex
  server/lib/tuist/qa/logs/buffer.ex
  server/lib/tuist_web/channels/qa_log_channel.ex
  server/lib/tuist_web/components/account_dropdown.ex
  server/lib/tuist_web/components/layouts/ops.html.heex
  server/lib/tuist_web/live/layout_live.ex
  server/lib/tuist_web/live/ops_qa_live.ex
  server/lib/tuist_web/live/ops_qa_live.html.heex
  server/lib/tuist_web/live/ops_qa_logs_live.ex
  server/lib/tuist_web/live/ops_qa_logs_live.html.heex
  server/lib/tuist_web/router.ex
  server/mix.exs
  server/mix.lock
  server/priv/ingest_repo/migrations/20250811155755_add_qa_logs_table.exs
  server/priv/repo/migrations/20240926093919_add_error_tracker.exs
  server/priv/repo/migrations/20250813084853_create_billing_token_usage.exs
  server/priv/repo/seeds.exs
  server/runner/lib/runner/qa/agent.ex
  server/runner/lib/runner/qa/client.ex
  server/runner/lib/runner/qa/log_streamer.ex
  server/runner/test/qa/client_test.exs
  server/test/support/tuist_test_support/fixtures/qa_fixtures.ex
  server/test/tuist/billing/token_usage_test.exs
  server/test/tuist/qa/logs/buffer_test.exs
  server/test/tuist/qa_test.exs
  server/test/tuist_web/channels/qa_log_channel_test.exs
Labels: type:enhancement, domain:dashboard, size:XXL, lgtm

#8011 fix(cli): generation regression
  cli/Sources/TuistKit/Mappers/Factories/GraphMapperFactory.swift
  cli/Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersBuilder.swift
Labels: type:bug, domain:generated-projects, size:L, lgtm

#8020 fix(server): disable Prometheus in production
  server/fly.prod.toml
Labels: type:bug, size:XS, lgtm

#7995 feat(server): use a global storage
  .env.json
  pnpm-lock.yaml
  server/config/runtime.exs
  server/lib/tuist/environment.ex
  server/lib/tuist/storage.ex
  server/mix.exs
  server/priv/secrets/can.yml.enc
  server/priv/secrets/prod.yml.enc
  server/priv/secrets/stag.yml.enc
  server/test/tuist/storage_test.exs
Labels: type:enhancement, size:L, domain:cache, lgtm

#8046 fix(server): sanitize metadata values to prevent String.Chars protocol errors
  CLAUDE.md
  server/lib/tuist/http/prom_ex_plugin.ex
  server/lib/tuist/telemetry/sanitizer.ex
  server/test/tuist/telemetry/sanitizer_test.exs
Labels: type:bug, size:M, lgtm

#8027 feat(server): improve QA reports with more granular steps
  server/lib/tuist/authorization.ex
  server/lib/tuist/qa.ex
  server/lib/tuist/qa/qa_test_summary.eex
  server/lib/tuist/qa/run.ex
  server/lib/tuist/qa/screenshot.ex
  server/lib/tuist/qa/step.ex
  server/lib/tuist_web/controllers/api/qa_controller.ex
  server/lib/tuist_web/controllers/qa_controller.ex
  server/lib/tuist_web/plugs/api/authorization/authorization_plug.ex
  server/lib/tuist_web/router.ex
  server/mix.exs
  server/priv/repo/migrations/20250815134927_make_qa_step_description_optional.exs
  server/priv/repo/migrations/20250818104313_rename_qa_step_summary_to_action.exs
  server/priv/repo/migrations/20250818105845_remove_qa_run_summary.exs
  server/priv/repo/migrations/20250818131516_rename_qa_step_description_to_result.exs
  server/priv/repo/migrations/20250818155249_remove_qa_screenshot_file_name_and_title.exs
  server/priv/repo/seeds.exs
  server/runner/lib/runner/qa/agent.ex
  server/runner/lib/runner/qa/client.ex
  server/runner/lib/runner/qa/tools.ex
  server/runner/test/qa/agent_test.exs
  server/runner/test/qa/client_test.exs
  server/runner/test/qa/tools_test.exs
  server/test/support/tuist_test_support/fixtures/qa_fixtures.ex
  server/test/tuist/qa/run_step_test.exs
  server/test/tuist/qa/screenshot_test.exs
  server/test/tuist/qa_test.exs
  server/test/tuist_web/controllers/api/qa_controller_test.exs
  server/test/tuist_web/controllers/qa_controller_test.exs
Labels: type:enhancement, size:XXL, lgtm

#8055 feat(server): live streaming QA logs
  server/lib/tuist/environment.ex
  server/lib/tuist_web/channels/qa_log_channel.ex
  server/lib/tuist_web/live/ops_qa_logs_live.ex
  server/lib/tuist_web/live/ops_qa_logs_live.html.heex
  server/mix.lock
  server/priv/repo/seeds.exs
  server/runner/lib/runner/qa/agent.ex
Labels: type:enhancement, size:M, lgtm

#8067 chore(cli): fix failing BundeListCommandService test
  cli/Tests/TuistKitTests/Services/Bundle/BundleListCommandServiceTests.swift
Labels: type:bug, size:XS, domain:cli

#8072 fix(server): runtime errors processing telemetry events for Prometheus
  server/mix.exs
  server/mix.lock
Labels: type:bug, size:XS, lgtm

#8058 feat(server): use Appium for describe_ui
  .env.json
  server/lib/tuist/environment.ex
  server/lib/tuist/qa.ex
  server/lib/tuist/qa/qa_test_summary.eex
  server/lib/tuist/ssh_client.ex
  server/mix.lock
  server/priv/repo/migrations/20250821093804_change_qa_step_issues_type.exs
  server/priv/secrets/can.yml.enc
  server/priv/secrets/prod.yml.enc
  server/priv/secrets/stag.yml.enc
  server/runner/lib/runner.ex
  server/runner/lib/runner/commands/qa.ex
  server/runner/lib/runner/qa/agent.ex
  server/runner/lib/runner/qa/appium_client.ex
  server/runner/lib/runner/qa/sleeper.ex
  server/runner/lib/runner/qa/tools.ex
  server/runner/mix.exs
  server/runner/test/qa/agent_test.exs
  server/runner/test/qa/appium_client_test.exs
  server/runner/test/qa/tools_test.exs
  server/test/test_helper.exs
  server/test/tuist/qa_test.exs
Labels: type:enhancement, size:XXL, lgtm

#8074 fix(server): make migrations reversible
  server/priv/ingest_repo/migrations/20250715093853_add_performance_indexes_and_computed_columns.exs
  server/priv/repo/migrations/20241119161955_add_index_previews_project_id.exs
  server/priv/repo/migrations/20250128153554_add_path_to_xcode_projects.exs
  server/priv/repo/migrations/20250320095026_add_metadata_to_preview.exs
  server/priv/repo/migrations/20250528140917_drop_artifacts_foreign_key.exs
  server/priv/repo/migrations/20250612115646_remove_xcode_target_fk_from_test_case_runs.exs
  server/priv/repo/migrations/20250613140005_add_binary_build_duration_to_xcode_targets.exs
  server/priv/repo/migrations/20250613144635_add_binary_build_duration_to_xcode_graphs.exs
  server/priv/repo/migrations/20250615093614_rename_previews_to_app_builds.exs
  server/priv/repo/migrations/20250623090458_drop_xcode_tables.exs
  server/priv/repo/migrations/20250623091758_clients_key_pair_types.exs
  server/priv/repo/migrations/20250623091800_clients_signatures_adapters.exs
  server/priv/repo/migrations/20250805130346_create_qa_screenshots.exs
  server/priv/repo/migrations/20250815134927_make_qa_step_description_optional.exs
Labels: type:bug, size:L, lgtm

#8075 chore(server): disable distributed cache
  server/lib/tuist/application.ex
Labels: type:enhancement, size:S, domain:cache, lgtm

#8081 chore(server): keep ClickHouse connections alive, and use IPv6 if available
  server/config/runtime.exs
  server/lib/tuist/application.ex
Labels: size:S, lgtm

#8082 fix(server): launch errors related to ClickHouse and Cachex
  server/lib/tuist/application.ex
  server/lib/tuist/key_value_store.ex
Labels: type:bug, size:S, domain:cache, lgtm

#8083 chore(server): revert global bucket
  server/priv/secrets/prod.yml.enc
Labels: size:XS, domain:cache

#8014 refactor(server): move all remaining authorization logic to letme
  server/lib/tuist/accounts/account_token.ex
  server/lib/tuist/authorization.ex
  server/lib/tuist/authorization/checks.ex
  server/lib/tuist/qa.ex
  server/lib/tuist_web/app.ex
  server/lib/tuist_web/authentication.ex
  server/lib/tuist_web/authorization.ex
  server/lib/tuist_web/channels/qa_log_channel.ex
  server/lib/tuist_web/components/account_dropdown.ex
  server/lib/tuist_web/components/layouts/account.html.heex
  server/lib/tuist_web/controllers/api/account_controller.ex
  server/lib/tuist_web/controllers/api/invitations_controller.ex
  server/lib/tuist_web/controllers/api/organizations_controller.ex
  server/lib/tuist_web/controllers/api/project_tokens_controller.ex
  server/lib/tuist_web/controllers/api/projects_controller.ex
  server/lib/tuist_web/controllers/billing_controller.ex
  server/lib/tuist_web/controllers/runs_controller.ex
  server/lib/tuist_web/live/account_settings_live.ex
  server/lib/tuist_web/live/billing_live.ex
  server/lib/tuist_web/live/create_project_live.ex
  server/lib/tuist_web/live/layout_live.ex
  server/lib/tuist_web/live/members_live.ex
  server/lib/tuist_web/live/projects_live.ex
  server/lib/tuist_web/plugs/api/authorization/authorization_plug.ex
  server/test/tuist/accounts/account_token_test.exs
  server/test/tuist/accounts_test.exs
  server/test/tuist/authentication_test.exs
  server/test/tuist/authorization/checks_test.exs
  server/test/tuist/authorization_test.exs
  server/test/tuist/guardian_test.exs
  server/test/tuist_web/authorization_test.exs
  server/test/tuist_web/channels/qa_log_channel_test.exs
  server/test/tuist_web/controllers/api/account_tokens_controller_test.exs
  server/test/tuist_web/controllers/api/qa_controller_test.exs
  server/test/tuist_web/controllers/api/registry/swift_controller_test.exs
  server/test/tuist_web/live/layout_live_test.exs
  server/test/tuist_web/plugs/api/authorization/authorization_plug_test.exs
  server/test/tuist_web/plugs/authentication_plug_test.exs
Labels: type:enhancement, size:XXL, lgtm

#8048 fix(cli): revert caching only the default architecture
  .github/workflows/cli.yml
  Tuist/ProjectDescriptionHelpers/Module.swift
  app/Project.swift
  cli/Sources/TuistKit/Commands/Cache/CacheService.swift
Labels: size:M, lgtm, domain:cli

#8084 fix(server): runs metadata failing to upload
  cli/Sources/TuistKit/Utils/TuistAnalyticsServerBackend.swift
  cli/Sources/TuistServer/OpenAPI/Client.swift
  cli/Sources/TuistServer/OpenAPI/Types.swift
  cli/Sources/TuistServer/OpenAPI/server.yml
  cli/Sources/TuistServer/Services/AnalyticsArtifactUploadService.swift
  cli/Sources/TuistServer/Services/CompleteAnalyticsArtifactsUploads.swift
  cli/Sources/TuistServer/Services/ListBundlesService.swift
  cli/Sources/TuistServer/Services/MultipartUploadCompleteAnalyticsService.swift
  cli/Sources/TuistServer/Services/MultipartUploadGenerateURLAnalyticsService.swift
  cli/Sources/TuistServer/Services/MultipartUploadStartAnalyticsService.swift
  cli/Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
  cli/Tests/TuistKitTests/Utils/TuistAnalyticsServerBackendTests.swift
  cli/Tests/TuistServerTests/AnalyticsArtifactUploadServiceTests.swift
  server/lib/tuist_web/controllers/api/analytics_controller.ex
  server/lib/tuist_web/router.ex
  server/test/tuist_web/controllers/analytics_controller_test.exs
Labels: type:bug, size:XXL, lgtm

#8089 chore(server): add data export documentation for legal compliance
  CLAUDE.md
  handbook/CLAUDE.md
  server/data-export.md
Labels: size:L, domain:docs, lgtm

#8086 feat(server): retrieve QA screenshots from S3, show for actions
  server/lib/tuist_web/channels/qa_log_channel.ex
  server/lib/tuist_web/live/ops_qa_logs_live.ex
  server/lib/tuist_web/live/ops_qa_logs_live.html.heex
  server/mise.toml
  server/runner/lib/runner/qa/tools.ex
  server/runner/test/qa/tools_test.exs
Labels: type:enhancement, size:L, lgtm

#8094 fix(cli): caching issues due to incompatible architectures
  cli/Sources/TuistKit/Commands/Cache/CacheService.swift
  cli/Sources/TuistKit/Commands/CacheCommand.swift
  cli/Sources/TuistKit/Commands/EnvKey/EnvKey.swift
Labels: size:M

#8095 chore(server): Disable Prometheus temporarily in our production server
  server/fly.prod.toml
Labels: size:XS, lgtm

#8087 feat(runner): submit step reports asynchronously
  server/lib/tuist_web/controllers/api/qa_controller.ex
  server/lib/tuist_web/router.ex
  server/runner/lib/runner/qa/agent.ex
  server/runner/lib/runner/qa/client.ex
  server/runner/lib/runner/qa/tools.ex
  server/runner/test/qa/agent_test.exs
  server/runner/test/qa/client_test.exs
  server/runner/test/qa/tools_test.exs
  server/test/tuist_web/controllers/api/qa_controller_test.exs
Labels: type:enhancement, size:L, lgtm

#8096 fix(cli): arch incompatibilities when using the cache
  cli/Sources/TuistCache/CacheVersionFetcher.swift
Labels: type:bug, p1, size:S, domain:cache, lgtm

#8100 fix(server): memory leak with Prometheus metrics
  server/config/runtime.exs
  server/lib/tuist/prom_ex.ex
  server/lib/tuist/prom_ex/striped_peep.ex
  server/test/tuist/prom_ex/striped_peep_test.exs
Labels: type:bug, size:L, lgtm

#8107 feat(server): skip dev releases in registry
  server/lib/tuist/registry/swift/packages.ex
  server/test/tuist/registry/swift/packages_test.exs
Labels: type:enhancement, size:M, domain:registry

#8106 fix(server): retry on :closed_for_writing
  server/lib/tuist/application.ex
  server/lib/tuist/github/client.ex
  server/test/tuist/github/client_test.exs
  server/test/tuist/vcs_test.exs
Labels: type:bug, size:L, lgtm

#8109 fix(server): prevent scientific notation in trend badge display
  server/lib/tuist_web/components/trend_badge.ex
Labels: type:bug, size:S, domain:dashboard

#8108 fix(server): replace all `Timex.from_now` with our date formatter
  server/lib/tuist_web/live/bundles_live.ex
  server/lib/tuist_web/live/bundles_live.html.heex
  server/lib/tuist_web/live/projects_live.ex
Labels: type:bug, size:S
