Repository tuist/tuist, pull requests merged in 2025-03, with the labels that each got.

#7372 Fix reporting ran at date of runs
  Sources/TuistCore/Analytics/CommandEvent.swift
  Sources/TuistKit/Commands/TrackableCommand/CommandEventFactory.swift
  Sources/TuistKit/Commands/TrackableCommand/TrackableCommand.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/CreateCommandEventService.swift
  Tests/TuistKitTests/CommandTracking/CommandEventFactoryTests.swift
  Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
Labels: changelog:fixed, size:XXL, lgtm

#7374 Update dependencies with known vulnerabilities
  docs/package.json
  docs/pnpm-lock.yaml
  mise.toml
Labels: changelog:fixed, size:S, lgtm

#7371 Make selective testing cache targets with passing tests, even if the test run ultimately failed
  Package.resolved
  Package.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistKit/Utils/XCResultService.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
Labels: changelog:added, size:L, lgtm

#7376 Update XcodeGraph
  Package.resolved
  Package.swift
Labels: changelog:changed, size:S, lgtm

#7340 Add tuist inspect build command
  Package.resolved
  Package.swift
  Sources/TuistAcceptanceTesting/ServerAcceptanceTestCase.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
  Sources/TuistCore/Automation/XcodeBuildControlling.swift
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Commands/Inspect/InspectBuildCommand.swift
  Sources/TuistKit/Commands/InspectCommand.swift
  Sources/TuistKit/Services/Inspect/InspectBuildCommandService.swift
  Sources/TuistKit/Services/Inspect/Models/ActivityLog.swift
  Sources/TuistKit/Services/Inspect/Models/LogStoreManifest.swift
  Sources/TuistKit/Services/Inspect/Utilities/BackgroundProcessRunner.swift
  Sources/TuistKit/Services/XcodeBuildService.swift
  Sources/TuistServer/Services/CreateBuildService.swift
  Sources/TuistSupport/MachineEnvironment.swift
  Sources/TuistSupport/Utils/DerivedDataLocator.swift
  Sources/TuistSupport/Utils/Environment.swift
  Sources/TuistSupport/XCActivityParser/XCAcitivityParser.swift
  Sources/TuistSupport/XCActivityParser/XCActivityLog.swift
  Sources/TuistSupport/XCActivityParser/XCActivityLogSection.swift
  Sources/TuistSupportTesting/Utils/MockEnvironment.swift
  Tests/TuistAutomationIntegrationTests/XcodeBuild/XcodeBuildControllerIntegrationTests.swift
  Tests/TuistAutomationTests/XcodeBuild/XcodeBuildControllerTests.swift
  Tests/TuistKitAcceptanceTests/AccountAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/InspectAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/ShareAcceptanceTests.swift
  Tests/TuistKitTests/CommandTracking/CommandEventFactoryTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectBuildCommandServiceTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  docs/.vitepress/bars.mjs
  docs/.vitepress/strings/en.json
  docs/docs/en/guides/develop/insights.md
  docs/docs/en/index.md
  docs/docs/public/images/guides/develop/insights/builds-dashboard.png
  docs/docs/public/images/guides/develop/insights/inspect-build-scheme-post-action.png
  fixtures/xcode_project_with_inspect_build/.gitignore
  fixtures/xcode_project_with_inspect_build/App.xcodeproj/project.pbxproj
  fixtures/xcode_project_with_inspect_build/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme
  fixtures/xcode_project_with_inspect_build/App/AppApp.swift
  fixtures/xcode_project_with_inspect_build/App/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/xcode_project_with_inspect_build/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/xcode_project_with_inspect_build/App/Assets.xcassets/Contents.json
  fixtures/xcode_project_with_inspect_build/App/ContentView.swift
  fixtures/xcode_project_with_inspect_build/App/Preview Content/Preview Assets.xcassets/Contents.json
  fixtures/xcode_project_with_inspect_build/AppTests/AppTests.swift
  fixtures/xcode_project_with_inspect_build/Tuist.swift
Labels: changelog:added, size:XL, lgtm

#7355 Overhaul the get started CLI workflow
  Package.resolved
  Package.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceTestCase.swift
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Commands/InitCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/InitCommandService.swift
  Sources/TuistKit/Services/InitService.swift
  Sources/TuistKit/Services/LoginService.swift
  Sources/TuistKit/Services/Start/InitGeneratedProjectService.swift
  Sources/TuistKit/Utils/InitPrompter.swift
  Sources/TuistServer/Session/ServerSessionController.swift
  Sources/TuistSupport/Errors/ErrorHandler.swift
  Templates/default/default.swift
  Templates/default/mise.stencil
  Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/InitAcceptanceTests.swift
  Tests/TuistKitTests/CommandEnvironmentVariables/CommandEnvironmentVariableTests.swift
  Tests/TuistKitTests/Services/InitCommandServiceTests.swift
  Tests/TuistKitTests/Services/InitServiceTests.swift
  Tests/TuistKitTests/Services/Start/InitGeneratedProjectServiceTests.swift
  Tests/TuistSupportTests/Errors/ErrorHandlerTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  docs/.vitepress/bars.mjs
  docs/.vitepress/data/cli.js
  docs/.vitepress/locale-redirects.txt
  docs/.vitepress/strings/en.json
  docs/docs/en/cli/shell-completions.md
  docs/docs/en/guides/quick-start/create-a-project.md
  docs/docs/en/guides/quick-start/get-started.md
  docs/docs/en/guides/quick-start/install-tuist.md
  docs/docs/en/guides/quick-start/optimize-workflows.md
  docs/docs/es/guides/quick-start/create-a-project.md
  docs/docs/es/guides/quick-start/optimize-workflows.md
  docs/docs/ja/guides/quick-start/create-a-project.md
  docs/docs/ja/guides/quick-start/optimize-workflows.md
  docs/docs/ko/guides/quick-start/create-a-project.md
  docs/docs/ko/guides/quick-start/optimize-workflows.md
  docs/docs/pt/guides/quick-start/create-a-project.md
  docs/docs/pt/guides/quick-start/optimize-workflows.md
  docs/docs/ru/guides/quick-start/create-a-project.md
  docs/docs/ru/guides/quick-start/optimize-workflows.md
  fixtures/xcode_project_ios_app/.gitignore
  fixtures/xcode_project_ios_app/App.xcodeproj/project.pbxproj
  fixtures/xcode_project_ios_app/App/AppApp.swift
  fixtures/xcode_project_ios_app/App/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/xcode_project_ios_app/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/xcode_project_ios_app/App/Assets.xcassets/Contents.json
  fixtures/xcode_project_ios_app/App/ContentView.swift
  fixtures/xcode_project_ios_app/App/Preview Content/Preview Assets.xcassets/Contents.json
Labels: size:XXL, lgtm

#7383 Fix ProjectAutomation.graph() method
  Sources/ProjectAutomation/Tuist.swift
Labels: type:enhancement, changelog:fixed, size:XS, lgtm

#7389 Sort the targets before printing them
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistKit/Services/XcodeBuildService.swift
Labels: changelog:fixed, size:XS, lgtm

#7388 Add `build-for-testing` and `test-without-building` support to `tuist test`
  Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift
  Sources/TuistCore/Automation/XcodeBuildControlling.swift
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistAutomationTests/XcodeBuild/XcodeBuildControllerTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: type:enhancement, changelog:added, size:L, lgtm

#7391 Improve error handling
  Package.resolved
  Package.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistSupport/Errors/ErrorHandler.swift
  Sources/TuistSupport/Utils/AlertController.swift
  Sources/TuistSupportTesting/Errors/MockErrorHandler.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistSupportTests/Errors/ErrorHandlerTests.swift
Labels: type:enhancement, changelog:changed, size:L, lgtm

#7393 Fix duplicated warning alerts
  Package.resolved
  Package.swift
  Sources/TuistCore/Models/LintingIssue.swift
  Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersBuilder.swift
  Sources/TuistSupport/Utils/AlertController.swift
Labels: changelog:fixed, size:S, lgtm

#7396 [Docs] fix link to registry
  docs/docs/en/index.md
Labels: changelog:fixed, size:XS, lgtm

#7397 Show errors using the error alert
  Sources/TuistKit/Commands/TuistCommand.swift
Labels: type:bug, changelog:fixed, size:XS, lgtm

#7361 New Crowdin updates
  docs/.vitepress/strings/es.json
  docs/.vitepress/strings/ja.json
  docs/.vitepress/strings/ko.json
  docs/.vitepress/strings/pt.json
  docs/.vitepress/strings/ru.json
  docs/docs/es/cli/shell-completions.md
  docs/docs/es/guides/develop/cache.md
  docs/docs/es/guides/develop/insights.md
  docs/docs/es/guides/quick-start/get-started.md
  docs/docs/es/guides/quick-start/install-tuist.md
  docs/docs/es/index.md
  docs/docs/es/server/on-premise/install.md
  docs/docs/ja/cli/shell-completions.md
  docs/docs/ja/contributors/cli/logging.md
  docs/docs/ja/contributors/code-reviews.md
  docs/docs/ja/contributors/issue-reporting.md
  docs/docs/ja/contributors/principles.md
  docs/docs/ja/contributors/translate.md
  docs/docs/ja/guides/automate/continuous-integration.md
  docs/docs/ja/guides/develop/cache.md
  docs/docs/ja/guides/develop/insights.md
  docs/docs/ja/guides/develop/projects/adoption/new-project.md
  docs/docs/ja/guides/quick-start/get-started.md
  docs/docs/ja/guides/quick-start/install-tuist.md
  docs/docs/ja/guides/tuist/about.md
  docs/docs/ja/index.md
  docs/docs/ja/server/on-premise/install.md
  docs/docs/ko/cli/shell-completions.md
  docs/docs/ko/contributors/cli/logging.md
  docs/docs/ko/contributors/get-started.md
  docs/docs/ko/guides/develop/cache.md
  docs/docs/ko/guides/develop/insights.md
  docs/docs/ko/guides/develop/projects.md
  docs/docs/ko/guides/develop/selective-testing.md
  docs/docs/ko/guides/develop/selective-testing/generated-project.md
  docs/docs/ko/guides/develop/selective-testing/xcodebuild.md
  docs/docs/ko/guides/quick-start/get-started.md
  docs/docs/ko/guides/quick-start/install-tuist.md
  docs/docs/ko/guides/share/previews.md
  docs/docs/ko/index.md
  docs/docs/ko/server/on-premise/install.md
  docs/docs/pt/cli/shell-completions.md
  docs/docs/pt/guides/develop/cache.md
  docs/docs/pt/guides/develop/insights.md
  docs/docs/pt/guides/quick-start/get-started.md
  docs/docs/pt/guides/quick-start/install-tuist.md
  docs/docs/pt/index.md
  docs/docs/pt/server/on-premise/install.md
  docs/docs/ru/cli/shell-completions.md
  docs/docs/ru/guides/develop/cache.md
  docs/docs/ru/guides/develop/insights.md
  docs/docs/ru/guides/develop/projects.md
  docs/docs/ru/guides/develop/projects/best-practices.md
  docs/docs/ru/guides/quick-start/get-started.md
  docs/docs/ru/guides/quick-start/install-tuist.md
  docs/docs/ru/index.md
  docs/docs/ru/server/on-premise/install.md
Labels: size:XXL

#7399 Fix `--help` error not showing
  Package.resolved
  Package.swift
  Sources/TuistAcceptanceTesting/ServerAcceptanceTestCase.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/ShareService.swift
  Sources/TuistSupport/UI/UI+ServiceContext.swift
  Sources/TuistSupport/Utils/AlertController.swift
  Sources/TuistSupport/Utils/ThreadSafe.swift
  Tests/TuistKitAcceptanceTests/ShareAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_ios_app_with_appclip.1.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_ios_app_with_appclip.2.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_ios_app_with_appclip.3.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_ios_app_with_appclip.4.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_ios_app_with_appclip.5.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_ios_app_with_frameworks.1.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_ios_app_with_frameworks.2.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_ios_app_with_frameworks.3.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_xcode_app.1.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_xcode_app.2.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_xcode_app_files.1.txt
  Tuist/ProjectDescriptionHelpers/Module.swift
  mise.toml
  mise/tasks/.gitignore
  mise/tasks/benchmark/build
  mise/tasks/benchmark/run
  mise/tasks/build-cross-platform.sh
  mise/tasks/bundle/app
  mise/tasks/bundle/cli
  mise/tasks/clean
  mise/tasks/docs/build
  mise/tasks/docs/deploy
  mise/tasks/docs/dev
  mise/tasks/docs/generate-cli-docs
  mise/tasks/docs/generate-manifests-docs
  mise/tasks/fixturegenerator/build
  mise/tasks/fixturegenerator/run
  mise/tasks/install
  mise/tasks/lint
  mise/tasks/lint-fix
  mise/tasks/spm/tuist/build
  mise/tasks/spm/tuist/edit
  mise/tasks/spm/tuist/generate
  mise/tasks/spm/tuist/run
  mise/tasks/spm/tuist/test
  mise/tasks/workspace/generate/server-openapi-code
  mise/tasks/workspace/release/homebrew-cask
  mise/utilities/derived_data_path.sh
  mise/utilities/setup.sh
  mise/utilities/xcode_path.sh
Labels: type:bug, changelog:fixed, size:L, lgtm

#7412 Install create-dmg using the asdf plugin
  mise.toml
  mise/tasks/bundle/app
Labels: changelog:changed, size:XS, lgtm

#7410 Add `Sendable` conformance to `Plugin` type in ProjectDescription
  Sources/ProjectDescription/Plugin.swift
Labels: changelog:fixed, size:XS, lgtm

#7394 Fix issues where attempting to build-for-testing schemes with no test targets didn't do anything
  Sources/TuistAutomation/Utilities/BuildGraphInspector.swift
  Sources/TuistCore/Automation/XcodeBuildControlling.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistAutomationTests/Utilities/BuildGraphInspectorTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:fixed, size:L, lgtm

#7380 Create test targets for local SPM packages
  Sources/ProjectAutomation/Project.swift
  Sources/ProjectDescription/PackageSettings.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/Graph/ModelExtensions/Project+Core.swift
  Sources/TuistCore/GraphTraverser/GraphTraversing.swift
  Sources/TuistCore/Models/PackageSettings.swift
  Sources/TuistDependencies/Mappers/ExternalDependencyPathWorkspaceMapper.swift
  Sources/TuistDependencies/Mappers/PruneOrphanRemoteTargetsGraphMapper.swift
  Sources/TuistGenerator/Extensions/Graph+Extras.swift
  Sources/TuistKit/Mappers/Factories/GraphMapperFactory.swift
  Sources/TuistKit/Services/ProjectAutomation+ManifestMapper.swift
  Sources/TuistKit/Utils/ManifestGraphLoader.swift
  Sources/TuistLoader/Loaders/RecursiveManifestLoader.swift
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Sources/TuistLoader/Models+ManifestMappers/PackageSettings+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Project+ManifestMapper.swift
  Sources/TuistLoader/Models/DependenciesGraph.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Sources/TuistSupport/Constants.swift
  Sources/TuistSupport/SwiftPackageManager/PackageType.swift
  Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistDependenciesTests/Mappers/ExternalDependencyPathWorkspaceMapperTests.swift
  Tests/TuistDependenciesTests/Mappers/PruneOrphanRemoteTargetsGraphMapperTests.swift
  Tests/TuistLoaderTests/Loaders/ManifestModelConverterTests.swift
  Tests/TuistLoaderTests/Loaders/PackageSettingsLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/RecursiveManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/SwiftPackageManagerGraphLoaderTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: type:enhancement, changelog:added, size:XL, lgtm

#7401 New Crowdin updates
  docs/.vitepress/strings/ru.json
  docs/docs/es/cli/logging.md
  docs/docs/es/index.md
  docs/docs/ja/cli/logging.md
  docs/docs/ja/guides/develop/projects/adoption/new-project.md
  docs/docs/ja/index.md
  docs/docs/ko/cli/logging.md
  docs/docs/ko/index.md
  docs/docs/pt/cli/logging.md
  docs/docs/pt/index.md
  docs/docs/ru/cli/logging.md
  docs/docs/ru/contributors/cli/logging.md
  docs/docs/ru/contributors/get-started.md
  docs/docs/ru/guides/develop/projects.md
  docs/docs/ru/guides/quick-start/get-started.md
  docs/docs/ru/index.md
Labels: size:M

#7413 Fix the releasing of the app
  .github/workflows/release.yml
Labels: changelog:fixed, size:XS, lgtm

#7398 fix: absolute paths in the SRCROOT build setting
  Sources/TuistAutomation/ProjectMappers/SourceRootPathProjectMapper.swift
  Sources/TuistDependencies/Mappers/ExternalDependencyPathWorkspaceMapper.swift
  Sources/TuistKit/Mappers/Factories/ProjectMapperFactory.swift
  Tests/TuistAutomationTests/ProjectMappers/SourceRootPathProjectMapperTests.swift
  Tests/TuistDependenciesTests/Mappers/ExternalDependencyPathWorkspaceMapperTests.swift
  Tests/TuistKitTests/Mappers/Factories/ProjectMapperFactoryTests.swift
Labels: type:bug, changelog:fixed, size:L, lgtm

#7402 Record recent paths
  Package.resolved
  Package.swift
  Sources/TuistKit/Commands/BuildCommand.swift
  Sources/TuistKit/Commands/EditCommand.swift
  Sources/TuistKit/Commands/GenerateCommand.swift
  Sources/TuistKit/Commands/TestCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Commands/XcodeBuildCommand.swift
  Sources/TuistSupport/Utils/RecentPathRememberableCommand.swift
  Sources/TuistSupport/Utils/RecentPathsStore.swift
  Sources/TuistSupportTesting/TestCase/ServiceContext+Tests.swift
  Sources/tuist/TuistCLI.swift
  Tests/TuistLoaderTests/Loaders/Mocks/MockFileSystem.swift
  Tests/TuistSupportTests/Utils/RecentPathsStoreTests.swift
Labels: type:enhancement, changelog:added, size:L, lgtm

#7415 Fix duplicate SwiftPM resources due to different path casing
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: type:bug, changelog:fixed, size:M, lgtm

#7418 Improve tuist share CLI output
  Package.resolved
  Package.swift
  Sources/TuistCore/Analytics/RunMetadataStorage.swift
  Sources/TuistKit/Commands/ShareCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/ShareCommandService.swift
  Sources/TuistServer/Services/AnalyticsArtifactUploadService.swift
  Sources/TuistServer/Services/MultipartUploadArtifactService.swift
  Sources/TuistServer/Services/PreviewsUploadService.swift
  Sources/TuistSupportTesting/TestCase/ServiceContext+Tests.swift
  Tests/TuistKitAcceptanceTests/ShareAcceptanceTests.swift
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_ios_app_with_appclip.2.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_ios_app_with_appclip.3.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_ios_app_with_frameworks.2.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_xcode_app.1.txt
  Tests/TuistKitAcceptanceTests/__Snapshots__/ShareAcceptanceTests/test_share_xcode_app_files.1.txt
  Tests/TuistKitTests/Services/ShareCommandServiceTests.swift
  Tests/TuistKitTests/Services/__Snapshots__/ShareCommandServiceTests/test_share_app_bundles.1.txt
  Tests/TuistKitTests/Services/__Snapshots__/ShareCommandServiceTests/test_share_ipa.1.txt
  Tests/TuistKitTests/Services/__Snapshots__/ShareCommandServiceTests/test_share_tuist_project.1.txt
  Tests/TuistKitTests/Services/__Snapshots__/ShareCommandServiceTests/test_share_tuist_project_with_a_specified_app.1.txt
  Tests/TuistKitTests/Services/__Snapshots__/ShareCommandServiceTests/test_share_tuist_project_with_a_specified_appclip.1.txt
  Tests/TuistKitTests/Services/__Snapshots__/ShareCommandServiceTests/test_share_xcode_app.1.txt
  Tests/TuistServerTests/Services/AnalyticsArtifactUploadServiceTests.swift
  Tests/TuistServerTests/Services/PreviewsUploadServiceTests.swift
Labels: type:enhancement, changelog:changed, size:L, lgtm

#7375 Migration to XcodeProj 9
  Package.resolved
  Package.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Generator/ConfigGenerator.swift
  Sources/TuistGenerator/Generator/LinkGenerator.swift
  Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift
  Sources/TuistGenerator/Settings/DefaultSettingsProvider.swift
  Sources/TuistGenerator/Utils/SettingsHelper.swift
  Sources/TuistMigration/Utilities/SettingsToXCConfigExtractor.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/LinkGeneratorTests.swift
  Tests/TuistGeneratorTests/Generator/ProjectDescriptorGeneratorTests.swift
  Tests/TuistGeneratorTests/Settings/DefaultSettingsProviderTests.swift
Labels: changelog:changed, size:L, lgtm

#7420 Update previews to the latest API
  Sources/TuistKit/Services/ShareCommandService.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/GetPreviewService.swift
  Sources/TuistServer/Services/MultipartUploadStartPreviewsService.swift
  Sources/TuistServer/Services/PreviewsUploadService.swift
  Tests/TuistKitTests/Services/ShareCommandServiceTests.swift
  Tests/TuistServerTests/Services/PreviewsUploadServiceTests.swift
Labels: changelog:changed, size:L, lgtm

#7424 Track build insights for auto-generated schemes by default
  Sources/ProjectDescription/ConfigGenerationOptions.swift
  Sources/TuistCore/Models/TuistGeneratedProjectOptions.swift
  Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift
  Sources/TuistGenerator/Mappers/AutogeneratedWorkspaceSchemeWorkspaceMapper.swift
  Sources/TuistGenerator/Utils/BuildInsightsActionMapper.swift
  Sources/TuistKit/Generator/GeneratorFactory.swift
  Sources/TuistKit/Mappers/Factories/ProjectMapperFactory.swift
  Sources/TuistKit/Mappers/Factories/WorkspaceMapperFactory.swift
  Sources/TuistLoader/Models+ManifestMappers/Config+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/TuistGeneratedProject+ManifestMapper.swift
  Sources/TuistSupport/Utils/Environment.swift
  Sources/TuistSupportTesting/Utils/MockEnvironment.swift
  Tests/TuistGeneratorTests/GraphMappers/AutogeneratedWorkspaceSchemeWorkspaceMapperTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift
  Tests/TuistGeneratorTests/Utils/BuildInsightsActionMapperTests.swift
  Tests/TuistKitIntegrationTests/Commands/DumpServiceIntegrationTests.swift
  Tests/TuistKitTests/Mappers/Factories/ProjectMapperFactoryTests.swift
  Tests/TuistKitTests/Mappers/Factories/WorkspaceMapperFactoryTests.swift
  docs/docs/en/guides/develop/insights.md
  fixtures/ios_app_with_frameworks/Tuist.swift
Labels: type:enhancement, changelog:added, changelog:changed, size:XL, lgtm

#7426 Add support for macOS UI test target with bundle dependency
  Sources/TuistGenerator/Linter/GraphLinter.swift
Labels: type:enhancement, changelog:added, size:XS, lgtm

#7429 GraphLoader: ensure deterministic loading of XCTest.
  Sources/TuistCore/Graph/GraphLoader.swift
Labels: changelog:changed, size:XS, lgtm

#7435 Extract the initialization logic of ServiceContext to make it reusable
  Sources/TuistKit/Extensions/ServiceContext+Tuist.swift
  Sources/tuist/TuistCLI.swift
Labels: type:enhancement, changelog:changed, size:L, lgtm

#7434 Fix tuist init stuck on authentication
  Package.resolved
  Package.swift
  Sources/TuistKit/Services/InitCommandService.swift
  Tests/TuistKitTests/Services/InitCommandServiceTests.swift
Labels: type:bug, changelog:fixed, size:M, lgtm

#7373 Make redundant dependencies check only for local
  Sources/TuistKit/Services/Inspect/GraphImportsLinter.swift
  Tests/TuistKitTests/Services/Inspect/InspectRedundantImportsServiceTests.swift
Labels: changelog:fixed, size:M, lgtm

#7438 Disable build insights unless fullHandle is defined in Tuist.swift
  Sources/TuistCore/Models/TuistGeneratedProjectOptions.swift
  Sources/TuistLoader/Models+ManifestMappers/TuistGeneratedProject+ManifestMapper.swift
  Tests/TuistLoaderTests/Loaders/ConfigLoaderTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/TuistGeneratedProject+ManifestMapperTests.swift
Labels: type:bug, changelog:fixed, size:M, lgtm

#7441 Disable pushing build insights in projects without Tuist.swift
  Sources/TuistCore/Models/TuistGeneratedProjectOptions.swift
Labels: type:bug, changelog:fixed, size:XS, lgtm

#7443 Improve tuist registry output, fix resolving registry transitive dependencies
  Sources/TuistKit/Commands/Registry/RegistryLoginCommand.swift
  Sources/TuistKit/Commands/Registry/RegistrySetupCommand.swift
  Sources/TuistKit/Services/Registry/RegistryLoginCommandService.swift
  Sources/TuistKit/Services/Registry/RegistrySetupCommandService.swift
  Sources/TuistSupport/Utils/DefaultsController.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistKitTests/Services/Registry/RegistryLoginCommandServiceTests.swift
  Tests/TuistKitTests/Services/Registry/RegistryLoginServiceTests.swift
  Tests/TuistKitTests/Services/Registry/RegistrySetupCommandServiceTests.swift
  Tests/TuistKitTests/Services/Registry/RegistrySetupServiceTests.swift
  docs/docs/en/guides/develop/registry.md
Labels: changelog:fixed, changelog:changed, size:XL, lgtm

#7447 Fix incorrect registry CI link
  docs/docs/en/guides/develop/registry.md
Labels: changelog:fixed, size:XS
