Repository tuist/tuist, pull requests merged in 2025-01, with the labels that each got.

#7208 Update install-tuist.md, added fish completions docs
  docs/docs/en/guides/quick-start/install-tuist.md
Labels: changelog:added, size:XS, lgtm

#7212 Temporarily comment out secrets to unblock PRs from forks
  codemagic.yaml
Labels: changelog:changed, size:M

#7213 Fix inspect implicit-imports false positives for external targets
  Sources/TuistKit/Services/Inspect/InspecImplicitImportsService.swift
  Tests/TuistKitTests/Services/Inspect/InspectImplicitImportsServiceTests.swift
  fixtures/app_with_spm_dependencies/Features/FeatureOne/Project.swift
Labels: changelog:fixed, size:S, lgtm

#7211 Fix tuist generate for local SPM packages does not respect swift language mode for generated projects
  Sources/TuistLoader/SwiftPackageManager/SettingsMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/SettingsMapperTests.swift
Labels: changelog:fixed, size:S, lgtm

#7006 Embed static frameworks with bundled resources instead of generating a new bundle
  Package.resolved
  Package.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  fixtures/app_with_mac_bundle/App/Sources/ContentView.swift
  fixtures/app_with_mac_bundle/ResourcesFramework/Package.swift
  fixtures/app_with_mac_bundle/ResourcesFramework/Sources/ResourcesProvider.swift
  fixtures/app_with_mac_bundle/ResourcesFramework/Sources/Test.swift
  fixtures/app_with_mac_bundle/ResourcesFramework/Sources/demo.json
  fixtures/app_with_mac_bundle/ResourcesFramework/Sources/greeting.txt
  fixtures/ios_app_with_framework_and_resources/StaticFramework2/Sources/StaticFramework2Resources.swift
Labels: changelog:changed, size:XL, lgtm

#7186 Allow [.]mise.toml in directories targeted by 'tuist init'
  Sources/TuistKit/Services/InitService.swift
  Tests/TuistKitTests/Services/InitServiceTests.swift
Labels: changelog:changed, size:M

#7129 Improve performance of tuist graph command
  Sources/TuistKit/Services/ProjectAutomation+ManifestMapper.swift
Labels: type:enhancement, changelog:changed, size:S

#7200 Add TestableTarget.parallelization property
  Package.resolved
  Package.swift
  Sources/ProjectDescription/TestableTarget.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistLoader/Models+ManifestMappers/TestableTarget+ManifestMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  fixtures/ios_app_with_custom_scheme/App/Project.swift
Labels: type:enhancement, changelog:added, size:L, lgtm

#7216 Update outdated note about having to use SPM to run tuist
  docs/docs/en/contributors/get-started.md
Labels: changelog:changed, size:XS, lgtm

#7220 Tidy up Configuration.swift
  Sources/ProjectAutomation/Configuration.swift
Labels: size:S, lgtm

#7224 Revert "Temporarily remove comment out secrets to unblock PRs from forks (#7212)
  codemagic.yaml
Labels: changelog:changed, size:M, lgtm

#7225 Add registry support for Xcode integration of packages in Tuist Projects
  .gitignore
  Sources/ProjectDescription/Package.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistLoader/Models+ManifestMappers/Package+ManifestMapper.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  docs/docs/en/guides/develop/build/registry.md
  fixtures/.gitignore
  fixtures/app_with_registry_and_alamofire_as_xcode_package/.package.resolved
  fixtures/app_with_registry_and_alamofire_as_xcode_package/App.xcworkspace/xcshareddata/swiftpm/configuration/registries.json
  fixtures/app_with_registry_and_alamofire_as_xcode_package/App/Sources/ContentView.swift
  fixtures/app_with_registry_and_alamofire_as_xcode_package/App/Sources/MyApp.swift
  fixtures/app_with_registry_and_alamofire_as_xcode_package/Project.swift
  fixtures/app_with_registry_and_alamofire_as_xcode_package/Tuist.swift
Labels: type:enhancement, changelog:added, lgtm

#7222 Fix race condition when running multiple tuist dump commands in parallel
  Sources/TuistLoader/Loaders/CachedManifestLoader.swift
  Tests/TuistLoaderTests/Loaders/CachedManifestLoaderTests.swift
  Tests/TuistLoaderTests/Loaders/Mocks/MockFileSystem.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
Labels: changelog:fixed, size:L, lgtm

#7209 Add ability to change account username
  Sources/TuistKit/Commands/Account/AccountUpdateCommand.swift
  Sources/TuistKit/Commands/AccountCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/AccountUpdateService.swift
  Sources/TuistKit/Services/WhoamiService.swift
  Sources/TuistServer/Models/ServerAccount.swift
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/AuthTokenRefreshService.swift
  Sources/TuistServer/Services/UpdateAccountService.swift
  Sources/TuistServer/Session/ServerSessionController.swift
  Tests/TuistKitAcceptanceTests/AccountAcceptanceTests.swift
  Tests/TuistKitTests/Services/AccountUpdateServiceTests.swift
  Tests/TuistKitTests/Services/WhoamiServiceTests.swift
  Tests/TuistServerTests/Services/AuthTokenRefreshServiceTests.swift
  Tests/TuistServerTests/Session/ServerSessionControllerTests.swift
Labels: type:enhancement, changelog:added, size:XXL, lgtm

#7228 Fix flaky test_create_list_and_revoke_project_token test
  Package.resolved
  Tests/TuistKitAcceptanceTests/ProjectAcceptanceTests.swift
Labels: size:XS, lgtm

#7229 Embed prebuilt frameworks in unit test target without a host app
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistAutomationAcceptanceTests/TestAcceptanceTests.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  fixtures/multiplatform_app/.gitignore
  fixtures/multiplatform_app/Modules/App/Sources/TuistApp.swift
  fixtures/multiplatform_app/Modules/MacOSStaticFramework/Resources/logo.png
  fixtures/multiplatform_app/Modules/MacOSStaticFramework/Sources/MacOSStaticFrameworkClass.swift
  fixtures/multiplatform_app/Modules/MacOSStaticFrameworkTests/Sources/MacOSStaticFrameworkClassTests.swift
  fixtures/multiplatform_app/Modules/MultiPlatformTransitiveDynamicFramework/Sources/MultiPlatformTransitiveDynamicFrameworkClass.swift
  fixtures/multiplatform_app/Modules/WatchOSDynamicFramework/Sources/WatchOSDynamicFrameworkClass.swift
  fixtures/multiplatform_app/Modules/iOSStaticFramework/Resources/logo.png
  fixtures/multiplatform_app/Modules/iOSStaticFramework/Sources/iOSStaticFrameworkClass.swift
  fixtures/multiplatform_app/Project.swift
  fixtures/multiplatform_app/Tuist/Config.swift
Labels: type:enhancement, changelog:fixed, size:L, lgtm

#7234 Fix handling relative symbolic links
  Package.resolved
  Package.swift
  Tests/TuistLoaderTests/Loaders/Mocks/MockFileSystem.swift
Labels: type:bug, changelog:fixed, size:S, lgtm

#7233 Add command to run to authenticate in the error message when unauthenticated
  Sources/TuistServer/Client/ServerClientAuthenticationMiddleware.swift
Labels: type:enhancement, changelog:changed, size:XS, lgtm

#7232 Revert embedding static framework instead of generating a resource bundle
  Package.resolved
  Package.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistCoreTests/Graph/GraphTraverserTests.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  fixtures/app_with_pocket_svg/.gitignore
  fixtures/app_with_pocket_svg/App/Sources/AppApp.swift
  fixtures/app_with_pocket_svg/App/Sources/ContentView.swift
  fixtures/app_with_pocket_svg/App/Tests/AppTests.swift
  fixtures/app_with_pocket_svg/Project.swift
  fixtures/app_with_pocket_svg/Tuist/Config.swift
  fixtures/app_with_pocket_svg/Tuist/Package.resolved
  fixtures/app_with_pocket_svg/Tuist/Package.swift
  fixtures/app_with_sbtuitesttunnel/.gitignore
  fixtures/app_with_sbtuitesttunnel/App/Sources/ContentView.swift
  fixtures/app_with_sbtuitesttunnel/App/Sources/MyApp.swift
  fixtures/app_with_sbtuitesttunnel/App/Tests/AppTests.swift
  fixtures/app_with_sbtuitesttunnel/Project.swift
  fixtures/app_with_sbtuitesttunnel/Tuist.swift
  fixtures/app_with_sbtuitesttunnel/Tuist/Package.resolved
  fixtures/app_with_sbtuitesttunnel/Tuist/Package.swift
Labels: changelog:fixed, size:XL, lgtm

#7187 Fix issue where schemes with testplans and no explicit targets did not run any tests
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
Labels: changelog:fixed, size:L, lgtm

#7237 Rename .mise.toml to mise.toml in the project created by tuist init
  Templates/default/default.swift
  codemagic.yaml
  fixtures/app_with_revenue_cat/.mise.toml
  mise.toml
Labels: changelog:changed

#7238 Fix backwards compatibility of tuist graph --format json output
  Sources/ProjectAutomation/Configuration.swift
Labels: changelog:fixed

#7241 Fix false positive warning for external targets without sources
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift
Labels: changelog:fixed

#7245 Change tuist graph --format json output to XcodeGraph. Use tuist graph --format legacyJSON for legacy output.
  Sources/TuistKit/Commands/GraphCommand.swift
  Sources/TuistKit/Services/GraphService.swift
  Tests/TuistKitTests/Services/GraphServiceTests.swift
Labels: changelog:changed

#7273 fix: link status .none shouldn't block other dependencies from linking
  Sources/TuistGenerator/Generator/LinkGenerator.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  fixtures/ios_app_with_none_linking_status_framework/App/Sources/AppDelegate.swift
  fixtures/ios_app_with_none_linking_status_framework/Project.swift
  fixtures/ios_app_with_none_linking_status_framework/ThyFramework/Sources/ThyFramework.swift
Labels: changelog:fixed

#7028 Add support for binary targets in Package.swift
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistLoaderTests/Loaders/SwiftPackageManagerGraphLoaderTests.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
  docs/docs/en/guides/develop/projects/dependencies.md
  fixtures/app_with_spm_dependencies/Tuist/Package.resolved
  fixtures/app_with_spm_dependencies/Tuist/Package.swift
  fixtures/app_with_spm_xcframework_dependency/Project.swift
  fixtures/app_with_spm_xcframework_dependency/README.md
  fixtures/app_with_spm_xcframework_dependency/Sources/App/ContentView.swift
  fixtures/app_with_spm_xcframework_dependency/Sources/App/MyApp.swift
  fixtures/app_with_spm_xcframework_dependency/Tuist/Package.swift
Labels: changelog:added, size:L, lgtm
