Repository tuist/tuist, pull requests merged in 2025-04, with the labels that each got.

#7422 Support defining `.metal` files as sources in bundle products
  .github/workflows/release.yml
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGenerator/Extensions/Target+Extras.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Linter/TargetLinter.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift
  fixtures/generated_bundle_with_metal_files/Bundle/Sources/Bundle.swift
  fixtures/generated_bundle_with_metal_files/Bundle/Sources/Metal.metal
  fixtures/generated_bundle_with_metal_files/Project.swift
  fixtures/generated_bundle_with_metal_files/Tuist.swift
Labels: type:enhancement, changelog:changed, size:L, lgtm

#7366 Add Model Context Protocol (MCP) server via `tuist mcp` command
  Package.resolved
  Package.swift
  Sources/TuistKit/Commands/MCP/MCPSetupClaudeCommand.swift
  Sources/TuistKit/Commands/MCP/MCPSetupCommand.swift
  Sources/TuistKit/Commands/MCP/MCPStartCommand.swift
  Sources/TuistKit/Commands/MCPCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/MCP/MCPCommandService.swift
  Sources/TuistKit/MCP/MCPConfigurationFileController.swift
  Sources/TuistKit/MCP/MCPResourcesRepository.swift
  Sources/TuistKit/MCP/MCPServerCommandResolver.swift
  Sources/TuistKit/Services/MCP/MCPSetupClaudeCommandService.swift
  Sources/TuistSupport/Utils/RecentPathsStore.swift
  Tests/TuistKitTests/MCP/MCPConfigurationFileControllerTests.swift
  Tests/TuistKitTests/MCP/MCPResourcesRepositoryTests.swift
  Tests/TuistKitTests/MCP/MCPServerCommandResolverTests.swift
  Tests/TuistKitTests/Services/MCP/MCPSetupClaudeCommandServiceTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  docs/.vitepress/bars.mjs
  docs/.vitepress/icons.mjs
  docs/.vitepress/strings/en.json
  docs/docs/en/guides/ai/mcp.md
Labels: type:enhancement, changelog:added, size:XL, lgtm

#7455 fix: Fix `organization remove member` command
  Sources/TuistServer/OpenAPI/Client.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
Labels: changelog:fixed, size:M, lgtm

#7456 Fix getting the executable path from the `mcp setup claude` command
  Sources/TuistGenerator/Utils/BuildInsightsActionMapper.swift
  Sources/TuistKit/MCP/MCPServerCommandResolver.swift
  Sources/TuistSupport/Utils/Environment.swift
  Sources/TuistSupportTesting/Utils/MockEnvironment.swift
  Tests/TuistGeneratorTests/Utils/BuildInsightsActionMapperTests.swift
Labels: type:bug, changelog:fixed, size:S, lgtm

#7457 Fix the MCP command in the docs
  docs/docs/en/guides/ai/mcp.md
Labels: size:XS, lgtm

#6680 Add ability to generate a focused set of targets using tags
  Sources/ProjectDescription/Target.swift
  Sources/ProjectDescription/TargetMetadata.swift
  Sources/TuistCore/GraphTraverser/GraphTraverser+Extra.swift
  Sources/TuistCore/Models/TargetQuery.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistKit/Commands/Cache/CachePrintHashesService.swift
  Sources/TuistKit/Commands/GenerateCommand.swift
  Sources/TuistKit/Generator/GeneratorFactory.swift
  Sources/TuistKit/Mappers/Factories/GraphMapperFactory.swift
  Sources/TuistKit/Mappers/FocusTargetsGraphMappers.swift
  Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
  Sources/TuistKit/Services/GenerateService.swift
  Sources/TuistKit/Services/Inspect/InspectImplicitImportsService.swift
  Sources/TuistKit/Services/Inspect/InspectRedundantImportsService.swift
  Sources/TuistKit/Services/RunService.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Sources/TuistLoader/Utils/ProjectDescription+TestData.swift
  Tests/TuistCoreTests/Graph/GraphTraversingTests.swift
  Tests/TuistKitTests/Mappers/FocusTargetsGraphMappersTests.swift
  Tests/TuistKitTests/Services/Cache/CachePrintHashesServiceTests.swift
  Tests/TuistKitTests/Services/GenerateServiceTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectImplicitImportsServiceTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectRedundantImportsServiceTests.swift
  Tests/TuistKitTests/Services/RunServiceTests.swift
  fixtures/ios_app_with_frameworks/Project.swift
Labels: type:enhancement, changelog:added, size:L, lgtm

#7419 Fix: Local package not in project Package Dependencies
  Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift
  Tests/TuistGeneratorTests/Generator/ProjectDescriptorGeneratorTests.swift
Labels: changelog:fixed, size:L, lgtm

#7458 Fix tuist share when the bundle version is not semantic
  Sources/TuistAutomation/Utilities/AppBundle.swift
  Sources/TuistGenerator/Utils/BuildInsightsActionMapper.swift
  Sources/TuistKit/MCP/MCPServerCommandResolver.swift
  Sources/TuistSupport/Utils/Environment.swift
  Sources/TuistSupportTesting/Utils/MockEnvironment.swift
  Tests/TuistAutomationTests/Utilities/AppBundleLoaderTests.swift
  Tests/TuistKitTests/Services/ShareCommandServiceTests.swift
Labels: changelog:fixed, size:M, lgtm

#7460 Fix test plan container reference in a workspace
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistLoader/Models+ManifestMappers/TestAction+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/TestPlan+ManifestMapper.swift
  Tests/TuistAutomationAcceptanceTests/TestAcceptanceTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/TestPlan+ManifestMapperTests.swift
  fixtures/app_workspace_with_test_plan/App/AppTestPlan.xctestplan
  fixtures/app_workspace_with_test_plan/App/Project.swift
  fixtures/app_workspace_with_test_plan/App/Sources/ContentView.swift
  fixtures/app_workspace_with_test_plan/App/Sources/TuistTestExampleApp.swift
  fixtures/app_workspace_with_test_plan/App/Tests/TuistTestExampleTests.swift
  fixtures/app_workspace_with_test_plan/Tuist.swift
  fixtures/app_workspace_with_test_plan/Workspace.swift
Labels: changelog:fixed, size:L, lgtm

#7461 Ignore resources inside XCFramework in the SwiftPM XcodeProj integration
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:fixed, size:M, lgtm

#7442 Fix formatting of the synthesized resource accessor source file
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Sources/TuistGenerator/Templates/AssetsTemplate.swift
Labels: changelog:fixed, size:M, lgtm

#7463 Remove docs for Cursor MCP integration
  docs/docs/en/guides/ai/mcp.md
Labels: changelog:changed, size:M

#7462 Improve tuist run CLI output
  Sources/TuistAutomation/Utilities/AppRunner.swift
  Sources/TuistKit/Commands/RunCommand.swift
  Sources/TuistKit/Services/RunCommandService.swift
  Tests/TuistAutomationTests/Utilities/AppRunnerTests.swift
  Tests/TuistKitAcceptanceTests/ShareAcceptanceTests.swift
  Tests/TuistKitTests/Services/RunCommandServiceTests.swift
  Tests/TuistKitTests/Services/RunServiceTests.swift
Labels: type:enhancement, changelog:changed, size:XXL

#7471 Fix tree-shaking target references from test plans when selective testing
  Sources/TuistKit/Mappers/TreeShakePrunedTargetsGraphMapper.swift
  Tests/TuistKitTests/Mappers/Graph/TreeShakePrunedTargetsGraphMapperTests.swift
Labels: changelog:fixed

#7469 Efficiently precompute hash for registry dependencies
  Sources/TuistLoader/Loaders/SwiftPackageManagerGraphLoader.swift
  Sources/TuistLoader/Models/SwiftPackageManagerWorkspaceState.swift
  Tests/TuistDependenciesAcceptanceTests/DependenciesAcceptanceTests.swift
  Tests/TuistLoaderTests/Loaders/SwiftPackageManagerGraphLoaderTests.swift
Labels: changelog:fixed

#7467 Add support for selectively testing UI tests
  Sources/TuistAutomation/XcodeBuild/XcodeBuildArgumentParser.swift
  Sources/TuistCache/CacheGraphContentHasher.swift
  Sources/TuistCore/Simulator/SimulatorController.swift
  Sources/TuistHasher/GraphContentHasher.swift
  Sources/TuistHasher/TargetContentHasher.swift
  Sources/TuistKit/Commands/Cache/CachePrintHashesService.swift
  Sources/TuistKit/Generator/GeneratorFactory.swift
  Sources/TuistKit/Services/TestService.swift
  Tests/TuistAutomationTests/XcodeBuild/XcodeBuildArgumentParserTests.swift
  Tests/TuistCacheIntegrationTests/CacheGraphContentHasherIntegrationTests.swift
  Tests/TuistCacheTests/CacheGraphContentHasherTests.swift
  Tests/TuistCoreTests/Simulator/SimulatorControllerTests.swift
  Tests/TuistHasherTests/GraphContentHasherTests.swift
  Tests/TuistHasherTests/TargetContentHasherTests.swift
  Tests/TuistKitTests/Services/Cache/CachePrintHashesServiceTests.swift
  Tests/TuistKitTests/Services/TestServiceTests.swift
  docs/docs/en/guides/develop/selective-testing/generated-project.md
Labels: changelog:added

#7473 Do not output informational messages when --json is passed
  Sources/TuistKit/Extensions/ServiceContext+Tuist.swift
Labels: changelog:fixed

#7414 New Crowdin updates
  docs/.vitepress/strings/es.json
  docs/.vitepress/strings/ja.json
  docs/.vitepress/strings/ko.json
  docs/.vitepress/strings/pt.json
  docs/.vitepress/strings/ru.json
  docs/docs/es/guides/ai/mcp.md
  docs/docs/es/guides/develop/insights.md
  docs/docs/es/guides/develop/registry.md
  docs/docs/ja/guides/ai/mcp.md
  docs/docs/ja/guides/develop/insights.md
  docs/docs/ja/guides/develop/registry.md
  docs/docs/ko/guides/ai/mcp.md
  docs/docs/ko/guides/develop/cache.md
  docs/docs/ko/guides/develop/insights.md
  docs/docs/ko/guides/develop/registry.md
  docs/docs/ko/guides/quick-start/install-tuist.md
  docs/docs/ko/guides/tuist/about.md
  docs/docs/ko/index.md
  docs/docs/pt/guides/ai/mcp.md
  docs/docs/pt/guides/develop/insights.md
  docs/docs/pt/guides/develop/registry.md
  docs/docs/ru/cli/logging.md
  docs/docs/ru/guides/ai/mcp.md
  docs/docs/ru/guides/develop/insights.md
  docs/docs/ru/guides/develop/projects/cost-of-convenience.md
  docs/docs/ru/guides/develop/registry.md
Labels: size:XL

#7478 Do not remove duplicated -I "include path" parameter from OTHER_SWIFT_FLAGS
  Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift
  Tests/TuistKitTests/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapperTests.swift
Labels: changelog:fixed

#7476 Include build status in build insights
  Sources/TuistKit/Services/Inspect/InspectBuildCommandService.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/CreateBuildService.swift
  Sources/TuistSupport/XCActivityParser/XCAcitivityParser.swift
  Sources/TuistSupport/XCActivityParser/XCActivityBuildStep.swift
  Sources/TuistSupport/XCActivityParser/XCActivityLog.swift
  Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
  Tests/TuistGeneratorTests/Linter/GraphLinterTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/AutogeneratedSchemesProjectMapperTests.swift
  Tests/TuistKitTests/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapperTests.swift
  Tests/TuistKitTests/Services/GenerateServiceTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectBuildCommandServiceTests.swift
Labels: changelog:added

#7492 Ignore unused symbols in synthesized resource interface files by Periphery
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
Labels: changelog:fixed

#7493 Fix issue where targets with no sources generated an empty compile sources phase, leading to issues in watchOS apps
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
Labels: changelog:fixed

#7501 Fix missing sources build phase for some products when no build files present
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistKitAcceptanceTests/CacheAcceptanceTests.swift
Labels: changelog:fixed

#7498 Add support for tvOS bundle icon format
  Sources/TuistAutomation/Utilities/AppBundle.swift
  Sources/TuistKit/Services/ShareCommandService.swift
  Tests/TuistAutomationTests/Utilities/AppBundleLoaderTests.swift
Labels: changelog:fixed

#7507 Fix hashing of XCFrameworks with relative symlinks
  Package.resolved
  Package.swift
  Sources/TuistCore/ContentHashing/ContentHasher.swift
  Tests/TuistCoreTests/ContentHashing/ContentHasherTests.swift
Labels: changelog:fixed

#7516 Fix sending tuist xcodebuild insights
  Sources/TuistAcceptanceTesting/TuistAcceptanceTestCase.swift
  Sources/TuistKit/Commands/XcodeBuild/XcodeBuildArchiveCommand.swift
  Sources/TuistKit/Commands/XcodeBuild/XcodeBuildBuildCommand.swift
  Sources/TuistKit/Commands/XcodeBuild/XcodeBuildBuildForTestingCommand.swift
  Sources/TuistKit/Commands/XcodeBuild/XcodeBuildCommand.swift
  Sources/TuistKit/Commands/XcodeBuild/XcodeBuildTestCommand.swift
  Sources/TuistKit/Commands/XcodeBuild/XcodeBuildTestWithoutBuildingCommand.swift
  Sources/TuistKit/Services/XcodeBuild/XcodeBuildBuildCommandService.swift
  Sources/TuistKit/Services/XcodeBuild/XcodeBuildTestCommandService.swift
  Tests/TuistKitAcceptanceTests/InspectAcceptanceTests.swift
  Tests/TuistKitTests/Services/XcodeBuildTestCommandServiceTests.swift
Labels: changelog:fixed

#7479 Do not treat generated resource bundles as plugins
  Sources/TuistCore/Graph/GraphTraverser.swift
  Sources/TuistCore/Graph/ModelExtensions/Target+Core.swift
  Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/Generator/BuildPhaseGeneratorTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  fixtures/app_with_mac_bundle/App/Sources/ContentView.swift
  fixtures/app_with_mac_bundle/Project.swift
  fixtures/app_with_mac_bundle/ProjectResourcesFramework/Sources/ResourcesProvider.swift
  fixtures/app_with_mac_bundle/ProjectResourcesFramework/Sources/greeting.txt
Labels: changelog:fixed

#7490 Fix bundles including executables
  Sources/TuistAcceptanceTesting/TuistAcceptanceFixtures.swift
  Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift
  Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift
  Tests/TuistGeneratorTests/ProjectMappers/ResourcesProjectMapperTests.swift
  fixtures/generated_ios_static_library_with_string_resources/.gitignore
  fixtures/generated_ios_static_library_with_string_resources/GeneratediOSStaticLibraryWithStringResources/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  fixtures/generated_ios_static_library_with_string_resources/GeneratediOSStaticLibraryWithStringResources/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  fixtures/generated_ios_static_library_with_string_resources/GeneratediOSStaticLibraryWithStringResources/Resources/Assets.xcassets/Contents.json
  fixtures/generated_ios_static_library_with_string_resources/GeneratediOSStaticLibraryWithStringResources/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  fixtures/generated_ios_static_library_with_string_resources/GeneratediOSStaticLibraryWithStringResources/Resources/en.lproj/Localizable.strings
  fixtures/generated_ios_static_library_with_string_resources/GeneratediOSStaticLibraryWithStringResources/Sources/ContentView.swift
  fixtures/generated_ios_static_library_with_string_resources/GeneratediOSStaticLibraryWithStringResources/Sources/GeneratediOSStaticLibraryWithStringResourcesApp.swift
  fixtures/generated_ios_static_library_with_string_resources/Project.swift
  fixtures/generated_ios_static_library_with_string_resources/Tuist.swift
  fixtures/generated_ios_static_library_with_string_resources/Tuist/Package.swift
Labels: changelog:fixed

#7524 Enable testing search paths for IssueReportingTestSupport
  Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  Tests/TuistLoaderTests/SwiftPackageManager/PackageInfoMapperTests.swift
Labels: changelog:fixed

#7530 Include available organizations in tuist init
  Sources/TuistKit/Services/InitCommandService.swift
  Sources/TuistKit/Utils/InitPrompter.swift
  Tests/TuistKitTests/Services/InitCommandServiceTests.swift
Labels: changelog:changed

#7465 Embed and sign dynamic frameworks for bundle targets
  Sources/TuistCore/Graph/GraphTraverser.swift
  fixtures/macos_bundle_with_framework/Info.plist
  fixtures/macos_bundle_with_framework/Project.swift
  fixtures/macos_bundle_with_framework/Sources/App/AppDelegate.swift
  fixtures/macos_bundle_with_framework/Sources/App/main.swift
  fixtures/macos_bundle_with_framework/Sources/MyBundle/Bundle.swift
  fixtures/macos_bundle_with_framework/Sources/MyFramework/Framework.swift
  fixtures/macos_bundle_with_framework/Tuist.swift
Labels: type:enhancement, changelog:added, size:XS

#7531 Introduce `tuist hash cache` and `tuist hash selective-testing` to get the hashes for cache and selective-testing
  .github/workflows/release.yml
  BREAKME.md
  Sources/TuistAcceptanceTesting/TuistAcceptanceTestCase.swift
  Sources/TuistKit/Commands/Cache/CachePrintHashesService.swift
  Sources/TuistKit/Commands/CacheCommand.swift
  Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  Sources/TuistKit/Commands/Hash/HashCacheCommand.swift
  Sources/TuistKit/Commands/Hash/HashSelectiveTestingCommand.swift
  Sources/TuistKit/Commands/HashCommand.swift
  Sources/TuistKit/Commands/TuistCommand.swift
  Sources/TuistKit/Services/Hash/HashCacheCommandService.swift
  Sources/TuistKit/Services/Hash/HashSelectiveTestingCommandService.swift
  Sources/TuistKit/Services/TestService.swift
  Sources/TuistKit/Services/XcodeBuild/XcodeBuildTestCommandService.swift
  Tests/TuistGeneratorTests/Settings/DefaultSettingsProviderTests.swift
  Tests/TuistKitAcceptanceTests/HashAcceptanceTests.swift
  Tests/TuistKitTests/Services/Hash/HashCacheCommandServiceTests.swift
  Tests/TuistKitTests/Services/Hash/HashSelectiveTestingCommandServiceTests.swift
  Tests/TuistKitTests/Services/Hash/__Snapshots__/HashSelectiveTestingCommandServiceTests/outputsAWarning_when_generatedProject_and_noHashes.1.txt
  Tests/TuistKitTests/Services/Hash/__Snapshots__/HashSelectiveTestingCommandServiceTests/run_outputsAWarning_when_generatedProject_and_noHashes.1.txt
  Tests/TuistKitTests/Services/Hash/__Snapshots__/HashSelectiveTestingCommandServiceTests/run_outputsAWarning_when_xcodeProject_and_noHashes.1.txt
  Tests/TuistKitTests/Services/TestServiceTests.swift
  mise.toml
Labels: type:enhancement
