Repository tuist/tuist, pull requests merged in 2025-06, with the labels that each got.

#7619 Remove Codemagic from the README
  README.md
Labels: size:S, lgtm

#7613 Tuist internal test might failed depending on user system language
  Project.swift
Labels: size:XS, lgtm

#7627 Use a pool lock when running acceptance tests that require a simulator
  Sources/TuistTesting/TestCase/TestingSimulators.swift
  Sources/TuistTesting/TestCase/Traits/TuistTestFixtureTestingTrait.swift
  Sources/TuistTesting/TestCase/Traits/TuistTestMockedDependenciesTrait.swift
  Sources/TuistTesting/TestCase/TuistTest.swift
  Sources/TuistTesting/Utils/PoolLock.swift
Labels: type:enhancement, size:L, lgtm

#7614 Remove generated bundles for inspecting in implicit and redundant dependencies search
  Sources/TuistKit/Services/Inspect/GraphImportsLinter.swift
  Tests/TuistKitTests/Services/Inspect/InspectRedundantImportsServiceTests.swift
Labels: changelog:changed, size:M, lgtm

#7631 Fix sandbox failure on CI
  Sources/TuistLoader/Loaders/ManifestLoader.swift
Labels: changelog:fixed, size:XS, lgtm

#7609 Add buildOrder to Scheme's Build Action
  Sources/ProjectDescription/BuildAction.swift
  Sources/ProjectDescription/BuildOrder.swift
  Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift
  Sources/TuistLoader/Models+ManifestMappers/BuildAction+ManifestMapper.swift
  Sources/TuistLoader/Utils/ProjectDescription+TestData.swift
  Tests/TuistGeneratorTests/Generator/SchemeDescriptorsGeneratorTests.swift
  Tests/TuistLoaderTests/Extensions/TuistTestCase+ManifestMappers.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Scheme+ManifestMapper.swift
Labels: type:enhancement, changelog:added, size:M, lgtm

#7628 Remove redundant dependencies checking between App and UITest target
  Sources/TuistKit/Services/Inspect/GraphImportsLinter.swift
  Tests/TuistKitTests/Services/Inspect/InspectRedundantImportsServiceTests.swift
Labels: type:enhancement, changelog:fixed, size:M, lgtm

#7638 Ignore missing glob directory for resources and additional files
  Sources/TuistLoader/Models+ManifestMappers/CopyFileElement+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/CopyFilesAction+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/FileElement+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/ResourceFileElement+ManifestMapper.swift
  Sources/TuistLoader/Models+ManifestMappers/Target+ManifestMapper.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/CopyFileElement+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/FileElement+ManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/ResourceFileElementManifestMapperTests.swift
  Tests/TuistLoaderTests/Models+ManifestMappers/Target+ManifestMapperTests.swift
Labels: changelog:changed, size:L, lgtm

#7644 Bump noora
  Package.resolved
  Package.swift
Labels: changelog:changed, size:S, lgtm

#7647 Fix typo in docs.
  docs/docs/en/guides/develop/projects/dependencies.md
Labels: size:XS, lgtm

#7649 Fix redundant import check for UITests with host application
  Sources/TuistKit/Services/Inspect/GraphImportsLinter.swift
  Tests/TuistKitTests/Services/Inspect/InspectRedundantImportsServiceTests.swift
Labels: changelog:fixed, size:S, lgtm

#7639 Add file and module metadata to inspected builds
  Sources/TuistKit/Services/Inspect/InspectBuildCommandService.swift
  Sources/TuistServer/Models/ServerBuild.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/CreateBuildService.swift
  Sources/TuistXCActivityLog/XCActivityBuildFile.swift
  Sources/TuistXCActivityLog/XCActivityBuildStatus.swift
  Sources/TuistXCActivityLog/XCActivityLog.swift
  Sources/TuistXCActivityLog/XCActivityLogController.swift
  Sources/TuistXCActivityLog/XCActivityTarget.swift
  Tests/TuistKitAcceptanceTests/InspectAcceptanceTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectBuildCommandServiceTests.swift
  Tests/TuistXCActivityLogTests/XCActivityLog/XCActivityLogControllerTests.swift
Labels: type:enhancement, changelog:added, size:XXL, lgtm

#7653 Fix CircleCI PR variable
  Sources/TuistSupport/Utils/GitController.swift
Labels: changelog:fixed, size:XS, lgtm

#7654 Bump Rosalind
  Package.resolved
  Package.swift
Labels: changelog:changed, size:S, lgtm

#7663 Fix docs for adding a post action for build insights
  docs/docs/en/guides/develop/insights.md
Labels: size:S

#7665 Add missing post-action to relevant schemes
  Project.swift
  Sources/TuistAutomation/Utilities/TargetRunner.swift
  Sources/TuistKit/Services/BuildService.swift
  Tests/TuistAutomationTests/Utilities/TargetRunnerTests.swift
  Tests/TuistKitTests/Services/BuildServiceTests.swift
Labels: type:enhancement, size:M

#7671 Poll for the latest activity log when it's not immediately available
  Sources/TuistKit/Services/Inspect/InspectBuildCommandService.swift
  Sources/TuistSupport/Extensions/ConcurrencyExtensions.swift
  Tests/TuistKitTests/Services/Inspect/InspectBuildCommandServiceTests.swift
Labels: type:enhancement, changelog:fixed, size:L, lgtm

#7674 Attach git remote url origin metadata to the inspected build
  Package.swift
  Sources/TuistGit/GitController.swift
  Sources/TuistGit/GitInfo.swift
  Sources/TuistKit/Commands/TrackableCommand/CommandEventFactory.swift
  Sources/TuistKit/Services/Inspect/InspectBuildCommandService.swift
  Sources/TuistKit/Services/Inspect/InspectBundleCommandService.swift
  Sources/TuistLoader/Loaders/TemplateGitLoader.swift
  Sources/TuistPlugin/PluginService.swift
  Sources/TuistServer/OpenAPI/Types.swift
  Sources/TuistServer/OpenAPI/server.yml
  Sources/TuistServer/Services/CreateBuildService.swift
  Sources/TuistServer/Services/PreviewsUploadService.swift
  Sources/TuistXCActivityLog/XCActivityLogController.swift
  Tests/TuistGitTests/GitControllerTests.swift
  Tests/TuistKitTests/CommandTracking/CommandEventFactoryTests.swift
  Tests/TuistKitTests/CommandTracking/TrackableCommandTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectBuildCommandServiceTests.swift
  Tests/TuistKitTests/Services/Inspect/InspectBundleCommandServiceTests.swift
  Tests/TuistLoaderTests/Loaders/TemplateGitLoaderTests.swift
  Tests/TuistPluginTests/PluginServiceTests.swift
  Tests/TuistServerTests/PreviewsUploadServiceTests.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
Labels: type:enhancement, changelog:added, size:L, lgtm

#7677 Merge the takeaways before printing
  Sources/TuistSupport/Utils/AlertController.swift
Labels: changelog:fixed, size:XS, lgtm

#7681 Report graph and targets' binary build duration
  cli/Sources/TuistCore/Analytics/CommandEvent.swift
  cli/Sources/TuistCore/Analytics/RunCacheTargetMetadata.swift
  cli/Sources/TuistCore/Analytics/RunGraph.swift
  cli/Sources/TuistCore/Analytics/RunMetadataStorage.swift
  cli/Sources/TuistCore/Cache/CacheItem.swift
  cli/Sources/TuistKit/Commands/TrackableCommand/CommandEventFactory.swift
  cli/Sources/TuistKit/Commands/TrackableCommand/TrackableCommand.swift
  cli/Sources/TuistServer/OpenAPI/Types.swift
  cli/Sources/TuistServer/OpenAPI/server.yml
  cli/Sources/TuistServer/Services/CreateCommandEventService.swift
  cli/Tests/TuistKitTests/CommandTracking/CommandEventFactoryTests.swift
Labels: type:enhancement, changelog:added, size:XL, lgtm

#7698 Add GitHub Copilot instructions for code reviews
  .github/PULL_REQUEST_TEMPLATE.md
  .github/copilot-instructions.md
Labels: type:enhancement, size:M, lgtm

#7690 feat: optimize download of previews, support grouped previews
  .gitignore
  CLAUDE.md
  Tuist/ProjectDescriptionHelpers/Module.swift
  app/Project.swift
  app/Resources/TuistApp/Assets.xcassets/AppIconPlaceholder.imageset/AppIconPlaceholder.svg
  app/Resources/TuistApp/Assets.xcassets/AppIconPlaceholder.imageset/Contents.json
  app/Resources/TuistApp/Assets.xcassets/MenuBarIcon.imageset/Contents.json
  app/Resources/TuistApp/Assets.xcassets/MenuBarIcon.imageset/Tuist-Filled.png
  app/Resources/TuistApp/Assets.xcassets/MenuBarIcon.imageset/Tuist-Filled@2x.png
  app/Resources/TuistApp/Assets.xcassets/MenuBarIcon.imageset/Tuist-Filled@3x.png
  app/Sources/TuistMenuBar/Extensions/DestinationType+Extras.swift
  app/Sources/TuistMenuBar/Services/DeviceService.swift
  app/Sources/TuistMenuBar/Views/AppPreviews/AppPreview.swift
  app/Sources/TuistMenuBar/Views/AppPreviews/AppPreviewsViewModel.swift
  app/Sources/TuistMenuBar/Views/DevicesView/DevicesViewModel.swift
  app/Sources/TuistMenuBar/Views/SimulatorRow/SimulatorRow.swift
  app/Tests/TuistMenuBarTests/Services/AppCredentialsServiceTests.swift
  app/Tests/TuistMenuBarTests/Services/DeviceServiceTests.swift
  app/Tests/TuistMenuBarTests/ViewModels/AppPreviewsViewModelTests.swift
  app/Tests/TuistMenuBarTests/ViewModels/DevicesViewModelTests.swift
  app/Tests/TuistMenuBarTests/ViewModels/SimulatorRowViewModelTests.swift
  cli/Sources/TuistAutomation/Utilities/AppBundleLoader.swift
  cli/Sources/TuistAutomation/Utilities/AppRunner.swift
  cli/Sources/TuistCore/Simulator/SimulatorRuntime.swift
  cli/Sources/TuistKit/Commands/RunCommand.swift
  cli/Sources/TuistKit/Services/RunCommandService.swift
  cli/Sources/TuistKit/Services/ShareCommandService.swift
  cli/Sources/TuistServer/Client/ServerAuthenticationController.swift
  cli/Sources/TuistServer/Models/AppBuild.swift
  cli/Sources/TuistServer/Models/AppBuildUpload.swift
  cli/Sources/TuistServer/Models/DestinationType+PreviewSupportedPlatform.swift
  cli/Sources/TuistServer/Models/Preview.swift
  cli/Sources/TuistServer/OpenAPI/Types.swift
  cli/Sources/TuistServer/OpenAPI/server.yml
  cli/Sources/TuistServer/Services/GetPreviewService.swift
  cli/Sources/TuistServer/Services/MultipartUploadCompletePreviewsService.swift
  cli/Sources/TuistServer/Services/MultipartUploadGenerateURLPreviewsService.swift
  cli/Sources/TuistServer/Services/MultipartUploadStartPreviewsService.swift
  cli/Sources/TuistServer/Services/PreviewsUploadService.swift
  cli/Sources/TuistSimulator/DestinationType.swift
  cli/Tests/Fixtures/App.ipa
  cli/Tests/TuistAutomationTests/Utilities/AppBundleLoaderTests.swift
  cli/Tests/TuistAutomationTests/Utilities/AppRunnerTests.swift
  cli/Tests/TuistKitTests/Services/RunCommandServiceTests.swift
  cli/Tests/TuistKitTests/Services/ShareCommandServiceTests.swift
  cli/Tests/TuistServerTests/PreviewsUploadServiceTests.swift
  cli/Tests/TuistServerTests/Utilities/ServerAuthenticationControllerTests.swift
  mise/tasks/bundle/app
  mise/tasks/workspace/generate/server-openapi-code
Labels: type:enhancement, changelog:changed, size:XL, lgtm

#7704 Add penetration testing policy to security handbook
  handbook/CLAUDE.md
  handbook/handbook/security/secure-development-and-operations/penetration-testing-policy.md
Labels: size:L, security, lgtm

#7706 Ensure .env.json is available when releasing the Tuist macOS app
  .github/workflows/release.yml
Labels: size:XS

#7711 Fix release failing due to branch protections
  .github/workflows/release.yml
Labels: size:S

#7716 chore: change TuistApp product name in debug
  .github/workflows/app.yml
  .swiftformat
  app/Project.swift
  cli/Sources/TuistKit/Services/ShareCommandService.swift
Labels: size:S, lgtm

#7719 Fix uploading .ipa icon
  cli/Sources/TuistServer/Services/PreviewsUploadService.swift
  cli/Tests/TuistServerTests/PreviewsUploadServiceTests.swift
Labels: type:bug, changelog:fixed, size:S, domain:previews, lgtm

#7721 Add acceptance tests for sharing .ipa
  cli/Sources/TuistTesting/Utils/SwiftTestingHelper.swift
  cli/Tests/TuistKitAcceptanceTests/ShareAcceptanceTests.swift
  mise/tasks/cli/lint.sh
Labels: type:enhancement, size:M, lgtm

#7724 fix: disable Debug executable for Manifests scheme
  cli/Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift
Labels: changelog:fixed, size:XS, lgtm

#7726 Add Sajda app logo to README.md
  README.md
  assets/companies/sajda_app.svg
Labels: size:XS, lgtm

#7736 fix: Update documentation link to point to correct URL
  cli/Sources/ProjectDescription/TargetDependency.swift
Labels: size:XS, domain:docs, lgtm

#7735 Fix generation failing due to missing SwiftPM binary artifact
  cli/Sources/TuistGenerator/Mappers/AutogeneratedWorkspaceSchemeGraphMapper.swift
  cli/Sources/TuistKit/Mappers/Factories/GraphMapperFactory.swift
  cli/Sources/TuistKit/Mappers/Factories/WorkspaceMapperFactory.swift
  cli/Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  cli/Tests/TuistGeneratorTests/GraphMappers/AutogeneratedWorkspaceSchemeWorkspaceMapperTests.swift
  cli/Tests/TuistKitTests/Mappers/Factories/WorkspaceMapperFactoryTests.swift
Labels: changelog:fixed, domain:generated-projects, size:XL, lgtm

#7738 fix: SWIFT_OPTIMIZATION_LEVEL-O not -Owholemodule
  Package.resolved
  Package.swift
  cli/Tests/TuistGeneratorTests/Generator/ConfigGeneratorTests.swift
  cli/Tests/TuistGeneratorTests/Settings/DefaultSettingsProviderTests.swift
Labels: changelog:fixed, size:S, lgtm

#7749 Add .extensionKitExtension to canEmbedBundles valid products list
  cli/Sources/TuistCore/Graph/GraphTraverser.swift
Labels: type:enhancement, size:XS, lgtm

#7739 feat: add inspect option to allow to ignore targets with given tag during redundant dependencies inspection
  cli/Fixtures/ios_app_with_implicit_dependencies/Project.swift
  cli/Fixtures/ios_app_with_implicit_dependencies/Tuist.swift
  cli/Fixtures/ios_app_with_implicit_dependencies/Tuist/Config.swift
  cli/Sources/ProjectDescription/ConfigInspectOptions.swift
  cli/Sources/ProjectDescription/Tuist.swift
  cli/Sources/TuistCore/Models/Tuist.swift
  cli/Sources/TuistCore/Models/TuistGeneratedProjectOptions.swift
  cli/Sources/TuistKit/Services/Inspect/GraphImportsLinter.swift
  cli/Sources/TuistKit/Services/Inspect/InspectImplicitImportsService.swift
  cli/Sources/TuistKit/Services/Inspect/InspectRedundantImportsService.swift
  cli/Sources/TuistLoader/Loaders/ConfigLoader.swift
  cli/Sources/TuistLoader/Models+ManifestMappers/Tuist+ManifestMapper.swift
  cli/Tests/TuistKitTests/Commands/DumpServiceIntegrationTests.swift
  cli/Tests/TuistKitTests/Services/Inspect/InspectRedundantImportsServiceTests.swift
  cli/Tests/TuistLoaderTests/Loaders/ConfigLoaderTests.swift
Labels: type:enhancement, changelog:added, size:L, lgtm

#7757 Fix `tuist inspect redundant-import` check when `watchApp` depends on `watchAppExtension`
  cli/Sources/TuistKit/Services/Inspect/GraphImportsLinter.swift
  cli/Tests/TuistKitTests/Services/Inspect/InspectRedundantImportsServiceTests.swift
Labels: changelog:fixed, size:M, lgtm
