Repository tuist/tuist, pull requests merged in 2025-07, with the labels that each got.

#7740 feat: decouple CLI credentials from the menu bar credentials
  Package.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  app/Project.swift
  app/Resources/TuistApp/Assets.xcassets/TuistIcon.imageset/Contents.json
  app/Resources/TuistApp/Assets.xcassets/TuistIcon.imageset/icon_128x128.png
  app/Resources/TuistApp/Assets.xcassets/TuistIcon.imageset/icon_128x128@2x.png
  app/Resources/TuistApp/Assets.xcassets/TuistIcon.imageset/icon_256x256.png
  app/Sources/TuistApp/AuthenticationService.swift
  app/Sources/TuistApp/TuistApp.swift
  app/Sources/TuistAppStorage/AppStorage.swift
  app/Sources/TuistAuthentication/AuthenticationService.swift
  app/Sources/TuistAuthentication/AuthenticationState.swift
  app/Sources/TuistMenuBar/Models/AuthenticationState.swift
  app/Sources/TuistMenuBar/Services/AppCredentialsService.swift
  app/Sources/TuistMenuBar/Services/DeviceService.swift
  app/Sources/TuistMenuBar/Services/ServerURLService.swift
  app/Sources/TuistMenuBar/Views/AppPreviews/AppPreviews.swift
  app/Sources/TuistMenuBar/Views/AppPreviews/AppPreviewsViewModel.swift
  app/Sources/TuistMenuBar/Views/DevicesView/DevicesViewModel.swift
  app/Sources/TuistMenuBar/Views/MenuBarLoginView.swift
  app/Sources/TuistMenuBar/Views/MenuBarView/MenuBarView.swift
  app/Sources/TuistOnboarding/LogInView.swift
  app/Tests/TuistMenuBarTests/Services/AppCredentialsServiceTests.swift
  app/Tests/TuistMenuBarTests/Services/DeviceServiceTests.swift
  app/Tests/TuistMenuBarTests/ViewModels/AppPreviewsViewModelTests.swift
  app/Tests/TuistMenuBarTests/ViewModels/DevicesViewModelTests.swift
  cli/Sources/TuistKit/Services/LoginService.swift
  cli/Sources/TuistKit/Utils/Dependencies.swift
  cli/Sources/TuistServer/Client/ServerAuthenticationController.swift
  cli/Sources/TuistServer/Client/ServerSessionController.swift
  cli/Sources/TuistServer/OpenAPI/server.yml
  cli/Sources/TuistServer/Services/ServerEnvironmentService.swift
  cli/Sources/TuistServer/Utilities/CachedValueStore.swift
  cli/Sources/TuistServer/Utilities/JWT.swift
  cli/Sources/TuistServer/Utilities/ServerCredentialsStore.swift
  cli/Sources/TuistTesting/TestCase/TuistTest.swift
  cli/Tests/TuistKitTests/Services/LoginServiceTests.swift
  cli/Tests/TuistServerTests/Session/ServerSessionControllerTests.swift
  cli/Tests/TuistServerTests/Utilities/ServerAuthenticationControllerTests.swift
  cli/Tests/TuistServerTests/Utilities/ServerCredentialsStoreTests.swift
Labels: size:XXL

#7762 ci: fix mise version when releasing app
  .github/workflows/release.yml
Labels: changelog:fixed, size:XS

#7764 Fix missing Noora output in log files
  cli/Sources/TuistKit/Commands/TuistCommand.swift
  cli/Sources/TuistKit/Utils/Dependencies.swift
Labels: type:bug, changelog:fixed, size:M, lgtm

#7766 Fix building iOS app
  cli/Sources/TuistServer/Client/ServerAuthenticationController.swift
  cli/Sources/TuistServer/Utilities/CachedValueStore.swift
Labels: changelog:fixed, size:S

#7771 Update macOS provisioning profile
  .optional.env.json
Labels: size:XS

#7775 fix: clear credentials on authentication failure
  app/Sources/TuistMenuBar/Utilities/ErrorHandling.swift
Labels: changelog:fixed, size:XS, lgtm, domain:app

#7776 fix: don't show error when cancelling authentication
  app/Sources/TuistAuthentication/AuthenticationService.swift
Labels: changelog:fixed, size:XS, lgtm

#7778 fix: released app missing staple
  .github/workflows/release.yml
  .optional.env.json
  mise/tasks/app/bundle.sh
Labels: type:bug, changelog:fixed, size:S, security

#7779 Upgrade XCLogParser to fix parsing some activity logs
  Package.resolved
  Package.swift
  app/Sources/TuistAuthentication/AuthenticationService.swift
Labels: changelog:fixed

#7781 feat: iOS app launch screen
  app/Project.swift
  app/Resources/TuistApp/Assets.xcassets/LaunchScreenBackground.imageset/Contents.json
  app/Resources/TuistApp/Assets.xcassets/LaunchScreenBackground.imageset/LaunchScreenBackground.png
  app/Resources/TuistApp/Assets.xcassets/LaunchScreenBackground.imageset/LaunchScreenBackground@2x.png
  app/Resources/TuistApp/Assets.xcassets/LaunchScreenBackground.imageset/LaunchScreenBackground@3x.png
  app/Resources/TuistApp/Assets.xcassets/TuistRoundedIcon.imageset/Contents.json
  app/Resources/TuistApp/Assets.xcassets/TuistRoundedIcon.imageset/TuistRoundedIcon.png
  app/Resources/TuistApp/Assets.xcassets/TuistRoundedIcon.imageset/TuistRoundedIcon@2x.png
  app/Resources/TuistApp/Assets.xcassets/TuistRoundedIcon.imageset/TuistRoundedIcon@3x.png
  app/Resources/TuistApp/iOS/LaunchScreen.storyboard
Labels: type:enhancement, changelog:added, size:L, lgtm

#7790 Add version as part of the preview server schema
  server/lib/tuist_web/api/schemas/preview.ex
  server/lib/tuist_web/controllers/api/previews_controller.ex
  server/test/tuist_web/controllers/api/previews_controller_test.exs
Labels: type:enhancement, changelog:added, size:M, domain:previews, lgtm

#7797 Improve keyboard flow on authentication pages
  server/lib/tuist_web/live/user_login_live.ex
  server/lib/tuist_web/live/user_registration_live.ex
  server/mix.exs
  server/mix.lock
Labels: type:enhancement, size:S, lgtm, server

#7798 Fix CI failures
  server/lib/tuist_web/live/user_login_live.ex
  server/lib/tuist_web/live/user_registration_live.ex
  server/priv/gettext/default.pot
Labels: size:M, server

#7791 Migrate CommandEvents to UUID primary key
  server/lib/tuist/command_events.ex
  server/lib/tuist/command_events/event.ex
  server/lib/tuist/command_events/test_case_run.ex
  server/lib/tuist/xcode/clickhouse.ex
  server/lib/tuist/xcode/clickhouse/xcode_graph.ex
  server/lib/tuist/xcode/clickhouse/xcode_target_denormalized.ex
  server/lib/tuist/xcode/postgres/xcode_graph.ex
  server/lib/tuist_web/api/schemas/command_event.ex
  server/lib/tuist_web/controllers/api/analytics_controller.ex
  server/lib/tuist_web/controllers/api/runs_controller.ex
  server/lib/tuist_web/controllers/runs_controller.ex
  server/lib/tuist_web/live/layout_live.ex
  server/lib/tuist_web/plugs/loader_plug.ex
  server/priv/click_house_repo/migrations/20250701125026_update_clickhouse_xcode_graph_command_event_id_to_string.exs
  server/priv/click_house_repo/migrations/20250702083709_update_xcode_targets_denormalized_view_types.exs
  server/priv/gettext/default.pot
  server/priv/repo/migrations/20250623090458_drop_xcode_tables.exs
  server/priv/repo/migrations/20250625090000_migrate_command_events_to_uuid_primary_key.exs
  server/priv/repo/seeds.exs
  server/test/support/tuist_test_support/fixtures/command_events_fixtures.ex
  server/test/support/tuist_test_support/fixtures/xcode_fixtures.ex
  server/test/tuist/command_events/test_case_run_test.exs
  server/test/tuist/command_events_test.exs
  server/test/tuist/xcode/postgres/xcode_graph_test.exs
  server/test/tuist/xcode_test.exs
  server/test/tuist_web/controllers/analytics_controller_test.exs
  server/test/tuist_web/controllers/api/runs_controller_test.exs
  server/test/tuist_web/controllers/runs_controller_test.exs
  server/test/tuist_web/live/run_detail_live_test.exs
  server/test/tuist_web/plugs/loader_plug_test.exs
Labels: type:enhancement, changelog:changed, size:XXL, lgtm, server

#7795 Remove extraenous secret file
  mise/tasks/env/edit.sh
  mise/tasks/env/encrypt.sh
  mise/tasks/server/env/edit.sh
  mise/tasks/server/env/encrypt.sh
  server/.env.dev.json
Labels: size:M, lgtm

#7801 Fix the number of the cycles
  handbook/handbook/company/6-week-cycles.md
Labels: size:S, lgtm

#7804 Fix mise install in acceptance tests
  .github/workflows/server-production-deployment.yml
Labels: size:XS, lgtm

#7802 Fix incorrect Target initialization syntax in documentation
  cli/Sources/ProjectDescription/Project.swift
  docs/docs/en/guides/features/registry/generated-project.md
Labels: size:S, domain:docs, lgtm

#7805 Fix server CLA
  .github/workflows/server-cla.yml
Labels: changelog:fixed, size:XS, lgtm

#7800 feat: implement profile
  app/Sources/TuistApp/TuistApp.swift
  app/Sources/TuistAuthentication/AuthenticationService.swift
  app/Sources/TuistAuthentication/AuthenticationState.swift
  app/Sources/TuistMenuBar/Views/MenuBarView/MenuBarView.swift
  app/Sources/TuistNoora/NooraAvatar.swift
  app/Sources/TuistProfile/ExternalLinkRow.swift
  app/Sources/TuistProfile/ProfileView.swift
  cli/Sources/TuistServer/OpenAPI/Types.swift
  cli/Sources/TuistServer/OpenAPI/server.yml
Labels: type:enhancement, size:L, lgtm

#7810 ci: add script to upload the iOS app to App Store Connect
  .github/workflows/app-release.yml
  app/Project.swift
  app/Sources/TuistPreviews/PreviewsView/PreviewsViewModel.swift
  mise/tasks/app/upload-ios.sh
Labels: size:L, lgtm

#7811 Fix CLA workflow branch protection issue
  .github/workflows/server-cla.yml
Labels: changelog:fixed, size:XS, lgtm

#7820 feat: use deviceURL instead of itms scheme to install previews
  app/Sources/TuistPreviews/PreviewRunButton.swift
  cli/Sources/TuistServer/Models/ServerPreview.swift
  cli/Sources/TuistServer/OpenAPI/Types.swift
  cli/Sources/TuistServer/OpenAPI/server.yml
  server/lib/tuist_web/api/schemas/preview.ex
  server/lib/tuist_web/controllers/api/previews_controller.ex
  server/test/tuist_web/controllers/api/previews_controller_test.exs
Labels: type:enhancement, changelog:changed, size:M, domain:previews, lgtm

#7821 docs: add note about Objective-C resource accessor limitation
  docs/docs/en/guides/features/projects/synthesized-files.md
Labels: size:XS, domain:docs, lgtm

#7817 Remove the environment from the server CLA pipeline
  .github/workflows/server-cla.yml
Labels: size:XS

#7822 ci: fix app release
  .github/workflows/app-release.yml
Labels: size:XS

#7759 Migrate command events to use UUIDs
  Package.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  cli/Sources/TuistServer/Models/ServerCommandEvent.swift
  cli/Sources/TuistServer/OpenAPI/Types.swift
  cli/Sources/TuistServer/OpenAPI/server.yml
  cli/Sources/TuistServer/Services/AnalyticsArtifactUploadService.swift
  cli/Sources/TuistServer/Services/CompleteAnalyticsArtifactsUploads.swift
  cli/Sources/TuistServer/Services/MultipartUploadCompleteAnalyticsService.swift
  cli/Sources/TuistServer/Services/MultipartUploadGenerateURLAnalyticsService.swift
  cli/Sources/TuistServer/Services/MultipartUploadStartAnalyticsService.swift
  cli/Tests/TuistKitTests/Utils/TuistAnalyticsDispatcherTests.swift
  cli/Tests/TuistKitTests/Utils/TuistAnalyticsServerBackendTests.swift
  cli/Tests/TuistServerTests/AnalyticsArtifactUploadServiceTests.swift
Labels: type:enhancement, changelog:changed, size:L, lgtm, domain:cli

#7829 feat: remove run button when a preview can't be run
  app/Sources/TuistPreviews/PreviewRunButton.swift
Labels: size:S

#7793 Migrate CommandEvents to Clickhouse
  mise/tasks/server/clickhouse/start.sh
  server/lib/tuist.ex
  server/lib/tuist/accounts.ex
  server/lib/tuist/authorization.ex
  server/lib/tuist/command_events.ex
  server/lib/tuist/command_events/clickhouse.ex
  server/lib/tuist/command_events/clickhouse/event.ex
  server/lib/tuist/command_events/postgres.ex
  server/lib/tuist/command_events/postgres/event.ex
  server/lib/tuist/command_events/test_case_run.ex
  server/lib/tuist/ops/daily_slack_report_worker.ex
  server/lib/tuist/projects.ex
  server/lib/tuist/runs.ex
  server/lib/tuist/runs/analytics.ex
  server/lib/tuist/runs/build.ex
  server/lib/tuist/runs/build_target.ex
  server/lib/tuist/xcode/clickhouse.ex
  server/lib/tuist/xcode/postgres.ex
  server/lib/tuist/xcode/postgres/xcode_graph.ex
  server/lib/tuist_web/authorization.ex
  server/lib/tuist_web/components/runs/ran_by_badge.ex
  server/lib/tuist_web/controllers/api/account_controller.ex
  server/lib/tuist_web/controllers/api/analytics_controller.ex
  server/lib/tuist_web/controllers/api/runs_controller.ex
  server/lib/tuist_web/live/build_run_live.ex
  server/lib/tuist_web/live/build_run_live.html.heex
  server/lib/tuist_web/live/builds_live.ex
  server/lib/tuist_web/live/cache_runs_live.ex
  server/lib/tuist_web/live/cache_runs_live.html.heex
  server/lib/tuist_web/live/generate_runs_live.ex
  server/lib/tuist_web/live/generate_runs_live.html.heex
  server/lib/tuist_web/live/overview_live.ex
  server/lib/tuist_web/live/run_detail_live.ex
  server/lib/tuist_web/live/run_detail_live.html.heex
  server/lib/tuist_web/live/test_runs_live.ex
  server/lib/tuist_web/live/test_runs_live.html.heex
  server/lib/tuist_web/plugs/loader_plug.ex
  server/priv/click_house_repo/migrations/20250702083710_create_command_events_clickhouse.exs
  server/priv/click_house_repo/migrations/20250708112228_make_command_events_legacy_id_serial.exs
  server/priv/repo/seeds.exs
  server/test/tuist/accounts/workers/update_account_usage_worker_test.exs
  server/test/tuist/accounts_test.exs
  server/test/tuist/command_events/clickhouse/event_test.exs
  server/test/tuist/command_events/postgres/event_test.exs
  server/test/tuist/command_events_test.exs
  server/test/tuist/xcode_test.exs
  server/test/tuist_web/controllers/analytics_controller_test.exs
  server/test/tuist_web/controllers/api/account_controller_test.exs
  server/test/tuist_web/live/cache_runs_live_test.exs
  server/test/tuist_web/live/generate_runs_live_test.exs
  server/test/tuist_web/live/run_detail_live_test.exs
  server/test/tuist_web/live/test_runs_live_test.exs
  server/test/tuist_web/plugs/loader_plug_test.exs
Labels: type:enhancement, changelog:changed, size:XXL, lgtm, server

#7831 Increase timeout on Xcode graph insertion
  server/lib/tuist/xcode/clickhouse.ex
Labels: type:enhancement, changelog:changed, size:S, lgtm

#7832 Make Mautic sync more robust
  server/.credo.exs
  server/lib/tuist/mautic.ex
  server/lib/tuist/mautic/workers/sync_companies_and_contacts_worker.ex
Labels: changelog:fixed, size:S, lgtm

#7834 Improve command events queries for Clickhouse
  server/lib/tuist/command_events/clickhouse.ex
  server/lib/tuist/command_events/clickhouse/event.ex
  server/lib/tuist/command_events/postgres.ex
  server/lib/tuist/command_events/postgres/event.ex
  server/lib/tuist/runs.ex
  server/priv/click_house_repo/migrations/20250715093853_add_performance_indexes_and_computed_columns.exs
  server/test/tuist/xcode_test.exs
Labels: type:enhancement, changelog:changed, size:L, lgtm

#7837 Improve indexes and add projection for CommandEvents
  server/priv/click_house_repo/migrations/20250715155316_optimize_command_events_indexes_and_add_projection.exs
Labels: type:enhancement, changelog:added, size:L, lgtm

#7839 feat: support page
  server/assets/marketing/css/pages.css
  server/assets/marketing/css/pages/support.css
  server/config/config.exs
  server/lib/tuist_web/marketing/controllers/marketing_controller.ex
  server/lib/tuist_web/marketing/controllers/marketing_html/support.html.heex
  server/lib/tuist_web/router.ex
Labels: type:enhancement, changelog:added, size:L, lgtm

#7841 Update ordering key of Clickhouse CommandEvents
  server/lib/tuist/command_events/clickhouse.ex
  server/lib/tuist/command_events/clickhouse/event.ex
  server/lib/tuist/vcs.ex
  server/priv/click_house_repo/migrations/20250715193142_change_command_events_primary_key.exs
Labels: type:enhancement, changelog:changed, size:L, lgtm

#7843 chore: improve server seed performance
  server/priv/repo/seeds.exs
Labels: type:enhancement, changelog:changed, size:L, lgtm

#7825 Do not use globbing for paths that are not look like globs
  cli/Sources/TuistLoader/Models+ManifestMappers/TargetAction+ManifestMapper.swift
  cli/Sources/TuistLoader/Models/FileSysteming+Glob.swift
  cli/Tests/TuistLoaderTests/Models+ManifestMappers/TargetScript+ManifestMapperTests.swift
Labels: type:enhancement, changelog:changed, size:M, lgtm

#7833 feat: add blog post about Elixir and Tuist's server architecture
  server/priv/marketing/blog/2025/07/15/elixir.md
Labels: size:L, lgtm

#7845 Fix billing worker
  server/lib/tuist/command_events/clickhouse.ex
  server/test/tuist/accounts_test.exs
Labels: type:bug, changelog:fixed, size:L, lgtm

#7819 fix: add support for Swift interoperabilityMode setting
  Package.resolved
  Package.swift
  cli/Fixtures/ios_app_with_cplusplus_interoperability/.gitignore
  cli/Fixtures/ios_app_with_cplusplus_interoperability/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  cli/Fixtures/ios_app_with_cplusplus_interoperability/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  cli/Fixtures/ios_app_with_cplusplus_interoperability/App/Resources/Assets.xcassets/Contents.json
  cli/Fixtures/ios_app_with_cplusplus_interoperability/App/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  cli/Fixtures/ios_app_with_cplusplus_interoperability/App/Sources/AppApp.swift
  cli/Fixtures/ios_app_with_cplusplus_interoperability/App/Sources/ContentView.swift
  cli/Fixtures/ios_app_with_cplusplus_interoperability/App/Tests/AppTests.swift
  cli/Fixtures/ios_app_with_cplusplus_interoperability/Project.swift
  cli/Fixtures/ios_app_with_cplusplus_interoperability/README.md
  cli/Fixtures/ios_app_with_cplusplus_interoperability/Tuist.swift
  cli/Fixtures/ios_app_with_cplusplus_interoperability/Tuist/Package.resolved
  cli/Fixtures/ios_app_with_cplusplus_interoperability/Tuist/Package.swift
  cli/Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift
  cli/Sources/TuistLoader/SwiftPackageManager/SettingsMapper.swift
  cli/Tests/TuistAutomationAcceptanceTests/BuildAcceptanceTests.swift
  cli/Tests/TuistLoaderTests/SwiftPackageManager/SettingsMapperTests.swift
Labels: type:enhancement, size:L, domain:dependencies, lgtm

#7851 Rework runs analytics
  server/lib/tuist/command_events.ex
  server/lib/tuist/command_events/clickhouse.ex
  server/lib/tuist/command_events/postgres.ex
  server/lib/tuist/runs/analytics.ex
  server/lib/tuist_web/live/overview_live.ex
Labels: type:enhancement, size:XL, lgtm

#7854 Move more analytics aggregates to Clickhouse
  server/lib/tuist/command_events.ex
  server/lib/tuist/command_events/clickhouse.ex
  server/lib/tuist/command_events/postgres.ex
  server/lib/tuist/runs.ex
  server/lib/tuist/runs/analytics.ex
  server/lib/tuist_web/live/builds_live.ex
  server/lib/tuist_web/live/overview_live.ex
  server/test/tuist/command_events_test.exs
  server/test/tuist/runs/analytics_test.exs
  server/test/tuist/runs_test.exs
Labels: type:enhancement, changelog:changed, size:XL, lgtm

#7863 Fix regression from #7854
  server/lib/tuist/command_events/clickhouse.ex
  server/test/tuist/command_events_test.exs
Labels: changelog:fixed, size:L, lgtm

#7864 Fix token refresh crashing
  server/lib/tuist/authentication.ex
  server/test/tuist_web/controllers/api/auth_controller_test.exs
Labels: changelog:fixed, size:S, lgtm

#7866 Send telemetry around failing token refreshes
  docs/docs/en/guides/server/self-host/telemetry.md
  server/lib/tuist/analytics.ex
  server/lib/tuist/authentication.ex
  server/lib/tuist/authentication/prom_ex_plugin.ex
  server/lib/tuist/prom_ex.ex
  server/lib/tuist_web/controllers/api/auth_controller.ex
  server/lib/tuist_web/headers.ex
  server/test/tuist/xcode_test.exs
  server/test/tuist_web/controllers/api/auth_controller_test.exs
Labels: type:enhancement, size:L, lgtm

#7878 Normalize secrets handling to use string keys consistently
  CLAUDE.md
  server/config/test.exs
  server/lib/tuist/environment.ex
  server/test/tuist/environment_test.exs
  server/test/tuist/xcode_test.exs
Labels: type:enhancement, changelog:changed, size:L, lgtm

#7881 Sanitize user handles from special characters in email addresses
  server/lib/tuist/accounts.ex
  server/test/tuist/accounts_test.exs
Labels: type:enhancement, changelog:added, size:L, lgtm

#7884 Fix PromEx ETS flush timeout
  server/config/runtime.exs
Labels: changelog:fixed, size:XS, lgtm

#7861 Add a card to project overview that shows the build time saved
  CLAUDE.md
  docs/docs/en/guides/features/projects/best-practices.md
  server/assets/app/app.css
  server/assets/app/css/pages/overview.css
  server/lib/tuist/runs/analytics.ex
  server/lib/tuist/utilities/date_formatter.ex
  server/lib/tuist_web/components/app_components.ex
  server/lib/tuist_web/live/overview_live.ex
  server/lib/tuist_web/live/overview_live.html.heex
  server/mix.exs
  server/mix.lock
  server/priv/repo/seeds.exs
  server/test/support/tuist_test_support/fixtures/xcode_fixtures.ex
  server/test/test_helper.exs
  server/test/tuist/runs/analytics_test.exs
  server/test/tuist_web/utilities/date_formatter_test.exs
Labels: type:enhancement, changelog:added, size:XL, domain:dashboard, lgtm

#7889 Remove legacy artifact path handling
  server/lib/tuist/command_events.ex
  server/lib/tuist/command_events/clickhouse/event.ex
  server/lib/tuist/command_events/postgres/event.ex
  server/priv/click_house_repo/migrations/20250721130110_drop_legacy_artifact_path_column.exs
  server/priv/repo/migrations/20250721130110_drop_legacy_artifact_path_column.exs
Labels: type:enhancement, changelog:changed, size:M, lgtm

#7903 fix(server): cache hits count
  server/lib/tuist/command_events.ex
  server/lib/tuist/command_events/clickhouse.ex
  server/lib/tuist/command_events/clickhouse/event.ex
  server/lib/tuist/command_events/postgres.ex
  server/lib/tuist/command_events/postgres/event.ex
  server/lib/tuist_web/controllers/apple_app_site_association_controller.ex
  server/lib/tuist_web/live/billing_live.ex
  server/lib/tuist_web/live/overview_live.ex
  server/lib/tuist_web/live/overview_live.html.heex
  server/test/support/tuist_test_support/fixtures/command_events_fixtures.ex
  server/test/tuist/accounts/workers/update_all_accounts_usage_worker_test.exs
  server/test/tuist/command_events/postgres/event_test.exs
  server/test/tuist/command_events_test.exs
Labels: type:bug, size:L, domain:cache, lgtm

#7908 fix(server): billing date
  server/lib/tuist_web/live/billing_live.ex
  server/lib/tuist_web/live/billing_live.html.heex
  server/test/tuist_web/live/billing_live_test.exs
Labels: size:S, lgtm

#7907 fix(cli): token refresh race condition
  Package.resolved
  Package.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
  app/Sources/TuistAuthentication/AuthenticationService.swift
  cli/Sources/TuistAnalytics/Utilities/TuistAnalyticsDispatcher.swift
  cli/Sources/TuistKit/Commands/Auth/AuthCommand.swift
  cli/Sources/TuistKit/Commands/Auth/RefreshTokenCommand.swift
  cli/Sources/TuistKit/Commands/EnvKey/EnvKey.swift
  cli/Sources/TuistKit/Commands/TuistCommand.swift
  cli/Sources/TuistKit/Services/Auth/AuthRefreshTokenService.swift
  cli/Sources/TuistKit/Services/Inspect/InspectBuildCommandService.swift
  cli/Sources/TuistKit/Services/LoginService.swift
  cli/Sources/TuistKit/Utils/Dependencies.swift
  cli/Sources/TuistProcess/BackgroundProcessRunner.swift
  cli/Sources/TuistServer/Client/ServerAuthenticationConfig.swift
  cli/Sources/TuistServer/Client/ServerAuthenticationController.swift
  cli/Sources/TuistServer/Client/ServerSessionController.swift
  cli/Sources/TuistServer/Utilities/JWT.swift
  cli/Sources/TuistServer/Utilities/ServerCredentialsStore.swift
  cli/Sources/TuistSupport/Utils/Environment.swift
  cli/Tests/TuistCoreTests/MetadataProviders/XCFrameworkSignatureProviderIntegrationTests.swift
  cli/Tests/TuistKitAcceptanceTests/AccountAcceptanceTests.swift
  cli/Tests/TuistKitTests/Services/Auth/AuthRefreshTokenServiceTests.swift
  cli/Tests/TuistKitTests/Services/Inspect/InspectBuildCommandServiceTests.swift
  cli/Tests/TuistKitTests/Services/LoginServiceTests.swift
  cli/Tests/TuistLoaderTests/Loaders/Mocks/MockFileSystem.swift
  cli/Tests/TuistServerTests/Client/ServerClientAuthenticationMiddlewareTests.swift
  cli/Tests/TuistServerTests/Session/ServerSessionControllerTests.swift
  cli/Tests/TuistServerTests/Utilities/ServerAuthenticationControllerTests.swift
  cli/Tests/TuistServerTests/Utilities/ServerCredentialsStoreTests.swift
Labels: type:bug, size:XXL, lgtm

#7922 fix(server): fix server not launching after embracing semver versioning
  docs/docs/en/guides/server/self-host/install.md
  server/lib/tuist/environment.ex
  server/lib/tuist_web/live/ops_configuration_live.ex
  server/lib/tuist_web/plugs/on_premise_plug.ex
  server/lib/tuist_web/router.ex
  server/test/tuist_web/plugs/on_premise_plug_test.exs
Labels: type:bug, size:L, lgtm

#7925 feat(server): Include the fediverse creator tag in the marketing pages' posts
  server/lib/tuist/marketing/blog.ex
  server/lib/tuist_web/components/layout_components.ex
  server/lib/tuist_web/marketing/controllers/marketing_controller.ex
Labels: type:enhancement, size:S, lgtm

#7933 fix(server): Fix empty release notes in GitHub releases
  .github/workflows/release.yml
Labels: type:bug, size:XS, lgtm

#7935 chore(server): Fix fly.prod.toml configuration for multiple processes
  server/fly.prod.toml
Labels: type:bug, size:S, lgtm

#7936 fix(docs): increase Node memory limit to fix docs deployment
  .github/workflows/docs.yml
  .github/workflows/handbook-deploy.yml
  docs/package.json
  handbook/package.json
  pnpm-lock.yaml
Labels: size:S, domain:docs, lgtm
